### ISSUE TITLE
Using Ctrl shortcuts

### ISSUE THREAD

**Issue by NatashaDK** [photopea/photopea#1005]
Try this :

Open PP
Click on "New Project"
Click CREATE

Ctrl + A
Ctrl + C
Ctrl + N
Click CREATE

Ctrl + V      - this is where the bug happens 

From now on, whenever you pres Ctrl, PP opens the New Project dialog  :-(

Love from Natasha / Denmark

**Comment by photopea** [comment]
Hi, I fixed it (and I hope I did not break anything else). Thanks!

BTW. in my latest Chrome, Ctrl + N always opens a new window of a browser (we can not prevent it). But we can use Ctrl + Alt + N instead.

**Comment by NatashaDK** [comment]
Thanx, this is perfect! 

Love from Natasha / Denmark

**Comment by beto-aveiga** [comment]
I have the same problem. `Ctrl` keys does not work. In fact, if I press `ctrl`+`[SOME KEY]` it behaves as if I had only pressed `[SOME KEY]`. Thus, `ctrl+z` becomes `z`, `ctrl+o` becomes `o`.

I already confirmed this behavior here http://jsfiddle.net/p45f44zb/14/ When I pressed ctrl it does not show anything.

And here is my suggestion, could you incorporate this script to capture keys? http://www.gmarwaha.com/blog/2009/06/16/ctrl-key-combination-simple-jquery-plugin/ This script works for me capturing keys with `ctrl`

I'm using Ubuntu 18, this problem is happening in Firefox 65.0.1 (64-bit) and Chrome 72.0.3626.119 (Official Build) (64-bit)

Thanks! :+1

**Comment by photopea** [comment]
Hi, when you go to http://jsfiddle.net/p45f44zb/14/ , click into the white area, and then press Ctrl. You have to see some text (key code). What that text is?

**Comment by beto-aveiga** [comment]
Hi, very sorry for my late response. If I press ctrl I see nothing. If I press any other key then I see that key.

**Comment by photopea** [comment]
Hi, this is very strange. In a correct browser environment, the web app should be notified, that you pressed a Ctrl key.

Can you update your Ubuntu? Or search the internet, if anybody had a similar problem in their browser? It is not related to Photopea. No web app is able to detect, that you press the Ctrl.

**Comment by beto-aveiga** [comment]
Yes, I admit it is weird because it happens to me with other web apps. 
However, I give you the code above which does work for my configuration, please check it... or give it as an option in your app because maybe I'm not the only one with this problem.
Or is it the language? I talk Spanish and I have "English International" as my keyboard language, to write easily chars with accents like áéíóú and so on.
My Ubuntu install is a few weeks ago, so it should work properly and it is updated. 
I will change my language. I will notify if it does make a change or not in your app or in the jsfiddle you suggest.

**Comment by photopea** [comment]
I think we can call it a bug in your OS or in your browser. It is a bad thing to adapt your software because of bugs in other software. 

Could you report it to Ubuntu or Chrome? I can report it for you, but they may ask me questions about details, which I will not be able to answer.

**Comment by beto-aveiga** [comment]
No problem, I won't report it, I kind of fixed it somehow... 
To make `ctrl` key work I first press `left alt`, then simultaneously `ctrl` with any other relevant key combination. 
Doing that in the jsfiddle you gave me, it shows all keys I have pressed, including `alt`, but it works as there are no other combinations with those multiple keys... I mean `left alt + ctrl + z` behaves as `ctrl + z`. So, for now I will try to get use to it. 
Changing input languages did not change anything, I thought it could be something related to "international keyboard layouts" or "dead keys", but in my tests I found no difference whatsoever.
By the way, it is awesome how similar is Photopea to Photoshop, it is an excellent portable replacement for most of the functionalities.
Many thanks.

**Comment by photopea** [comment]
Maybe you have some keyboard settings in BIOS or something, so that the Alt key behaves as Ctrl key.

I would really try to report it to Ubuntu if I were you.

Or maybe this will help? https://askubuntu.com/questions/791893/ctrl-modifier-key-not-working

**Comment by beto-aveiga** [comment]
Thanks for your time. Ctrl is not working only for webpages in browsers. Out of Chrome or Firefox I can do everything with Ctrl, and I use keyboard shortcuts a lot. I don't like using the mouse as much as I like using the keyboard. If the error was not happening on Firefox I would think it's Chrome, but happens in both.

I tell you more, in the browser (be it Chrome or Firefox) I can do Ctrl +Tab, Ctrl + T,  Ctrl + N, Ctrl +  Shift + N, everything... However, Ctrl combinations do not work for websites. I think I will report it, following your advice.

I already did what's on the answer https://askubuntu.com/questions/791893/ctrl-modifier-key-not-working

Thanks again.
