### ISSUE TITLE
Cannot delete anchors on SVG

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#1031]
My manufacturer have send me this PDF for the template of a box i am producing.

And i need to delete some anchors (the one on the outside).

But happens that i cannot do it!  O_o

I still can delete anchors on path i created, but not this one.

When i try to delete a particular anchor i delete the whole shape!

Maybe you can check what is really happening with this file.  

Cheers!
[Box Template.pdf](https://github.com/photopea/photopea/files/2546726/Box.Template.pdf)

**Comment by photopea** [comment]
Hi Alvaro, this problem is related to our recent update with Live Shapes, where each path corresponds to a Live Shape record.

In your record, one path consists of multiple "parts" (i.e. with Path tool, you can select and move only the complete object, not its parts). The deletion of anchors was not ready for such case. I fixed it. Thank you!

**Comment by avagp** [comment]
(ﾉ◕ヮ◕)ﾉ
Thanks!

**Comment by nenochis-1** [comment]
Hi! I have the same problem. I want to delete just a part of the path and when I click on it with Path Select or with Direct Select and then delete, the whole shape is gone :(
I'm a beginner so maybe I'm doing something wrong or is there a problem with the file?
[224-pdf.pdf](https://github.com/photopea/photopea/files/2734726/224-pdf.pdf)

Thanks!

**Comment by photopea** [comment]
@nenochis-1 I fixed it :)  Every disconnected part of a shape is now movable separately now.
