### ISSUE TITLE
Change tabs, losing tools

### ISSUE THREAD

**Issue by golngaz** [photopea/photopea#1034]
sometimes, when I switch tabs on Firefox, the tools layout disappears and I should to refresh de webpage.
I switch to a collapsed tab.

Firefox 60.0, 64 bits
Fedora 7.1

I take this opportunity to thank creators of this fantastic online tool!

**Comment by photopea** [comment]
Hi, this sounds very strange, it never happened to me :(  I just tried to switch tabs in FF, everything went well.

My guess is, that it is either the Resize problem (when it happens again, can you try to resize the window, instead of the Refresh?)  or Firefox kills Photopea completely to save RAM (in that case, you should probably change Firefox settings somehow, or get more RAM).

**Comment by photopea** [comment]
I have to close it because of lack of details. It is also not clear, if you refer to "tabs" of your browser, or "tabs" with several documents inside Photopea.
