### ISSUE TITLE
Doesn't work offline

### ISSUE THREAD

**Issue by mgiuca** [photopea/photopea#1066]
The service worker reads from the cache but doesn't populate it. This app is currently installable in Chrome but is at risk of not being installable in the future.

In your AmA you said this:
"Once Photopea.com is loaded, there is no communication with the server after that (you can disconnect from the internet and use it offline)."

Which I guess means once you've loaded it in a browser tab. Still, it would be more app-like if I could actually use it offline.

**Comment by photopea** [comment]
Hi! Currently, we make money with ads, and they don't work offline :(  We also don't want people to use versions of Photopea, which are weeks or months old.

**Comment by benfredwells** [comment]
I don't understand this response.
re: ads: are you worried that users will deliberately run offline to avoid seeing ads?
re: updating: if you build your SW right this will just work.

Your responses on the AMA really impressed me but I think your comments about Photopea working offline were misleading.

**Comment by photopea** [comment]
When photopea is loaded in a browser window, it will keep working, no matter if you disconnect ro connect back to the internet.

I think that the ability to start Photopea while offline is not very useful. Currently, I spend about 1 hour a year on my laptop offline. And the amount of time people spend offline is decreasing. Making the browser keep the local copy of Photopea would slow down the loading time a bit for everybody, while being useful only to 0.0001 percent of people.

**Comment by benfredwells** [comment]
> When photopea is loaded in a browser window, it will keep working, no matter if you disconnect ro connect back to the internet.

I understand, I just think that it isn't impressive or noteworthy and calling it out is misleading to normal folks. They will think you mean something else (well, I thought you meant something else anyway).

> I think that the ability to start Photopea while offline is not very useful. Currently, I spend about 1 hour a year on my computer offline. And the amount of time people spend offline is decreasing. Making the browser keep the local copy of Photopea would slow down the loading time a bit for everybody, while being useful only to 0.0001 percent of people.

Fair enough, that's your experience. I think what you're saying is that the benefits aren't worth the cost. This is your app so that's your call, but I think you are underestimating the benefits and overestimating the costs:

- it seems that you are basing the usefulness of this on your own experience only. Another data point: I live in a rich western country (Australia) but would use this a lot, as I commute on a bus every day and use my laptop heavily there. Yes, I can tether, but I prefer not to and the connection is usually patchy when I do. Another data point: folks in developing countries have different connection quality and costs.

- I can understand you being sensitive to load time as Photopea is pretty slow to load. However adding a SW cache would actually speed up load times as you wouldn't need to hit the network. Looking in dev tools very quickly it seems like your load time is affected by load and unzipping all your code. You could eliminate this for all but the first loads after a new version is released. While there is a slight overhead to all fetches when you have a SW, you're actually incurring that already because of your empty fetch handler.

- As Matt hinted Chrome will be breaking your install button unless you improve your offline experience. Not sure when this will happen but we do not want to promote installation of sites that do not work offline, which is why we check for the fetch handler. I don't know if this is important to you or not.

- The development cost of doing this is not great. You should be able to get it working pretty quickly, depending on how complex your load and build systems are. If you have any questions or concerns about it let me know and I'd be happy to help out in any way I can.

Anyway, as I said it's your product so the choice is yours. I know personally I'm quite hesitant to start relying on something that only works if my network is up.

Best of luck with everything!

**Comment by photopea** [comment]
-- I know personally I'm quite hesitant to start relying on something that only works if my network is up.

What offline search engine do you rely on? Do you have an offline Wikipedia, too? :P

**Comment by jhit** [comment]
Sorry, but this is disappointing.
There are so many occasions I have to work without connection (travel/train, off-grid location, isolated corporate network)
Make it a Premium feature then the loss in Ad displays will not matter, but give us the opportunity to launch it without connection. I develop in docker containers for the same reason - to work while offline.

One word to the "We also don't want people to use versions of Photopea, which are weeks or months old." argument. If people are happy with an older version, why would you want to force them to update?

I like Photopea, but not being able to launch offline is a huge annoyance. And not being able to save files to disk that I opened from disk is the second major issue I have.

Make it offline usable and wrap it in an electron app please. That would make me pay Premium long term.

Thanks for the great app Photopea already is.

**Comment by jazoom** [comment]
> What offline search engine do you rely on?

Offline search engine is ridiculous and has nothing to do with anything.

> Do you have an offline Wikipedia, too? :P

Ummm, yes.

https://en.m.wikipedia.org/wiki/Wikipedia:Database_download

**Comment by mgiuca** [comment]
> > Do you have an offline Wikipedia, too? :P
> 
> Ummm, yes.
> 
> https://en.m.wikipedia.org/wiki/Wikipedia:Database_download

Well, that (i.e., downloading the entire database) isn't really what we'd have in mind when considering an "offline Wikipedia". Rather, you would implement some caching so that if the user is offline, they can still read articles they've already seen, and perhaps also any articles linked from articles they've already seen.

Jake Archibald wrote a little demo (it's a bit flaky) of what an offline Wikipedia PWA would look like: https://wiki-offline.jakearchibald.com/

In general, when thinking about offline support for a PWA, think about how an equivalent native app on Android or iOS would behave when offline. You can make your web app do that too! At the very least, Android and iOS apps generally show some form of UI when offline, rather than a blank page saying "Could not connect to app." Many will often cache data as well.

The search engine even isn't as ridiculous as it would seem: have you tried using the Google Search app when offline? It doesn't just give an error. It lets you type a search, then says it will get back to you when results are available, and notifies you when your connection is back online.

There are lots of ways to imagine any app working with partial functionality when offline. An image editor should be able to have almost full functionality.

**Comment by hitchcott** [comment]
I'd pay for premium if this worked offline.

@photopea Airplanes exist.

**Comment by JesusIsJehovah** [comment]
What bullshit this is - I'm looking for a an offline version so I can get around the internet. To not say this is useful is nonsense and just more insanity as always. I want a Portable version as I'm looking for an alternative to Gimp.

I tired of gibberish and how you companies and programmers do stuff - jailing us in more and more and stealing our data. Anyway... That's all from me.

**Comment by DUOLabs333** [comment]
If anyone in this thread is still interested in an offline version, I am making one [here](https://github.com/DUOLabs333/Photopea-Offline).

**Comment by vehosah** [comment]
> When photopea is loaded in a browser window, it will keep working, no matter if you disconnect ro connect back to the internet.
> 
> I think that the ability to start Photopea while offline is not very useful. Currently, I spend about 1 hour a year on my computer offline. And the amount of time people spend offline is decreasing. Making the browser keep the local copy of Photopea would slow down the loading time a bit for everybody, while being useful only to 0.0001 percent of people.

It's not very useful to you, it's useful to a million of us who don't have internet all day :p

**Comment by photopea** [comment]
Photopea has been working offline for several years now. Just disconnect from the internet and open www.Photopea.com in your browser to see it.

**Comment by vehosah** [comment]
> -- I know personally I'm quite hesitant to start relying on something that only works if my network is up.
> 
> What offline search engine do you rely on? Do you have an offline Wikipedia, too? :P

No but we have gimp :p

**Comment by vehosah** [comment]
> -- I know personally I'm quite hesitant to start relying on something that only works if my network is up.
> 
> What offline search engine do you rely on? Do you have an offline Wikipedia, too? :P
I don't know is Photoshop online only :D

**Comment by vehosah** [comment]
> Hi! Currently, we make money with ads, and they don't work offline :( We also don't want people to use versions of Photopea, which are weeks or months old.

Uhh what bullshit did we read?

**Comment by camoody1** [comment]
@vehosah Back for your one douche comment per six months, I see. I look forward to your next one sometime in August. 👍🏼

**Comment by vehosah** [comment]
> @vehosah Back for your one douche comment per six months, I see. I look forward to your next one sometime in August. 👍🏼

Thanks, anything else for your douchebag mouth to say or you just came to bitch about it for my comment 😂

**Comment by Xeddius** [comment]
It's clear this is a feature that people want, there are many people who travel and do not live in a country in Europe where WIFI access is practically a human right. There are people willing to pay money for this feature, and yet the developers just ignore it because they feel like their measly ad revenue is superior. It's sad, but this is why I can't switch from GIMP or 🏴‍☠️ Photoshop

**Comment by vehosah** [comment]
> -- I know personally I'm quite hesitant to start relying on something that only works if my network is up.
> 
> What offline search engine do you rely on? Do you have an offline Wikipedia, too? :P

Yes :p

**Comment by Xeddius** [comment]
> Do you have an Offline Wikipedia too?

This is actually one of the dumbest comments on here
Quite literally there is an entire community dedicated to preserving snapshots of wikipedia for offline use. Kiwix is software I helped contribute to for this exact purpose. I can download literally all of wikipedia within about 80-90gb onto an SD card and have it literally anywhere without internet.

It must be nice to live such a privileged life that you're never without wifi/signal. 
Typical behavior of a spoiled euro dev. I'm surprised they're not French.

**Comment by vehosah** [comment]
> @vehosah Back for your one douche comment per six months, I see. I look forward to your next one sometime in August. 👍🏼

Understandable have a douche life, douchebag 👍
