### ISSUE TITLE
can't load big tiff image

### ISSUE THREAD

**Issue by kwkwkwkw** [photopea/photopea#1080]
tried a few big tiff images larger than 100MB but can open a >400MB PSD file

**Comment by photopea** [comment]
Hi, do you see any error when opening your TIFF file? Could you send it to us to support@photopea.com , or put it online and send us a link?

**Comment by kwkwkwkw** [comment]
no, no error was displayed and just halted there showing "Loading" until the browser to show webpage loading error.
![photopea loading tiff error](https://user-images.githubusercontent.com/23471726/48276850-ff4ec080-e483-11e8-8a18-bfa1c31a685b.jpg)

**Comment by photopea** [comment]
Can you try to disable WebGL (More - Use WebGL) before opening your file?

**Comment by kwkwkwkw** [comment]
tried the same 245MB file which is 4080x2874 px, 300dpi, 8bit/channel, the same case with/without using WebGL.
The same case for an even bigger file 2.1GB, 5472x3648 px, 240dpi, 16bit/channel, with/without using WebGL.

It's seems working fine with those smaller size files even enabled the WebGL.
Files like below listed are fine:

44.2MB, 3406x2271 px, 2400dpi, 16bit/channel
34.7MB, 2870x4203 px, 2900dpi, 8bit/channel
56.2MB, 3852x2578 px, 300dpi, 8bit/channel
114MB, 5472x3648 px, 100dpi, 16bit/channel

BTW, one more issue I have just met which is the program doesn't render correct the colors(shows black color only) with a higher bits/channel tiff file.

**Comment by photopea** [comment]
Hi, I really need some of your files, to be able to test them and find the problem.

**Comment by photopea** [comment]
Hi @kwkwkwkw . I fixed the problem - you can open your TIFF in Photopea now. Your 245 MB file contains 22 MB of the main image, and the rest is Photoshop-specific data (other layers, masks, adjustment layers, etc.)

Note, that Photopea only opens the main image at the moment. I doubt any TIFF viewer can open more than the main image. If you wish to save your work in progress (with layers and masks), save it as PSD instead of TIFF.
