### ISSUE TITLE
Fit the area does the same as pixel to pixel

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#109]
On the Zoom tool, the fix the area button and the pixel to pixel, zooms in/out the canvas at the same level.

I assume pixel to pixel is right, because it seems so, but fit the area is completely smaller than the whole work space.

I am using chromebook, with chrome 53

**Comment by photopea** [comment]
Hi,
"pixel-to-pixel"  means, that 100 pixels of the image will be 100 pixels of your monitor.
"Fit the area" should zoom in as much as possible, while keeping the whole image area is visible.

Note, that Photopea can zoom only to values like 1x, 2x, 3x, .... or 1/2, 1/3, 1/4 ....  It can not zoom to 2/3 etc.  So if your image has 500px and workspace has 700px, it will stop at 1x, because 2x (1000px) would be too much and it can not zoom to 150% (1.5x)

**Comment by avagp** [comment]
That explains the outcome.  👍
