### ISSUE TITLE
Screen font fuzzy

### ISSUE THREAD

**Issue by Eatabean** [photopea/photopea#1098]
When I enter text and change the font size, the text outline is sharp (vectorized), but when I try to zoom in on the text layer after clicking on a different layer, the text outlines are fuzzy. When the document is saved it loses resolution. I changed the image size resolution but see no difference. Two different screens, lots of different resolution settings tried.

**Comment by photopea** [comment]
Hi, Photopea renders everything into Pixels. So you will always see pixels after you zoom in, no matter if it is a photo or a text. Only when you export to a vector format (such as SVG or PDF), the text and vectors will be sharp.

If you goal is to make a raster image (like PNG or JPG) and you don't like the pixellation, you should increase the resolution (Image - Image Size - make the pixel size 2x or 3x larger - 2000 instead of 1000).
