### ISSUE TITLE
From imported PDF, Photopea does not detect shadow as a property of shape

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#1099]
I have imported this work as PDF to Photopea, and the shadows from many elements of the design are ported as another shape, but no as a shadow from the original path.

This for example:
![image](https://user-images.githubusercontent.com/11801254/48679529-4d448200-eb70-11e8-9360-26de51f70e0b.png)

Is imported like this:
![image](https://user-images.githubusercontent.com/11801254/48679569-ccd25100-eb70-11e8-9205-5f04bd28dfc4.png)
The shadow is now a bitmap.
And i don't know how PDFs are handled (i know they are weird) but also the paw path is divided as you can see.

Here i leave you with the PDF and SVG so you can check if you need.
[Caja Kiltros.pdf](https://github.com/photopea/photopea/files/2593357/Caja.Kiltros.pdf)

[Caja Kiltros SVG.zip](https://github.com/photopea/photopea/files/2593363/Caja.Kiltros.SVG.zip)

**Comment by photopea** [comment]
I am afraid I can not help you. PDF does not support any representation of shadows (like SVG or CSS do). All programs, that generate PDFs, store shadows as bitmaps. So when you take a PDF, it is impossible to say, which bitmap is a shadow of another object.

When you zoom in to a shadow in a PDF viewer, you don't see pixels, because the bilinear interpolation is used.

I recommend you to store your work as a PSD, AI or Sketch file, and export to PDF only as the last step. PDF was not meant to be an "editable" format.
