### ISSUE TITLE
Suggestions (Info Panel)

### ISSUE THREAD

**Issue by kevintey** [photopea/photopea#1101]
Hello!

Suggestion to update the info panel, so that it shows the histogram of the current image, and also color info on the areas the mouse is hovering. Possible?

![sugg-info-histogram](https://user-images.githubusercontent.com/41601071/48685888-cfc25580-ebf3-11e8-9264-3e204c849bc4.jpg)

I think the info panel should at least contain the color where your mouse is hovering for quick reference.
Thanks!

**Comment by photopea** [comment]
There is a problem with this, because currently, the result image is stored on the GPU. Reading it to RAM after each mouse move would slow down the editor (e.g. you are dragging the layer outside the view, the histogram should change in real-time). 

You can read colors with the Color Picker. It reads the image from GPU just once you use it, not all the time.
