### ISSUE TITLE
Photoshop can not open PSD file

### ISSUE THREAD

**Issue by bobus123** [photopea/photopea#1112]
Photoshop: Could not complete your request because of a program error.
Please help 
https://mega.nz/#!EpZiSaaL!zsiJrAw9-CxsnuCiFnt5keA8LulP0Wmrg_lVsfmfc6g

**Comment by bobus123** [comment]
Adobe Photoshop CC 19.1.0 Release

**Comment by photopea** [comment]
Hi, was this PSD made out of a PDF file? Could you send us the PDF file, too?

**Comment by bobus123** [comment]
https://www.dropbox.com/s/zyz5xvyl1l4t0x7/181115%20MOTR%20Poster%2052%20no%20MIPCOM.pdf?dl=0

https://www.dropbox.com/s/k57js711wec5un6/181110%20MOTR%20One%20Pager%20no%20MIPCOM.pdf?dl=0

**Comment by rcoenen** [comment]
works fine for me

**Comment by photopea** [comment]
So there was a bug in converting texts from PDF to PSD. I fixed it. If you convert your PDF to PSD again, the new PSD will work in all versions of Photoshop.

Note, that texts, that you see in Photopea, look wrong. You need to give Photopea (or Photoshop) the required font, so that they can be re-rendered properly.
