### ISSUE TITLE
Publish to Imgur account?

### ISSUE THREAD

**Issue by rossum** [photopea/photopea#1129]
Right now, it seems like File | Publish to Imgur is an anonymous upload. It would be nice if that uploaded image could be tied to an already-logged-in Imgur account so one could see the image in their account, or delete it, or modify it, etc.

Please let me know if I am overlooking how to do this.

**Comment by photopea** [comment]
The original purpose of this button was to let people quickly share images with each oter (e.g. make a screenshot, paste it into Photopea, crop it, highlight something with a brush, press Publish to Imgur, send your friend a link via a message (or use a link in a message on Facebook / Twitter / Reddit / Github / any forum, where you can write text).

In order to upload to Imgur into your account, we would have to redirect you to Imgur, so that you log in (if not logged in already) and give Photopea permissions to work with your account.

I don't think many people would use it at the moment. There are probably more important storages (like Dropbox), which we should implement first. So I recommend you to strore an image locally, and upload it manually to your Imgur. As soon as browsers let us do it, we will let you copy an image into a clipboard, so that you can paste it into Imgur directly (Ctrl+V).
