### ISSUE TITLE
Set theme with api?

### ISSUE THREAD

**Issue by byrning** [photopea/photopea#113]
Hi,

Is it possible to set the theme with API?  If not, would be nice feature.

Thanks.

**Comment by photopea** [comment]
Hi, do you actually need it, or are just trying to come up with new features? :)

For the future, I am planning to use API only to handle data and "logic", the environment properties would be completely up to the user.

**Comment by byrning** [comment]
lol, we'd use it. The "iron blue" theme colors work better with our dashboard design. So it doesn't necessarily need to override the user's theme setting, just would be nice to set the default theme to "iron blue" instead of "silver."

thanks.

**Comment by photopea** [comment]
Right now, each user has environment settings, that contain: theme, language, visibility of rulers and guides, foreground and background color.
When user loads Photopea for the first time, these settings are set to default values. Since then, they are stored in the cache of a browser (or online, if you log in). 
When user visits Photopea through your iframe and there already are some settings (in cache or on the server), should these settings be replaced by settings defined over the API?  If they change it manually, the settings will be replaced again after reloading the page.
Some users may get engry, when you rewrite their settings, but I can't see any better solution.

**Comment by byrning** [comment]
Well I think it would be nice for the API to set the "default" theme. If the user changes the theme manually, or if the theme has already been set previously and cached, then I guess the user's setting should override the API default.

**Comment by photopea** [comment]
The problem is, that "custom user settings" (which are stored in a browser or on the server) are generated not only when user changes some property, but right after loading Photopea.com 

So your "iron blue" theme will apply only when user visits your page (and Photopea) for the first time. If user has visited Photopea.com (directly or through some other iframe) before, API parameters would be ignored. Is such behavior sufficient for you? :)

**Comment by byrning** [comment]
That works.     

I guess down the line, depending on what level of customization you want to give platform providers, you may want to store the theme settings with the domain name(or an identifier), so that xyz.com's theme settings can be different from abc.com's. But, that's a "nice to have."

thanks.

**Comment by photopea** [comment]
But people, who would try implement the API, already know Photopea.com, and when they will be testing these API features, they would see no effect (because custom settings have been generated for them).

Thus, I think that API parameters should rewrite custom user settings. If your users complain, that they change the theme to silver and it gets back to Iron Blue the next time, you must explain it to them somehow.

**Comment by byrning** [comment]
Okey dokey, that works too. ;)   Your suggestion would be my preference anyways.

**Comment by photopea** [comment]
Ok, you can use "theme" parameter now, see https://www.photopea.com/api/

Example URL: https://www.photopea.com?p=%7B%22environment%22:%7B%22theme%22:2%7D%7D

**Comment by byrning** [comment]
Perfect thanks.
