### ISSUE TITLE
Cannot transform layer

### ISSUE THREAD

**Issue by talentlessguy** [photopea/photopea#1234]
When I tap `Ctrl + Shift + I` nothing happens, except a note in history.

![image](https://user-images.githubusercontent.com/35937217/52720850-7a5ed000-2fb9-11e9-962c-e28c09d21f3e.png)

**Comment by photopea** [comment]
Hi, I tried to press Ctrl + Shift + I , but no note in the history appeared. How exactly did you do it?

You should use Alt + Ctrl + T to start a Free Transform.

**Comment by talentlessguy** [comment]
> 
> 
> Hi, I tried to press Ctrl + Shift + I , but no note in the history appeared. How exactly did you do it?
> 
> You should use Alt + Ctrl + T to start a Free Transform.

In previous Photopea versions I used Ctrl Shift T. Weird stuff.

**Comment by photopea** [comment]
Actually, Photopea requires Ctrl + T to start a free transform, and Shift + Ctrl + T to repeat the last transform again (see Edit - Transform - Again) - this feature was added yesterday.

But many browsers open a new tab, when Ctrl and T is pressed at the same time. But my Chrome on Windows doesn't open a new tab, when Alt is pressed. So that is why I suggest to add Alt to those shortcuts. But maybe your browser works differently.

I just hope one day users will be able to press any keys, and web apps will be able to detect, what keys were pressed (as it is possible in native apps).
