### ISSUE TITLE
Ad Blocker Is Disabled

### ISSUE THREAD

**Issue by LunacoXd** [photopea/photopea#1263]
Ad Blocker Is Disabled For Photopea but it keeps saying that it is blocking ads and the pop up will not go away please fix this I need to art.

**Comment by photopea** [comment]
Hi, can you reload Photopea.com ?

**Comment by LunacoXd** [comment]
I tried reloading it is not working.

**Comment by photopea** [comment]
Can you try it in Incognito mode?  Are you still using any extensions? I think it may be because of some extension.

**Comment by LunacoXd** [comment]
I tried Incognito as well still does not work was not giving me this problem a week ago and I haven't done anything to my browser or laptop.

**Comment by photopea** [comment]
We change Photopea several times a day.

What web browser do you use? Are ads on the right side displayed correctly?

**Comment by LunacoXd** [comment]
I'm using chrome and the ads are displaying correctly.

**Comment by photopea** [comment]
So when you open an Incognito mode and go to www.Photopea.com, and wait 10 seconds, you see a message "Your device seems to be removing our ads. Please, watch our ads, or get a Premium account." ?

I just did the same in Chrome, and it does not happen.

**Comment by LunacoXd** [comment]
Yes that is what happens

**Comment by photopea** [comment]
Can you update Chrome browser? What version are you using? What is your operating system?

**Comment by photopea** [comment]
Are you using a Chromebook? One more person reported the same problem: https://twitter.com/HuitzFPS/status/1102984720109981707

**Comment by darryn11** [comment]
I am also having this problem. 
Turned ad block off, gave exceptions for this site, tried incognito mode. 
Version: 68.0.3440.84 (Official Build) (64-bit)
OS: Windows 10

**Comment by ruchsia** [comment]
Same here, I actually cannot use the service, because I have to dismiss this message every few seconds. Adblocker is turned off and I have even clicked on some of the ads.

**Comment by photopea** [comment]
Hi, I updated it a bit. Can you try it again? If you still see the message, can you look into a Console (right-click - Inspect Element - Console)? There should be a text "*** Number". Can you tell me what number do you see?

**Comment by photopea** [comment]
Guys, please, anybody, look into the Console and tell me, what number you see after "***" .

**Comment by CrazyCorbeau** [comment]
wowza,hope this gets fixed soon

**Comment by photopea** [comment]
@CrazyCorbeau  Can you look into a Console (right-click - Inspect Element - Console)? There should be a text "*** Number". Can you tell me what number do you see?

**Comment by photopea** [comment]
I think it should be solved now.

**Comment by BOBBYERTLY** [comment]
I see 0.5

**Comment by photopea** [comment]
@BOBBYERTLY have you tried to disable all extensions? There is something preventing the correct initialization of Photopea. It can be a browser itself :(  You should use standard browsers, which display websites in a standard way.

**Comment by TheJaredWilcurt** [comment]
Tried in portable versions of Chrome and Firefox on Windows 10. Alert dialog appears everytime. Incredibly annoying. I've gotten to the point where I'm trying to reverse engineer your code to fix this client side and use a plugin to run my script after page load. This is really bad. Just turn the thing off for everyone until you figure out how to do it right.

**Comment by photopea** [comment]
@TheJaredWilcurt What exactly do you see in the web console?

We do not have enough resources to test Photopea in 3627 browsers and their versions. But I am quite confident to say, that your browser is not displaying the webpage the way it was supposed to be displayed. It is a bug in that browser, and you should report it to the creators of that browser.

**Comment by TheJaredWilcurt** [comment]
I don't think anyone is asking you to test your app in three thousand six hundred twenty seven browsers.

I think we're asking you to make it work in the most popular browser (Chrome) on the most popular operating system (Windows). And until you can figure out how to do that, don't annoy the shit out of your users.

🤷‍♂

**Comment by photopea** [comment]
@TheJaredWilcurt This message about unblocking ads has been there for a long time, and you are the first one in the last two months, who is reporting, that it is shown to you even when you don't block ads.

I don't see any reason to change the behavior, as ads help us make money for the development. So I really need to get information from you (what you see in the console), to be able to possibly fix it, or to explain to you how to fix your browser.

**Comment by harmonystudio** [comment]
@photopea First of all, thanks for a great and free tool. I experienced the same issue, and the culprit was that there were two ad blockers, only one whitelisting photopea. Entirely my fault, but until I figured it out, I managed to get pretty worked up about the every 30 sec popup. The app was effectively unusable and it was very frustrating not knowing what's happening. For less tech-savvy users, seeing a popup every 30 seconds and not knowing why will be a deal breaker.

This would especially be problematic in newer version of Chrome, where browser extensions that user interacts with very little are hidden under the three dot menu. This makes it even harder to spot that a) any extensions are installed or active b) to explain to users where to look for extenions

Please consider changing the popup to something a bit more user friendly. A banner covering a small portion of the working area, or the same area which is occupied by ads when adblockers are disabled. Perhaps adding a note about disabling all the extensions and closing all browser windows and then re-opening the browser would be useful as well. Was necessary in my case. Without terminating every Chrome instance and restarting the issue was persisting even after disabling all extensions and re-loading Photopea.

**Comment by photopea** [comment]
@harmonystudio Thanks for your comment. There are millions of people using Photopea, and such problems are reported only once in a while. We really think it is not fair to let some people hide ads, while others have to watch them. Advertisement (or paying directly for a Premium account) is very important for the future of Photopea.

And there is another thing, that disturbs me while reading your comment. It seems like you let third-party software read and process all you see or type on the internet, and you let it rewrite the content under your hands. But what is even worse, you are not even aware of the software doing it.

I really don't want content-rewriting to become a common practice on the web. I think people should see the websites exactly as authors created them. And if you read unexpected text / see unexpected image / notice an unexpected functionality, you should at least be aware, that you are allowing some extension to rewrite all your websites.

**Comment by TheJaredWilcurt** [comment]
I'm using a standard, boring, vanilla copy of Chrome on a standard boring copy of Windows 10. I only mentioned "portable" to signify that I also tested it in portable Chrome and Firefox to ensure that there are no settings, extensions, or plugins interfering. This also happens in Firefox.

Here is console logs though. The first one had so much I had to reduce font size and stretch it up in full screen (which pushes the ad off screen). This is from an incognito view, to ensure that everything is downloaded fresh:

![log](https://user-images.githubusercontent.com/4629794/58137394-14a96200-7c00-11e9-875b-ed54d88d700f.png)

This was a soft-refresh, much less in the console, so I shrunk the dev tools down to show that ads are actually loading.
![log2](https://user-images.githubusercontent.com/4629794/58137395-14a96200-7c00-11e9-8060-40346fac4bd6.png)

**Comment by photopea** [comment]
@TheJaredWilcurt  This is so strange. The message should be shown only when the AdBlock is detected. And whenever AdBlock is detected, it should print "*** X" in the console. But I don't see anything like that in your console :/ 

Also, the message should not be shown to people, who open Photopea for the first time (even with AdBlock). Which is always true in incognito Window (unless you open it for a second time in the same incognito window).

I changed the code a bit. Can you please show us again what you see in the console?

**Comment by maciej-gurban** [comment]
Sorry for hijacking the thread, but I'd like to offer a different perspective on the ads vs popup issue.

I think you'd find that many people use ad blockers for a good reason, even though they technically do rewrite the content of each website. The contents of websites showing ads are often filled with irrelevant, clickbait or otherwise unwanted or distracting pieces. Without them you're also exposed to being tracked by the ad networks. The ad blockers themselves are pretty well vetted and in many cases open-source, so other than being against principle of 3rd parties changing client-side content of a website, there's not much argument against them.

I haven't got an idea what revenue are you getting from ads, but wanted to offer alternatives which don't expose users to the above mentioned issues and still provide you with a solid revenue stream. One such option would be using Patreon. You'd be positively surprised at the number of users willing to support a product by committing to its recurring financial support. As a user, I'd rather spend a minute setting up a Patreon support for Photopea than be exposed to ads for the rest of my usage of the app. I'd imagine this to be the case for many others.

You don't necessarily need to remove the ads right off the bat. You could show your own banner there, encouraging people to pledge support for the app. Perhaps it would turn out that over-time the pledged support would be high enough that you could afford to drop ads altogether, or perhaps not, but it's impossible to tell without trying.

**Comment by photopea** [comment]
@maciej-gurban Thanks for your comment! I wanted to avoid donations, as I wanted people who donate money to get something in return, but that is actually a regular selling.

So you suggest to hide ads for users, who donate on Patreon? How much would you be willing to donate? Photopea offers a Premium account (with no ads): 20 USD for 90 days.

I tried to show a banner asking to buy Premium to people with AdBlock, but it did not lead to any increase in orders. But when I made watching ads mandatory, the ad revenue grew about 30%.

Personally, I never tried to block ads on the web in my life. Do you have any idea what "personal data" exactly is being "tracked"? When some article mentions "ads tracking people", they are never specific about what it means. I think there is an unfair hatred created towards ads. They are amazing thing, which helps creators make money while offering products for free.

**Comment by maciej-gurban** [comment]
To be honest, I didn't realize there's a "Pro" version of Photopea until you mentioned it. I suppose that works and is an even better idea. My only suggestion would be to work on making that fact easier to notice in the UI. "Account" button might hint at that, but different phrasing might bring better results.

As for cookies, [this article](https://privacy.net/stop-cookies-tracking/) has some good points. From a bit different angle, but if you're interested in getting your perspective on supporting work through ads challenged, this article would be a good starting point: https://www.thatseemsimportant.com/content/sam-harris-content-creator-supporting-work-without-running-ads/

**Comment by TheJaredWilcurt** [comment]
Still getting the same results as before (alert still occurring every 30-ish seconds) in Incognito with no extensions installed in Chrome on Windows 10. Console log:

![photopea](https://user-images.githubusercontent.com/4629794/58282878-f87b0180-7d74-11e9-878c-47341b96967e.png)

* * *

As far as "tracking", Mozilla made a tool that lets you see the thousands of trackers you have from just regular internet usage unless (you are using a tool to block them):

* https://www.youtube.com/watch?v=PvqGy9wz_wA

* * *

>Do you have any idea what "personal data" exactly is being "tracked"?

3rd parties track what websites (and specifically what pages on those sites) you visit, what you search for, how long you stay on those sites, how often you re-visit them. They can [fingerprint](https://pixelprivacy.com/resources/browser-fingerprinting/) you so you don't need to be logged in and if you dump their tracking cookies they can still know who you are and add details about you to their profile. They can (and do) sell this information to other companies as well.

The problem people have with ads isn't really the ads themselves, but the disproportionate invasion of privacy in exchange for accessing a website/webapp. Though some people just [dislike marketing in general](https://www.youtube.com/watch?v=tHEOGrkhDp0).

**Comment by photopea** [comment]
@TheJaredWilcurt Whenever Photopea tries to show an alert about ads, it should print "***" in the console before that. I am 99.99 % sure about that. So your case is incredibly strange :(  Is there an antivirus (Kaspersky, etc.) or any other software, which can rewrite websites that you access, before they are shown to you? Because I am 99.99 % sure, that something is rewriting Photopea for you, and since PP is HTTPS, it must be something inside your computer.

Of course, if you visit a website A and B, and both use ads from a company C, then, when visiting B, the company C may know, that your device visited A before (how much time you spent there, etc.). But it would be absolutely the same, if sites A and B cooperated in some way, even without ads. I guess you can never prevent such cooperation. If these were shops, the owner of shop A can tell the owner of shop B, that a person with a red hat visited them at 10 am. 

But they don't know your name, address, or any sensitive information. Also, attempts of "fingerprinting" never work 100% (there can be many people with red hats).

**Comment by DaRealAK** [comment]
My Photopea is Rapidly doing the SAME THING. I have No Extensions that may affect Ads. What shall I do?

**Comment by DaRealAK** [comment]
> My Photopea is Rapidly doing the SAME THING. I have No Extensions that may affect Ads. What shall I do?

![image](https://user-images.githubusercontent.com/81315197/125314535-e644ee80-e353-11eb-9f3f-0eee7797a325.png)
This all I get

**Comment by photopea** [comment]
@DaRealAK  Try this tutorial: https://www.photopea.com/tuts/ads-in-photopea-do-not-work-what-to-do/

**Comment by flyingrobotpig** [comment]
I had the same issue, paused adblocker but it still came up with the message. I also had to disable privacy badger on photopea, then it worked

**Comment by photopea** [comment]
I don't know what a privacy badger is :( Photopea just needs a browser, that will display it the way it was meant to be displayed, and to be able to access any domain of the world wide web, just like the internet was supposed to work, that is all.

**Comment by flyingrobotpig** [comment]
It's an extension that can block trackers and things like that on websites, probably was interfering with whatever checks for ads, pausing it stopped the popup.

**Comment by rCarleon** [comment]
For anyone facing the issue with the ad blocker dialog: Additionally, to the ad blocker, I had to disable "I don't care about cookies" extension on my browser for Photopea to work.

**Comment by kojinshugi** [comment]
> For anyone facing the issue with the ad blocker dialog: Additionally, to disabling ad blocker, I had to disable "I don't care about cookies" extension on my browser for Photopea to work.

Thanks for this - also the addon can be turned back on after you accept the cookies.
