### ISSUE TITLE
When saving PSD the merged shapes unmerge

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#1276]
When merging the shapes on the sub-folder **Mala Leche v4 > Lado Centro > Logo > Dealer > Cuerpo** and then saving the file as PSD, i got every merged shape unmerged!!

Here is the file:
[Expansion Base (2).zip](https://github.com/photopea/photopea/files/2955266/Expansion.Base.2.zip)

Here is a video showing this issue:
[video showing this .zip](https://github.com/photopea/photopea/files/2955269/video.showing.this.zip)

**Comment by photopea** [comment]
Hi, I believe this is because of solving one of our previous bugs. You probably have multiple "open" shapes in one layer. Adobe Photoshop can not render layers, which contain multiple open paths in one layer. To keep our PSD working well in Photoshop, we split such layers.

[curves.zip](https://github.com/photopea/photopea/files/2955630/curves.zip)

**Comment by avagp** [comment]
I imagined something related.  :)

Thanks!

**Comment by photopea** [comment]
I am ready to remove this confusing feature, once Adobe fixes this in Photoshop. I wrote them an email, but nobody responded :(

**Comment by avagp** [comment]
They don't want to cooperate with you. Face it

XD
