### ISSUE TITLE
more of a complaint

### ISSUE THREAD

**Issue by CrazyCorbeau** [photopea/photopea#1303]
I don't like the new brush...I prefer to see my mouse when I'm drawing

**Comment by photopea** [comment]
Hi, what exactly happens? Could you describe it or make a video?

**Comment by CrazyCorbeau** [comment]
There's nothing wrong with it,I just prefer to see my mouse when I'm drawing as the circle seems to throw me off

**Comment by photopea** [comment]
Oh, you mean seeing the mouse cursor (arrow) instead of seeing a circle of the brush.

Actually, Photopea was supposed to show you a circle of the brush for many years. There was probably a bug in your browser, so you could not see it. And now, you see it.

I think you can get used to the brush circle, if you give it a try (like several hours). It may seem uncomfortable at first, but maybe you would realise that it is actually better, if you give it a try.

**Comment by CrazyCorbeau** [comment]
i'd still prefer to see my mouse cursor but ok

**Comment by photopea** [comment]
I am sure you will see, that seeing a brush cursor is more comfortable. You can press [ and ]  to change the cursor size and see the live preview.

**Comment by CrazyCorbeau** [comment]
what?

**Comment by photopea** [comment]
what what?

**Comment by CrazyCorbeau** [comment]
> I am sure you will see, that seeing a brush cursor is more comfortable. You can press [ and ] to change the cursor size and see the live preview.

what do you mean by that ^

**Comment by photopea** [comment]
Using a Brush tool with a circle cursor, instead of the "arrow" cursor, is more comfortable.

**Comment by CrazyCorbeau** [comment]
not for me xD
