### ISSUE TITLE
New dodge and blur tooltips missing letter help 

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#134]
Hi,
the new blor tool tip does not have the letter in parenthesis at hte end, which key is binded to it?

Also, just being picky, but why the dodge tool is selected by the letter O, and no the letter D?

:)

Keep the good work!

**Comment by photopea** [comment]
Hi,
I think it is not right to reinvent the wheel, so current keys for tools are inspired by Adobe Photoshop and Pixlr (which was probably inspired by Photoshop).  In these programs, the blur tool does not have any key bound to it (probably because there is not enough keys). Do you think that other keys would be more suitable? 

You may try to search the internet, why O is for Dodge in these programs :)

**Comment by avagp** [comment]
I searched it, and I belive is because once was Overexpose Tool instead of Dodge Tool

:)
