### ISSUE TITLE
Rasterize Layer Style error

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#1348]
When I clicked Rasterize Layer Style on top layer/folder it showed this error.

file:
[svg-svg.zip](https://github.com/photopea/photopea/files/3096243/svg-svg.zip)

error:
pp.js:5059 Uncaught TypeError: Cannot read property 'add' of undefined
    at zU.Lc (pp.js:5059)
    at xQ.Tg (pp.js:5188)
    at xQ.jy (pp.js:5186)
    at tV.xa.zw (pp.js:4263)
    at xX.zw (pp.js:8357)
    at xX.zl.a (pp.js:9)
    at xX.tv.a (pp.js:5881)
    at mZ.tv.a (pp.js:5881)
    at mx.tv.a (pp.js:5881)
    at mY.tv.a (pp.js:5881)

**Comment by photopea** [comment]
Hi, I fixed it by disabling the Style Rasterization. It does not make any sense on folders, because they can not have any raster content themselves.

Rasterizing Layer Styles is tricky in general, when there are multiple styles on one layer. E.g. The Stroke may have a Multiply Blend Mode, the Drop Shadow may have the Overlay blend mode, but the result layer can have only one blend mode.
