### ISSUE TITLE
Export in lower resolution - so much blur

### ISSUE THREAD

**Issue by andrewio** [photopea/photopea#1450]
Hi, my regular task is exporting image in lower resolution. And Photopea photo produce so much blur on photo compare with photoshop.

So I work with 1372 x 1035 canvas in 144 DPI. And I need 516 x 389 image as result. 

So I experiment with resamling and dpi. No result. Much blur.

More Over, Photopea doesn't save my export size and I need write sizes manually every time I export.

In Addition, Photopea has not convenient slider with percents, so I need to enter and calculating manually.

**Comment by photopea** [comment]
Hi, you are absolutely right. There was a bug and downscaled images became blurry.

I fixed it. Output images should be much sharper now.

Also, I made Photopea remember your last export size, so that you don't have to enter it again.

For what value do you need a slider? You can "slide" the Width or Height by clicking and dragging the label "Width" itself. Any label can be dragged this way in Photopea.

**Comment by andrewio** [comment]
http://joxi.ru/1A5M4BLUDOXL1A

**Comment by photopea** [comment]
You can use Percent in Photopea, instead of Pixels, and type your own value in Percent: https://imgur.com/vM9QqDQ
