### ISSUE TITLE
How to switch to the code?

### ISSUE THREAD

**Issue by Fgeniy** [photopea/photopea#146]
Hi, there! I have a problem with that, I can see psd-file but I can't work with my code and I need to close your plugin to see the code, Maybe I do smth wrong? Thnx for making Brackets more better!

**Comment by photopea** [comment]
Hi, current plugin opens up using the whole area of Brackets. I am not sure if it is possible to open such plugins in "panels" in Brackets, so you could see both text editor and Photopea plugin.

Maybe you can just open www.Photopea.com in a web browser instead of Brackets plugin? Brackets and Photopea would be in different windows, but it should work in the same way.

**Comment by Fgeniy** [comment]
okay, I've solved - just open new window for Brackets and open Photopea there! profit! and without installing Photoshop with many-many tools that I don't use) thnx again!

**Comment by photopea** [comment]
I didn't know you can have multiple windows of Brackets :D 

I have noticed, that currently, Brackets do not support WebGL. So if you use Photopea for opening 200 MB PSD, 4000 x 3000 px,  it may be a little slow ... That is why I would prefer using it in a standard modern browser.
