### ISSUE TITLE
Can't save as .psd

### ISSUE THREAD

**Issue by mady1234** [photopea/photopea#15]
I just edited a .psd file, but now I cannot save it as a .psd file anymore, only for web.

**Comment by photopea** [comment]
Hi, there may be a bug in Photopea. I am very sorry for that. 

Can you show us your file, so we can test it? Can specify a little, what exactly did you do?

**Comment by photopea** [comment]
You can also send me your PSD to support@photopea.com

**Comment by photopea** [comment]
It can not be solved, because of the lack of any additional information :(

**Comment by Kshitij-Banerjee** [comment]
Happened to me again. 

We can't share the file since it does not allow to save . :(

**Comment by Kshitij-Banerjee** [comment]
Browser Console says. :: 
pp.js:306 Uncaught TypeError: Cannot read property '__name' of null

**Comment by Kshitij-Banerjee** [comment]
J.writeDescriptor	@	pp.js:306
La.writeAddInfo	@	pp.js:339
ia.writeLayerRecords	@	pp.js:349
ia.Encode	@	pp.js:345
V.writeLayerInfo	@	pp.js:368
V.writeLayerAndMaskInfo	@	pp.js:367
V.Encode	@	pp.js:362
fa.EncodePSD	@	pp.js:994
fa.SaveProject	@	pp.js:994
da.doSysaction	@	pp.js:1013
Ha.dispatchEvent	@	pp.js:115
A.dispatchEvent	@	pp.js:788
A.dispatchEvent	@	pp.js:788
Ka.onSelect	@	pp.js:1041
Ha.dispatchEvent	@	pp.js:115
A.dispatchEvent	@	pp.js:788
Ja.onMU	@	pp.js:992

**Comment by Kshitij-Banerjee** [comment]
wasted all my effort because of this.

**Comment by photopea** [comment]
Hi Kshitij,  I am very sorry for your loss :(  would you help me and others to fix this?

The problem is in editing the text layer. I would like to know, what did you do with the text layer, before it happened. Can you do the same thing in your PSD and make it fail again? If yes, can you please exactly describe the steps, what to do with the text layer, to reproduce this bug?

**Comment by photopea** [comment]
Hi, it just happened to me too, for the first time. I have no text layers at all.

There is one classic layer, which is empty. When I delete it, saving as PSD works. But when I go back in history and return it, saving does not work again. The strange thing is, that the error is in the function, which generates binary data for a text layer (but there is no text layer in the Layers panel).

I tried to reproduce the bug in the new window, doing the same steps, but without success (it was possible to save the PSD).

**Comment by photopea** [comment]
So, in my case, the problem was not related to text layer, but to layer styles (it is on the same line of code, that't why I thought it was text layer).

This problem was my nightmare for a long time, because many people reported it and I had no clue what could go wrong. I hope I have fixed the problem and I hope it is gone for good and will never happen again.

**Comment by kimfal74** [comment]
I can't save my .psd file either. I started from scratch and now I can't save it? I get this message:
Squirrelpreneur-Logo.psdFailed - System busy
blob:https://www.photopea.com/0b125ece-0971-4b8e-a929-f6053c4c47ff
