### ISSUE TITLE
Shortcut problem on linux: ctrl + alt + t opens a terminal

### ISSUE THREAD

**Issue by JohannesBe** [photopea/photopea#1534]
Please rebind the `ctrl+alt+t` shortcut for linux users, since this opens a terminal on most UNIX-like systems and hence is captured at system level and never propagated to the browser. Since the `free-transform` tool is one of the most used features by a lot of people, this is rather important from a usability perspective (I know the regular `ctrl+t` is not usable and neither is `ctrl+shift+t , since those respectively open  a new tab / the last closed tab, so I guess we have to bind to something completely different on linux?)

Maybe more in general: allow configurable shortcut keys?

**Comment by photopea** [comment]
Hi, I really don't like to change the behaviour of Photopea because of the system differences :(  I am already quite sad because of the fact, that Windows and Mac computers have different keyboards (with/without Ctrl, Command, Option key etc.)

Actually, Photopea starts Free Transform when Ctrl and T are pressed simultaneously. So if browsers allow us to use this shortcut, it will work in Photopea without us doing any change at our side. Maybe you could reconfigure your browser not to open a new tab on Ctrl+T? Or find another key (other than Alt), which you can add to Ctrl+T and neither the browser, nor the OS would do anything for that shortcut?

**Comment by KnIfER** [comment]
What about putting it to a right-click context menu? then users can either click on the menu or right-click -> press T to enter Free Transform.  Anywa, Ctrl+Alt+T has an uncomfortable gesture...

**Comment by photopea** [comment]
You can start the Free Transform in Edit - Free Transform.

**Comment by KnIfER** [comment]
Oh i see

**Comment by KnIfER** [comment]
7 years later —— I'm now using AHK to allow `ctrl+t`, `ctrl+d` shortcuts for photopea.com : 

```ahk
^t::
	send ^!{t}
return 
```

**Comment by photopea** [comment]
You can simply press Edit - Free Transform, it is two clicks.
