### ISSUE TITLE
Suggestion - integrate Guide Guide plugin

### ISSUE THREAD

**Issue by hallworth** [photopea/photopea#1584]
Guide Guide is an essential plugin that allows you to generate guides and grids easily.  I'd love to see this functionality in PhotoPea. https://guideguide.me/

**Comment by photopea** [comment]
Hi, I added a similar tool. It is called a Guide Guy :)  Window - Guide Guy.
![image](https://user-images.githubusercontent.com/15955558/62162768-3e29ec80-b319-11e9-8508-512e6575ce2e.png)

**Comment by MichalSZZ** [comment]
@photopea 
I just tested that tool and work great!
Very very usefull function is creating grid layout from selection! WOW.
I can make 990 px width rectangle selection in the center of artboard and then, make my own grid layout inside of it. 

One usefull thing is missing (corresponding to PS) - live preview checkbox.

**Comment by MichalSZZ** [comment]
2nd important thing:
I can't make column with specific width.
E.g.:
I make 990px selection with rectangle selection tool.
Inside of it, I want to have 3 columns with specific width (and auto gaps).
@photopea  is it possible to add that?

**Comment by photopea** [comment]
I added an option to add a column width (then, column count and column gaps are automatically calculted).

Live updates are a bit tricky. Changing guides should add an action to a History, and it is not clear when it should be added. Or if you enter values into Guide Guy, move a guide manually, and change values in Guide Guy, should it be added to current guides, or replace current guides?

**Comment by MichalSZZ** [comment]
> I added an option to add a column width (then, column count and column gaps are automatically calculted).

In Photoshop I can set up number of columns, width and gaps in one time. But it's works a little different, because there isn't a possibility to make layout from selection (what is soooo great in Photopea).

![obraz](https://user-images.githubusercontent.com/38118273/62268568-838d0d80-b430-11e9-8514-ec7ade3921e7.png)

How it should work? That is only a idea...
Example 1 (simple): 
I make guide layout inside selection (e.g. 990px).
I set up 3 cols and gap 30px  (width is empty - auto)
Layout will be: 3 colums that auto fits from left to right to the selection (width will be calculated automaticaly)

Example 2:
I make guide layout inside selection (e.g. 990px).
I set up 3 cols and width to 310px (gap is empty - auto)
Layout will be: 3 colums that auto fits from left to right to the selection (gaps will be calculated automaticaly)

Example 3:
I make guide layout inside selection (e.g. 990px).
I set up 3 cols, width to 310px and gap to g.e. 10 px
Layout will be: 3 colums from left of the selection (now in Photopea there isn't function "center" like in PS) and 40px space (990 - 3x310 - 2x10) from the right of selection (no auto fitting to the selection - when all 3 parameters are added) 

I must think about the best UX solution for that. Please give me some time :)
That is very good addon and should be the best in whole Internet! :)

> Live updates are a bit tricky. Changing guides should add an action to a History, and it is not clear when it should be added. Or if you enter values into Guide Guy, move a guide manually, and change values in Guide Guy, should it be added to current guides, or replace current guides?

I undestand. Maybe it should keep that information as a step only after actepting with "Add Guides" button? I think that how it works in Photoshop.
![obraz](https://user-images.githubusercontent.com/38118273/62269332-01521880-b433-11e9-83c7-7066ba73881a.png)

History step 1: all guides before using Guide Gay
History next step: add all information about all guides from Guide Gay (tracking changes like in GIT - only differences?)

**Comment by MichalSZZ** [comment]
https://guideguide.me/documentation/use-the-grid-form/

"The wildcard ~ character is used to tell GuideGuide to automatically calculate the leftover space in a grid."

But in photoshop users know "(auto)" like in "Text Leading"

**Comment by photopea** [comment]
I fixed the behaviour. It should be "closer to what you expect". The value 0 corresponds to "auto".
