### ISSUE TITLE
delete non-last step in history (without deleting all that follows) - feature suggestion

### ISSUE THREAD

**Issue by ewnjtgouierg** [photopea/photopea#1603]
Imagine situation when you want to UNDO something you have done, but the problem is that you already did something very important and hard-to-repeat after it.

For example, you reduced image size to save a test image to try it out, then forgot to change the size back and did some difficult adjustments. Now you realize that you didn't do it on original high-resolution image, so you cannot save your work - you need to somehow check the values, note them down and try to replicate everything.

It would be so cool if you could just click on the "Change size" step in the history and then hit DEL or click a trash delete icon to delete it.

If I understand correctly, history panel "replays" the actions applying them one after another anyway - so it SHOULD be possible to implement?

I understand that deleting some steps could result in inconsistency, so, perhaps, some warning would make sense?

PS has the "allow non-linear history" mode - seems related and may be makes sense to check it out

p.s. Sorry if I actually missed some simple method that already exists to resolve situations like this

**Comment by photopea** [comment]
Why don't you enlarge the image after doing your changes? BTW. you can save the small version of the image by changing the size in Save For Web window (there is no need to resize the whole document).

Your idea would not work. Let's say you made the resolution 4x smaller, and then, painted a small 20 x 20 px painting with a Brush tool ("pixel art"). You want to remove the resizing step. What do you want to get instead of your 20x20px painting? If you just want to enlarge it, you can simply change the image size with Image - Image Size.

Every action has a previous state and a new state. It is not clear, how should new actions be "changed", if the preceding action is deleted. It would be probably impossible for most of actions.

If you don't want to lose quality after resizing, keep your graphics in smart objects.

**Comment by ewnjtgouierg** [comment]
thanks for taking time to explain this and for the tip about smart objects
