### ISSUE TITLE
opens 300dpi PDF as a 144dpi PDF - WHY?

### ISSUE THREAD

**Issue by gtswhitt** [photopea/photopea#1617]
I have a trifold brochure created at 300dpi.  I flattened it, and exported it as a PDF file.  When I open the flattened PDF file it is the same dimensions but is set to 144dpi.  I'd like to give the printer a 300dpi PDF file.  Why does Photopea change the DPI like that?  Is there any program out there where I can check the dpi on the saved PDF to see if it is still 300dpi and photopea just has a bug in it when it reopens PDFs?  I'm on the free version.

I also have to save them a thousand times because your website times out and doesn't seem to be able to handle large files.  It simply decides "whoops, too much info" and closes.  I guess I'll have to buy photoshop if I want to create billboards.  But this really stinks on a trifold brochure, having to constantly save it and reopen it hundreds of times a day until the project is done.  My downloads folder is huge in revisions, needlessly.

**Comment by photopea** [comment]
Hi, you can not check the DPI of a PDF file, because PDF files do not have any DPI. They have only physical dimensions (inches, cm, mm ...). E.g. a PDF file can be a page 10 x 10 inches, and a red circle in the middle with a diameter of 7 inches. There is no DPI.

When you open a PDF file in Photopea, the DPI value is made up (since there is no DPI in PDF). But if you check the size in Inches (or cm, mm...), it should correspond to the original PDF. If you want, you can change the DPI value in Photopea to 300 (but no program can "extract" the value 300 from a PDF, because PDF files do not have any DPI).

You can buy Adobe Photoshop, if you want, but it can not open or save PDF files (without a complete rasterization). I recommend you to buy Adobe Illustrator instead. 

I recommend you to decrease the DPI value in Photopea. It will use less RAM (and the preview will look more pixelated), but it has no impact on the exported PDF.

**Comment by gtswhitt** [comment]
I did not know that about PDF's.  I've used PS7 for 13 years now without a problem but Adobe probably blocked my pirated/hacked PS7's license number when I downloaded their free trials recently.  I hate to have to learn something new now.  Oh well.  I knew this would happen one day.  I seriously hate being hostage to any online-only versions and paying monthly for anything.  If you know of anything I can buy and actually install rather than being online and works with all the PS7 tools, let me know.

**Comment by photopea** [comment]
I don't know what exactly are you trying to achieve.

Photopea is free to use, you can pay only to hide ads. The features are the same for everybody.

**Comment by gtswhitt** [comment]
I just took my 300dpi layers PSD file that's 8-1/2 X 11 inches and saved it as a JPG image.  When I open the JPG image the file size says it's now 43 inches wide at 72 dpi.  What's the story on JPG's?  43 inches?

**Comment by gtswhitt** [comment]
Well, I'd rather not have to buy anything from Adobe and be held hostage monthly and only being able to create things online, because if you time out from large files then I'm sure they will as well.  So I'm looking for something that is a program installation that works like photoshop.  Gimp sucks.  This is my daughter http://tricitieswebsolutions.com/img/Graphics/before-after.jpg  Will I be able to do that in Illustrator?

**Comment by photopea** [comment]
Hi, I just tried to open PDF in Photopea, saved it as JPG, and opened the JPG in Photopea. The size (in inches) remained the same (JPG as the PDF). Did you do something in between?

Photopea may crash, if you open PDF with 30 pages or more. It should not crash during photo editing.

**Comment by photopea** [comment]
When you have a PSD 8-1/2 X 11 inches and export it as JPG, the JPG size (in inches) should be the same.  Where exactly do you see 43 inches?

Adobe illustrator can not do photo manipulation as in your example. But it can edit PDF files.

**Comment by gtswhitt** [comment]
I'll create a video for you to watch what I'm doing.

**Comment by gtswhitt** [comment]
Please watch the video until the end.  At first in trying to replicate what happened, I recreated the exact steps I would normally take, either saving as a PDF and then opening it to make a JPG or make a JPG from the PSD flattened without doing a PDF first, and it seems to work.  However, I've only been using these two PSD files over and over again.  But I have them all over the place in having to save them intermittently before a RAM shutdown.  But I've never changed the document size.  I can promise you that, as there was no need to and surely wouldn't have.  At the end of the video, I open one file at it was half the width. And you'll see the one that converted to 34 inches.  But I do nothing differently than what you see being done in the video.  I would have taken no other steps to have caused that 34 inch file at all.  The steps I take are in the video.  I just cannot replicate it again but sure would like to know now why it's half the width now and if it's half the width, then surely the program is doing that and could have caused the double width as well, don't ya think?  Here's the video link.  It opens great in Opera without having to download it.  http://tricitieswebsolutions.com/img/photopea.mp4

**Comment by gtswhitt** [comment]
You may also notice why a jpg opens as a psd as well.  That made no sense on that part of the video.

**Comment by gtswhitt** [comment]
Maybe I just need a good study course on dpi.  LOL  All I know is these printers cry for 300dpi and if I can't see 300dpi after saving a PDF or JPG, etc. then I have no idea what dpi I'm sending to them.  I just need to make sure it's 300dpi.  You say with PDF's that wouldn't be an issue for this type of flattened PSD brochure, so I'm fine with that until I hear them crying.  But not understanding why my PS7 will save JPG's as 300dpi but not photopea or if I'm doing something wrong.

**Comment by photopea** [comment]
I am sorry, your video is 15 minutes, it seems you are doing the same thing over and over. And you did not add any voice comentary (so I have no idea what is the point of each step).

When you open any file (PSD, JPG, PDF, GIF ...) in Photopea, it converts every file to a PSD, and you work with a PSD from that point.

As I said, PDF can not have the DPI, so nobody can say "your PDF is not 300 dpi". When you open a PDF in Photopea and check the DPI, this value is always 144, it is made up and does not mean anything (because every PSD must have some DPI value).

To create a 300 dpi JPG, open any document, go to Image - Image Size, enter the DPI value of 300, press OK. Then, export as JPG.

**Comment by gtswhitt** [comment]
I thought you weren't supposed to go from 72dpi to 300dpi with jpg images or it gets pixelated.

**Comment by photopea** [comment]
If you have a JPG or PSD at 72dpi, and you want 300dpi, while having the same size in inches, there is no other way.

**Comment by photopea** [comment]
Ok I will close it for now.

**Comment by SomeKindaHack** [comment]
Hello Mr.Photopea! I've been following your work since you first appeared on Reddit a number of years ago. I also tell everyone I can about your this app. But I ran into this issue that this person posted about and before I could contribute my questions and answers, life pulled me away, but I'm back now. 

It's the only issue I have when using your app. But it makes it impossible for me to use.

I worked as a graphic designer for 4 years in an advertising agency. I've submitted dozens if not hundreds of print pieces (and web) to printers, newspapers, and magazines. 99% of the time I submitted them as PDFs (as per the printers request). the last time I used photopea to do this (about a year ago), i found like the original poster of this issue did, that my 300 ppi image was reduced to 144, and was by any decent printshop's standards, un-printable. (Again the majority prefer PDF files.)

You absolutely can save PDFs to a particular resolution, and by doing so, when that PDF is opened that resolution is the base/native resolution of that file. I've been doing it for years, on multiple versions of the software.

Here is a video of a person saving a PDF in photoshop showing them selecting the 300 print ready resolution https://youtu.be/Mxvow4d5VMo?t=60  and I'll paste a screenshot of that image.

![Saving a PDF with a specific resolution in Photoshop](https://user-images.githubusercontent.com/44933523/153981000-95e7b75d-451e-43e7-8139-4d1312464558.JPG)

And in doing so, when you then open that file (another screenshot from another source as I don't own photoshop right now) the modal box shows that the initial resolution is at 300 ppi (pixels per inch)

The photo below is from this site https://learn-photoshop.club/resources/free-tutorials/open-pdf-in-photoshop/

![Setting to choose when Opening a PDF in Photoshop](https://user-images.githubusercontent.com/44933523/153981333-bf74bd7b-9a46-4eb7-96ed-2e7103720c0c.JPG)

So yeah, I've been doing this in Photoshop forever, and desperately want to be able to do it using Photopea.

Thank you for all the work you put into this app!

**Comment by photopea** [comment]
What exactly do you want to do in Photopea?

PDF files do not have any DPI (Resolution). When you open a PDF in Photoshop, you can rasterize it at whatever DPI (any Resolution) you want, you can use 72 DPI or even 10000 DPI. There is no DPI inside a PDF file.

**Comment by SomeKindaHack** [comment]
Good morning! I simply want to be able to use Photopea in the same way I used for Photoshop for years. That when i save a PDF at 300 ppi, that it opens at a default of 300ppi, otherwise it's unprintable. 

I don't know what to tell you regarding that there isn't any "dpi" saved in a pdf. Why else would the saving dialogue ask you to input a ppi to save it at? (See the first picture in my last comment). Also using the "Press Quality" setting also preserves the PDF at 300 ppi.

But when I save a 300 ppi in Photopea, it just drops that information and reduces the resolution to 144 ppi. And if you then raise the ppi to 300 it's blurry and unprintable. Every print shop takes PDFs. Even the copiers at Staples take PDFs.

I'm not new at this, I've been using Photoshop for print projects for years. Photoshop DOES save PDFs at a 300 ppi resolution.
Here is a random printshop showing to save a PDF using photoshop @ 300 ppi (though for some reason they just Jpeg compression), which I have never used. I always use the "None" setting, as the jpeg setting can create some ugly compression.

https://www.kopytek.com/create-print-ready-files/

So again, if I open a PDF in Photoshop that I saved @ 300 ppi in photoshop, the open dialogue box shows 300 ppi as a default. 
But Photopea doesn't let me save the ppi (it just does a save for web ppi). 

I sent along pictures in my last comment that clearly show that I can save PDFs in photoshop at 300 ppi (so long as they were 300 ppi to begin with). And i attached a picture that shows that open dialogue/modal box, when you open one of those PDFs.

I appreciate you reading and responding to my comments, I really want to use Photopea for my various side projects.

**Comment by SomeKindaHack** [comment]
Thank you for going out of your way to work with me on this. I do know the difference between raster and vector, and I know a lot of people don't. (I wrote a blog page about it at my last job.) 
https://colonialmarketing.com/how-to-submit-artwork-and-graphics-for-your-business/

What I DIDN'T know was that Photopea was fundamentally different than Photoshop, as from what you're saying Photopea ONLY uses vector graphics. (Though you can obviously have some vector graphics in Photoshop too.)

I'm about to start a time sensitive contract job that I have to work on today. But I do want to try this. I don't currently have Photoshop but I might be able to find some old files. I'll have to dig around though. 

Let me circle back around on this in a day or so (possibly tonight).

I'm excited to see if we can figure this out.

Thanks!!

**Comment by photopea** [comment]
When you export a PDF in Photopea, you can enable "rasterize all", and it will work as Photoshop (one JPG image per PDF page). The DPI will correspond to the DPI you have set in Image - Image Size.

When you load a PDF into Photopea, and you dont like the DPI of 144, you can change it in Image - Image Size (as all bitmaps extracted out of a PDF are Smart Objects at their original resolution ... if you know Smart Objects). Photopea opens a PDF as Shape Layers, Smart Objects and Text layers (everything is resizable without losing the quality).

**Comment by SomeKindaHack** [comment]
Sorry for my delayed response. I'm in the middle of a couple of new jobs, and still hunting for better ones that offer more hours.

I tried your suggestion of increasing the ppi inside the photopea (thanks for mentioning Smart Objects and clarifying how your program works), and though it did seem to work, I don't understand how or why photopea defaults to 144 ppi instead of the 300 ppi that the PDF is saved at.

144 ppi is a a resolution, I don't understand why that one is chosen and not say 72ppi or my desired 300ppi? 

If someone has to manually increase the ppi every time the PDF is accessed, it defeats the purpose using a PDF to send a design to a print shop or even printing to an office printer. 

If "Press Qualtiy" is chosen in photoshop when saving a PDF it keeps the file at 300ppi, if another (lesser) setting is chosen, it typically decreases the resolution.

Print shops specifically want a PDF saved at a particular resolution (300ppi Press Quality), and will sometimes even charge to open the file and further manipulate it in Photoshop. 

And since I don't currently have Photoshop (because if I did I wouldn't be using Photopea), I can't test whether a PDF file saved in Photopea (which save to default resolution of 144ppi) will properly open its resolution at 300ppi in Photoshop. It wouldn't matter though, because again, Photoshop would be required, so why bother using Photopea for that process?

Below is a file that was saved in 300 ppi, when opened in Photopea it opens at 144, and yes it can be increased to 300, but if you open it in Photoshop it will list 300ppi as the default resolution.

So again, if I'm sending a file that I saved in 300 in Photopea and send it to a print shop or try to print it directly to a printer, it saves at 144ppi, and unless it's re-opened and manipulated, it will be printed at 144ppi in an printing environment that demands that everything is @300 ppi, and it will be blurry and pixelated (which is what I experienced).

[Sandhills Bank_Carolina Forest  2018 v5.pdf](https://github.com/photopea/photopea/files/8104779/Sandhills.Bank_Carolina.Forest.2018.v5.pdf)

**Comment by photopea** [comment]
Let me repeat it:

- PDF files do not have any PPI!
- The default PPI in Photopea is 144.
- The default PPI in Photoshop is 300.

Photosohp will set the default PPI to 300 for **every PDF**.  Photosohp will never set the PPI of any PDF file to 200 or 400, because there is no such thing as **a PPI of a PDF file**.

Please let me know, that you understand how Photosohp works (that it is not "detecting a PPI of your PDF file", because there is no such thing).

**Comment by SomeKindaHack** [comment]
Hey again, well, it's looking like we won't be getting this solved. So I hope I haven't wasted your time.

And I guess **i don't understand** that there isn't any ppi info saved in a PDF, when print shops specifically ask me to save a PDF to a specific resolution (300ppi). Why would they ask me to do this if there isn't any ppi info in the photoshop PDF file?

I can save a PDF to whatever resolution I want in Photoshop. If I create a 72pp, or a 96, or 300ppi resolution image in photoshop, and save it in Photoshop as any of those resolutions (as seen in the dialogue box below), when i open it in Photoshop (or any other program), that file has that same saved resolution as set in that dialogue box below.

![image](https://user-images.githubusercontent.com/44933523/155028548-bebb4db5-05c8-4d73-aebf-12d0d745b0c6.png)

And if there isn't any PPI info saved, then why is the **above** dialogue box asking me what resolution to save it in? That's the Photoshop save PDF dialogue box.

The whole point of my post is that I've always saved the resolution in a PDF in photoshop, and sent it to print shops or printers, and was surprised when photopea downsized that resolution to 144ppi. 

**If Photopea simply works fundamentally different, then so be it, and there's nothing to be done.** 

But I definitely save PDF files to whatever resolution I want to in Photoshop.

I think I've made this a frustrating conversation for you, and if so I apologize. I was just so happy to come across Photopea, but if I can't use it the same way i use photoshop to save PDFs, then I have to go back to using that program, which i don't want to do. At least I can save JPG and PNGs to full resolution in Photopea.

Thanks again for making this program and for responding to inquiries like this on the forum, and I hope you have a good week.

**Comment by photopea** [comment]
Photopea works the same as Photoshop. You can load a PDF at any resolution (100, 1000, 10000 PPI), and if you decide to save a rasterized PDF, you can also save at any PPI.

**Comment by SomeKindaHack** [comment]
Ok well I did that (checked rasterized), but when I open it again in photopea it opens at 144, which i assume is what a desktop printer will see it as, because that's what happened when I've gone to print something on an office printer.

This was the file saved at 300. But it opens to 144.
[test.pdf](https://github.com/photopea/photopea/files/8112335/test.pdf)

**Comment by photopea** [comment]
The same thing happens in Adobe Photoshop. If you export a PDF in Photoshop at 100 PPI and load it back, it will open at 300. If you export a PDF at 600 PPI, it will load back in 300 PPI.

**Comment by photopea** [comment]
You are asking me to do the "impossible" - detect a PPI of a PDF file. But no program in the world can do that. Not even Photoshop.

**Comment by SomeKindaHack** [comment]
> The same thing happens in Adobe Photoshop. If you export a PDF in Photoshop at 100 PPI and load it back, it will open at 300. If you export a PDF at 600 PPI, it will load back in 300 PPI.

That has not been my experience, as quite often I made lower resolution copies of advertisements to email as a proof, and when i opened them in Photoshop they opened at the resolution that I saved them in (72ppi), with that dialogue box that I pasted above. 

Photoshop presents you with the native ppi of the file before it opens it see below. I've done this hundreds of times. See below.

![image](https://user-images.githubusercontent.com/44933523/155034462-4397c141-aa4b-4a94-af19-fb18a39b49d6.png)

But if you say it's impossible then that's where we'll leave it.

Thanks for your time. 

PS (But if i do get photoshop in the future I'll make a screenshot movie and show you a file open up to the resolution i saved it at :)

**Comment by photopea** [comment]
I think you do not know Adobe Photoshop at all.

Please, do show me two PDF files, which Photoshop loads at a different PPI.

**Comment by SomeKindaHack** [comment]
So those pictures showing 100ppi resolution don't prove it to you? 
Well it's probably going to be a few months before i get photoshop again.  So it'll be awhile before I can make a movie showing me opening a PDF that has that dialogue box in my last comment showing them at the lower resolution that I save it at.
And yeah again I'd open up PDF proofs that I created like those pictures in the comment above (showing 72 ppi), it was something I did daily. 
But whatever, I've never made a graphics program before, and you have, so I have to default to your experience.
(But I will make that movie one day :)

**Comment by photopea** [comment]
I think someone typed the 100ppi into those boxes.

**Comment by photopea** [comment]
But really, does it make any sense to you, for a PDF to have any PPI?

What about a one-page PDF, a page is 5 x 7 inches, and there is a red circle in the middle, with a diameter of 4 inches. Everything is vector graphics. What should be the PPI of such PDF file? And what woud be the purpose of the PPI value in this case?

**Comment by SomeKindaHack** [comment]
Here's video from an old version of photoshop where the file opens at a low resolution

https://youtu.be/h1_uDnNOGu8?t=42

**Comment by photopea** [comment]
As I said, you should manually enter a PPI value when opening a PDF file. There is no PPI value inside PDF file.

**Comment by SomeKindaHack** [comment]
It said 43.701 before they overwrote it to 600ppi? It wasn't defaulted to 300 ppi like you said they would.

**Comment by photopea** [comment]
It was 43.701 pixels per centimeter, not per inch. I dont know what is the default value in Photoshop. It probably remembers the one you entered the last time.

**Comment by SomeKindaHack** [comment]
Here's video from an old version of photoshop where the file opens at a low resolution

https://youtu.be/h1_uDnNOGu8?t=42

********************

Ok well thanks for going through it. As i don't have access to PS (and checked every video on youtube) i have nothing further to contribute.

have a good night!

**Comment by SimonEast** [comment]
If I may comment on a 5-year-old thread, I think this issue still persists. Here is a raster PDF opened in both Adobe Reader (on the left) and PhotoPea (on the right). There is a clear loss in resolution in PhotoPea.

![Screenshot - Thu 11 Apr 24 , 8_24_28 am](https://github.com/photopea/photopea/assets/813734/55b93967-8bdd-482d-be07-f2f61e8b1c47)

You can download [doc (9).pdf](https://github.com/photopea/photopea/files/14938439/doc.9.pdf) for yourself.


## Further Details

I also think there is some confusion here about what constitutes DPI or PPI. 

@photopea is _somewhat_ correct in that DPI/PPI is not as relevant when it comes to vector graphics. However, it DOES have significant meaning for raster/bitmap graphics, and these are often embedded into a PDF.

I'm not sure if the PDF file format itself explicitly declares the PPI value for each embedded image, but it is easily calculable as the PPI is simply a combination of the pixel dimensions of the image and the physical print size. There is a command-line tool `pdfimages.exe` (which I think comes part of the [Poppler](https://github.com/oschwartz10612/poppler-windows) library) which extracts raster images from a PDF file in their original dimensions. Here it shows a list of images from that same PDF:

```
poppler-0.68.0_x86\bin\pdfimages.exe -list "D:\Downloads\doc (9).pdf"
page   num  type   width height color comp bpc  enc interp  object ID x-ppi y-ppi size ratio
--------------------------------------------------------------------------------------------
   1     0 stencil  1696  2652  -       1   1  ccitt  no         7  0   301   300 40.6K 7.4%
   2     1 image    2850  3600  gray    1   8  jpeg   no        11  0   300   300  274K 2.7%
```

You'll see that the image pixel dimensions are displayed, and it has also managed to extract (or calculate the PPI). 

In theory, each embedded image could potentially have a different PPI.

So what should PhotoPea do when opening PDF files? I suppose to prevent any loss of resolution, it should import at the highest PPI that is used by raster images in the document. It appears that it is not doing this currently (perhaps defaulting to 144 ppi) and as such causing a loss of resolution, especially when 300ppi is commonly used in the printing industry.

**Comment by photopea** [comment]
Each raster image has a specific resolution (width and height in pixels). It can be inserted into a PDF at any dimension / rotation / scale. So you can have a 1x1 pixel image being 1x1 inch in size, and next to it, you can have a 100x100 pixel image being 1 inch wide and 0.1 inch tall, rotated by 45 degrees.

Photopea has a "raster preview" and it renders all vector files at DPI 144. You can change it in Image - Image Size - DPI.

![image](https://github.com/photopea/photopea/assets/15955558/6f8b64fb-0d76-4e18-a4fd-f440dacd1a6b)

**Comment by GemAquarius82** [comment]
> If I may comment on a 5-year-old thread, I think this issue still persists. Here is a raster PDF opened in both Adobe Reader (on the left) and PhotoPea (on the right). There is a clear loss in resolution in PhotoPea.

Why are you comparing a zoomed-in image in Photopea to the Photoshop one when even from the naked eye you can tell that if you were to zoom into the Photoshop pdf the same pixelation would occur.

**Comment by SomeKindaHack** [comment]
> > If I may comment on a 5-year-old thread, I think this issue still persists. Here is a raster PDF opened in both Adobe Reader (on the left) and PhotoPea (on the right). There is a clear loss in resolution in PhotoPea.
> 
> Why are you comparing a zoomed-in image in Photopea to the Photoshop one when even from the naked eye you can tell that if you were to zoom into the Photoshop pdf the same pixelation would occur.

This entire thread was a result of me going to an office depot and using their printer to print a PDF. I worked at a marketing company for 4 years, and dealt with hundreds of print jobs. So there I am, going to print a PDF that I thought I'd saved in Photopea as a 300 ppi PDF. 

I've sent tons of 300ppi pdfs to various printshops. (Some had specific instructions to save the pdfs at 300 ppi.) So I go to print on this standalone copier and bam, 144ppi. Now it's a standalone copier, I can't tell it to increase the ppi to 300. It doesn't work like that.

I've not had Photoshop in 5 years since I made this thread, so I've never been able to demonstrate how my 300ppi PDFs created in photoshop, had a default resolution of 300 ppi during output. As Photoshop specifically asks me to choose a resolution setting when creating a PDF.

![155028548-bebb4db5-05c8-4d73-aebf-12d0d745b0c6](https://github.com/photopea/photopea/assets/44933523/1cecd2a6-6d38-4f03-a850-59418d90c8da)

But having learned from the creator that Photopea is purely vector based, I've given up trying to use Photopea as a tool to create PDFs and just use it to create Jpgs or PNGs if I use this platform. It would've simply been nice to allow the user to choose what the default of a PDF opens to. As 144ppi is not recommended for print jobs. Seems like an arbitrary number, so why not let that arbitrary number be 300ppi?

But I'm over it. Just wanted to mention the original reason for this post.
