### ISSUE TITLE
Integrate remove.bg service

### ISSUE THREAD

**Issue by rcoenen** [photopea/photopea#1626]
Integrate the awesome artificial intelligence-based background removal service remove.bg similar to for example how this plugin integrates it with photoshop 
https://www.remove.bg/photoshop

There is an API available
* https://www.remove.bg/g/developers

**Comment by photopea** [comment]
Regarding the API of remove.bg: they allow only 50 API calls (50 images) per month for free. Then, it is 18 cents per image. I am afraid we are not able to pay for our users, so that they can use it.

I could try to implement a similar tool into Photopea, and offer it for free. But I think these methods do not work that well nowadays. If you try remove.bg multiple times, it works well maybe in 70% of cases. In the remaining cases, it removes a part of a foreground, or keeps a part of a background, and you can do nothing about it.

I think our Refine Edge tool works much better, even though it may take 5 - 30 seconds per image, to roughly define the foreground and the background. https://www.photopea.com/learn/refine-edge

**Comment by photopea** [comment]
We have added a similar feature to Select - "Remove BG".

https://twitter.com/photopeacom/status/1611412094309515267
