### ISSUE TITLE
Feature request - confirm end of making selection with polygonal lasso tool

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#1667]
Only when process of that selection was very long or have many points.
Or that can be a checkbox on toolbar near refine edge button (user may want to check it when know that start hard selection). After double click should be a window with confirmation about end of process.
I use polygonal lasso tool very oft. When I want to cut off something that is very complex I fear all the time that in some point my mouse can make double click and waste my time and job.

I only asking :) Photoshop doesn't have such a feature :)

**Comment by photopea** [comment]
Polygonal lasso can be also confirmed by pressing Enter, or clicking on the first point in the sequence.

I guess we would have to add a checkbox "Confirm with Double-click", which you would disable.

I think it would make the UI overly complicated. If your mouse really does double-clicks instead of single clicks, you should fix or replace that mouse (that was the reason why I replaced my last two mice, even though everything else worked well).

I can also change the conditions for a second click. E.g. the time betwenn the clicks should be between 100 and 300 ms (now, it is between 0 and 250 ms).
