### ISSUE TITLE
Resolution has become tiny

### ISSUE THREAD

**Issue by celestialkat** [photopea/photopea#1672]
![Capture](https://user-images.githubusercontent.com/55119429/64577914-3140f400-d3c1-11e9-8b29-08d7699d20ba.JPG)
I'm not sure what I've done, but the resolution was fine last week, and then all of a sudden, perhaps I hit some keys, the resolution has now resized and it's TINY.

How do I restore it to default?

**Comment by kappische** [comment]
Try ctrl+0 to reset zoom in your browser/app? :)

**Comment by photopea** [comment]
It looks like you zoomed out the webpage. Go to the browser options (in the top right corner) and set the zoom to 100%.

**Comment by hjimenez3** [comment]
The past of couple of days I have been having the same problems with the resolution.  I was working on a file recently, and it yielded small resolution like the screenshot shown by the original user who created this thread.  It was not the zoom because the other tabs shows up normally at 100%, and I even restarted workstation.  Restarting workstation didn't work, and so I cleared the cache, and temporary files from Chrome; that did not resolve issue.  I also temporarily changed resolution to different resolutions (which was not recommended for my system), and then returned to my original system resolution (which was recommended by Windows 10) thinking it was a glitch in Windows 10 with the display adapter; problem was not resolved.  

My workstation is running Intel HP Graphics 4000.  Perhaps the original poster had the same issues but gave up before giving more details.  

Thanks for any help ahead of time.

**Comment by photopea** [comment]
Hi, you should change the zoom of the webpage. Click three bars in the top right corner and set the zoom to 100%.

The browser allows you to set a different zoom for each webpage.

**Comment by hjimenez3** [comment]
I took a careful look at the Chrome menu (denoted with vertical "..." and found zoom); I was able to promptly fix the issue.  I was previously using zoom for the canvas so I can see the canvas at the pixel level.  The focus went accidentally to the Chrome tab, and accidentally zoomed its entire contents, instead of just the canvas.  

Thank you!
