### ISSUE TITLE
Eraser with 1 pixel size

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#1780]
I have trouble erasing exactly one pixel with one pixel sized eraser. It keeps part of original (blue) color on that pixel when I click on it with eraser. I want to erase it completely. I have Opacity 100% Flow 100% Smooth 0% and no pressure control with 1px brush as you can see on screenshot. I tried also normal brush, squared brush and various brush settings but nothing seems to work to erase one pixel completely...
![image](https://user-images.githubusercontent.com/6370548/68106542-38c4db00-fee2-11e9-883b-4c80d72e64c1.png)

**Comment by photopea** [comment]
Hi, this works the same way in Photoshop and probably other programs.

It is because we are trying to preserve geometrical correctness (through antialiasing). Even if you paint exactly at the middle of a pixel, the brush (circle) covers only PI/4 of that pixel. To remove the color completely, the brush should cover whole pixel (so it is impossible with a brush size 1). 

I recommend using a rectangluar selection (or a Magic Wand) and clearing the selected area.

**Comment by hxim** [comment]
> Hi, this works the same way in Photoshop and probably other programs.

Hello I read here https://helpx.adobe.com/photoshop/using/erasing-parts-image.html there is something called "Pencil mode" in Photoshop that does what I need. Is it possible to have it in photopea? I used rectangluar selection and clearing but it is very uncomfortable when working with pixel graphics.

**Comment by photopea** [comment]
Ok, I added the pencil mode :)
