### ISSUE TITLE
Object select not work on this picture

### ISSUE THREAD

**Issue by ioma8** [photopea/photopea#1788]
I am unable to select the man with the new object select feature.
![man-wearing-a-beanie-2911403](https://user-images.githubusercontent.com/6624752/68380325-e4bf2e00-014f-11ea-94c2-5bf970f9d1e2.jpg)

**Comment by photopea** [comment]
Just follow two rules: Cross should be fully inside an object, and the rectangle should not touch the object. So something like this: 
![image (1)](https://user-images.githubusercontent.com/15955558/68381658-80ea3480-0152-11ea-85e1-1f9c0a02f51e.png)

But it did not select the man in my case either. It thinks the cap and the jacket belong to the background, because they are white.
![image (2)](https://user-images.githubusercontent.com/15955558/68381810-c0b11c00-0152-11ea-9228-c3d982f79943.png)
