### ISSUE TITLE
Ideas: Rasterize/ Distribute layer styles with folders.

### ISSUE THREAD

**Issue by GavHern** [photopea/photopea#1835]
I think it would be pretty cool to be able to rasterize the style of a folder seeing as you can apply styles to them. It would just rasterize it to each of the layers in the folder.

I also think, as of writing this, that there should also be a feature to distribute the style among the layers in the folder. (Get rid of the style on the folder and apply it to each of the layers inside of it.)

**Comment by photopea** [comment]
I don't know what you mean by "rasterize the style of a folder to each of the layers in the folder". So there would still be styles, or new layers would be added? Do you have any example of the initial state and the final state, that you need?

You can copy-paste styles with a right-click (in Layers panel) - Layer Style - Copy, Layer Style - Paste.

Putting a style of a folder to the layers inside would completely change the look (e.g. if you have a Stroke, the stroke of a top layer would cover the bottom layer). Even if a folder contains only  identical layers, e.g. there would be several drop shadows instead of one, which would look much darker.

**Comment by GavHern** [comment]
> Putting a style of a folder to the layers inside would completely change the look (e.g. if you have a Stroke, the stroke of a top layer would cover the bottom layer). Even if a folder contains only identical layers, e.g. there would be several drop shadows instead of one, which would look much darker.

Didn't realize this, nevermind. I also just realized that you can copy/ paste styles yesterday so scratch what I said, sorry.

**Comment by photopea** [comment]
ok I will close it now.
