### ISSUE TITLE
CTRL + Z on Belgian keyboard will force try quit

### ISSUE THREAD

**Issue by DjovDev** [photopea/photopea#1839]
Using a Belgian keyboard, when pressing CTRL + Z to go back in steps, the following is asked: "There is unsaved work in New Project.psd. Do you really want to close it?".

Pressing CTRL + W on a Belgian keyboard does the same. Not sure how this behaves on other keyboard types.

**Comment by photopea** [comment]
Almost in all browsers, Ctrl+W is used to close the current browser tab.

Are you sure the that in your computer, the tabs close even after pressing Ctlr+Z ?

I am talking about the "Z" key above the "S" key. It should work as "W" in English keyboard and close the tab. But it should not close the tab, if you are switched to a Belgian keyboard layout.

**Comment by DjovDev** [comment]
Hey,

Indeed. CTRL + W attepts to close the tab. However, the CTRL + Z (on Belgian keyboard) tries to close the file within the application.

**Comment by photopea** [comment]
I think I fixed it. Now, Photopea should detect the "local" keyboard layout. Please, let me know if it works now.

**Comment by DjovDev** [comment]
That was fast! :)

**Comment by photopea** [comment]
I could be faster, but I was playing a game on my phone.

**Comment by pieterjandesmedt** [comment]
Not sure this is fixed... On a Dvorak keyboard, Ctrl+Z zooms out, while Ctrl + ; does undo. Keys te select tools seem to randomly work or not.

**Comment by photopea** [comment]
Hi, what character is typed when you press Z on your keyboard? If it is Z, then, Ctrl+Z should do a step back.

**Comment by pieterjandesmedt** [comment]
Yeah, that's the weird part: typing `Z` in text tool gives me a Z, but `Ctrl+Z` doesn't do Undo, while `Ctrl+;` does. The `;` on Dvorak corresponds to the `Z` on Qwerty.

**Comment by photopea** [comment]
I think I have fixed it. Now, if some key generates a letter between A and Z, it should be recognized correctly.

**Comment by pieterjandesmedt** [comment]
Amazing that you can fix things this fast! Shortcuts with letters seem to work correctly now. Only some shortcuts that have no letter in them still have weird effects. E.g.: `Ctrl+.` does Merge Down (Dvorak `.` is on the position of Qwerty `E`).

**Comment by photopea** [comment]
That should be fixed now, too :)

**Comment by pieterjandesmedt** [comment]
I went through the Keyboard Shortcuts and found a few more Dvorak bugs :)

- `Ctrl + ;` does Undo like `Ctrl + Z` now, instead of Show/Hide Guides
- `Ctrl + Alt + Shift + S` does Show/Hide Guides instead of Export
- `Ctrl + '` does nothing, should Show/Hide Grid
- `?` does nothing, should show Keyboard Shortcuts
- `Ctrl + Alt + T` opens Preferences (like `Ctrl + K`), should do Free Transform
- `Ctrl + Alt + G` does nothing, should  do Clipping Mask
- `Ctrl` on mac doesn't do Move, but `Cmd` does (maybe just change the Keyboard Shortcuts page)

Everything else works now!

**Comment by photopea** [comment]
I don't know if these shortcuts are possible to detect. On each keystroke, we only know what hardware key is pressed, and what character could be typed at that keypress.

When you hold Ctrl+Alt and hit T, we know only, that it is "a hardware K". Does it type T when you hit that combination in some text field? If not, there is no way for us to tell, that you wanted Ctrl+Alt+T to be performed.

**Comment by photopea** [comment]
But it seems like if you press Ctrl+Alt+T, the browser should tell us, that the T corresponds to typing "t". So it is really strange.

Can you update your OS and the browser?

**Comment by pieterjandesmedt** [comment]
I don't know which library you're using to intercept keystrokes, so I can't really help there, but when I press `Ctrl + Alt + T`, I get this:
```
KeyboardEvent: key='Control' | code='ControlLeft'
KeyboardEvent: key='Shift' | code='ShiftLeft'
KeyboardEvent: key='T' | code='KeyK'
```
[via here](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/code)

So the (hardware) keycode is `K`, but the (software) key itself is `T`. Is it possible to interpret `KeyboardEvent.key` instead of `KeyboardEvent.code`?

**Comment by photopea** [comment]
You see, we only know a "KeyK" and "†" , none of them are related to a letter "T".

Can you reconfigure your keyboard, so that Alt+T still types "t" instead of a symbol "†" ?

**Comment by pieterjandesmedt** [comment]
When I set the keyboard to Qwerty, `Alt+T` still gives the dagger symbol. I guess it's a Mac thing.
```
KeyboardEvent: key='Control' | code='ControlLeft'
KeyboardEvent: key='Alt' | code='AltLeft'
KeyboardEvent: key='†' | code='KeyT'
```

`Alt+G` is `©`
`Ctrl + Alt + Shift + S` is `Í`

**Comment by photopea** [comment]
I know about that. Photopea considers the "key" parameter, only if it is a letter between A and Z. Otherwise, it ignores it and the "code" parameter is used.

So if you switch to Qwerty keyboard, everything should work well.

**Comment by pieterjandesmedt** [comment]
So only shaky support for keyboard layouts other than Qwerty? Example for the question mark `?` that you need to access keyboard:

In Belgian/French Azerty:
```
KeyboardEvent: key='?' | code='KeyM'
```
In Dvorak:
```
KeyboardEvent: key='?' | code='BracketLeft'
```
In German Qwertz:
```
KeyboardEvent: key='?' | code='Minus'
```

I agree Javascript keyboard input is hard, but I think it would be a good thing to let Photopea move away from the 'code' and only look at 'key', or it risks alienating a lot of international users. You can't just tell everyone to 'switch your keyboard to qwerty'. Ok, you can, because Photopea is your creation, but it's not very user-friendly :)

I mean... Photoshop has _a lot_ of non-letter shortcuts. Often-used things like increase/decrease brush size/hardness or Snap are handled by non-letter shortcuts...

**Comment by photopea** [comment]
@pieterjandesmedt But as you see, if we detect only the "key" and ignore "code", we can not detect Alt+Ctrl+Something in your case. Am I right?

**Comment by photopea** [comment]
So let's say Photopea requires a shortcut Shift+:  to do something. But the keyboard of your country requires holding Shift to type a colon. What should we do in such case?

Also, cyrillic keyboards don't have latin letters at all :(

**Comment by pieterjandesmedt** [comment]
Well, I wouldn't try to solve this kind of hairy problem myself, since it has been solved already by people smarter than me. Just use a robust library like [hotkeys](https://github.com/jaywcjlove/hotkeys) or the like. It's super easy to define key combinations and detects everything just fine, even on my weird keyboard ;)

**Comment by photopea** [comment]
Are you sure it detects all combinations we need even on your keyboard in Mac?

**Comment by pieterjandesmedt** [comment]
I tested this:
```
hotkeys('[,],{,},shift+[,shift+],ctrl+;,ctrl+alt+t,?,shift+/', function (event, handler) {
  console.log('handler.key', handler.key)
  console.log('event.key', event.key)
});
```
output:
```
handler.key shift+/
event.key ?

handler.key [
event.key [

handler.key ]
event.key ]

handler.key shift+[
event.key {

handler.key shift+]
event.key }

handler.key ctrl+alt+t
event.key †

handler.key ctrl+;
event.key ;
```
So here you could check both `handler.key` and `event.key` and then see if you need to execute some function. That should cover all bases, I think.

**Comment by photopea** [comment]
But I think that library depends on a "keyCode" value, which is not recommended to use in new browsers :/

https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode

**Comment by pieterjandesmedt** [comment]
Hmm, ok... What about [mousetrap](https://craig.is/killing/mice)?

**Comment by photopea** [comment]
Are all shortcuts working in mousetrap? I think all these libraries, that are 10 - 15 years old, use the keyCode property. It seems like it is not possible to detect some shortcuts without it.

I submitted a request to hotkeys: https://github.com/jaywcjlove/hotkeys/issues/198

And to Chrome Developers: https://bugs.chromium.org/p/chromium/issues/detail?id=1090008

**Comment by photopea** [comment]
Could you check, what is the value of "keyCode", when you press Alt+Ctrl+T on your keyboard?

**Comment by pieterjandesmedt** [comment]
This is the event:
```
keydown Alt-Control
  altKey: true
  charCode: 0
  code: "KeyK"
  composed: true
  ctrlKey: true
  key: "†"
  keyCode: 84
```

**Comment by photopea** [comment]
That is rigit, keyCode 84 means a "T" key, and we can detect it through that (just like hotkeys and mousetrap do)

I am just confused, because the latest standards suggest not using this property. I decided to ask the W3C directly here: https://github.com/w3c/uievents/issues/267

**Comment by pieterjandesmedt** [comment]
Yeah... Using `code` is not the way to go. [This page](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key) says:
> `KeyboardEvent.code` is useful when you want to handle keys based on their physical positions on the input device rather than the characters associated with those keys; this is especially common when writing code to handle input for games that simulate a gamepad-like environment using keys on the keyboard.

But the value of `key` gets modified by the `shift` and `alt` keys, leading to weirdness like `†`
> The `KeyboardEvent` interface's key read-only property returns the value of the key pressed by the user, taking into consideration the state of modifier keys such as `Shift` as well as the keyboard locale and layout.

So that leaves `keyCode`, or maybe a combination of `keyCode` and `key`?

**Comment by photopea** [comment]
@pieterjandesmedt now, for Photopea in Chrome, shortcuts shouls work well for any keyboard settings (including Dvorak). Can you please check if everything works well in your case?
