### ISSUE TITLE
PWA issue: Set Photopea as default for opening .psd files

### ISSUE THREAD

**Issue by rcoenen** [photopea/photopea#1901]
I have installed Photopea as Progressive Web App, so that I can easily launch it on my Mac without having to fire up Chrome first. It lives on my Mac like a standard app with it's own icon on the dock and everything else you'd expect from a regular app.

I then proceeded to associate Photopea with psd files, setting it to be the default app to open psd files on my Mac

Sadly, when double clicking (or right-click and use "Open with" and then select Photopea) on a PSD file, it correctly opens the PWA version of Photopea, but Photopea then does not proceed to load the PSD file itself. 

Please fix if possible! This would greatly enhance my workflow

![image](https://user-images.githubusercontent.com/753704/72671058-d83e3800-3a12-11ea-808c-9ecb9e7f6af1.png)

**Comment by photopea** [comment]
Hi, I did some research and it seems like it is not possible to do it at the moment :(  But if you find a web app, which can do it, let us know and we will implement it in a similar way.

**Comment by perice** [comment]
Hey,

I think it can be done:

https://blog.ailon.org/pwa-on-windows-file-type-association-50ff97c97620

Do you think that would work for Photopea?

Thanks,
Peter

**Comment by photopea** [comment]
@perice I don't think it can be considered a web technology. That solution will only work only on MS Windows and only for people, who have Microsoft Store accounts.

That would be quite similar as converting Photopea to a native app for a specific operating system and distributing it on the app store for that system. We prefer to implement open technologies only, which are not dependent on any specific operating system or any specific company.

**Comment by perice** [comment]
@photopea got it, thanks!

**Comment by TheCelticChemist** [comment]
The feature is here, the future is now. Here's how to set up Google Chrome progressive web apps (like Photopea) in Windows as default file handlers in 7 steps:

**STEP 1:**
![Step 1](https://user-images.githubusercontent.com/14154480/149047059-1add77a6-90b3-4e5a-aae7-5b255553bdf1.png)

In Google Chrome, go to Photopea.com and 'Install app' from the address bar to install it as what is known as a "progressive web app."

![Step 1 Result](https://user-images.githubusercontent.com/14154480/149047243-e4c169e4-095a-41d5-a4ef-cb8a469906f3.png)

You will now see Photopea open in a new window and show in your taskbar, which you can pin to your taskbar for future use. As a bonus, I'll show you how to easily add a Photopea shortcut to your desktop and start menu at the end of this tutorial.

**STEP 2:**
![Step 2](https://user-images.githubusercontent.com/14154480/149047761-289c6f89-fa86-454f-9173-132ad20d2e23.png)

In Google Chrome, go to chrome://flags. Look for 'File Handling API' and set it to 'Enabled'. (This feature is experimental, but I can assure you firsthand that it works.) For this to take effect, your Photopea progressive web app will likely need to close along with your Chrome browser needing to restart. If it somehow doesn't automatically, then I recommend you close them and reopen Chrome manually.

**STEP 3:**
![Step 3](https://user-images.githubusercontent.com/14154480/149042903-989b9254-d3ce-4d87-8b52-7f11c0a1b16b.png)

If you would like all files of a certain type (like .psd files), to be opened by default in Photopea, then find and select a file of this type. You'll notice in my step 3 example image that the GIMP icon is in the lower right corner of the file, meaning my file is presently set to open by default in GIMP. We're going to change this to Photopea.

**STEP 4:**
![Step 4](https://user-images.githubusercontent.com/14154480/149043109-9a4caaf9-bd7a-4c25-88ad-ef55b8106320.png)

Right click it. (Yes, I'm a stickler for fine detail. Better to be too clear than to be too vague.)

**STEP 5:**
![Step 5](https://user-images.githubusercontent.com/14154480/149050115-7408c69b-6cef-47d8-87a7-2a5a5ec441f3.png)

Click 'Open with'. You will likely see Photopea in the expanded context menu, but _don't_ select it here unless you specifically want to open the file in Photopea _without_ setting Photopea as the default for opening this file type.

**STEP 6:**
![Step 6](https://user-images.githubusercontent.com/14154480/149050495-a0690743-9c05-4ee0-a32d-f5152b894495.png)

In the 'How do you want to open this file?' prompt screen that pops up, select Photopea. **If you want to ensure Photopea opens this file type from here on out,** then check 'Always use this app to open .psd files." Though if the file you are using for this is not a .psd file type, then instead of ".psd" it will say the file type of the file you selected. NOTE: You can always follow these steps again to set another application as the default for these file types later.

**STEP 7:**
![Step 7](https://user-images.githubusercontent.com/14154480/149051156-38fd0e5d-963a-4bed-9e65-ea7b9d3cdb4a.png)

A new prompt should show saying "Don't ask again when opening these file formats in this app." This will _not_ set all of these file types to be opened in Photopea by default. The only upside to checking this is obviously that you won't be bothered by this each time you try to open any of these file types.

**NOTE:**
![Step 7 Note](https://user-images.githubusercontent.com/14154480/149051803-28595016-3ce9-4a3e-8c1b-c2139c995d11.png)

The one minor downside I noticed after checking this is that the next time I tried to open a file type that was listed such as a .png (or as in my example, a .ico file type) I was shown a "How do you want to open this file type?" prompt again only it asked "Keep using this app?" And as well, I once again had to select "Always use this app to open _____ files?" It appears the first time you open any and every one of the file types that are listed in the previous prompt at the start of step 7, then you will have to reestablish your default application for opening them through this new prompt. It's a fairly minor inconvenience since it's only the once if you select "Always use this app to open _____ files?"

![Step 7 Result 1](https://user-images.githubusercontent.com/14154480/149052860-3926849f-656c-40f7-980a-8cc2eb550455.png)

And if your file is in fact compatible with Photopea, then it should open up directly in the app from here! You did it! The last thing to note is that any file you set up to open by default in Photopea will open in a new window. Though you can always drag the tab of your project at the top of the screen into the window you mean to be working in and then close out of this new window.

![Step 7 Result 2](https://user-images.githubusercontent.com/14154480/149053259-78f4b00f-4217-4eff-90dd-7338db1b6da6.png)

Now you'll notice that your file has a new icon in the bottom right corner that is the same icon as the Chrome Web Store. And yeah, I know... I wish it was the Photopea icon too, but I can only do so much. If you figure out how to make it show as the Photopea icon, then I'd be interested in knowing how, so please share with the rest of us. Now as promised...

**BONUS**
![Bonus 1](https://user-images.githubusercontent.com/14154480/149059576-fb54701d-9176-4fdd-a806-d2083377765b.png)

In Google Chrome, go to chrome://apps. If you already have apps then there's a good chance that (for whatever reason) your new apps appear on the next page, which you can access by clicking the arrow on the right, or navigate by the tabs at the bottom.

![Bonus 2](https://user-images.githubusercontent.com/14154480/149059660-179c58e7-d772-4e3e-85d2-47dfedf6cf23.png)

You can drag and drop this into the first page of apps if you have room.

![Bonus 3](https://user-images.githubusercontent.com/14154480/149059716-bcc865b1-653b-4ffa-bf45-d24b674aa1c8.png)

Right click the Photopea app and the select "Create shortcuts..."

![Bonus 4](https://user-images.githubusercontent.com/14154480/149059806-e402385a-4b27-48b8-8a3f-cdaa7b8d9d2d.png)

From here you can check to create a desktop shortcut and/or a start menu shortcut. And that's all, folks! Enjoy using Photopea like a standalone app now! Unless of course you are in the wrong section of Photopea when you click "Ctrl H" and open up your Chrome history, _amiright?_ I can't be the only one being driven crazy by that...

**Comment by MichalSZZ** [comment]
Great work. I didn't check it yet, but I have to try it on my second laptop (where I don't have Adobe CC)

**Comment by rcoenen** [comment]
That's great! Is this now possible due to an enhancement in Google Chrome
or are you exploiting a feature that was always there? Is it Chrome
specific? Should it work on Mac or Linux?

**Comment by photopea** [comment]
I recommend to wait, until it is available in a stable Chrome. Then, it will work for everyone by default, without changing any settings.

**Comment by rcoenen** [comment]
I just tried this.. and it works amazingly well! Wow. Game changer!
Workflow improvement of 1500%!

this is the missing link that allows me to delete Photoshop once and for
all!

**Comment by TheCelticChemist** [comment]
It is my understanding that this is a very new feature. The first mention I saw of using progressive web apps as the default file handler was just a few weeks old. I had to do a bit of a deep dive to find the solution we were looking for. And since I remembered this being the top result when I started my web hunt, I thought I should come back and share using as many keywords as possible so others could find this through a Google search. I'm glad it worked for you and hopefully Chrome implements this as a standard feature here soon. As you can see from my chrome://flags page, I don't usually mess around with experimental features. The only downside I noticed though was that Chrome refused to open back up after I implemented it until I restarted my computer. Hopefully you didn't have that issue because I forgot to include it in the tutorial.

**Comment by TheCelticChemist** [comment]
Also, as I don't have Mac or Linux, so I can't testify as to whether it will work on those devices. Sorry about that. But at least we know it works for PC only about a year after you asked. lol

**Comment by rcoenen** [comment]
It fails on Mac. You can associate .psd with the Photopea PWA but when you
then double click, it fails to open

**Comment by rcoenen** [comment]
@TheCelticChemist How about saving non-PSDs back to the file system?
For example, here I have opened a .png file in Photopea/PWA (right click -> open with -> Photopea)
I made a modification and now I want to save the file back to the filesystem. 
But I can not simply hit 'save' I need to save it as a .PSD first?

It would be great if you could open, modify, and then save back in the original format for at least .png and .jpg in addition to .psd

![image](https://user-images.githubusercontent.com/753704/149364202-9d6a3a9d-abbe-40aa-ac36-753ad81d6b97.png)

**Comment by photopea** [comment]
I am not completely sure if it is a right thing to do.

Saving a JPG or a PNG requires setting the quality, etc.  If the default quality of Photopea is not good enough for you, it will be a problem, because the old version of your file will be lost (the new version will rewrite it).

Also, I think many people expect, that after pressing "Save", it should save the entire work with layers and everything. They might be surprised, that after saving, they ended up with just one JPG and everything else is lost.

**Comment by rcoenen** [comment]
I agree that opening-saving JPEGs leads to generational loss, and that
saving back in JPEG with the same compression level is tricky (because you
cannot work out what compression setting was used initially)... yet this is
exactly what Photoshop does.
Try it: open a JPEG, make a modification,m hit CTRL-S. It saves directly
back to JPG and no compression quality window pops up first.
I suppose they're using some EXIF or other meta-data to store compression
settings? And when unavailable b./c you opened a JPEG from another tool
that didnt save the compressionlevel as  meta-data... they might popup a
compression window before save?

Quite often I am not using layers at all. I simply want to quickly cross
some privacy sensitive data out or whatever or maybe crop some stuff off
and save it back. That is more than 50% of what I use Photopea form
Either way, the workflow would improve massively. Think about use
cases where you just need to annotate a screenshot for some documentation
or something.. and where pure quality is not the highest priority.

**Comment by photopea** [comment]
Ok, I will do it :) please, start a separate issue for it.

**Comment by rcoenen** [comment]
@photopea Brilliant, thanks! OK I have opened a new issue #4233

**Comment by MuoBinAlshekh** [comment]
>

**Comment by camoody1** [comment]
@MuoBinAlshekh Do you have a question or issue related to this ticket?
