### ISSUE TITLE
Plz add advanced lens blur effect with depth map reader as in psc6 2020!

### ISSUE THREAD

**Issue by 7Wdev** [photopea/photopea#1915]
Good job guys

**Comment by photopea** [comment]
I think it is done automatically in a phone when taking a photo. Do you really want to open your photo in Photopea and do it manually?

**Comment by 7Wdev** [comment]
Yes !!!! 
Look at this video :
https://youtu.be/URpkcNZqZeU

Don't care for the spoken language , just look at the filter and how to setup depth map on it, it is very awesome feature that photopea should be have it...

**Comment by MichalSZZ** [comment]
I use that functionality a lot! Few days ago I wanted to create similar issue :)

I use it for example to make a realistic blur of the shadow. Sharp near the object and more blurred at the end of shadow.

There is a many more examples how to use it.

And... it isn't a Smart Blur! :)
That is good news for you @photopea  because you can do it better than Adobe ;)

Here is nice simulator (reference for beginners in photographing) https://dofsimulator.net/en/
You can simulate many bokeh effects for the backgrounds and many more. 

And now... just try imagine something.
You have photo taken from smartphone with DOF. Open it in photopea. Photopea can show you oryginal file as a layer, DOF as a grayscale layer and Portrait photo as you can see in your phone.
With DOF changed in layer mask, you can reedit bokeh effect in Photopea to oryginal layer with many more possibilities (smartphone editors have small number of options).

**Comment by MichalSZZ** [comment]
And that isn't any new feature in Photoshop 2020. Lens blur is in PS since 10(?) years? :)

**Comment by 7Wdev** [comment]
> And that isn't any new feature in Photoshop 2020. Lens blur is in PS since 10(?) years? :)

**Comment by 7Wdev** [comment]
> And that isn't any new feature in Photoshop 2020. Lens blur is in PS since 10(?) years? :)



> I use that functionality a lot! Few days ago I wanted to create similar issue :)
> 
> I use it for example to make a realistic blur of the shadow. Sharp near the object and more blurred at the end of shadow.
> 
> There is a many more examples how to use it.
> 
> And... it isn't a Smart Blur! :)
> That is good news for you @photopea because you can do it better than Adobe ;)
> 
> Here is nice simulator (reference for beginners in photographing) https://dofsimulator.net/en/
> You can simulate many bokeh effects for the backgrounds and many more.
> 
> And now... just try imagine something.
> You have photo taken from smartphone with DOF. Open it in Photopea. Photopea can show you oryginal file as a layer, DOF as a grayscale layer and Portrait photo as you can see in your phone.
> With DOF changed to layer mask, you can reedit bokeh effect in Photopea to oryginal layer with many more possibilities (smartphone editors have small number of options).

No, it still looks fake , the lens blur filter with depth map reader is more relastic

**Comment by MichalSZZ** [comment]
@7Wdev I look on the Videos in YouTube... all of watched be me is described as 2020 but... they use hand made mask for it...
 I don't know what do you mean by "it still looks fake", and why do you close issue...

**Comment by MichalSZZ** [comment]
It looks innatural because it is made by the program. PS can do that since 10 years and we bkth ask for that functionality in Photopea...
