### ISSUE TITLE
72 DPI export is too low for HD

### ISSUE THREAD

**Issue by ktdid518** [photopea/photopea#1926]
Will DPI export options be made available soon? I need to export to PS at 150 DPI.

Thanks!

**Comment by photopea** [comment]
You can set the DPI of a current document in Image - Image Size. Or is it related to the conversion from Sketch? Maybe we could read the DPI from Sketch files.

**Comment by ktdid518** [comment]
It's related to the conversion from Sketch to Photoshop. Sketch is vector based so all elements are always crisp and per their export settings you can choose what resolution. 

However, when dragging/dropping to Photopea there is no option to choose what resolution the conversion should be made in, aside from the option to further reduce DPI.

**Comment by photopea** [comment]
A PSD file, that you get in Photopea, is also vector-based. You can change the resolution in Image - Image size (if you double the resolution, you will not lose any quality, since the PSD contains only text, smart objects and vector shapes, which remain "smooth").

**Comment by ktdid518** [comment]
I do have some files that "are too large" to be upsized to 150dpi. BUT, most are upsizing OK.

I did not expect the upsizing outcome to work for bitmap images, but so far it's working well. Thank you again!

**Comment by photopea** [comment]
So I looked at the content of a Sketch file again, and I can not find any DPI info.

Sketch uses units (e.g. an artboard can be 1000x1000 units), but there are no parameters to deduce a physical size (how large is that artboard in Inches or meters).

Photopea assumes a default resolution of 72 Sketch units per Inch, and one sketch unit is converted into one pixel in Photopea. You can change these values it in Image - Image Size (e.g. enter a new size in Meters), without losing or gaining any quality.

**Comment by ktdid518** [comment]
Thank you!

**Comment by photopea** [comment]
You are welcome, thanks for buying a Premium account! :)

As you open Sketch files and save them as PSD, you can do the same with Adobe XD files, Figma files and even PDF files :)

**Comment by ktdid518** [comment]
Hey. I'm just revisiting this…

The resolution issue is still an issue. Photopea is not converting the vector sketch file to a vector photopea/photoshop file, so the files are stuck at the 72 dpi bitmap quality, which is too low for my needs—they cannot be sized up and retain quality.

Designing for web at 72 dpi is not done anymore as we are designing for HDI screens. 150 dpi is the minimum.

Can we get the choice to convert files at 150 dpi instead of 72 dpi?

This would be amazing!

Thank you!
<img width="1714" alt="Screenshot 2020-02-17 18 02 42" src="https://user-images.githubusercontent.com/57205847/74691427-c9cd7280-51b0-11ea-8581-6bbdb3c6ffb9.png">

**Comment by photopea** [comment]
Hi, Photopea IS converting the vector sketch file to a vector PSD file and they CAN be sized up and retain quality.

if you do Image - Image Size, you should be able to increase the "quality". It should work well. Why are you saying it does not work?

**Comment by ktdid518** [comment]
It's not working that way for me at all. My files are pixelated and not vector. When I scale up the DPI per Image Size, it does nothing to change that. You can see the poor resolution on the example I included.

**Comment by photopea** [comment]
You have to increase the size in pixels, not the DPI value. If your document was 100 pixels wide and you keep it 100 pixels, you will still be 100 pixels wide (the pixel is a tiny square with a same color over its whole area).

![pea](https://user-images.githubusercontent.com/15955558/74691933-3bbfaf00-51e5-11ea-9738-8cfdbab6f008.png)

**Comment by photopea** [comment]
We can not produce 2x or 10x higher resolution for everybody, as it would result in huge PSD files (gigabytes in size) for large Sketch files.

**Comment by ktdid518** [comment]
Here's a screeshot of a file viewed at 100% just after converting from sketch to photopea—you can see the pixelation.
<img width="1293" alt="Screenshot 2020-02-17 18 23 28" src="https://user-images.githubusercontent.com/57205847/74691940-faaea700-51b2-11ea-8fa9-473c7ad7e9df.png">

Then, when I zoom in, this issue is more apparent.
<img width="1689" alt="Screenshot 2020-02-17 18 23 36" src="https://user-images.githubusercontent.com/57205847/74691960-1154fe00-51b3-11ea-84a5-9a9cd589f459.png">

**Comment by ktdid518** [comment]
We need 2X PDFs though…that's the nature of what we do now.

I am unable to size-up per Image Size view the dimensions. I get a black artboard as my results.

<img width="1239" alt="Screenshot 2020-02-17 18 30 22" src="https://user-images.githubusercontent.com/57205847/74692111-c4bdf280-51b3-11ea-9485-59b422c2ac77.png">
<img width="1127" alt="Screenshot 2020-02-17 18 30 45" src="https://user-images.githubusercontent.com/57205847/74692112-c5568900-51b3-11ea-9de2-3e53e6f70e84.png">

**Comment by photopea** [comment]
In Adobe Photoshop, the maximum document size is 30 000 x 30 000 pixels. 

So if your artboards are 19 000 pixels wide in Sketch, and you want it to be 38 000 pixels in a PSD file, I am afraid such PSD file can not exist :(

**Comment by ktdid518** [comment]
That was me attempting to scale up via the dimensions. 

That sketch file is: 1280px x 9578 px, vector.

After I drag and drop it into Photopea, Image Size says it is: 1280px x 9578 px, 72 dpi (too low res, not vector).

Scaling up via the resolution in Image Size to 150 dpi does not improve quality as you said.

I attempted to scale up per your recemmendation via the dimensions 2X: 256 px x 19156 px, 72 dpi — this produces the black screen.

So…I cannot achieve vector or high res skecth file conversions via Photopea.

**Comment by photopea** [comment]
Black screen? There is probably not enough memory in your graphics card.

You can save it as a PSD anyway, it should look well in Photoshop. Or you can simply do Image - Image Size in Photoshop, it will produce the same result.

**Comment by ktdid518** [comment]
Because the file is 72 dpi and not vector, I cannot scale up cleanly in photoshop either, it looses quality, not gains it. I'm stuck with 72 dpi  :-(  I need 150 or vector.

**Comment by photopea** [comment]
Please try it in Photoshop. If you enter the DPI 150 in Photoshop, and check "Resample", you will get the graphics in a double resolution.

**Comment by photopea** [comment]
PSD files from Photopea are vector files. If you open a Sketch file in Sketch App, and look at your monitor with a magnifying glass, you will also see pixels. That is not what a vector graphics mean.

**Comment by ktdid518** [comment]
Yes, I have even tried this in Photoshop even though I know better. Vector is math based and crips lines that are endlessly scalable. These files are not that. They are bitmap and resolution-dependent. A file that is 72dpi cannot be made twice it's size and maintain quality or improve quality—it only degrades—which is the case here. So when I upsize the 72 dpi Photopea in Photoshop it does not turn the bitmap pixelation to clean vector lines.

I appreciate the hard work you've done to create this product and I am a paying user. Like I said this is the biggest roadblock in using your product. The first like app to allow high res conversions will be the winner.

**Comment by photopea** [comment]
Here is one of my Sketch files, right after I open it in Photopea and zoom in. The text "Commit Log" is about 20 px tall.

![image (4)](https://user-images.githubusercontent.com/15955558/74734707-63e3f800-524f-11ea-9407-d2c7c224a2ee.png)

Then, I go to Image - Image Size, check "Resample", and enter the DPI of 150 (instead of 72). 

![image (6)](https://user-images.githubusercontent.com/15955558/74734754-7b22e580-524f-11ea-8e1f-8ed3dc31fbc8.png)

Now, the resolution is bigger. The text "Commit Log" is about 50 px tall.
![image (5)](https://user-images.githubusercontent.com/15955558/74734830-aad1ed80-524f-11ea-85f1-d8752f07f433.png)

I can enter the DPI of 300 or even 1000, everything will look smooth, because vector graphics do not lose quality during scaling.

**Comment by ktdid518** [comment]
I do not have a "resample" tick box to check, but it shouldn't matter, right? 

Again, here's a sketch file right after opening in Photopea (it's not smooth):
<img width="1429" alt="Screenshot 2020-02-18 09 19 57" src="https://user-images.githubusercontent.com/57205847/74744317-08564200-5230-11ea-8e95-e2df71570b99.png">

And, here it is after I've upped the resolution to 150 (still not smooth):
<img width="1601" alt="Screenshot 2020-02-18 09 20 35" src="https://user-images.githubusercontent.com/57205847/74744373-1d32d580-5230-11ea-8467-cdebbabd3b42.png">

**Comment by photopea** [comment]
Please, reload Photopea with an F5 button (or a Reload button in your browser). We updated it today. You are probably still using a version from yesterday. There should be a "Resample" tick box for everybody, who visits www.Photopea.com

**Comment by ktdid518** [comment]
I now have the "Resample" tick box. However, the 72 dpi issue is still the same :-(

**Comment by photopea** [comment]
I dont know what 72 dpi issue you mean. If you double the DPI, there should be 2x more pixels for the same object (e.g. for a letter or a circle).

**Comment by ktdid518** [comment]
The files is restricted to be no more than the quality of a bitmap 72 dpi. It ca nbe scaled up, BUT that obviously does not increase the quality. The type is pixelated. Only a few objects are "smart" (vector). I need clean, smooth, high res files.

As I said from the beginning, 72 dpi is not suitable for web design files in 2020. They must be 150 dpi.

**Comment by photopea** [comment]
As I said, you can change the DPI of a PSD file in Photopea or Photoshop.

As you saw in my example above, the text is scaled accordingly. I think you dont understand how it works :(

Could you make a Sketch file, and then, recreate the same thing in Photoshop as a PSD file, so that I can see, how do you want the PSD to look like?

**Comment by ktdid518** [comment]
I completely understand how it works…I've been doing this for 20 years. 

Can you get someone else on your team to help?

**Comment by ktdid518** [comment]
Increasing the size does not increase quality. I need 150 dpi (at least) (preferably vector, like Sketch) quality as all other web designers do.

**Comment by photopea** [comment]
If you entered the DPI 150 in Photopea, it is a PSD file with a DPI of 150. How can you prove it is not?

**Comment by ktdid518** [comment]
Yes, the DPI changes, BUT NOT THE QUALITY. The quality is the issue as I stated from the beginning. We need the files to be 150 dpi from the start.

**Comment by ktdid518** [comment]
Please pass this along to another team member who better understands. Thank you.

**Comment by photopea** [comment]
I am the only creator of Photopea. I am afraid you do not understand how Photoshop and PSD files work. 

If you can recreate a Sketch file in Photoshop, and it looks differently than the PSD from Photopea, I can even pay you for it :D

**Comment by ktdid518** [comment]
Well, then we're stuck with low res 72 dpi files.

**Comment by MichalSZZ** [comment]
@ktdid518 I have a few questions:

1. Do you work on **high density screen like Retina?**
2. Do you talk about what do you see on screen in Photopea vs the same project viewing in Sketch?
3. The problem is in exported PDF files with your project AND/OR exported assets AND/OR only in viewing it in program before an export?

I have PC with standard screen. Mac with retina. Newest Photoshop and other CC programs. I can check it even in Figma or Sketch tommorow to try help you, but I must to know excacly where is the problem. 

Photopea is pixel based program like Photoshop. And you can not zoom in endless with sharp (vector like) edges. In Illustrator you have view like in Sketch (vector base view) but you can change rendering view to pixel and then zooming (not scaling) vectors shows pixels like in Photoshop or Photopea.

My retina screen on Mac have 144dpi (PPI) probably, because when I make screenshot and paste it in Photoshop, it have that DPI (PPI) in "create new" panel. 

But I have same opinion about DPI like Ivan. It doesn't matter in web designing. 
When I make website project in Photoshop, I set up 72 DPI and work in real pixels (like 1920 width)
The other thing is how I prepare elements in my design for export. When I have image in avatar and it is a raster graphic, I can make Smart Object at 1/2 or 1/3 real size of graphic in it.
When I create assets, I can set @2 and @3 in export panel for rasters (SVG with vectors dont have that problem).
When I'm coding HTML/CSS I use bigger images (like @2 mostly, @3) twice big in pixels not twice bigger in DPI!

**Comment by ktdid518** [comment]
Hi @MichalSZZ 

Thanks for jumping in and lending an extra hand.

1. Yes, I work from a retina screen which means that anything still set to 72dpi looks pixelated to me. As most devices that we design for now are also high density, this is the case for them as well—as you know, which is why we no longer supply 72 dpi assets for web. (Yes, SVG when possible, and 2X for .jpgs, etc.)

2. Sketch is vector so all elements appear smooth. When I open sketch files in Photopea they are degraded to 72 dpi bitmap which makes them pixelated on my retina screen—the type is jagged.

3. I am currently only using Photopea to covert full web page layouts to Photoshop to provide to developers. As the conversion from sketch to Photopea degrades the file from vector to low res bitmap, I am stuck with that low res quality, when I truly need at least 150 dpi (144). I would always handle an of the assets outside of Photopea for handoff.

I completely understand all the things you’re saying…expect that for me, it’s very important that my text render smoothly and that is not happening at 72dpi. This is why it would be very useful of the conversion from sketch to Photopea created files at 144 dpi to start.

Thanks for any help you can offer!

**Comment by MichalSZZ** [comment]
> Thanks for jumping in and lending an extra hand.

I'm "jump in" that convesation because I understand both of you :)
I agree with Ivan (author of the Photopea) who said that in graphics making for screens, DPI doesn't really matter for endpoint user.
And i'm agree with your feelings when viewing something on high density display. That is a problem with Photopea but with Photoshop too. Both programs render view as a pixels (even fonts or vector graphics).

Endpoint user will have perfect website (app or anything that your team is making).
I say that, because what you see on Photopea, is not what endpoint user will get in the browser.
Frontend developers will code text as a text for example. 

Can you try do one thing...?
With your oryginal sketch project (opened by Photopea), go to file -> "export as" and use .svg.
What do you see on Retina display in preview window (save for web)? Clear and sharp fonts? That is the point - I think that window use a browser preview not pixel preview like in Photoshop or Photopea. Sketch maybe use that type of preview all the time (I can't test it now, but I can go to someone from my company who have Sketch and Retina display). 
When I drag and drop photopea window (with opened save for web popup) to my 24" monitor I see pixels. When I drag again to Retina, that feeling is disapearing magicaly ;) 

I don't say that everything is OK witch Photopea now (I see some "DPI"/resolution bugs when opening file made in PS - but I think that Ivan try to resolve your problem and he is testing online :) )
