### ISSUE TITLE
zoom glitch: zooms out when should zoom in.

### ISSUE THREAD

**Issue by blordpluto** [photopea/photopea#1949]
### Steps to Reproduce:

On a modern mac laptop, on a clean new document, hold the ⌘ key and press minus. The canvas zooms out. That is as expected.

Then, without lifting your finger from the ⌘ key, press the plus key. Unexpectedly, the canvas zooms out a second time, when it should zoom in (back to its original magnification.

I can reproduce this at any initial zoom level. (Curiously, it doesn't seem to happen in the other direction, when the first step is a zoom-in, followed by a zoom-out. But any zoom-in that occurs after a zoom-out gets misfired as a zoom-out.) I often play around with zoom, trying different magnifications while I work, so this is really jarring for me.

P.S. Ivan, congratulations on an incredible project. Really impressive, game-changing work. 🏆

**Comment by photopea** [comment]
Hi, I believe it is a bug in Mac OS. When the Command key is pressed, it does not inform the webapp about releasing of any keys.

This app shows, which keys are pressed at the moment: http://jsfiddle.net/p45f44zb/14/ . Click into the white area and press the same keys you did in Photopea.

It is also mentioned here: https://stackoverflow.com/questions/27380018/when-cmd-key-is-kept-pressed-keyup-is-not-triggered-for-any-other-key

Try to update your Mac OS. Maybe it is fixed in the latest version.

**Comment by blordpluto** [comment]
Thanks for the quick reply. I am on 10.14.6 and can reproduce that the keyup in the fiddle doesn't fire when the cmd is still held. Looks like this is expected behavior, and never going to be fixed. Nevertheless I have seen some other browser apps work around this. And there really should be a workaround.

I don't see why keyup not firing really matters here. Can't you just listen for keydown on minus/plus. Then if the meta key is depressed, fire the event appropriate UI event? It's expected that the meta key goes down before the other character, so as far as I can tell you don't need to handle the reverse-order case when the user holds plus, then presses command.

**Comment by photopea** [comment]
When you press the Plus key, Photopea thinks both Minus and Plus are pressed. So it is not clear, if you want to zoom in or out.

**Comment by blordpluto** [comment]
Right, that's the bug. My point is it could be made clear _if the callback gets the triggering event, and not only a flat list of currently depressed keys_. I can't see your code of course but in principle it's very possible.

**Comment by photopea** [comment]
You mean, if the user presses both Plus and Minus, and holds both, it should zoom outside, because Minus has been pressed later, after Plus. But we try to keep Photopea as simple as possible, and holding both Plus and Minus is "undefined behaviour".

It is sad, that Apple did not fix this bug eariler. It is even more sad, that people still buy their products. I hope that gradually, it will be replaced by better operating systems.
