### ISSUE TITLE
Modifiers messed up on Chromebook

### ISSUE THREAD

**Issue by wernight** [photopea/photopea#196]
Sure I'm aware of the nightmare of Alt behaving as a right click on Chromebooks.

Outside of that, especially on Chromebook but not only, often it seems that Photopea thinks that I'm holding down some modifier keys like Ctrl / Alt / Shift, when I'm not. It looks as if there is an internal state that remains. I'd suggest to reset the modifier state on most operations. Like selecting a tool with the mouse, pressing escape...

**Comment by photopea** [comment]
Hi,
it happened to me, when I clicked Ctrl+T for a free transform, but due to a bug in Chrome, it opened a new Tab. I released the Ctrl while being in the new tab, and after returning to PP, it thought that Ctrl is still pressed ("keyup" event was not delivered to PP).

For that case, there is a feature, that after going outside the PP, all keys are reset to the "released" state. Maybe your problem is related to something else ... could you try to find a sequence of actions, which leads to this behaviour?

**Comment by wernight** [comment]
For example Ctrl + Alt + Space + Click will show the context menu but then PP thinks Alt remains pressed.

Using it a while I find PP sometimes getting stuck on some keys but not sure which. I mean that I don't have yet reproducible steps for other modifiers.

**Comment by photopea** [comment]
Can you try it here: http://jsfiddle.net/p45f44zb/3/  - different key combinations? Can you get to a state, when you don't hold any keys, but it shows you, that you are still pressing a key?

**Comment by wernight** [comment]
This fiddle cannot capture special keys. I think only a website run as standalone is *capable* of capturing them.

Looks like it's possible to capture them: https://stackoverflow.com/questions/7836204/chrome-fullscreen-api
