### ISSUE TITLE
PNG transparency black

### ISSUE THREAD

**Issue by chanels88** [photopea/photopea#2000]
I have saved out a PNG image with a transparent background. When I bring it into inDesign the transparency shows as black.

Is there a way to fix this?

**Comment by photopea** [comment]
Hi, what version of InDesign are you using? Old Adobes software can not handle paletted PNGs with transparency (it is a bug). Can you update your InDesign?

Otherwise, when you export a PNG from Photopea, check "don't use palettes". The PNG file will be a bit larger, but you will avoid that bug in InDesign.

**Comment by chanels88** [comment]
We just bought inDesign for use in the Office last week so I'm assuming it's pretty up to date. I'll try the "don't use palettes" option and see how that goes!

**Comment by chanels88** [comment]
Yep, that last fix worked. Thank you so much :-)

**Comment by photopea** [comment]
I wrote an email to Adobe, maybe they will fix it in the future version. The standard for transparent paletted PNGs exists for many years, so it is really strange, that they still did not fix it.
