### ISSUE TITLE
Complex SVG Animation from LOOOM

### ISSUE THREAD

**Issue by enzyme69** [photopea/photopea#2002]
[_defb9acf-0664-4fa1-bb30-a56834d2ea3e.svg.zip](https://github.com/photopea/photopea/files/4357571/_defb9acf-0664-4fa1-bb30-a56834d2ea3e.svg.zip)

I am loading a complex SVG from animation app called LOOOM.

The SVG loads fine per folder wise, but the color disappear and also, only 1st frame seems to be displayed, the rest SVG is simply a blank vector.

Is there a quick way to export SVG folder into animation?

Also, is there a quick way to simply batch save all "folder" as each separate SVG?

<img width="1221" alt="Screen Shot 2020-03-20 at 12 37 48 pm" src="https://user-images.githubusercontent.com/3952687/77129506-587f2900-6aa8-11ea-9926-67a1100726e2.png">

**Comment by photopea** [comment]
Hi, I fixed the problem with the colors.

When you see a "blank vector", it is because their parent folder has the Opacity set to 0.

I don't think there is any reasonable way to build the CSS animation editor into Photopea :/ Currently, an SVG file is converted into a PSD, and then, a PSD back to a SVG, and many original parameters may be lost.

**Comment by enzyme69** [comment]
Thank so much! Color is working and opacity also, perfect! Can I do 1 time donation cheers~

**Comment by photopea** [comment]
You can order a Premium account. They are based on one-time payments, there are no "recurrent" payments.
