### ISSUE TITLE
Continue writing after changing font

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#2030]
I started typing some text. After I typed first word with selected font I wanted second word to be with different font. So I changed font in toolbar in top and closed font list. But now I wanted to continue writing text with new font but it does not work and when I click for example some letter V it changes tool to Move Tool instead.

**Comment by photopea** [comment]
So the bug is the following: If you are typing a text inside a text layer, and you click outside the canvas, and that click did not change any text style parameter, the text area "loses focus" and you can not continue typing (even though you still see the cursor).

I made a following change: after choosing a font, the font menu is hidden. Now, you don't have to "click elsewhere" to hide it, and you can continue typing.

However, the bug from the first paragraph is still true. It would require serious change in the structure of our program to fix it.
