### ISSUE TITLE
Glyphs

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#2138]
1.) For some glyphs (in screenshot first red circle) it says "No known character for this glyph". What does it mean? Is it then impossible to insert such glyph into my document?
2.) When I click empty square after last glyph (in screenshot second red circle)  it shows error in console:
pp.js:9159 Uncaught TypeError: Cannot read property 'Mh' of undefined
    at _U.dJh (pp.js:9159)
    at _G.Vl.u (pp.js:9)
    at _G.BY.u (pp.js:7099)
    at _G.Al (pp.js:7171)

As you can see this is Liberation Sans font in this screenshot:
![image](https://user-images.githubusercontent.com/6370548/81779706-8c4d5c80-94f5-11ea-80b3-fc05d7e1ded6.png)

**Comment by photopea** [comment]
Hi, I fixed the error.

The message "No known character for this glyph" means, that there does not exist a Unicode character, which the font converts to that glyph.

In general, a font converts a sequence of Unicode codes (numbers between 0 and 120 000) to a sequence of glyphs (vector images) + the coordinates of each glyph. Two sequences are not required to have the same length (e.g. a whole word can be replaced by a single glyph). You can also have conditional glyphs (use this glyph for A, if T is before A, and use another glyph for A otherwise). It is quite hard to find a Unicode sequence, which would produce glyphs containing a specific glyph.

**Comment by hxim** [comment]
I noticed when you are not currently writing text with Type Tool and click on some glyph it does nothing. I think it would be nice if user could somehow insert any glyph as vector shape layer similar to Custom Shape Tool. Is this possible?

**Comment by photopea** [comment]
BTW. I noticed, that in Photoshop, you can add any glyph into a text layer. It is placed into a text as a character 65533, and then, there is an extra information, that a specific glyph should be directly placed at that position in a string (ignoring the rules of a font). Of course, you can not copy-paste such string outside Photoshop, and the glyph becomes nonsense, when you change the font. Should we implement it, too?

Yes, we can create a vector shape from a glyph. But maybe, if we allowed any glyph to be pasted into a text layer, the user can simply convert a text layer to a shape.

**Comment by photopea** [comment]
In DejaVu Sans font, there are many pairs of Unicode characters, that are converted to a single glyph. But usually, there is a single Unicode character, that is converted to the same glyph.

E.g. this is one character:
Á  - Unicode [00C1](https://www.fileformat.info/info/unicode/char/00c1/index.htm)

These are two characters:
Á - Unicode [0041](https://www.fileformat.info/info/unicode/char/0041/index.htm) + [0301](https://www.fileformat.info/info/unicode/char/0301/index.htm)

Both strings are converted to a same glyph in most of the fonts.
