### ISSUE TITLE
Ungroup layers

### ISSUE THREAD

**Issue by photopea** [photopea/photopea#215]
According to one of reviews: https://chrome.google.com/webstore/detail/photopea/fmophgdjdipcbfjiopifpngdjmemonko/reviews

Photopea is missing the Ungroup feature. We should try to find out what it is and add it.

**Comment by photopea** [comment]
I was not able to say, what ungrouping means. Layers can be arranged manually by dragging them in the Layers panel.

**Comment by nospam2k** [comment]
I don't know why this is closed. Create a group of layers (only one group) and try to move a layer out. Cannot be done. You cannot put a layer above the top item.

**Comment by photopea** [comment]
@nospam2k I just tried and I can drag the layer outside the folder. Are you sure you are doing it correctly, dropping layer above the folder instead of on its center?

**Comment by nospam2k** [comment]
Ok, I just tried it again. I was going to send a video but I realized you have to have it in the EXACT position so that you can see a single bold line just above the group. I'll provide the video so others can see.

Fail:
https://user-images.githubusercontent.com/1284287/196810999-c3292d37-4b8c-4518-ae75-24bd7d65492e.mov

Success:
https://user-images.githubusercontent.com/1284287/196811249-322cdd23-3b86-402d-9c05-8c99fda3d623.mov

**Comment by photopea** [comment]
Yes, that is how it works. It is placed at the bold line. If there is a rectangle around a folder layer, it will be placed into a folder.
