### ISSUE TITLE
Edit Lasso Select after double clicking or pressing enter

### ISSUE THREAD

**Issue by coolcraftnet18** [photopea/photopea#2206]
https://imgur.com/a/IFEYjaq
Sometimes I accidentally double click and my selection for photopea is finished. Do you think you could add an undo feature like gimp has? Look at the video for more details.

**Comment by photopea** [comment]
Hi, now, you can press Escape to do a step back (return to the previous selection) and get the last polygon in front of you.

Be careful not to press Escape twice, because Escape while drawing a polygon means canceling the currently drawn polygon.

You can also use the Pen tool to create a path, and then, convert the path to a selection.

**Comment by MichalSZZ** [comment]
@photopea  Amazing solution! Works like a charm!
