### ISSUE TITLE
Issues with SSL not being verified as secure

### ISSUE THREAD

**Issue by bdbossmovemaker** [photopea/photopea#2283]
https://www.loom.com/share/2a310816ac4640c398c587b09cc72f6c

**Comment by photopea** [comment]
Hi, your video is quite long. Could you describe what exactly is the problem?

I see, that you use quite a lot of browser extensions. Are you sure your browser extensions are not redefining web certificates, in order to let extension creators know about your web activity?

Can you disable all browser extensions? Is that notification still there?

**Comment by bdbossmovemaker** [comment]
I uninstalled photopea and reinstalled something was wrong but it fixed the problem
