### ISSUE TITLE
Eye dropper tool does not get this grey color

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#2307]
I am attaching this picture.

There is 2 colors in there.

Use the eyedropper to copy one color and the paint the other side with it.

Now repeat the process, but the other one.

You will see that the lighter grey is not coppied by the eyedropper

![N - empanada](https://user-images.githubusercontent.com/11801254/87843685-8ae93900-c884-11ea-83c4-1759c2ddef20.png)

**Comment by photopea** [comment]
Hi, I see, that the bottom left pixel is different color, than the bottom right pixel.

I can pick both colors, and paint with both, and the painted area corresponds to the picked color.

Are you painting with opacity<100 ? Or with some fancy blend mode?

**Comment by hxim** [comment]
I tried it but I think both colors are same "#38332d" but bottom left area is painted with 99% opacity and top right area is painted with 100% opacity. It look lighter only because 1% of background goes through it :)
It has alpha A: 252 instead of A: 255 in Info window:
![image](https://user-images.githubusercontent.com/6370548/87856463-a35a6180-c91f-11ea-8208-f761156d16e3.png)

**Comment by photopea** [comment]
That is true. The top left corner pixel and the bottom left corner pixel have the same color, but they look different (lighter / darker), because they have different transparency. So I think we solved the mystery now :)

**Comment by avagp** [comment]
HHAHAHAHAH!

Not only programming skills, but detective skills you have!

Case Closed

**Comment by photopea** [comment]
The @hxim has detective skills. I did not see a color difference on my screen in the daylight :)
