### ISSUE TITLE
Overlapping sections of path are not filled

### ISSUE THREAD

**Issue by mattrossman** [photopea/photopea#2364]
I imported an SVG file into Photopea and this is how it looks:
![firefox_td1kHkUl7M](https://user-images.githubusercontent.com/22670878/89832538-7c153f80-db2d-11ea-9366-12c29fa4b4ef.png)

Meanwhile if I open the SVG directly in a browser like Firefox, those inward overlapping sections are filled.
![firefox_aRxx9TM72A](https://user-images.githubusercontent.com/22670878/89832544-7f103000-db2d-11ea-8776-6d561569871a.png)

**Comment by photopea** [comment]
Hi, the problem is, that we convert all opened files into a PSD format. In the PSD format, curves always have an even-odd filling rule, so you can not technically create a self-intersecting curve, where the intersection is filled. It is not possible in Photopea, Photoshop or any other PSD editor.

We could detect such intersections and remove them, but that would be modifying the actual bezier points, many users could mind it.

I think the designer should not create self-intersecting paths in their work. One point in that shape is redundant and could be omitted.
