### ISSUE TITLE
Keyboard shortcuts rebinding

### ISSUE THREAD

**Issue by michaelschufi** [photopea/photopea#2382]
Hi, first of all, thank you for this amazing tool. 🎉 

However, coming from a non-Photoshop world, a few basic Navigation features and shortcuts don't feel natural. For example:

- Zooming works in every major application besides Photoshop with `CTRL + MouseWheel` and not `ALT + MouseWheel`
- I really miss being able to drag the viewport with the middle mouse button like in GIMP

Is there a way to change the keyboard shortcuts to behave like this?

Also: Whenever I release the `ALT` key, my menu bar in Firefox shows up, which moves the whole browser tab. This makes the zooming even more tedious.

**Comment by photopea** [comment]
Our keyboard shortcuts correspond to the shortcuts of Adobe Photoshop, but they are also used in other photo editors. We think it is better if everybody learns the same shortcuts, instead of allowing everyone to use any shortcuts they want.

You can drag the viewport by holding the spacebar and moving with it with a mouse.

I reported the Firefox bug to Firefox developers more than a year ago, but they still did not fix it. You can see the progress here: https://bugzilla.mozilla.org/show_bug.cgi?id=1568130  . You can use some better browser until they fix it.

**Comment by michaelschufi** [comment]
GIMP. Affinity, Figma and probably also others have all the middle mouse button move. Those 3 all allow for SPACE+mouse movement. My suggestion is to add the middle mouse button move for the viewport in Photopea as well. 

Regarding the zooming:
Many apps like, the MS Office Suite, the aforementioned photo editors, all major browsers, and countless other programs bind zoom to `CTRL + MouseWheel` instead of `ALT + MouseWheel`. I understand that you want to attract Photoshop users primarily. This is completely fine and makes sense. But for many others it probably feels more natural to zoom like they are used to in other apps.

Zooming and moving the viewport is something people need all the time and completely in muscle memory. Nobody wants to relearn/retrain something so basic.

I am not saying any default setting should change. I am talking about giving the user a choice, at least for the modifier key.  Giving users a choice, so they can feel more "at home" makes transitioning to a new app more attractive and easier.

I hope you reconsider.
