### ISSUE TITLE
Feature request: SVG fonts

### ISSUE THREAD

**Issue by nonvieri** [photopea/photopea#2393]
I'd appreciate if there would be support for SVG-based colorful fonts ;)

**Comment by photopea** [comment]
Hi, Photopea supports SVG fonts for over two years, see here: https://blog.photopea.com/color-fonts-in-photopea.html

Do you have any specific font which does not work?

**Comment by nonvieri** [comment]
this one https://github.com/samuelngs/apple-emoji-linux/releases

doenst work for me :/

**Comment by photopea** [comment]
I downloaded that file "AppleColorEmoji.ttf", but I can not install it in Windows. Can you use that TTF file in any program at all?

**Comment by photopea** [comment]
So I did some research. Your font does not contain any SVG fonts. It does not contain vector graphics at all.

Your font contains a PNG image (136 x 128 pixels) for every character.

It contains 3270 PNG images. Since the TTF is around 34 MB, each PNG image is around 10 kB. Here are some PNGs I manually extracted from a TTF file.

![anchor](https://user-images.githubusercontent.com/15955558/91475925-945ebb80-e89c-11ea-9ba4-4db58dce846d.png)
![door](https://user-images.githubusercontent.com/15955558/91475929-94f75200-e89c-11ea-8e65-b1384d389c53.png)
![woman](https://user-images.githubusercontent.com/15955558/91475930-94f75200-e89c-11ea-8167-dda8543ec4ab.png)

Making Photopea support these PNG fonts would be quite hard. Since they are quite rare, I would prefer not to implmenet them.

**Comment by nonvieri** [comment]
![image](https://user-images.githubusercontent.com/46636729/91487238-d3344780-e883-11ea-8df0-27ba2ded067d.png)

doesn't work at all for me

**Comment by nonvieri** [comment]
no color svg font works

**Comment by photopea** [comment]
Can you send me a color SVG font which does not work? Your previous font was not an SVG font.

**Comment by nonvieri** [comment]
[seguiemj.zip](https://github.com/photopea/photopea/files/5138468/seguiemj.zip)

**Comment by photopea** [comment]
That font is not SVG either. But it is a "COLR" font, which is still vector graphics, and is quite easy to add into Photopea.

It is implemented now :)

![image](https://user-images.githubusercontent.com/15955558/91496828-21197180-e8bd-11ea-94d8-b04cf7a7ae21.png)

**Comment by nonvieri** [comment]
Can you please add support to SBIX?

Il giorno gio 27 ago 2020 alle ore 18:29 Photopea <notifications@github.com>
ha scritto:

**Comment by photopea** [comment]
The SBIX table refers to fonts, where a character is e.g. a JPG image. We do not support raster fonts at the moment.
