### ISSUE TITLE
save as txt issue

### ISSUE THREAD

**Issue by ghiathkamel** [photopea/photopea#2399]
hello everyone,
when i save the photo as jpg
it save as text file not jpg
the issue only on chrome not in firefox
thanks

**Comment by photopea** [comment]
Hi, you have a browser extension in Google Chrome, which renames all files to TXT files.

Try to disable that extension. You can also use Photopea in Incognito mode, where all extensions are disabled.

**Comment by ghiathkamel** [comment]
you are right, it works in Incognito mode, but i dont have extension in Google Chrome, which renames all files to TXT files?

**Comment by photopea** [comment]
look into chrome://extensions . One of your extensions renames files to TXT. It probably is not named "Renaming files to TXT", but more like "Facebook" or "Google Docs" etc.

Today, people make extensions and name them "Facebook" so that you are afraid to delete them, while they track and control your browsing experience.

**Comment by ghiathkamel** [comment]
thank you my friend, I really like photopea :) easy to use and very powerful, is there plan to make it install in windows use it offline in my pc :)
yes you are right the Free Download Manager extensions renames files to TXT :*(

**Comment by photopea** [comment]
Yes, we discovered it here: https://github.com/photopea/photopea/issues/1373
