### ISSUE TITLE
Umbenennung der Ebenen

### ISSUE THREAD

**Issue by Rotstift9** [photopea/photopea#2405]
Beim Versuch  die Ebenen umzubennen (Doppelklick) öffnet sich regelmäßig in allen Browsern das Fenster für den Ebenenstil. So können die Ebenennamen auch für Animationen nicht erstellt werden. Das war aber schon lange Zeit ok.  Der Fehler tritt erst seit einiger Zeit laufend auf.

**Comment by Rotstift9** [comment]
Die automatische  Übersetzung ist aber mies. Es geht um Umbenennung der Ebenen.

**Comment by photopea** [comment]
Hi, could you write it in English, please?

**Comment by dentistformyeye** [comment]
You have to double-click the layer names. Otherwise, the layer styles window appears instead.
![image](https://user-images.githubusercontent.com/51429646/91926630-a75efa80-eca5-11ea-85d3-8253dce51835.png)
✓

![image](https://user-images.githubusercontent.com/51429646/91926663-bd6cbb00-eca5-11ea-9697-35b8070e94ae.png)
X

**Comment by photopea** [comment]
I think that is a correct behaviour. Double-clicking a layer should open Layer Styles. You need to double-click the layer name to rename the layer.

**Comment by dentistformyeye** [comment]
My bad, I didn't clarify. I was trying to let Rotstift9 know.

**Comment by photopea** [comment]
Ok, I will close it now.
