### ISSUE TITLE
Drop Shadow - Inner Shadow

### ISSUE THREAD

**Issue by mertgenco** [photopea/photopea#2408]
When I change one object's drop shadow angle, it automatically changes another object's inner shadow angle. This bug was really weird actually. I fixed the problem by rasterizing other object first. By the way they were not in the same group or something. Good app though! Thanks.

**Comment by photopea** [comment]
It is not a bug, it is a feature.

It can be very useful to set the angle of shadow for all layers at once. Because of this, there exists a "global angle", which can be modified just once.

When there is an input for an angle, there is also a checkbox "Use Global Angle". Uncheck it, to make the angle independent on the global angle. 

![image (1)](https://user-images.githubusercontent.com/15955558/91997069-fbb3ba00-ed39-11ea-90f4-1ce4f0a66e77.png)

**Comment by photopea** [comment]
Or you can keep the Global Angle checked, but uncheck it on the rest of layers (so that they don't change when you change the global angle).
