### ISSUE TITLE
Disable Adblock still persists after disabling adblock

### ISSUE THREAD

**Issue by restinrip** [photopea/photopea#2433]
When I disabled my adblock after using the site 1 time, it kept showing dialog boxes saying to disable my adblocker when I didn't have one active.

**Comment by photopea** [comment]
Hi, do you see ads in Photopea?

I think some other extensions could be blocking ads. They mignt not have "adblocker" in their name. Try to disable all extensions, or use Photopea in Incognito mode, where extensions are disabled.

**Comment by restinrip** [comment]
I disabled adblock in the installed version, but it keeps showing me the alerts. And the ads do not appear after I disabled it.

**Comment by photopea** [comment]
Hi, you are probably still blocking ads. Try to disable all browser extensions. Any extension is capable of modifying any website it wants.

**Comment by plablugoo** [comment]
I disabled all my extensions and I am able to export out files from Photopea but the pop up telling me to disable adblock still pops up. Also I don't see any ads.

**Comment by photopea** [comment]
@plablugoo Can you access this URL from your browser? https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js

**Comment by plablugoo** [comment]
nope I cant

**Comment by photopea** [comment]
Some software or antivirus in your computer is blocking that domain. Try to find out what is blocking it or ask your internet provider, if they are blocking it.

**Comment by photopea** [comment]
We disabled the adblock message for a while. But we will enable it again. Please, make sure you see ads in Photopea (and if not, try to fix it somehow), so that you dont have these problems next time.

Ads work well on a normal browser with a normal computer. They don't work only if you did something non-standard to your computer (installed extensions, firewalls, re-routers or other software) - you are the one who should know what was done to your computer.
