### ISSUE TITLE
Drop shadows and gradients banding

### ISSUE THREAD

**Issue by nospam2k** [photopea/photopea#2439]
Drop shadows and gradients are not smooth even when the smoothing is at 100%. Banding is happening even on a 1600x1600x72 full color image.

<img width="558" alt="Screen Shot 2020-09-13 at 4 41 45 PM" src="https://user-images.githubusercontent.com/1284287/93031494-1f032280-f5e0-11ea-84ae-27ec9890e66f.png">

**Comment by photopea** [comment]
Hi, I looked at it, and the "stripes" are often as close to themselves as possible.

E.g. this stripe is RGB 23,23,23, and the one next to it is RGB 24,24,24. There does not exist any RGB color in between. Should we make it like 23,24,23, so that it is not a shade of gray anymore?

By the way, for gradients, you can enable Dithering, which improves the visual look.

![image (3)](https://user-images.githubusercontent.com/15955558/93058628-eca10600-f66f-11ea-8cca-03953c0865d7.png)

**Comment by nospam2k** [comment]
Thanks for looking into this. From looking online, I see nearly every online gradient has this issue. I tried the dithering and that did help a little. I’m not sure how gradients are calculated but is it a resolution issue? I have an example of the effect I’m trying to reproduce and have been unsuccessful. I know it’s not a gradient but it gives the idea of the problem I’m trying to overcome with Photopea using gradients and shadows. You will notice the near lack of banding. There is some but much smoother. What’s interesting is this is an input re-exported from Photopea so I can see that it technically displayable. The question is it producible?

**Comment by photopea** [comment]
Hi, sure, tell us what problem you are trying to solve.

**Comment by nospam2k** [comment]
Answered through email, didn't bring in the image, I've updated the post.

**Comment by photopea** [comment]
Your image contains a lot of noise. You can add noise with Filter - Noise - Add Noise.

![New Project](https://user-images.githubusercontent.com/15955558/93134843-a3859c00-f6d9-11ea-9f0d-e56e62a72748.png)

**Comment by nospam2k** [comment]
Ahh... That's great. 2% noise smooths out the bounds!

**Comment by photopea** [comment]
It does not smooth anything, it is the opposite :D   If you go from one pixel in any direction, pixels are darker, brighter, then darker, then brighter again.
