### ISSUE TITLE
I can't open a layer style

### ISSUE THREAD

**Issue by catzinha** [photopea/photopea#2527]
I downloaded some styles and was using normally, but now, they are not working; when I click on the square, the site stops and works again, but the styles do not appear

**Comment by photopea** [comment]
Hi, could you please describe what should I do to make the problem happen on my computer?

**Comment by galzhica** [comment]
A few days ago I downloaded some styles and I was using them without problems, but since yesterday when I click on the layer then in blending options the styles that I downloaded and that I had been using do not load me and therefore I cannot use them. Could you please give me a solution for this problem? you can select one layer click on it and after that go to blending options and click on the box that appears on the right,you can see that the styles do not load.

**Comment by photopea** [comment]
I can not solve anything, if I can not make it happen on my computer.

I loaded several .ASL files into Photopea and they all work well. Can you give me your .ASL file?

**Comment by photopea** [comment]
I have to close it because of lack of details.
