### ISSUE TITLE
Clone stamp tool is giving me a red spot.

### ISSUE THREAD

**Issue by CNielsen2011** [photopea/photopea#2556]
I teach Photography and Photoshop for high schoolers. Some of them are struggling with the clone stamp tool and when I am showing them how to use it, they get a giant red spot that just gets bigger when they move their curser further from the area they defined with their brush. The spot won't go away and then they can use the clone stamp at all. I have them share their screen with me and I can't see any setting that would make this occur. If you know what is causing it, would you please tell me so I can help the students fix it? Or if it is a new bug let me know when you fix it. Thank you!
![Screen Shot 2020-10-23 at 11 08 15 AM](https://user-images.githubusercontent.com/73360474/97038735-1aefec00-1520-11eb-8ae1-3ba5addd3200.png)

**Comment by photopea** [comment]
Hi, I think it is related to a bug in Chromebooks (it happens only on Chromebooks). This bug was reported to Google in 2013, but they still have not fixed it https://bugs.chromium.org/p/chromium/issues/detail?id=248762 

You need to Alt+click to choose a source of cloning. But on Chromebooks, Alt+click acts as a right-click. Chromebooks do not allow websites to change that behaviour. 

Look into chrome://flags , there a setting to switch it from Alt+Click to Search+Click for right-click, as described here:
https://support.google.com/chromebook/thread/14888778?hl=en

**Comment by photopea** [comment]
So I think it has been fixed by disabling that feature.
