### ISSUE TITLE
Enhancement: Option to use specific version

### ISSUE THREAD

**Issue by monking** [photopea/photopea#256]
Perhaps just for Premium accounts: I'd like to be able to use a specific version of the software, and upgrade to newer versions only after I've had a chance to confirm that I can communicate any necessary changes to my team. Perhaps the iframe URL could contain a parameter specifying the desired version, and your UI could show a warning if the version will be deprecated.

**Comment by photopea** [comment]
Hi, are you talking about the version of Photopea editor, or the version of the API? Did you have any specific problem with it?
In general, we are extending the editor, while preserving all previous features. The same should hold for the API. We dared to change the API several times in the past (added / removed some parameters), since we were not aware of anybody using it in a serious scale.

**Comment by photopea** [comment]
I have to close it because of lack of details.
