### ISSUE TITLE
Unknown file format: <htm

### ISSUE THREAD

**Issue by splincode** [photopea/photopea#257]
I just open jpg file in url:
http://www.labpathautomation.com/wp-content/uploads/2016/02/data-center-1.jpg

![image](https://user-images.githubusercontent.com/12021443/29934290-40decc3c-8e83-11e7-88c3-ecc4ff2e8375.png)

**Comment by photopea** [comment]
Hi. In this case, images are downloaded to our server, and then Photopea loads them from the server.

When our server visits your URL, it returns some HTML page for robots. You have to ask the owner of that domain to fix it. 

Otherwise, I recommend to download your file locally and then open it in Photopea. Or right-click the image, choose Copy, and then press Ctrl+V in Photopea.
