### ISSUE TITLE
API - paste to selection ( .paste(TRUE) )

### ISSUE THREAD

**Issue by taime** [photopea/photopea#2595]
I'm trying to use the **TRUE** option  in  `app.activeDocument.paste(TRUE)` - it should paste clipboard image to selection.

```
mergedDoc = app.activeDocument
var x=11, y=22, sw=300, sh=200;
mergedDoc.selection.select([ [x,y], [x,y+sh], [x+sw,y+sh], [x+sw,y] ]);

mergedDoc.paste(TRUE)
```

P.S. 
Actually all I'm trying to do - is to paste image to specific position... Just something like `.paste([x,y])` would be perfect. But it looks like, it is not possible.. am I right?

It would be also ok, to move image to specific position after paste, could you please suggest any way to do it?

**Comment by IamFlea** [comment]
Bug confirmed. We need to wait for a hot fix. 

Unfortunately. I couldn't bypass it by selecting the pasted picture and then using translation :/

```js
var mergedDoc = app.activeDocument
var x=11, y=22;
var layer = mergedDoc.paste();
layer.translate(x,y);
```

There is some kind of TypeError (nil).

**Comment by photopea** [comment]
Hi, your script makes no sense to me. I think you need to call copy(); or cut(); before calling paste(); Otherwise, what should be pasted? 

Also your Javascript is not valid. You are using a variable TRUE without defining it. You need to define variables

     var TRUE = 1;

before using them. There is no default variable TRUE in Javascript. 

I recommend you to learn more about Javascript: https://www.w3schools.com/js/  and the scripting API: https://www.adobe.com/content/dam/acom/en/devnet/photoshop/pdfs/photoshop-cc-javascript-ref-2019.pdf

Or at least use scripts which can run in Adobe Photoshop (your script fails in Photoshop).

**Comment by taime** [comment]
@photopea 

1) **This was** example from https://www.adobe.com/content/dam/acom/en/devnet/photoshop/pdfs/photoshop-cc-javascript-ref-2019.pdf
**PAGE 96**

2) You can make selection manually, this has nothing about a bug. I've add copy to clipboard part below if you need it so to understand this bug

```
app.activeDocument = app.documents[1]
app.activeDocument.selection.selectAll() 
app.activeDocument.selection.copy()

app.activeDocument = app.documents[1]
mergedDoc = app.activeDocument
var x=11, y=22, sw=300, sh=200;
mergedDoc.selection.select([ [x,y], [x,y+sh], [x+sw,y+sh], [x+sw,y] ]);

var TRUE = 1;
mergedDoc.paste(TRUE)
```

P.S.
Thank you very much for your recommendations... but could we talk about bug now? The paste to selection from adobe docs doesn't work... that's the point. Please address your recommendation to learn js https://www.w3schools.com/js/  to adobe authors, because  this `mergedDoc.paste(TRUE)` exactly what they use in examples, without any `var TRUE = 1;`

**Comment by photopea** [comment]
I am very sorry for being rude.

I fixed the problem. The script should work well now (if you replace "TRUE" with "true").

You are right, Adobe made an error in their document, their script fails in Adobe Photoshop.
