### ISSUE TITLE
Paint Brush Select Color Not Working On Some Browsers

### ISSUE THREAD

**Issue by coolcraftnet18** [photopea/photopea#2641]
When I am on my Dell Chromebook 11, the color picker tool that is integrated in the paint brush tool doesn't work. I will press alt+click on the color and it will not do anything. I will take a video of the issue soon.

**Comment by photopea** [comment]
Hi, you can not use Alt+click shortcut on a chromebook, because it always performs a right-click. So we do not recommend Chromebook devices for using advancet webapps, such as Photopea.

We reported it to Chrome developers in 2013, but they have not fixed it: https://bugs.chromium.org/p/chromium/issues/detail?id=248762

Also, I think you can not install a different browser into a chromebook. So I would recommend using the Eyedropper tool to pick colors.
