### ISSUE TITLE
"please allow ads"

### ISSUE THREAD

**Issue by no0000000000** [photopea/photopea#2652]
i keep getting the popup asking to disable ad blocker but its already disabled on photopea. i've closed the site and reopened about four times and its still doing it. edit: also? having the pop up every 60 seconds is not necessary.

**Comment by photopea** [comment]
Hi, can you open Photopea in Incognito mode? Do you still see such message? Some of your browser extensions could be removing ads.

**Comment by mcarrick1954** [comment]
I'm having the same issue now. About 2 months ago (or longer) we were having the same issue and the district's IT department got rid of the adblocker that they had installed. Everything was fine until today when i opened Photopea and now it says there is an adblocker. I looked through all of the extensions and there were no adblockers. You say open Photopea in Incognito mode but how is that done?

**Comment by nanahooter** [comment]
I am having the same issue as @mcarrick1954 - teaching a class, no new software from IT department, and now crippling pop ups about adblock. Working district IT people to see if its on our end

**Comment by mcarrick1954** [comment]
Hello Nanahooter,

I don't think the problem is on our end (district IT). I believe it's on
Photopea. I used Photopea yesterday to prep for an upcoming project and I
had no problems. Today when I was demo-ing the project the annoying pop-ups
came back. I checked my Extensions and I didn't have any adblockers
running. I asked my students if they were getting the pop-ups and they said
yes. It didn't matter if they were on a PC, Apple product, or a Chromebook.
My laptop from home is now infected with  the pop-ups. I sent an email to
our IT department to see if they had installed something during the break
and haven't heard back from them (typical). I also have the post that you
saw. If you have any further info on this please share it with me. I will
do the same. Distance learning is hard enough.

**Comment by nanahooter** [comment]
@mcarrick1954 will do! This year has been rough and photopea was the one thing that was kind of working right! Will absolutely post update here if I hear of anything on reddit

**Comment by photopea** [comment]
How do you decide if an extension that you have is an ad blocker or not?

Any extension can do anything it wants to any website which you open. I am sure, if you disable all extensions, it should work. Try to disable extensions one by one until you find the one which does it.

Also, domains like https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js should be accessible from your computer, in order for our ads to work correctly.

**Comment by nanahooter** [comment]
@mcarrick1954 got a response from photopea detailing very affordable pricing solutions for schools as well as the process that I can go over with my DLS tomorrow. [Link here](https://www.reddit.com/r/photopea/comments/k43uf0/ad_block_pop_up/)

**Comment by mcarrick1954** [comment]
Great, thanks for the update.

**Comment by mcarrick1954** [comment]
I wanted you to know that I played around with the extensions and got
Photopea to work. I had Duck, Duck, Go running and stopped it. I just asked
my class if they are experiencing the ad block pop-up problem and no one
has said anything. Maybe they all went back to sleep but no complaints yet.
YAY

**Comment by mcarrick1954** [comment]
Awesome, thanks!

**Comment by photopea** [comment]
So I think it has been solved.
