### ISSUE TITLE
希望另存为PSD文件可以自定义命名

### ISSUE THREAD

**Issue by solomansh** [photopea/photopea#2690]
非常感谢这款photopea软件，帮了我很大忙。
使用了半天发现导出psd文件只能默认原文件名。
希望能增加一个导出psd文件自定义命名的步骤，这对使用者会有很大帮助。
再次感谢！！

**Comment by photopea** [comment]
Hi, you should change the settings of your web browser, so that the browser lets you rename the file before saving.

If you use Google Chrome, read this to learn how Google Chrome works: https://support.google.com/chrome/answer/95759?co=GENIE.Platform%3DDesktop&hl=en

I recommend you to enable "Ask where to save each file before downloading."

**Comment by solomansh** [comment]
Thank you!





------------------ 原始邮件 ------------------
发件人: Photopea <notifications@github.com&gt;
发送时间: 2020年12月14日 21:18
收件人: photopea/photopea <photopea@noreply.github.com&gt;
抄送: solomansh <865178122@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[photopea/photopea] 希望另存为PSD文件可以自定义命名 (#2690)





 
Hi, you should change the settings of your web browser, so that the browser lets you rename the file before saving.
 
If you use Google Chrome, read this to learn how Google Chrome works: https://support.google.com/chrome/answer/95759?co=GENIE.Platform%3DDesktop&amp;hl=en
 
I recommend you to enable "Ask where to save each file before downloading."
