### ISSUE TITLE
Downscaling images decreases quality

### ISSUE THREAD

**Issue by PeterDraex** [photopea/photopea#273]
Hey guys,

try to downscale a 2000 px wide image to 50px. 
If you do this in Photoshop, it'll give you a much sharper picture than if you do so in Photopea.

Otherwise great work guys!
Peter

**Comment by photopea** [comment]
Thank you very much for reporting it.  It was fixed in all places: Free Transform tool, Image - Image Size and in Save for Web window.  We are very sorry, that downscaling was so bad all this time.

Here is a demo (old result at the top, new result at the bottom).
![woman_50](https://user-images.githubusercontent.com/15955558/31618789-2a577ec6-b293-11e7-978c-1546c815a141.png)
