### ISSUE TITLE
Can't open photos from Flickr photostream

### ISSUE THREAD

**Issue by castlemanj** [photopea/photopea#2734]
I'm trying to open photos using the URL from my flickr photostream. This used to work several months ago but now when I paste the URL into "open from URL" dialogue I get an error message. Please advise.

Thank you,
--Jeff

**Comment by photopea** [comment]
Are you sure that you have a URL of a photo and not of a website? Can you share your URL with us? Can you open your URL in Incognito mode?

**Comment by castlemanj** [comment]
This is the URL:
https://www.flickr.com/photos/190169038@N07/50805330343/in/dateposted-public/
Yes I can open it in incognito mode.

**Comment by photopea** [comment]
This is a URL of a website. That website contains over 20 images (every icon, a "flickr" logo, they all are images).

You should be able to right-click an image in your browser and choose "copy image URL". But it seems like Flickr has blocked that feature.

Try to ask Flickr to allow you to copy image URLs. Otherwise, you will have to download a photo into your computer somehow, and open it in Photopea from your computer.

**Comment by castlemanj** [comment]
Okay thanks
