### ISSUE TITLE
I have a student who is using Photopea, but is missing the clone tool icon.

### ISSUE THREAD

**Issue by imockman** [photopea/photopea#2742]
I have a student who is using Photopea, but is missing the clone tool icon. May have a chromebook, but not sure why the icon is missing.  Any ideas on how to solve?

**Comment by photopea** [comment]
Photopea has about 50 tools and they can not be displayed all at the same time. If your screen is large, you see more tools, than someone with a smaller screen.

You should click and hold a tool button to see more tools under that button. Your student does not see some tools which you do, because he probably has a smaller screen. He should look for the Clone Stamp tool in a group under a Brush tool (probably).

**Comment by imockman** [comment]
Here is a screen shot of the students work space [https://drive.google.com/file/d/17hVb-v0ViKrl3HDhw0SE4DXEtu5lM37O/view?usp=sharing](url)

**Comment by photopea** [comment]
Here is a screen shot of Photopea on my computer. You see only 7 tools, if your scren is small.

![image (1)](https://user-images.githubusercontent.com/15955558/104247214-9ac68c00-5467-11eb-9fa2-bb03e607f562.png)
