### ISSUE TITLE
On PWA version Ctrl+W shortcut close active tab without any info 

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#2757]
Is there any option to make that shortcut working like in a browser version?
One of my student closed his project in that way and lost lot of work... Any warning about closing like in Photoshop or browser Photopea version will be good

**Comment by photopea** [comment]
Hi, the problem is, that web browsers do not allow websites to detect the Ctrl+W shortcut in a browser mode, but it is possible in a PWA mode. In a browser mode, Ctrl+W always tries to close a website.

I removed that shortcut from Photopea completely.

In a browser mode, Ctrl+W will try to close the website (we can not change it). In a PWA mode, this shortcut does nothing.

Whenever you try to close Photopea with unsaved work, you should always see a prompt, which you need to confirm by clicking "OK", or "Cancel" to continue your work.

**Comment by MichalSZZ** [comment]
Thank you very much!
