### ISSUE TITLE
Arabic problem

### ISSUE THREAD

**Issue by Roxgame95** [photopea/photopea#2794]
when trying to edit an arabic text the cursor doesn't stay in selected place

**Comment by photopea** [comment]
Hi, what does it mean?

**Comment by mustafaGFX** [comment]
@Roxgame95 
>  when trying to edit an arabic text the cursor doesn't stay in selected place

It's because the Arabic language is written from right to left, and the default direction for any text in photopea is from left to right.
to fix it you have to follow these steps : 

- Double Click on the text thumbnail in the layers panel to select the text
![Screenshot (79)](https://user-images.githubusercontent.com/70863817/105636426-07cb2000-5e71-11eb-9903-241b69a76789.png)
- go to window>paragraph
![Screenshot (80)](https://user-images.githubusercontent.com/70863817/105636433-131e4b80-5e71-11eb-8500-5c8a4ea7cf04.png)
- Click "اي بي" button
![Screenshot (79) (1)](https://user-images.githubusercontent.com/70863817/105636449-1fa2a400-5e71-11eb-9541-9929af384b03.png)


@photopea 
it will be better to select the direction of the text automatedly, 
if the user starts writing his text in Arabic, the text direction should be Arabic, and the same thing should happen with any language

the languages that written from right to left are about 5 languages, they all have the same alphabet

**Comment by photopea** [comment]
You can have both left-to-right and right-to-left parts in the same sentence. It is not possible to detect the main direction automatically, if there are e.g. both arabic and english words at once.

That is why you need to set the main text direction. It works this way in all text editors.

**Comment by AbanoubEhab** [comment]
that did not solve my isuee
when importing from pdf i just can't get it right 

that's how it suppos to look like

![image](https://github.com/user-attachments/assets/00f4bddf-6eb8-4da1-a199-47222ef1144b)

and that's how it look like

![image](https://github.com/user-attachments/assets/32dec3f9-fd43-4a2b-a862-ca59843bc9de)

**Comment by photopea** [comment]
Can you edit your PDF in some other software? PDF files were not meant to be edited, PDF format is for reading and printing.
