### ISSUE TITLE
Better .ora support

### ISSUE THREAD

**Issue by Reptorian1125** [photopea/photopea#2799]
.ora is essentially a open-source .psd format though only Krita is maintaining it as Krita has the most features in terms of layers and NDE editing. With better .ora support, you can work with Photopea and exchange between GIMP/Krita and other programs. Right now, it just loads separate images.

**Comment by photopea** [comment]
Photopea can already load GIMP XCF files.

Can Krita export files as PSD or XCF? Then, you would be able to open them in Photopea.

Should we add the support for .ora or .kra? What do you use most often?

**Comment by Reptorian1125** [comment]
Krita can export psd, not xcf. Ora can be more exchangeable as it is a open source version of psd. I would like a way to import/export with more blending modes. 

Paint.NET supports XOR mode. Krita supports every single modes that PDN. Ora does not have some of those modes supported by those programs as standard, however, you can manually edit to have those modes importable in Krita or PDN.

I use .kra more often, but will only use .ora as opposed to psd if I need to exchange with other software.

**Comment by Reptorian1125** [comment]
PSD format isn't open-source, it is proprietary format made by Adobe, people has to pay to get more information out of the psd format or reverse-engineer the format to try to support it. Krita already supports exporting to psd. 

There's no point into exporting to either xcf or pdn as they're not meant to be exchangeable. They're meant to be supported exclusively by their own respective format.

**Comment by photopea** [comment]
You are completely wrong.

The PSD format is publicly documented here: https://www.adobe.com/devnet-apps/photoshop/fileformatashtml/ . There are many programs which support the PSD format, nobody has to pay for it. Photopea also supports PSD, we did not pay anyone.

Can you find such detailed description of the KRA or ORA formats?

**Comment by photopea** [comment]
I think only the PSD format was made to be truly exchangeable, not ORA or KRA.

**Comment by Reptorian1125** [comment]
That site provides a good deal of info, but not everything. And yes, it is proprietary. A good search will show that. 

Ora could be made to be improved, yes and it probably won't be good as psd until gimp get adjustment layers which provides a incentive to upgrade the format. Here's the specs for ora - https://www.openraster.org/ .

```
a zip file with an xml document describing the layer structure and a png image for each raster layer or an svg image for each vector layer.
```
That in theory is easy to code import/export, and can be exchangeable. There are higher depth version as well, but in my use case, I find it okay to have non-destructive layers within kra, and then convert into ora when it is time to use the base info. Renaming to .zip gives me the option of extracting image. Ora is more of a basic psd with a slight benefit.

**Comment by dentistformyeye** [comment]
Microsoft's nominally "open" .docx and other OOXML formats aren't open formats because Microsoft still hasn't implemented the released specification in its own official apps; that's why Microsoft Word can't open some .docx files made by other programs and other programs can't open some .docx files made by Microsoft Word. The PSD format that Photoshop uses may not match the specification, so PSD is a proprietary format.

Even file formats with proper specifications might not be truly open formats depending on licensing. In any case, whether something costs money doesn't detemrine whether it is proprietary. Using open formats is a matter of personal philosophy. People who use free software such as Krita or GIMP probably prefer to use open formats as much as possible, so the PSD format is inconvenient for them. If prioritizing accessible, open formats over proprietary formats isn't something that @photopea considers to be very important yet, then @photopea may not have much incentive to add support for .ora files.

**Comment by photopea** [comment]
If you work with some program and store files in a certain format, I believe there is no law, which prevents you from modifying that file e.g. in Notepad, or by creating your own program which modifies that file (a file, which contains your work).

Are you aware of any editor, whose creators explicitly forbid modifying "your" files in "their" format? I think that would be quite rude and they would immediately lose customers.

I feel like you just call every format from a commercial company "proprietary" and every format from open-source programs as "free". I think it does not work that way.

**Comment by dentistformyeye** [comment]
> I believe there is no law, which prevents you from... creating your own program which modifies that file (a file, which contains your work).

Patent laws, as well as other laws regarding license agreements, can prevent people from publishing implementations for reading and writing file formats.

> Are you aware of any editor, whose creators explicitly forbid you modifying "your" files in "their" format?

Assuming that such a file format creator makes a program that users can use to modify those files, I don't know of a _specific_ file format that completely refuses to license the making of alternative programs for modifying files made by that program; I'm only sure that such a restriction is legal, at least in the US.

> I think that would be quite rude and they would immediately lose customers.

Even so, a person who wishes to write a program for reading/writing a file format must depend the proprietor's generosity or cautiousness. In addition, Microsoft made a [pledge not to sue](https://www.zdnet.com/article/promise-from-microsoft-not-to-sue-over-standards/) over implementations of the OOXML in order to ward off software developers' claims of anticompetitive practices and was probably in little danger of losing actual customers, i.e. end users.

> I feel like you just call every format from a commercial company "proprietary" and every format from open-source programs as "free". I think it does not work that way.

I didn't mean to imply anything about file formats made for specific programs and never claimed that KRA is a free format. Regardless, KRA and XCF aren't comparable to ORA because only ORA is meant for switching between programs. I only wanted to clarify that PSD is not open in the way that ORA is and that @photopea is free to decide whether to add support for the ORA format.
I made a mistake in my word choice in [my previous comment](https://github.com/photopea/photopea/issues/2799#issuecomment-803258853). "Open format" has multiple definitions; merely having public documentation satisfies some definitions, but not others. An open format under the former definition might have restrictions due to patents, trademarks, etc, in which case it would be still be proprietary. ([AAC](https://en.wikipedia.org/wiki/Advanced_Audio_Coding#Licensing_and_patents) is an example of an "open", but proprietary format.) When I said  "open format" in my previous comment, I meant to say "free format", which is a format that anyone can use for any purpose because there are no such restrictions. There is a version of OOXML that might be a free format, but the .docx version that Microsoft Word uses by default isn't a free format. ORA is a free format, but PSD isn't.

> I think only the PSD format was made to be truly exchangeable, not ORA or KRA.

ORA is meant to be exchangeable. PSD is made specifically for Photoshop and the documentation that Adobe released almost certainly doesn't support all Photoshop features. I think that PSD is so commonly supported (however incompletely) by other programs because the developers of those other programs want to make things as convenient as possible for their users who also use Photoshop; in other words, Photoshop is popular enough that developers of alternative programs feel pressured to add compatibility for PSD files.

**Comment by photopea** [comment]
I think I should close it now. With Photopea, we focus on formats, which are open (royalty-free) and used by many people in practice. Although ORA is royalty free, the demand for it has been very low, so I think it is not that much popular.
