### ISSUE TITLE
Justify Text function not always working

### ISSUE THREAD

**Issue by awilsonart** [photopea/photopea#2801]
It seems some days I can justify text and today I cannot. I am a graphic design teacher at a middle school and I have been using Photopea for distance learning as our Adobe is not available on the chromebooks we are using and this is really causing some confusion for my students. Any idea why this works sometimes and doesn't some other days? Thanks in advance for any help and thank you for making such an awesome program available for free! Total lifesaver!

**Comment by photopea** [comment]
Hi, do you have any more details? How can I make this issue happen myself?

**Comment by awilsonart** [comment]
I wish i knew how to make it happen or how make it stop it just seems to
happen some days and my a few students have had the same issue while others
have not thankfully. I record my classes so tomorrow i will send you a
video of it happening maybe that can help. Thank you so much for getting
back so fast! - warm regards,
Adam

**Comment by photopea** [comment]
Sure! Maybe you have chosen a wrong text layer, and the Justification has been changed in an other layer than you wanted.

**Comment by awilsonart** [comment]
No I don't think that's not the case as it will do the other alignment
protocols just won't perform a justify some days. Hopefully i can re create
it today for you during class. I'll be in touch and thanks again! 🙏🏻

**Comment by awilsonart** [comment]
Here is a download link for a video showing the issue...
https://we.tl/t-9VsFvDo9Yi

**Comment by photopea** [comment]
Oh, I understand it now.

When you set "Justify" in Photopea, it increases the gaps between words, so that the first word starts at the left edge, and the last word ends at the right edge. It does not change the gaps between letters, only between whole words.

The problem is, that in your case, a line of text has no spaces, so Photopea considers it to be one word (and one word in a line can not be justified). Just add one or two spaces somewhere in the middle and you should get what you want.

**Comment by awilsonart** [comment]
I tried this and it did not work unfortunately.

**Comment by photopea** [comment]
It should work. Can you show me a video of it?

**Comment by awilsonart** [comment]
Just went to make a video and now it's working. I wish I knew what to tell
you but I do appreciate your efforts in helping me out very much! Thanks
again! If I am able to recreate this again I will send a video to you.
Cheers!

**Comment by photopea** [comment]
If you have 2 or more words in a line, it should work well.

**Comment by awilsonart** [comment]
Ok it's happening again and I am recording a video for you.

**Comment by awilsonart** [comment]
Here is a link to a video example:  https://we.tl/t-vZNuLTj5lv

**Comment by photopea** [comment]
There is one more thing you should know about Photoepa. If your text box is 500 pixels wide, but you have a single word, that is 600 pixels wide, this word will go outside the box (because Photopea can not break one word into multiple lines.

In an image below, the red part are three words (justified correctly). The blue part is one long word (i.e. text with no spaces in between), and since it is too wide, it goes outside the box (the Justification does not have any effect on the blue part).

![image](https://user-images.githubusercontent.com/15955558/106048800-9e077c00-60e5-11eb-8b20-5bbb2fcae799.jpg)

**Comment by awilsonart** [comment]
Ahhhhhh. Ok I understand now. Thanks for your patience!
