### ISSUE TITLE
Perspective Crop Tool - makes sometime wrong result

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#2828]
Hi, when I use Perspective Crop Tool I don't know why, but sometimes (not always) proportion in the cropping results are bad (too wide).
I remember that I have that fail in Photoshop too some time ago.
How I should do that in proper way?

![obraz](https://user-images.githubusercontent.com/38118273/107024595-8779b880-67a8-11eb-84e7-dae5d49eb2c8.png)
![obraz](https://user-images.githubusercontent.com/38118273/107024444-5ac5a100-67a8-11eb-9177-04a074b989f7.png)

**Comment by photopea** [comment]
Imagine your image is completely white (all pixels are white). Someone tells you it is a photo of a white rectanlge on a white background, and tells you where are the corners of the rectangle. He asks you what is the aspect ratio of that original rectangle. How do you decide?

**Comment by MichalSZZ** [comment]
OK I understand but result can be Good crop or Bad (am I right?)? Can I decide somehow (with option in Photopea to do that), to change result to that alternative if first one is wrong? Without making perspective crop second time or more (because I still don't know how to draw correct one)?

**Comment by photopea** [comment]
It would probably take me a lot of time to explain it properly.

But in general, to estimate the aspect ratio correctly, the photo has to be identical as it came from the camera, and **never cropped**. 

Whenever you crop a photo (and you crop not around the center, i.e. the center of a photo changes), your new photo is "unrealistic" - such photo could never be taken by any camera. It is not possible to deduce any geometric properties in such case, because it is not a possible projection of a scene.

So I think there is no program in the world that would give you the expected aspect ratio, if you work with a cropped photo.

**Comment by ljcool2006** [comment]
My image isn't cropped and it's still broken for me
