### ISSUE TITLE
Lost Project

### ISSUE THREAD

**Issue by EOnac** [photopea/photopea#2837]
The Photopea website randomly reloaded and the project I had been working on for the past hour or so just disappeared. Is there any way of retrieving it? Nothing came up asking me to save it. I use Safari - does this make a difference? None of the other windows I had open reloaded, so I assume it's a bug within the Photopea website. Do let me know if I can get the project back. I was really pleased with what I was doing and would rather not restart.

**Comment by dentistformyeye** [comment]
If you switched to some other tab or app for a while, Safari or your computer in general might have tried to reduce the amount of memory it was using and prioritized whichever tabs/apps you were using most recently. The only way to recover a project is to save as PSD and save often. You could also try Edit > [Local Storage](https://blog.photopea.com/photopea-4-2-with-local-storage.html), but I think Local Storage is supposed to be for small resources rather than projects.

**Comment by photopea** [comment]
The web browser might "kill" any website, whenever it thinks it "misbehaves" in some way. I think in your case, Safari thought Photopea is using too much memory, so Safari killed it.

Can you update your Safari? Maybe a new version will not be so strict about using a lot of memory. Or try Chrome or Firefox. 

In general, Photopea has a setting such that you can not close it when there is an unsaved work (you will see a message to confirm that you really want to lose your unsaved work). But it seems like Safari ignores it.

**Comment by photopea** [comment]
But if you really went through the memory limits of your device, try to working with smaller resolutions, or save your work as PSD more often.
