### ISSUE TITLE
Double stroke - wrong render of style effect

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#2846]
I attached a PSD file. On preview between one and another stroke (added to a folder) there is a one pixel fake space.
![stroke-bad-rendering](https://user-images.githubusercontent.com/38118273/107239814-84412f80-6a29-11eb-8eae-0fe2c5a6022a.jpg)
[2020-12-09-polecaj-mail-ankieta-home.pl-13411.zip](https://github.com/photopea/photopea/files/5944590/2020-12-09-polecaj-mail-ankieta-home.pl-13411.zip)

**Comment by photopea** [comment]
Sadly, I do not know how to fix it. Our rendering pipeline is so complex, that even if I spent a day trying to fix it, there is a high chance that I would break something else.

If two stroke colors are different, the space should not be that visible. Also, you can add two strokes to one object (instead of the folder).

**Comment by MichalSZZ** [comment]
Ok. Thank you. That wasn't my project (just I made siple file to easly show the problem). In my file i must have 2 white strokes and one on folder.

Thank you for your time to respond.
