### ISSUE TITLE
Keyboard shortcuts with ctrl don't work

### ISSUE THREAD

**Issue by vadimmos** [photopea/photopea#2851]
On linux, when trying to use keyboard shortcuts with ctrl, for example "ctrl+Z" is triggered as "Z", "ctrl+shift+T" is triggered as "shift+T", etc.

**Comment by photopea** [comment]
Hi, the web browser has to tell the website which keys are pressed. If it does not, there is no other way for a website to know about which keys you pressed (websites do not have any direct access to your hardware). So there is nothing a website like Photopea can do about it. I think the Ctrl key does not work on any website in your case (so your problem is not related to Photopea).

Try to update your web browser or try another one. Or update your linux, download different drivers, etc.

**Comment by photopea** [comment]
I think it is a bug of your environment, which websites can not fix. Your browser could even be hiding your keystrokes from websites on purpose, to "protect you" and stuff. Nowadays, people install operating systems, browsers or browser extensions just because they have a word "privacy", "safety", "protection" in their name, while having no idea what it means.

We really can not do anything about it. You should fix your environment.

**Comment by rareseu** [comment]
@vadimmos I know it's late, but I recently noticed that when the "Show position of pointer when the Control key is pressed" option is enabled in Mouse settings (Linux Mint 22.1 Cinnamon), common CTRL shortcuts like CTRL+J, CTRL+Z, etc., do not work in many web apps such as Canva and Photopea. Disabling this setting restores normal shortcut functionality.

**Comment by photopea** [comment]
I think it makes sense. If you tell your OS to give a certain keyboard key a special functionality, you expect that functionality to happen when you press that key. Telling a current program that this key was pressed, and executing two actions at once, would make no sense.
