### ISSUE TITLE
ARTBOARD TOOL - BRUH....

### ISSUE THREAD

**Issue by timatismakle** [photopea/photopea#2898]
Please remove the artboard tool from the shortcut "V" and the move tool, place it somewhere in the menu of the crop tool or something. I think everyone is so used to hitting "V" a few times to select the move tool and now it select the artboard, which when used I don't know even how to revert, ctrl+z doesn't work.

**Comment by photopea** [comment]
If you have the artboard tool, press V to switch to the Move tool.

If you never used the Arboard tool, pressing V once will always switch you to the Move tool (the Artboard tool will never be enabled).

Artboard tool is enabled only if you have a Move tool and press V. So do not press V when you have the Move tool

**Comment by avagp** [comment]
I get you @timatismakle it is muscle memory, but Photoshop have the artboard tool on the SAME place.  :/

**Comment by MichalSZZ** [comment]
I think that in Photoshop tools are not changing in cycle when somebody hit key shortcut for that tool few times. It works in that way with ctrl(?) in photoshop

**Comment by avagp** [comment]
You are right @MichalSZZ , in photoshop you have to press and hold Shift and then the tool key to cycle through.
Here you can see it:
https://www.google.com/search?q=cycle+through+toll+photoshop&rlz=1CCZKSY_enCL923CL923&oq=cycle+through+toll+photoshop&aqs=chrome..69i57j0i67l3j0l3j46j0&sourceid=chrome&ie=UTF-8#kpvalbx=_Tp8uYLjWEICw5OUP6My6-AI11

**Comment by avagp** [comment]
Maybe that could change in Photopea?

**Comment by MichalSZZ** [comment]
I have friend with who I make lesson on Photopea. All the time he is very frustrated when Brush is changing to Pencil in Photopea.
I never had that problem using Photopea. Different people use Photopea in different way ;)

**Comment by photopea** [comment]
Ok, I fixed it. Photopea is not "cycling" tools by default, you need to hold Shift to do it (as in Photoshop).

The missing feature is: if you use e.g. a magic wand and close Photopea and open it again, it should set the Magic wand as the first tool (because you can not switch to Magic Wand by pressing W three times anymore).

**Comment by avagp** [comment]
Cool!

**Comment by timatismakle** [comment]
NICE!!! Thanks a lot :) Skrrrrrrrrr

**Comment by photopea** [comment]
Yeah .. I need to be told the same thing ten times to actually do it.

**Comment by avagp** [comment]
❤️

**Comment by photopea** [comment]
We already have people complaining about this: https://github.com/photopea/photopea/issues/2903

**Comment by avagp** [comment]
You should consider giving the new notice to the people.

Like posting on twitter/facebook, putting a sign on top of photopea at the beginng

:/

**Comment by avagp** [comment]
When i read the problem with @timatismakle i realized that i have always had the same problem with different tools.

When working i press the key to change the tool, but i have already selected, so i changed the tool and when i click i get another action. 

So the solution of having to press shift + key is more consistent, and also it is more consistent with photoshop.

Of course, people on #2903 will complain, because of muscle memory, today i had the same issue myself, but it will be gradually incorporated and become a second nature, and ultimately the problem with double selecting a tool with the key will be gone.


I am sharing this thought with you so you know i support this change, because i know there will be resistant to change at the beginning.
