### ISSUE TITLE
Artboard - Export as PNG and JPG should create multiple files

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#2899]
On Photoshop, when exporting a project to PNG or JPG with artboards, it  creates multiple files to download/save.

This should be the same with Photopea

**Comment by photopea** [comment]
I Implemented it.

When you use the Save for Web, and your project has artboards, and the format is PNG, JPG or GIF, there will be a checkbox "As Artboards". If you enable it, the saved file will be a ZIP file with an image for each artboard.

**Comment by photopea** [comment]
Another small fix - the checkbox is shown only if there are two or more artboards (not for one artboard).

**Comment by avagp** [comment]
![image](https://user-images.githubusercontent.com/11801254/113780576-662c3e80-96fd-11eb-96af-49925fe73555.png)
what is wrong here?

**Comment by avagp** [comment]
It does export as a zip with multiple images, so it is fine, maybe giving a different display on the preview when checking the "As Artboards", so i can get the idea.

Another thing is that the images inside the .zip have dates of 28 of feb, 1997, can that be fixed?

**Comment by photopea** [comment]
The preview shows a rectangular image with all artboards. The space between artboards is transparent.

I fixed the time in ZIP files. But note, that ZIP does not store the timezone. If two files were created on the same day, one at 10:30, another at 11:30, the second one could be created earlier than the first one (because it could be in a different timezone).
