### ISSUE TITLE
Ad Blocker Photopea

### ISSUE THREAD

**Issue by jholmes022021** [photopea/photopea#2939]
I am using Photopea and the ad blocker is coming up. I have refreshed, restarted, turned ad blocker off and updated the Chrome browser. Any other ideas to help me? It sounds like the same issue that happened previously. 
Thanks

**Comment by photopea** [comment]
Hi, can you see the ads in Photopea correctly? Do you still see a message in Incognito mode (i.e. with all extensions disabled)?

**Comment by ThePoser** [comment]
The same thing is happening to me.  I can't even finish my work at a decent rate because of the popup.  I turned off my adblocker, put photopea on the trusted sites, and I'm still getting the popup.

**Comment by photopea** [comment]
@ThePoser I am sorry, we would not exist at all, if people did not watch ads. So watching ads is really important to us.

You did not say if you see the ad or not?

**Comment by jholmes022021** [comment]
He a couple of students that are having issues. I have been working with them. I sent them and image of my ads and haven’t heard back yet.
Thank you for your response. Shall I respond to this email?
Jill

**Comment by photopea** [comment]
I do not understand your email. what is "he a couple"? what is "them and image"?

**Comment by EVanPelt** [comment]
Hello, I also am having a issue with the ad blocker message.  I work for a school and we are currently using the free software as an educational tool.  However, because we are using educational accounts, as both students and teachers are required to do, we have no control over ad blockers.  This is controlled by the school administration and it.  

Is there way to disable this for teachers working with students educational accounts?

**Comment by photopea** [comment]
We do not have any educational accounts. Anyone who opens Photopea.com can use it right away, without making any account. So there is no way for us to tell if the current user is a student or not.

Could you ask your school to disable your ad blockers? Ad blocking is even worse than software piracy and I am shocked that a school does it. It is just another way of evading pre-made mechanisms and preventing the software creators from making money from their work.

If you want no ads, and no paying for the software, try GIMP or Paint.net

**Comment by EVanPelt** [comment]
I understand and appreciate your issue with the ads, however, in education
there are a number of legal issues that need to be considered when dealing
with ads visible to school children.

As for educational accounts.  It's quite common for industry leaders to
make their software available to education at a great discount or for free,
as it means that software is being taught to future users, who in turn will
eventually pay for it.

Erik Van Pelt

**Comment by photopea** [comment]
You can make it run on your domain, and then, I can put your domain into the whitelist, as described here: www.Photopea.com .

Our Premium accounts are quite cheap, too.

**Comment by ag1974** [comment]
Your advertising system FUCKING SUCKS!!! I don't even have an adblocker on my DAMN COMPUTER AND YET you feel as if you need to ram that GOD AWFUL notification in my face EVERY 2 MINUTES!!! And I love your software. It is very beneficial to me. But please! Fix the pop-up so that the users WHO DON'T HAVE AN ADBLOCKER don't get the pop-up.

**Comment by ag1974** [comment]
> We do not have any educational accounts. Anyone who opens Photopea.com can use it right away, without making any account. So there is no way for us to tell if the current user is a student or not.
> 
> Could you ask your school to disable your ad blockers? Ad blocking is even worse than software piracy and I am shocked that a school does it. It is just another way of evading pre-made mechanisms and preventing the software creators from making money from their work.
> 
> If you want no ads, and no paying for the software, try GIMP or Paint.net
I completely agree and I understand making money off of the content you worked hard to make and you continue to work hard in order to make it free. The reason schools like to standardise advertisement is because a lot of content creators, mostly online news websites, love to abuse advertisement just so that they can make money. Chances are that this is why clickbait exists. The problem is that a lot of schools rely on internet news to teach classes. So they started using adblockers. Problem is, websites can ask to bypass your adblocker and if you refuse to do so, they can take the content away from you. Adblockers are ineffective. However, that said, your ads are not intrusive in the slightest. I don't mind your ads, but I don't have an adblocker and for some reason the site tells me to turn off my (nonexistent) adblocker. That's my issue.

**Comment by photopea** [comment]
@ag1974 Can you show us a screenshot of Photopea.com with ads as a proof, that ads are displayed correctly in your case?

What do you mean by an adblock? Any browser extension can try to remove ads. Open Photopea.com in icnognito mode to see, if ads work (browser extensions are disabled in Incognito mode).

**Comment by Crisicrack** [comment]
I have the exact same problem, I have already deactivated my adblocker, I know you need the ads and I don't mind seeing ads but it doesn't even let me see them, it keeps showing me that I have to deactivate my adblocker and I refresh the page and the popup keeps appearing, I hope it can be fixed and thank you.

**Comment by photopea** [comment]
@Crisicrack What is an adblocker? How do you know which extension does what?

Please, try to open Photopea with no browser extensions, e.g. in Incognito mode, and see if it works.

**Comment by EVanPelt** [comment]
This only just started happening for me, but I still can;t get it to stop.
Was there some update recently to Photopea that's causing this?

Again your product has been a lifesaver and I've no problem with seeing a
few ads, but nothing I do seems to fix the problem.  By the way I don't
believe Incognito is a valid/legal option for public educators while they
are working.  Certainly it is not something that would be looked favorably
upon by administrators.

EVP

**Comment by photopea** [comment]
@EVanPelt  We update Photopea about 10 times a day, fixing small bugs and improving things.

I am 99% sure you have a browser extension, which is blocking ads, so you have to disable it, there is no other way.

**Comment by jholmes022021** [comment]
My students have an ad blocker on their devices. I had them go in an allow the ads for Photopea. On ours you can allow it site, by site. See if yours works the same way. Until we figured this out, my students were having the same issues.
Good luck.
