### ISSUE TITLE
Path Select and Direct Select have the wrong icons in the sidebar after you select them

### ISSUE THREAD

**Issue by mittelmanda** [photopea/photopea#2952]

**Comment by photopea** [comment]
Hi, every tool icon changes the color after you select it. A black rectangle becomes a white rectangle, and a black arrow becomes a white arrow.

You can distinguish between the Path Select and Direct select, because the Direct Select is always just an outline (black or white).

![image](https://user-images.githubusercontent.com/15955558/109330130-a32e2700-785b-11eb-9ff8-8dc56517f33d.png)

**Comment by nothingshiru** [comment]
It confused me either. 
Because the icon of path select in photopea is similar to the icon of direct select, and the icon
 of direct select in photopea is same. 
![新建项目](https://user-images.githubusercontent.com/79258245/109785925-99376a00-7c47-11eb-8f6f-e289fb6c8e40.png)
