### ISSUE TITLE
PSD is now saving in txt!

### ISSUE THREAD

**Issue by luisckc** [photopea/photopea#2992]
Hi. By clicking on File, Save as PSD, is now saving in txt ...
When I manually change the file extension, from txt to psd, Photopea itself is able to open it.
Windows 10, Browser Microsoft Edge Version 89.0.774.48 (Official build) (64 bits). Yesterday, when trying Photopea in this browser for the first time, this did not happen.
I tested it in Chrome and also saved it as a txt. Windows 10, Google Chrome Version 89.0.4389.82 (Official version) 64 bits.
![Chrome-psd-txt](https://user-images.githubusercontent.com/67866380/110642720-0c823400-8192-11eb-8548-ca1a6224269c.png)
![Edge-psd-txt](https://user-images.githubusercontent.com/67866380/110642730-0e4bf780-8192-11eb-8641-dd99d30504c5.png)

**Comment by photopea** [comment]
Hi, you are using a browser extension, which renames your files to .TXT. You should disable that extension, or ask the authors of your extension to fix this problem.

This problem is being reported here almost every day, e.g. yesterday: https://github.com/photopea/photopea/issues/2990

https://github.com/photopea/photopea/issues/2979

https://github.com/photopea/photopea/issues/2868

https://github.com/photopea/photopea/issues/2778

https://github.com/photopea/photopea/issues/2770

There are so many people out there, who have no idea what their browser extensions do.

**Comment by luisckc** [comment]
I'm sorry. I will do better research next time. It was a download manager
in charge. I deleted the extension. Thank you very much for your assistance!

Em qua., 10 de mar. de 2021 às 11:23, Photopea ***@***.***>
escreveu:
