### ISSUE TITLE
Raw files are not opening

### ISSUE THREAD

**Issue by NasarBaig** [photopea/photopea#3044]
Dear Sir,

I am trying to open raw file from my canon dslr camera, the files extensions are CR2, I tried to open different raw files in the photopea free account, but it is keep on giving error.
Can you advise on this issue.

Thanks

**Comment by photopea** [comment]
I have about 60 CR2 files in my computer, all from different cameras, and they all work well in Photopea.

Can you send me your CR2 file to support@photopea.com ?

**Comment by NasarBaig** [comment]
I have emailed the file to your give address, please see what is the issue.
Thanks

**Comment by photopea** [comment]
I see it. It is a special format of CR2, which is not supported by Photopea.

Can you convert your file to DNG format? Photopea supports DNG very well. Otherwise, CR2 format is made by Canon and is not publicly described. Canon does not want anyone to open the CR2 files. Ask Canon to give you software for working with your file.

**Comment by NasarBaig** [comment]
Thanks for the help, I think it is a long process to do so, anyway I learn
that I can use my JPG images but can't use my raw images straight away.

Thanks again.
