### ISSUE TITLE
Problem opening PSD file, generated in photopea

### ISSUE THREAD

**Issue by Nils-1st-retail** [photopea/photopea#3047]
Hi,
I have a psd file, that was generated in photopea. But when i try opening it again i get an error
`pp.js:formatted:6434 Uncaught RangeError: Invalid typed array length: 986490`

The pds file in question can be downloaded here [https://drive.google.com/file/d/1X4b6TaLBVQr7ZDYeS-nT7b0p-_UNcY6B/view?usp=sharing](url)

**Comment by photopea** [comment]
Hi, I think your PSD file has been modified by some other program, after being exported from Photopea.

Are you using any browser extensions, which have a permission to read and modify the web content?

One of these extensions could modify the PSD file in order to protect you from viruses or something.
