### ISSUE TITLE
a issue with quick selection, it is not getting switched to subtract mode

### ISSUE THREAD

**Issue by parmonov98** [photopea/photopea#3101]
https://youtu.be/D4Tc67EoVCI

**Comment by photopea** [comment]
Hi, when you work with a Quick Mask, or with any other mask, a tool is aware only of the pixels of that mask. A tool (quick select or a magic wand) is not looking into other layers, etc.

It works the same in Adobe Photoshop and other programs.

**Comment by dentistformyeye** [comment]
@parmonov98 Quick mask and quick selection are different tools that usually aren't used together.
Quick selection is for when quick mask is off. It "paints" selections and tries to predict where there are edges. If there is no existing selection yet, the tool won't switch to Unite mode or Subtract mode because it has to make a new selection first.
When quick mask is on, instead of using selection tools, use the normal brush tool to paint with black (adds red) and white (remoes red). When you turn quick mask off again, the mask becomes a selection: areas that aren't fully red become selected.

**Comment by photopea** [comment]
@dentistformyeye  thanks for the explanation! :)   I will close it now.

**Comment by parmonov98** [comment]
> @dentistformyeye thanks for the explanation! :) I will close it now.

![image](https://user-images.githubusercontent.com/24564577/114126390-c693c980-9911-11eb-8481-a3be198dd89d.png)
![image](https://user-images.githubusercontent.com/24564577/114126733-6ea99280-9912-11eb-897c-f2b5da921faa.png)
(the section  selected here doesn't exist in photopea) how can I subtract an extra part of selection(object selection used to select) 
![image](https://user-images.githubusercontent.com/24564577/114126808-926cd880-9912-11eb-9981-32ea1a2726bf.png)

**Comment by dentistformyeye** [comment]
You could try quick mask. Press Q, use the normal brush tool to draw black (shows up as red) on the part that shouldn't be in the selection, then press Q again to turn off quick mask.
However, since the area you want to get red of has nearly straight edges, you could select it with the polygonal lasso tool in subtract mode.

**Comment by photopea** [comment]
Photopea does not have all features of all existing photo editors. If you prefer another photo editor, just use the other one, like Adobe Photoshop.

**Comment by parmonov98** [comment]
@photopea, can I add the feature? Actually, I'm trying to switch on free-ware software.
