### ISSUE TITLE
raw file opening 

### ISSUE THREAD

**Issue by pallawhee** [photopea/photopea#3114]
The software doesn't allow me to open and edit raw .cr3 files, I'd be really grateful if I could edit .cr3 files <3

**Comment by photopea** [comment]
Hi, sorry, but CR3 is not an open format and it seems to be too dificult to figure out. We want to encourage people to buy cameras, wich save raw photos in open formats, such as DNG. Pentax and Leica cameras can do that.

If you buy a camera from Canon or Nikon, you depend on these companies to provide you a software for editing your photos. At least they can save regular .JPG files, instead of some .CJPG (canon JPG), for which you would need an image viewer from Canon. But maybe in the future, they will replace JPG with their own proprietary format, and every manufacturer will have their own alternative to JPG, which will not work in regular image viewers.
