### ISSUE TITLE
Issue: Blend if has problem with the colors which are with 100% of brightness. 

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#3128]
For explaining the issue, here's a PSD. https://www.photopea.com/#isCJ8FUFy

There's a layer A which is a gradient from black to white, left side to right side, 
and a layer B filled with red in the top half, green in the bottom half. 
The red is with 100% brightness, the green is with 99% brightness. 
![IMG_20210424_233610](https://user-images.githubusercontent.com/79258245/115964862-046f2f80-a559-11eb-81db-40ed5c120f12.jpg)

Adjusted the sliders of blend if in layer A, you'll see the area of layer A above green is removed correctly, but the area above red isn't. The entire area above red is removed no matter how you adjusted the sliders even from 0 to 1 or from 255 to 254. 

Dragged the layer B over layer A, adjust the sliders of blend if in layer B. You'll see similar results.

Here's a video recorded how they works. 
The red area in layer B/area of layer A above red always disappeared when start adjusting. 

https://user-images.githubusercontent.com/79258245/115967862-8cf4cc80-a567-11eb-9183-dcb81107a18f.mp4

I have tried in different browsers(Chrome, Edge, Firefox) and 3 different Android devices. All is the same.

**Comment by nothingshiru** [comment]
I created another image and recorded what was going on. 

Blue is with 99% brightness, 
red is with 100% brightness. 

https://user-images.githubusercontent.com/79258245/114879586-ebb59a00-9e33-11eb-9754-6b386cd5309e.mp4

**Comment by dentistformyeye** [comment]
Blend-if seems to be working correctly for me.
Here's what I have if I change the top blend-if threshold for layer A, which is the gradient on top:
![image](https://user-images.githubusercontent.com/51429646/115966689-c3493200-a4fc-11eb-84c8-1c4d74cc3df2.png)

If I change the bottom threshold for layer A, one color disappears before the other, as expected, because green with 99% brightness is still lighter than red with 100% brightness:
![image](https://user-images.githubusercontent.com/51429646/115966713-d5c36b80-a4fc-11eb-95ba-b691f548b033.png)
![image](https://user-images.githubusercontent.com/51429646/115966735-ea9fff00-a4fc-11eb-9415-cf6ec052b096.png)

**Comment by nothingshiru** [comment]
It's weird.

I have just tried blend if on a computer with windows 10. It works correctly. And I tried to run Android on that computer by using a Android simulator software then tried it again. It works correctly too.

**Comment by photopea** [comment]
The same problem was happening on my phone, too (Android 6). It is fixed now.
