### ISSUE TITLE
Clone Tool

### ISSUE THREAD

**Issue by claire565** [photopea/photopea#3238]
Hi there

I'm learning so please bare with me.

I've always used the clone tool with no problem, yet now I can't used it as the cursor disappears when I go onto the image I'm working on.

It was absolutely fine last week but today, I just cannot get it to work.

What am I doing wrong? I've tried as a smart image and as a rasterized image but I just can't get it to work. 

I've enabled WebGL so I just don't know what I'm doing wrong.

Thanks for your help and apologies if this is the wrong place to post this.

Thanks.
Claire

**Comment by photopea** [comment]
Hi, if you set the cloning source (Alt+click), the cursor becomes a circle with a part of the image from the source.

There was a bug, if you set the source outside the image, the cursor was transparent (invisible). I added a little crosshair to the middle of a cursor, so that you can always see it.
