### ISSUE TITLE
Alt-click on layer thumbnail creates clipping mask instead of displays layer contents in the workspace

### ISSUE THREAD

**Issue by dentistformyeye** [photopea/photopea#3257]
Alt-clicking a layer thumbnail (instead of the eye button or another part of the layer entry) in the Layers panel should make the workspace display the contents of only that layer.
1. Click File > New > Create to create a new document.
2. Create a new empty layer and use the brush tool to make an obvious mark in the workspace.
3. Alt-click the layer thumbnail. >> Creates a clipping mask.

**Comment by photopea** [comment]
Why do you think it should work this way? I think it makes more sense to show only a specific layer after alt+clicking the eye icon.

**Comment by MichalSZZ** [comment]
@photopea  I don't know how long that function is in Photoshop, but behavior listed above is correct. Alt + click on the layer thumbnail should make a zoom on that layer in that way - to fit 100% the whole workspace (in width or height). I don't use it (maybe because it is a new thing) but that how it's work.

**Comment by dentistformyeye** [comment]
My bad, I was wrongly remembering that this feature had already been in Photopea and thought it had been affected by a bug. I don't need this feature, but if @photopea still implements it, be careful that it doesn't interfere with ctrl-alt-click and ctrl-alt-shift-click (making boolean selections) or alt-click for clipping mask.
