### ISSUE TITLE
plugin

### ISSUE THREAD

**Issue by mustafaGFX** [photopea/photopea#3300]
about 10 days ago I texted you and told  you that I wanna pay for some programmer to make me some plugins, and you told me what is plugin I want to create if you can create it for free and for all users, 

the plugin that I want to create is 3d elements plugin, it gives me png image of an object with any angle I want, which is very useful for graphic designers and photo manipulators

i designed the UI/UX of the plugin :

![michael-olsen-mSTK6URRWU8-unsplash (1) (2)](https://user-images.githubusercontent.com/70863817/119350968-3bdc1380-bca0-11eb-918f-51680f321cde.png)

![michael-olsen-mSTK6URRWU8-unsplash (1) (3)](https://user-images.githubusercontent.com/70863817/119350959-3979b980-bca0-11eb-95eb-a7e1fc63e040.png)

![4f9c41e2a5e6fccaeda0475f4aab4106](https://user-images.githubusercontent.com/70863817/119351047-5615f180-bca0-11eb-8b33-9d7c7b9702f6.gif)

![99358PICa7E0un3faZ3eC_PIC2018 (1)](https://user-images.githubusercontent.com/70863817/119352066-814d1080-bca1-11eb-944a-0d86878f4d7c.gif)

**Comment by photopea** [comment]
Should we have a database of 3D objects, or the user can only load their own 3D objects?

There is a million of ways how to render an object. You could want different lights and shadows, different materials (glass material, mirror material).

https://miro.medium.com/max/3200/0*-w-KEePVFAorKsfW
https://blogs-images.forbes.com/kevinmurnane/files/2017/11/Checkerboarding_DF_YT.jpg
https://d34urnl45u363e.cloudfront.net/store/article/213/image/large-a9f04513d4f6329548346619b91c616e.jpg

Do you think users will be happy if we offer just one, simple way of rendering a 3D object?

**Comment by mustafaGFX** [comment]
similar plugin 
https://www.pixelsquid.com/plugin_demo#

**Comment by mustafaGFX** [comment]
I think if we use an online free 3d objects website it will be great
like https://clara.io/library

but this website doesn't have good 3d objects, if it's even possible we can find a website that gives us good free objects

**Comment by mustafaGFX** [comment]
there a hundred sites that can provide us with a professional free 3d object but the problem is that they can't be rendered on the same site, just download and use them on your own software like blender or 3d max
https://free3d.com/

if we can have a database for these free 3d objects it will be great

**Comment by mustafaGFX** [comment]
BTW I'm good with blender 3d, I can design realistic objects just for photopea

**Comment by yikuansun** [comment]
@mustafaGFX Your plugin looks great, I think this would be awesome as a built-in plugin

**Comment by yikuansun** [comment]
@mustafaGFX That would be cool!

**Comment by yikuansun** [comment]
@photopea I think some libraries such as Three.js could handle different settings for rendering.

I would already be happy with a simple system with not much customization flexibility, as the output could be further edited using Photopea. I think some stock 3D asset platforms like Envato Elements just let you simply choose an angle and download the image, so I feel that having this basic feature would already be helpful for many users.

**Comment by mustafaGFX** [comment]
> That would be cool!

great, how can we contact or collaborate.... what do you think of using GitHub itself?

.
.
.
.




>  I think some stock 3D asset platforms like Envato Elements just let you simply choose an angle and download the image

that is exactly my idea :)

**Comment by mustafaGFX** [comment]
I have made the plugin experience and look and it really excites me :)
you can try the full plugin now

[the plugin](https://www.photopea.com/#%7B%22environment%22:%7B%22plugins%22:%5B%7B%22name%22:%223d%20elemnts%22,%22url%22:%22https://framer.com/embed/photopea--4t3qPaRjaGf8FjCpE9um/pDrs6VbHB%22,%22width%22:741,%22height%22:1300,%22icon%22:%22https://i.imgur.com/gVhnxj0.png%22%7D%5D%7D%7D)
[the plugin source](https://framer.com/share/photopea--4t3qPaRjaGf8FjCpE9um/pDrs6VbHB?fullscreen=1&highlights=0)

**Comment by yikuansun** [comment]
> great, how can we contact or collaborate.... what do you think of using GitHub itself?
Sure, you can drop messages into the issues sections of my repositories

> I have made the plugin experience and look and it really excites me :)
> you can try the full plugin now
This looks great! Is this just a UI design demonstration or will the final program be built directly onto it?

**Comment by mustafaGFX** [comment]
@yikuansun 
 no, it's  just a UI design demonstration, but it will be amazing if it looked like this or better

**Comment by photopea** [comment]
Guys, I am looking forward to see what you come up with :) I will close it here for now.

**Comment by yikuansun** [comment]
I have begun working on the development of this plugin. The JSON data is:
```
            {
                "name"  : "3D Elements",
                "url"   : "https://yikuansun.github.io/photopea-3delements/",
                "width" : 400,
                "height": 500,
                "icon"  : "https://yikuansun.github.io/photopea-3delements/icon.png"
            }
```
Currently, the plugin shows the viewer for one 3D model.
Here is the repository: https://github.com/yikuansun/photopea-3delements

**Comment by photopea** [comment]
Wow, that is nice :) I made a library for parsing 3D formats about 10 years ago:  http://k3d.ivank.net/?p=demos&d=parsingCollada

Also, I made a photorealistic 3D renderer 10 years ago, but it is very basic: http://blog.ivank.net/3d-tool-web-based-3d-model-viewer.html

**Comment by mustafaGFX** [comment]
wow wow wow wow that is super amaaaaazing 
omg i thought you forgot this plugin

@yikuansun you are my hero ❤️❤️

**Comment by mustafaGFX** [comment]
BTW the animations look very unique, I like them, excellent job :)

**Comment by yikuansun** [comment]
@photopea Your libraries are great! Currently, I'm using Google's `model-viewer`, but will consider using your libraries if more control options are needed.
Previously, I was using the Clara.io viewer API, which would work seamlessly with the Clara library. However, I found the viewer API to be too bad, so I used `model-viewer` instead. I will just use their REST API to import their models but use Google's viewer.

@mustafaGFX Thanks 😃

**Comment by yikuansun** [comment]
I don't think we can use Clara.io's library, Clara REST API falls apart to CORS (so its API just doesn't work with client-side JS). SketchFab, however, has [documentation](https://sketchfab.com/developers/download-api/downloading-models/javascript) for using its API with client-side JS, and SketchFab also has an impressive collection of models, so unless there are issues with payment or whatnot I will probably use SketchFab.

Currently, the placeholder library is just sample glTF files from the creators of GL. I set up my code so that to change which library to use, I just need to change the request-making function.

**Comment by yikuansun** [comment]
SketchFab's Download API restricts usage amount to only 15 a minute and only 50 a day, making it impossible to use for this plugin. I think the only option is to stick to the current library, or use another library whose data is open and does not require OAuth. Since there is an option for users to import other models, they can just download models on their own from places like Clara.io and Sketchfab.

I think the plugin is ready for people to use now. @photopea Could you add it to Photopea?

**Comment by photopea** [comment]
I added it to Photopea. I don't know who would use such plugin, as there are almost no useful models, and images do not look realistic, but let's see.

**Comment by Jeefr** [comment]
good👍

**Comment by mustafaGFX** [comment]
@yikuansun 

> I think the plugin is ready for people to use now

hey, that's amazing and I really appreciate it and appreciate that you have been tired to make it :)
but I have very few notes about the plugin

as @photopea said, there are almost no **_usefable_** models, and the plugin still needs one more step to be perfect and actually usable

1- is it possible to add the models manually, so that we can choose the usable models, also we can make the plugin have more models, if possible, I can add maybe 20/25 models per day.... after a month we would have about 700 usable models in average

2- it would be so much better to view the model's library on a page instead of making it as an pop-up window.

now:
![Screenshot (237)](https://user-images.githubusercontent.com/70863817/125615669-b3991c62-c2a4-4fcf-aad2-00245c238334.gif)


then:
![Screenshot (237) (1)](https://user-images.githubusercontent.com/70863817/125615688-8862c58f-ee15-4cd5-8025-6d7f43a217d5.gif)

3- search 
imagine that I am a graphic designer and I need a car model to use in my design, simply I can't use this plugin directly because it doesn't have a search bar where I can type what I need (car- bird- tree... etc

![Screenshot (237) (2)](https://user-images.githubusercontent.com/70863817/125617727-c420f830-3b74-48cb-b50c-74dec19372ee.png)

in general, the plugin is technically working well and the idea is amazing, but its actual experience is not usable, it can be perfect and the most usable plugin have ever made for photopea, we just need one more step

**Comment by mustafaGFX** [comment]
one more thing, can you please make it darker to match with the black them?

**Comment by yikuansun** [comment]
@mustafaGFX Thanks for the feedback! As for uploading the models, do you have any ideas about what platform to use for this? I was thinking of maybe making a Github repository that people can contribute to. Since I'm a bit of a developer myself, this process would probably seem much simpler to me than for a non-developer, so I'd like to hear what you think about it.

I can probably roll out the searchbar and library page pretty quickly, I'll get to it when I have time.



> one more thing, can you please make it darker to match with the black them?

I thought the default theme, which I think most people will be using, is Dark Grey, shouldn't we be using that?

**Comment by mustafaGFX** [comment]
> do you have any ideas about what platform to use for this

yeah, when it comes to manually add models to a database it becomes too easy to find free high-quality realistic models
we can use models from [free3d.com](https://free3d.com) or [cgtrader.com](https://www.cgtrader.com/free-3d-models)
they have not just usable models, they have amazing models

regarding making a Github repository that people can contribute to, it seems a good idea, but what about the non-developers?
can you program a page where we can add the models easily and host them under github.io ( [like this](https://yikuansun.github.io/) ), it would simplify the process for you to add more models and for everyone which meant everyone who is interested can upload his models to use them later

for the theme, I agree with you, most people use the default dark grey theme, so let's forget it for now until Ivan change the default theme to dark which I found it a great idea

**Comment by yikuansun** [comment]
@mustafaGFX I added a search bar, made the library in a page instead of popup, and made a simple form for submitting models. I have to verify submitted models for them to show up in the library. Currently, the form asks for file URL's similarly to adding Photopea PSD templates. Especially since I don't have a server, sending uploaded files proved to be a technical and logistic problem (there would be issues with security and storage location and whatnot). There are many easy ways to share file URL's, some of which I linked to on the form page. This is obviously a little more inconvenient for end users than direct uploads, but I think that it is a pretty good alternative since direct uploads are problematic.

> yeah, when it comes to manually add models to a database it becomes too easy to find free high-quality realistic models
> we can use models from [free3d.com](https://free3d.com) or [cgtrader.com](https://www.cgtrader.com/free-3d-models)

Yeah, I was trying things like these out previously, I looked at Clara.io and Sketchfab. However, for the models to be able to work with the plugin, the platforms need good API's (a way for apps and programs to read the data). Clara.io's API didn't work with client-side JS, and Sketchfab's API restricted how many models you can get per period of time (making it basically unusable for a mass-fetch like what we are going for). free3d and cgtrader don't even have API's. I researched for other platforms but none fit. It's a shame that Google Poly shut down because I think that might've worked well (API's made by Google are usually great).

**Comment by mustafaGFX** [comment]
wow, that looks great, and the search bar gives the plugin a professional look :)
.
.

> This is obviously a little more inconvenient for end users than direct uploads

> that it is a pretty good alternative since direct uploads are problematic.

it is not that bad, I'm very okay with it, I know it would be better to direct drag and drop files but as it efficiently works well I'm okay

regarding the API, I understand it would be so much better to use an API instead of manually add file by file, but I don't think that there is any good and professional website that gives a full free API for such a purpose, that is not logical, this was the main reason I asked you to make the plugin Depends on itself, not on a free unusable API

> yeah, when it comes to manually add models to a database it becomes too easy to find free high-quality realistic models
> we can use models from free3d.com or cgtrader.com

in our situation, the mentioned websites can only be used to download models and re-upload them on google drive or dropbox, I know some friends who maybe have their models on google drive, I will see what can I do

**Comment by yikuansun** [comment]
@mustafaGFX Gee... I almost forgot about Netlify! Netlify has a form handling API which allows for file uploads, and it even generates links for the files so I won't have to worry about storing the files myself. I implemented this, I think it's pretty great but I'd be glad to hear what you think. The **Reqest a Model** page has switched to being at [https://submit3dphotopea.netlify.app/](https://submit3dphotopea.netlify.app/).

**Comment by photopea** [comment]
@yikuansun hey, could you add your plugin into the new Plugins gallery? Window - Plugins.

Someone on  Reddit is looking for it: https://www.reddit.com/r/photopea/comments/v2bnra/3d_window/

**Comment by yikuansun** [comment]
Sorry, I kinda left this plugin to work on other things. I'll try to fix some things, bring it back up to date, and post it onto the new Plugins gallery.

**Comment by yikuansun** [comment]
@photopea I've fixed the problem and replied to the Reddit post.

Also, do you know what happened to @mustafaGFX ? I miss his presence on GitHub :(
