### ISSUE TITLE
Bug in photopea.

### ISSUE THREAD

**Issue by YDGFX** [photopea/photopea#3357]
Whenever I try to create a shape with the pen tool, the program suddenly stops working and now it's even when I try to duplicate a layer. I don't know what's going on behind screen but this is really bugging me, fix this problem as soon as possible.
Thanks!

**Comment by photopea** [comment]
I tried to create a shape and it works fine. What exactly are you doing? Is your web browser updated?

**Comment by YDGFX** [comment]
How do I update a web browser? Doesn't it update itself? I'll try showing a video as an example of how the program suddenly just stops working.

**Comment by YDGFX** [comment]
Wait, WHY DID IT SUDDENLY START WORKING???? ON GOD.

**Comment by photopea** [comment]
Ok, a video of a problem would be hepful. As I can not make Photopea stop working myself.

**Comment by YDGFX** [comment]
I took a video and I try to post it/send it but the video file type is not supported.

**Comment by photopea** [comment]
send it to support@photopea.com , or put into ZIP and upload ZIP here.

**Comment by photopea** [comment]
I received your video.

It is not clear, what oyu are trying to do, because you are not saying any voice comments.

The text looks "invisible", because you are typing the black text on a black background.

I see you are using many browser extensions. Maybe one of them is breaking Photopea.

We guarantee 100% functionality in a browser with no extensions. You should add extensions carefully, because you never know what exactly they do. Before you report any bug to us, please, make sure, that the bug happens in a browser with no extensions enabled.
