### ISSUE TITLE
Export PDF - Corner paths changes after exporting

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#3423]
![image](https://user-images.githubusercontent.com/11801254/122501975-ae9c8e00-cfc3-11eb-8b9c-b00a8efd7bfe.png)

Here are the files
[Archive (4).zip](https://github.com/photopea/photopea/files/6674417/Archive.4.zip)

**Comment by photopea** [comment]
You are stroking a vector path. There are several methods how to stroke corners (joints): 
![CapsAndJoints](https://user-images.githubusercontent.com/15955558/122639877-b875dc80-d0fc-11eb-8dec-a4aa8f22aa43.jpg)

Your stroke uses the "Miter" method.

One of your vector points looks like this:
![image (3)](https://user-images.githubusercontent.com/15955558/122639894-ce839d00-d0fc-11eb-88c7-e135f75b936e.png)

Photoshop considers it as not a corner (because both handles are opposite to each other, it is smooth). However, your PDF viewer considers it a corner, and draws a "blade" (with the miter method). So I think it is a bug in your PDF viewer.

I opened your PDF in Adobe Reader and it looks correctly (while it is incorrect in Chrope PDF viewer).

![image (4)](https://user-images.githubusercontent.com/15955558/122640060-a34d7d80-d0fd-11eb-9057-5a250e0e1146.png)

**Comment by photopea** [comment]
I have reported it to Chrome: https://bugs.chromium.org/p/chromium/issues/detail?id=1221783

**Comment by avagp** [comment]
Thanks for explaining and reporting!
