### ISSUE TITLE
Feature Request: Look At Fireworks

### ISSUE THREAD

**Issue by WebSpectrum** [photopea/photopea#3441]
I think you should take a closer look at Adobe Fireworks and some of it's intuitive features, like handles for adjusting gradient and pattern fills for example, makes working with gradient fills and masks much easier ...

**Comment by photopea** [comment]
What exactly are you talking about, and how should we combine it with what we have now?

If you are just used to Fireworks, and not used to Adobe Photoshop, it is better if you learn to use what we have, instead of asking us to remake it.

**Comment by WebSpectrum** [comment]
Well, if you want to make an inferior clone of Photoshop which is what you have done that is your choice. Adding something different and some Fireworks-like features could attract new users. I already use Photoshop  but prefer Fireworks for fast prototyping and quick jobs...

**Comment by gingerbeardman** [comment]
Fireworks had is Final release with CS6 (12) on May 7, 2012; 9 years ago.

Photoshop is still being sold today.

I think making a competitor to Photoshop was the right choice.

Though Fireworks did have some cool features.

**Comment by WebSpectrum** [comment]
Yes and a  lot of people still use it and are looking for alternatives ... No problem, I'll carry on using Photoshop, Fireworks and Affinity software ... You basically copied Photoshop from top to bottom ...

**Comment by photopea** [comment]
I don't mind adding new features, which can be inspired by other software, or are completely new. Most of our users know Photoshop and they suggests features from Photoshop (or GIMP sometimes).

@WebSpectrum Let's do it step by step. Can you suggest a specific feature, and to what tool it can be added? So that it does not sound like "you made a boat, now, remake it into a plane".
