### ISSUE TITLE
Feature Request - QR Code Generator

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#3453]
I use it a lot when I'm making something to print. 

I think that should to be easy to do for you, because there are many sites on the web that can do that. Most of them, are not free of cost when the user want something more (change the color, add a logo in the center, change the shape of squares, change url later, track the URL etc.)

Maybe you can do your own site with that generator. Put advertasing there and then the code from it add to Photopea as a Addon in Window->More (only the core of the code - generating black shapes from URL with one option at the start - Error correction https://en.wikipedia.org/wiki/QR_code#Error_correction it is a good solution for designers who wants to put logo or any other graphics there)

I always have use this one for Illustartor https://exchange.adobe.com/creativecloud.details.107.qr-code-maker.html but now - in my work I have Windows with permissions that block me to add the new addon :/

**Comment by photopea** [comment]
@hxim Would you be interested in making a QR plugin for Photopea? Simlar to your Emojis plugin? :) Maybe you can use an existing JS library for it.

**Comment by hxim** [comment]
@photopea Seems interesting. Maybe I could use api from here directly https://goqr.me/api/doc/create-qr-code/

**Comment by MichalSZZ** [comment]
@hxim sounds great!
If any help from my side will be needed - ask my anytime!

**Comment by MichalSZZ** [comment]
A huge advantage compared to any free tools on internet - will be a vector format as an output (most of pages generate for free only raster PNG and JPG - SVG are in paid accounts)

If someone is a designer then he know how to: 

- add a logo to that QR code
- change the color of squares
- make round shapes to have fancy look

**Comment by MichalSZZ** [comment]
I looked up on the API and they have everything what I need.
They have even offer to create a special QR codes https://goqr.me/qr-code-logo/ with logo etc.
@hxim If you will add a ECC parameter - the designer can put logo by hand in QR code, just after generating (when he will have a quick tutorial  about it)

**Comment by hxim** [comment]
Hi, now you can try initial version of QR Code Generator plugin here:
https://www.photopea.com/#%7B%22environment%22:%7B%22plugins%22:%5B%7B%22name%22:%22QR%20Code%20Generator%22,%22url%22:%22https://hxim.github.io/TwemojiPlugin/qrcode/qrcode.html%22,%22width%22:380,%22height%22:400,%22icon%22:%22https://hxim.github.io/TwemojiPlugin/qrcode/icon.png%22%7D%5D%7D%7D

**Comment by MichalSZZ** [comment]
#hxim you are my hero! :)

I tested it for a while
https://www.photopea.com/#ip2twubfT

works like a charm!

**Comment by photopea** [comment]
It really looks great! I added it into Photopea under Window - More - QR Code Maker :)

I really like, that you made it resizable, and that it remembers the last URL! Also, you copied the style of Photopea pretty closely :)  It would be nice, if the consecutive black squares were one rectangle (so that the SVG is smaller), but I guess that is what you get from the API.

@MichalSZZ There is a small disadvantage. Once you modify the SVG smart object, it becomes a PSD smart object, and it can not be free-transformed in a "vector way" anymore. Maybe we could somehow detect, if a document has no layer styles, adjustment layers, etc., and save the smart object back as the SVG (an identical file as you get with File - Export As - SVG).

**Comment by photopea** [comment]
@hxim Somehow, it takes 4 or more seconds, until the QR code in the preview is updated. And then, 4 more seconds when inserting into Photopea. Could you remember the last SVG in your plugin, and give it to Photopea as an ArrayBuffer?

**Comment by MichalSZZ** [comment]
@photopea separated "consecutive black squares" are good too, if you want to have "dotted" QR Code like this
content://com.android.chrome.FileProvider/images/screenshot/16246415172111059676904951378111.png

**Comment by hxim** [comment]
@photopea @MichalSZZ 
1. Yes, I also think those "separated black squares" are useful.
2. I updated the plugin so it loads svg only once via XMLHttpRequest instead of using img element with src attribute and to send it to photopea I encode svg content into dataURI. Inserting to photopea after preview is loaded should be super fast now. I could use ArrayBuffer but as far as I know with ArrayBuffer you can insert to photopea only as new document and not as smart object. and I believe inserting into existing documents as smart object is better way.

**Comment by photopea** [comment]
Yes, ArrayBuffer will open up as a new document. But you could run a script to duplicate layers into an old document and close the new one.

So I think it is fixed and I will close it now. But you can keep discussing, if you want, as I am not in charge of the plugin :)

**Comment by MichalSZZ** [comment]
The Q level has a wrong name...
![obraz](https://user-images.githubusercontent.com/38118273/123483893-c7cabd80-d607-11eb-8984-b320c07d3b46.png)
Shouldn't be "Quartile"?
