### ISSUE TITLE
i turned off adblock but it says i didnt

### ISSUE THREAD

**Issue by CatBowza** [photopea/photopea#3514]
Annoying pop up every few seconds saying to turn off my adblocker even though i have EVERY SINGLE ADBLOCKER ON MY COMPUTER OFF FOR THIS SITE. PLEASE FIX THIS.

**Comment by cyclops365** [comment]
Same. The fixes aren't working @photopea. Please sort it out!

**Comment by photopea** [comment]
I see that you think you disabled your adblockers. But why don't you mention the main thing - do you see the ads or not?

Maybe this can help you: https://www.photopea.com/tuts/ads-in-photopea-do-not-work-what-to-do/

**Comment by CryoPlenilune** [comment]
> Annoying pop up every few seconds saying to turn off my adblocker even though i have EVERY SINGLE ADBLOCKER ON MY COMPUTER OFF FOR THIS SITE. PLEASE FIX THIS.

Try clearing your cookies and cache!

**Comment by adamdived** [comment]
Browser Chrome here. Cleared the cache and cookies and everything. I'm using AdBlock with it. I entered "photopea.com" in a white list but somehow it still blocking it. I have to entirely disable the extension in order to see the advertisings. It's ok. It's fine, i can disable the extension. No problem, but it shouldn't work like that.

**Comment by photopea** [comment]
@adamdived It soulds like a bug in your AdBlock extension. It shouldn't work like that. Have you tried to find another adblock, which works better?

**Comment by photopea** [comment]
@adamdived Like really: if your AdBlock did not block any ads, or anything, how would Photopea be able to detect it?

**Comment by adamdived** [comment]
I wasn't complaining. I love Photopea and i want ads to be shown to support the development. All i said is that AdBlock extension, block ads even if Photopea is in the white list. I have to completely disable/uninstall the extension from the browser in order to make ads work, while usually i can pause it on certain web sites. I thought that putting photopea.com in the white list would have been enough to make it work. That's all i said.

**Comment by adamdived** [comment]
I installed uBlocker extension, paused on photopea.com and it works fine.
