### ISSUE TITLE
After I use Image/Canvas Size tool, Photopea glitches out

### ISSUE THREAD

**Issue by raivologo** [photopea/photopea#3517]
When I press ctrl (to do any shotcut) or delete, image/canvas size menu keeps appearing, the layer multiples when I click on it, clicking on the layer itself enables clipping mask... that and Photopea becomes a glitchy mess to work on.

What causes this error? How can I fix it?

**Comment by photopea** [comment]
I opened www.Photopea.com, I press Ctrl multiple times, but nothing happens. Should I open some document first?

**Comment by peterbonov** [comment]
I have the same issue too - it seems to crop up when I use the Alt+Ctrl+C shortcut to change the canvas size. After that basically any key press brings up the canvas dialog. It feels like a key is stuck, e.g. using the move tool creates copies of the layer instead of just moving it.

It clears up after exporting the image (maybe it's going through the native dialog or something?).

**Comment by photopea** [comment]
Oh, I see, it should be fixed now.
