### ISSUE TITLE
Browser + Window Executable Issue: Pop-Up

### ISSUE THREAD

**Issue by GMDBrandon** [photopea/photopea#3582]
Even though I have AdBlock paused, the ads won't pop up so the pop-up saying "oh let us use ads" will keep popping up. (i've used the words "pop up" three times in the same sentence) I can reload all I want, but it won't work. Even in the Windows Executable the pop-up comes. Could you fix this?

**Comment by photopea** [comment]
Hi, I think the bug is in your ad block. It is probably still blocking ads.

Do you have only one browser extension? Maybe some other extension is blocking ads in Photopea.

One thing I am fully certain about, is that if you disable all your browser extensions, you should not see any "pop ups". But it is hard to tell what of your extensions could be causing it (as any extension is allowed to do anything).

**Comment by js10222** [comment]
I've been having the same issue myself in Microsoft Edge. I don't have an ad blocker running yet I still get the periodic alert about displaying ads. Ads used to display fine. When I go to Firefox or Chrome, the alert stops and ads do show. In any case, Photopea is a great service.

**Comment by photopea** [comment]
I just tried Photopea in MS Edge  91.0.864.71 and I don't see any alert. Maybe you dont know which of your extensions blocks ads. Could you try to disable all extensions in Edge?

**Comment by photopea** [comment]
I think it was fixed, probably.
