### ISSUE TITLE
Feature request: CIE Luv color space

### ISSUE THREAD

**Issue by rocifier** [photopea/photopea#3649]
Currently Photopea uses an outdated model of RGB color space, which is simple mathematically but is quite inaccurate when compared to perceptual hue, value, and saturation of the human eye. As an artist using Photopea it would be ideal if the software could be configured to use the CIE Luv color space. This would mean that changing the saturation of any hue in the HSL dialog box would preserve its perceived value. Additionally, changing the hue slider would also preserve the perceived value which was defined.

A good example of a library which maps from Luv to HSL is HSLuv and a live demo of what I am referring to can be seen at https://www.hsluv.org/

Having worked professionally with optics and color space transformations in the past, I would be happy to answer any questions related to understanding or implementing this.

**Comment by photopea** [comment]
Every color in a real world can be expressed in different units (color spaces). Just like any mass of something can be expressed in different units (pounds, ounces, grams, tons).

So you would like to enter the color in our Color Picker in HSLuv space, instead of RGB or HSB? There exist hundreds of color spaces, and it is hard for us to choose, which are the most important (popular).

**Comment by photopea** [comment]
I was thinking about it, I think people can come up with a million ways to enter a color into a program. I don't see why this CIELuv is any better than the others. Also, you are the only person asking for it. I think it would only make Photopea larger and more complex, because of a feature, which almost nobody needs. So I would rather not add it.
