### ISSUE TITLE
Rounded rectangular tool is not available under shape section

### ISSUE THREAD

**Issue by shalomprasannan** [photopea/photopea#3697]

**Comment by MichalSZZ** [comment]
Yes. Because in Photopea all rectangles can have round corners. 
You can set corner redius on top  before you draw a rectangle or change corner radius in properties panel at any moment in the future.

Rounded rectangular shape in Photoshop is a very old feature when there wasn't 'live shapes' and ability to change corner radius after creating.

**Comment by photopea** [comment]
We have only a "Rounded Rectangle tool" in Photopea, but it is called a "Rectangle tool" and you can set any corner radius (it is zero by default).

**Comment by photopea** [comment]
But there are lots of people asking about this question. I think they are used to two different tools in Adobe Photoshop. So maybe we should add a second rectangl tool, where the default corner radius is not zero.
