### ISSUE TITLE
Noise when using selection tool over any colour 

### ISSUE THREAD

**Issue by ChildishGiant** [photopea/photopea#3704]
https://user-images.githubusercontent.com/13716824/131874094-33cf3846-70c5-40a5-ac8f-3f5c503eba90.mp4

**Comment by photopea** [comment]
Could you try these steps first? https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by ChildishGiant** [comment]
I've narrowed this down to Brave's "Fingerprint blocking", I've opened an issue on the relevant repo: https://github.com/brave/adblock-lists/issues/638

**Comment by photopea** [comment]
I believe Brave is doing it, because many years ago, there was a "research" paper stating, that rendered vector graphics can be used to fingerprint devices. Of course, that "research" is a complete garbage. All browsers should rasterize vector graphics identically. So if one renders it differently, than another, there is a bug in them.

You can keep using Brave, if you like pain. Or you can switch to a normal browser, like MS Edge, Firefox, Safari, Chrome or Opera.

**Comment by myfonj** [comment]
It is reportedly (from linked issue) also possible in Brave browser to disable tracking prevention and related fingerprint blocking for given origin, what should be supposedly viable workaround, if one insists on using that particular browser.
