### ISSUE TITLE
WEBP export error - saves as PNG (Firefox)

### ISSUE THREAD

**Issue by danielnydrle** [photopea/photopea#3756]
While trying to save an image as in a .webp format:

- I am unable to change the compression rate in the export window
- the client saves it as a .png instead

![image](https://user-images.githubusercontent.com/57211233/134332918-584d9df3-8bca-4417-afa0-0e3ce2cee394.png)
![image](https://user-images.githubusercontent.com/57211233/134332949-7a34f01b-6518-413e-bc29-dbd69ee80322.png)
![image](https://user-images.githubusercontent.com/57211233/134332970-3a2476e0-c6ed-45a2-9387-69edea402e44.png)

Works without a problem in MS Edge.

**Comment by photopea** [comment]
Hi, sadly, we do not have a WebP encoder, so we use the one that is built inside a browser: CanvasContext.toDataURL() - https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toDataURL

It was suggested to Firefox to improve the support for WebP, but they did not do it yet: https://bugzilla.mozilla.org/show_bug.cgi?id=1559743

**Comment by bernard-123lb** [comment]
On Chrome, the webp encoding appears to be in "lossy mode" all the time, we thus loose a lot of nice benefits of webp as a superior format for the web (on Chrome). Webp lossless mode is using similar techniques to PNG (ZIP) but tweaked for image domain like 2D lookups.

2011 chromium blog stating: On average, we get a 45% reduction in size when starting with PNGs found on the web, and a 28% reduction in size compared to PNGs that are re-compressed with pngcrush and pngout. https://blog.chromium.org/2011/11/lossless-and-transparency-encoding-in.html

Nice webp technical summary:
https://developers.google.com/speed/webp/docs/compression#lossless_webp

**Comment by bernard-123lb** [comment]
Here's a webassembly version of the encoder that can work in browser: https://github.com/saschazar21/webassembly/tree/main/packages/webp
Since it runs in a web worker, you can probably easily "delay" the loading of the bulk of the code until you need it to keep the Photopea fast. (lazy loading) 

It supports all the original library options from Google like "lossless" and "near_lossless" options which are quite powerful. I assume this is just a compilation in webassembly of the library.

@photopea If you do not intend to integrate this, I believe we can make a plugin. This became a popular & powerful format on the web, it might be worth it to include it.

**Comment by photopea** [comment]
It seems like Firefox already contains a WebP encoder, hooray!!!! :)

I think web browsers should provide lossless encoding, if you set the quality to 1. So if you set the Quality in Photopea to 100%, it is probably using the lossless encoding (I am not sure).
