### ISSUE TITLE
What is the cost of minifying PSD?

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#3785]
I would like to know what each option is doing. It's great to make files smaller, but what bad things can come of them?
![screenshot_20210928_010910](https://user-images.githubusercontent.com/79258245/134955284-125bce5d-d7ad-4b56-944c-c1b24370862c.jpg)

**Comment by photopea** [comment]
Hi, what bad things do you mean? There are no bad things. It only takes more time to produce a smaller PSD. So minifying a 100 MB PSD would take 40 seconds, many user just prefer a larger file, rather than waiting.

**Comment by nothingshiru** [comment]
The bad things I'm talking about are things like lost time(like you said), image quality, convenience, etc.

What differences does each option make?

**Comment by photopea** [comment]
Your 1 - 2 - 3  is correct! I thought it is obvious from the name of each option. Or, you will learn it yourself by trying them out.

If you put the entire file into a ZIP (option 3), the "ZIP for pixel data" is almost useless. 

- A PSD file with a 2 MPx layer is around 5 MB. 
- A JPG file with a 2 MPX image is around 150 kB.

If you insert a JPG smart object into a PSD, the PSD contains both a pixel layer (5 MB), and the JPG image (150 kB). The "Remove Smart Object pixels" will delete all pixels from Smart Object layers (5 MB), because they can be regenerated from the JPG inside. So the PSD is only 150 kB (+ a few extra kB for other things).

If you open such PSD in Photopea, Photopea automatically regenerates the pixels of a smart object layer, before displaying the file. However, Photoshop does not do that, so this option is not compatible with Photoshop (you would have to update the smart object manually in Photoshop, so that it is regenerated).

**Comment by nothingshiru** [comment]
It sounds like a "Blank preview image" for the PSD inside the PSD. 

Anyway, thank you very much for the explanation！
