### ISSUE TITLE
noise filter damages gifs

### ISSUE THREAD

**Issue by no0000000000** [photopea/photopea#3848]
as i said before but didn't yet have the proof.  if i am making gifs and try to add noise (which is a filter, since the last time the person responding didn't know what a noise filter is), the frames will damage.  once i removed the noise, the frames were fine.

https://user-images.githubusercontent.com/75169133/137645632-06fb38ea-8f3e-41f7-a69a-12b1c7afd646.mp4

**Comment by photopea** [comment]
Could you describe steps how to reproduce the problem? Your video contains just a part of a screen, it is not clear what you are doing.

**Comment by photopea** [comment]
your video does not show any image. it contains a small part of your screen.

Can you record the whole screen, or write steps: 1) open a GIF image. 2) click "Filter", 3) do something ...

**Comment by photopea** [comment]
I see that the GIF played well before adding a noise, and after adding a noise, it is still playing well. What exactly do you mean by "damaged"? How is it damaged?

Note, that the GIF format supports only 256 colors. Photopea selects the best palette of 256 colors for the animation. All colors in your animation are replaced by the most similar color in a palette. So the noise may "disappear".

You can export to PNG instead of GIF to preserve color information precisely.

**Comment by gse123** [comment]
I think he meant that Photopea creates a message on the screen literally saying 'some frames are damaged' (at 3:47)

no0000000000 - I noticed you only applied noise to one layer? Presumably that was just to show the error message. 
Also, try making the noise 'monochromatic'  as currently it is colour noise, which as mentioned above may be absorbed into the already limited palette of 256 colours....

**Comment by photopea** [comment]
It should work now. Photopea should export any image or animation, that you might ever have, as a GIF.

Keep in mind, that by adding noise to your frames, the size of a final GIF file might grow a lot.
