### ISSUE TITLE
the log in button won't turn to orange when i sign in

### ISSUE THREAD

**Issue by ilysfmjkihu** [photopea/photopea#3899]
does anyone know how to fix this?

**Comment by ilysfmjkihu** [comment]
ok it works but is there anyway you can fix that bc having to enable and disable my extensions is going to be a hassle...

**Comment by photopea** [comment]
Just find one extension which breaks Photopea and disable it, or ask the author of your extension to fix it. Do you need extensions? Do you know what they do? I use my browser without any extensions.

It is as if you had no monitor, and you asked me to fix Photopea, so that you can see what you are doing without a monitor. There are things you must have in order to use Photopea properly. A monitor, and a properly working web browser, are some of these things.
