### ISSUE TITLE
A.Zybin

### ISSUE THREAD

**Issue by Azybin** [photopea/photopea#3926]
Suddenly Message "Allow us to show you ads" appears, but your site included in Chrome settings as an security exclusion long time ago and I did not change anything! I checked settings - everything set up properly.
[Editor Settings.docx](https://github.com/photopea/photopea/files/7464256/Editor.Settings.docx)

**Comment by photopea** [comment]
You did not mention, if you see ads in Photopea or not?

Try this maybe: https://www.photopea.com/tuts/ads-in-photopea-do-not-work-what-to-do/

Let me know if you find out what was blocking ads in your case. Maybe it could help others, who can not disable their ad blocking mechanisms.

**Comment by Azybin** [comment]
I just see the advertising of your Editors, but I also has the same screen
before without your warning message:
[image: image.png]

**Comment by photopea** [comment]
Did you send an email to Github.com ? Github does not show your images to us :(

**Comment by Azybin** [comment]
No, I sent it to this Address
[image: image.png]

**Comment by photopea** [comment]
Sorry, but I do not see any images that you are sending. If you want to communicate with Photopea, send emails to support@photopea.com . If you are replying to emails from Github, they are sent to Github, and Github inserts them into this discussion only partially.

Please, reply directly with the web interface: https://github.com/photopea/photopea/issues/3926  instead of sending emails to some random address of Github.

**Comment by photopea** [comment]
I have to close it because the person stopped responding :(
