### ISSUE TITLE
after exporting as PDF image size changed 

### ISSUE THREAD

**Issue by prodigalsunn** [photopea/photopea#3983]
Hi,
I'm trying to export my projects as pdf but whenever I do the pdf image is much smaller.
for example a 383x383 image. when I export the project as pdf the output file will have a size of 127x127. although I checked the resolution before exporting + rasterized.

I tried it with all my prjoects, every time the pdf will turn out much smaller. (exporting PNG works fine though)

any solution how to fix this for me?

thanks a lot in advance.
kind regards

**Comment by photopea** [comment]
The PDF format uses "inches" as units. E.g. you have a PDF page of 7x7 inches, with a red circle in the middle, with the diameter of 5 inches. There are no pixels in PDF files. You can "rasterize" the PDF content at any resolution you want.

What do you mean that your "pdf is 383x383"? What units are these? Where do you see these numbers?

**Comment by prodigalsunn** [comment]
thanks for getting back still today. for the example I meant I have a PSD project in photopea that is 383x383 px.
when I click "export as PDF" a window pops up. there I select the resolution for the PDF file.

https://ibb.co/4V5zjgj

but when I check the image after exporting it to PDF, then it is much smaller. (127x127 px)
it became to small and does not fit the resolution anymore that I need for print.

is the photopea "export as pdf" option equal to the photoshop option "save as - pdf" ?

**Comment by photopea** [comment]
Photopea renders each PDF at 144 pixels per inch. So a 2 inch x 2 inch PDF will become a 288x288 pixel PSD, if you open it in Photopea.

"when I check the image after exporting it to PDF, then it is much smaller." - how do you check it? As I said, there are no pixels in a PDF, there are only inches.

**Comment by prodigalsunn** [comment]
in the past I used to design images for flyers and stickers with gimp and photoshop. when I saved the design as pdf and opened it in chrome, I was able to see the sticker in its original size.
that is not the case when I export my design that I made with photopea. when I open the pdf in chrome its way too small. the printing company wont accept that size for the sticker that I used to print.

I'm not really sure if its really 127x127 px. I just made a screenshot and pasted it in photopea to check the size of it.
but it is definitely too small because after exporting it as pdf it is somehow shrinked down in resolution.

I can actually see that when I compare it with the previous pdf designs that I successfully used to print the same sticker.

**Comment by photopea** [comment]
In a PDF viewer, you can set any zoom you want. 

In Photopea, press Image - Image Size, switch to Inches, and set any size you want.

**Comment by prodigalsunn** [comment]
ofcourse I compared the pdf files on 100% zoom.

my PSD project in photopea has the perfect size for the sticker.. in px or inches. 383x383 px or 1.28x1.28 inches.
changing the measuring unit wont help me for my problem. because also in inches my PSD file has the fitting size but when I export it as pdf it is definitely shrinked down. 
it actually completely lost its dimensions that were actually set in the psd. it is for sure not because of different zoom. I surely checked that. something is different here when exporting it.

if you have any further idea would be much appreciated.

**Comment by photopea** [comment]
I still can not see a any problem. All you say is that a PDF is "smaller than it should be", but you have not proven it in any way :( What makes you think your PDF is not 1.28x1.28 inches?

**Comment by photopea** [comment]
I will close it, as I think you are not using Photopea in the right way. This forum is not for a place for asking others how to use Photopea. You can ask for help here: https://www.reddit.com/r/photopea . You can also buy a book about Adobe Photoshop, since Photopea works in a similar way.

**Comment by prodigalsunn** [comment]
I know the issue. the problem is about photopea because it does not offer
"save as - pdf" option. it is only possible to export. since you were not
interested to take care of the issue I did some some web recherches and now
I can also tell you the reason why it cannot work...
Quote:

"I was using the* Export *function in Photoshop to export PNG images sized
at 150dpi via the Image Size dialog. After exporting and closing the files,
when I re-opened them into Photoshop, they opened at 72dpi with the pixel
dimensions about doubled.

After much web searching, I found that the Export function in Photoshop
always defaults to 72dpi and will scale your pixel dimensions up or down
depending whether 72 is higher or lower resolution than your working dpi.
Instead, it is necessary to use the *Save As* function in Photoshop and
choose PNG as the format. This preserves the dpi of your working file in
the saved file, and re-opening a file saved this way will open at whatever
dpi was set in the Image dialog when you saved (150dpi in my example)."

https://feedback-readonly.photoshop.com/conversations/photoshop/photoshop-images-not-saving-at-right-size-and-resolution/5f5f458d4b561a3d425355ad?page=2

like I said I designed before for the same sticker size 383x383 with
photoshop and I also converted it to pdf. but for best quality in photoshop
that is actually done via "save as - pdf" and not "export as"... It's a
mircale that you are not aware of this issue.
photopea definitely needs a better "save as" option.. otherwise it's
useless for some areas... just saying. do what you want with it.. but
reddit wont be able to help when photopea has options missing ;)

all the best

Am So., 14. Nov. 2021 um 19:47 Uhr schrieb Photopea <
***@***.***>:

**Comment by prodigalsunn** [comment]
moreover wondering if you have ever tried to export a 300 dpi project as
pdf with photopea ;)
it simply does not work. the support in the thread I posted is also trying
to put it on the users although it is actually obvious...

for photoshop it is easy to solve but I dont see any option for photopea.
but since you are not even aware of the issue I guess I will just have to
see it as a lil waste of time and move on...

anyways thanks.

Am So., 14. Nov. 2021 um 22:45 Uhr schrieb JM X ***@***.***>:

**Comment by popbee** [comment]
* sigh * 
This is clearly a typical confusion of not talking about the same thing. Once he understands, I can tell you that Ivan puts in every single bit of effort to fix and help with your problem and often very fast. This is proven many times.  Bear with him because Ivan gets a very high volume of often very basic/weird questions because the applications and the type of people using Photoshop/photopea is extremely diverse. Noobs questions takes a lot of time and does not help making a better software. He tries to answers to all of them, really. I do not know where he finds the time frankly. He's like a machine, hat's off.

@prodigalsunn The problem here is that you didn't find a way to convey concretely what you are doing.  Give him files to look at and try for himself, give him screenshots and steps of what you are seeing and clicking, give him tangible data to look at! 

I know a fair bit myself and I can say the words you are using don't always make sense technically (even if it's very clear to you). I mean stuff like:

`I'm not really sure if its really 127x127 px. I just made a screenshot and pasted it in photopea to check the size of it.`  and `of course I compared the pdf files on 100% zoom`  -- That's a clear sign that something is not understood correctly. You can't compare documents on the screen like this(?)

`383x383 px or 1.28x1.28 inches` -- That implies a 300 DPI (you didn't mention this!?) because here I have a 1200x1200 pixels image that I am printing at a tiny 1inches x 1inches (high density 1200DPI)  through a PDF export and it prints exactly the expected size.  

`because it does not offer "save as - pdf" option.` -- Save As vs. Export As means absolutely nothing technically: It is just a Photoshop "quirk" that it resamples images to 72 DPI by default when selecting Export As. To workaround a LIMITATION of photoshop, is to use the Save As where you have more control over the resampling of raster images inside a PDF. I didn't check but I suspect Photopea does not even do any resampling when exporting a PDF, so you no information is lost in any cases.  Note that if Ivan puts a Save As PDF option, it will behave exactly the same as the Export As PDF.

PDF (which is very similar to EPS) uses physical dimensions like inches (because it's meant for printing purposes!). It does contain raster images as well that often gets resampled (i.e. resolution change, not how big the image is printed on the page) because it can be very heavy in terms of megabytes. BTW using a PDF document "to preserve quality" is absolutely not the best way to go unless you are trying to print it yourself and control the final physical size of the print (physical inches, nothing to do with image resolution or pixels). Why not use the PNG format (exactly like in the photoshop thread) instead, you have much better control of the size of your image. PDF is the worst option to move images from one software to another, I have no idea why one would use this in the first place.

----

Ivan coded the whole thing himself so he knows what he is talking about. I mean, really to the last bit of absolutely everything. He does not know what is your pipeline and how you work with the tools and short of concretely explaining that to him, there is nothing he can do.  Help him help you!
