### ISSUE TITLE
Mac: Zoom keyboard shortcut bug

### ISSUE THREAD

**Issue by titoesteves** [photopea/photopea#4008]
Issue: On Mac, if you zoom out on an image via `cmd` + `-` keys and then try to zoom in via `cmd` + `+`, the zoom function continues to zoom out instead of zoom in. 

Steps to reproduce:
- add an image to photopea
- zoom out via `cmd` + `-` keys
- zoom in via `cmd` + `+` keys
- notice how it keeps zooming out instead of zooming in. 

Machine: MacOS Catalina 10.15.7
Browser: Chrome and Safari browsers

**Comment by photopea** [comment]
It is a well-known bug in Mac OS. When you hold a Command key, and release some key, the release is not reported to the program. So if you still hold Command and release the Minus, Mac OS does not tell us that you released the Minus.

https://stackoverflow.com/questions/27380018/when-cmd-key-is-kept-pressed-keyup-is-not-triggered-for-any-other-key

As you probably can not make Apple fix it, you would have to release the Command key before zooming in. Or use the Ctrl instead of the Commadn key.

**Comment by titoesteves** [comment]
That is an interesting bug indeed. I can confirm that using the `ctrl` key instead works fine. It is a good workaround. Thanks for the quick reply. Great product btw!
