### ISSUE TITLE
Feature Request: "Rulers" plugin

### ISSUE THREAD

**Issue by xan2622** [photopea/photopea#4020]
It would be cool to have a Photopea plugin that features "rulers" as shown in this video: https://youtu.be/TTn2USQJSt0
More info: [https://lazynezumi.com/rulers](https://www.anonymz.com/?https://lazynezumi.com/rulers)

When one of these rulers is activated, guides appear over the canvas, helping the artist draw straight lines, or bezier curved lines, ellipses, circles, parallel lines, work on perspective views, etc.

**Comment by photopea** [comment]
I do agree, that Lazy Nezumi Pro is a great program. But why don't you simply use Lazy Nezumi Pro, instead of asking us to turn Photopea into Lazy Nezumi Pro?

I am afraid that if we add all features of all existing editors into Photopea, it would become a huge mess. Adding a feature is just one thing. But integrating it into the rest of tools is much harder. Also, with too many features, it becomes harder to find a feature you need, and I am afraid nobody will ever find out, that Photopea has such plugin. So I give it up.

**Comment by xan2622** [comment]
> I am afraid that if we add all features of all existing editors into Photopea, it would become a huge mess.

I would answer the same as I did here: https://github.com/photopea/photopea/issues/4021#issuecomment-974858114

> I do agree, that Lazy Nezumi Pro is a great program. But why don't you simply use Lazy Nezumi Pro, instead of asking us to turn Photopea into Lazy Nezumi Pro?

To let **all** Photopea users also benefit from these great features (and for free). 

And because I think the requests that I posted make sense, I haven't suggested them just for the sake of adding features into your software, nor to annoy you. 😥  I wish all the best for Photopea, it's a great project that helps artists use great photo editing tools and [even earn money thanks to it](https://www.reddit.com/r/photopea/comments/qxuxyl/hi/). So **thank you**.
