### ISSUE TITLE
Feature request: add the ability to choose in the "Displace" effect: a displacement map in the PC

### ISSUE THREAD

**Issue by ThatMario** [photopea/photopea#4055]
Hi there, it is me again. I was following a tutorial to "**_How to Create Water Reflections With Realistic Ripples in Photoshop_**" on YouTube, and I found something lacking in Photopea to end the tuto. 

It lacks the ability to **choose a displacement map in the PC**, with the PSD format, etc. Like in this video:

https://youtu.be/0MvjWH8opK0?t=326

Is it possible to add it in Photopea? Cause it's literally impossible to create realistic water reflection without that.

**Comment by photopea** [comment]
Sorry, but a website can not scan through your hard drive and read everything what you have in your computer.

If a displacement map was linked to a file in your computer, and you opened such PSD in Photopea, Photopea would not be able to get to the file (find it on your hard drive), because websites do not see your hard drive.

You should insert your displacement map as a smart object and select that smart object for your displacement map.
