### ISSUE TITLE
Wikipedia Images plugin

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#4075]
I created plugin to search for main images in english wikipedia pages:
![obrazek](https://user-images.githubusercontent.com/6370548/144748220-c7a267e5-4006-459d-8ae5-776b7165b01e.png)
You can try it here:
https://www.photopea.com/#%7B%22environment%22:%7B%22plugins%22:%5B%7B%22name%22:%22Wikipedia%20Images%22,%22url%22:%22https://hxim.github.io/TwemojiPlugin/enwiki/enwiki.html%22,%22width%22:300,%22height%22:400,%22icon%22:%22https://hxim.github.io/TwemojiPlugin/enwiki/icon.ico%22%7D%5D%7D%7D

**Comment by photopea** [comment]
Is this really useful? There are much more images in the Window - More - Gallery, for any phrase.

Also, are thes eimages under the Wikimedia Commons license? That license is quite restrictive, Wikipedia could blame us for not explaining to our users how to handle their images the right way.

**Comment by hxim** [comment]
Often you can't find particular image in Window - More - Gallery. Try searching for example for "Carlsen" "obs studio" or "pyraminx".
There is not one "Wikimedia Commons license" Each image there can have different licences. For free images usually it is Creative Commons Attribution-Share Alike licenses I guess. You can open this image information with right click and Image information. I can add text informing that people should check license terms there before using image. Maybe with short paragraph in the top or bottom of plugin window what do you think?

**Comment by yikuansun** [comment]
> There are much more images in the Window - More - Gallery

I like the idea of having multiple sources of stock image galleries, for diversity, as well as because different collections have different purposes.

**Comment by photopea** [comment]
I see that many of these images are under GNU GPL v2. That is a really restrictive license. You can use the image for free, but you must provide your work also  for free (under GNU GPL v2), meaning that you can not sell your work for money. I think most of users do not expect that.

If people really want to break law, they can copy-paste images from other websites manually. I do not want Photopea to be encouraging people to break law. Because everything we added into Photopea so far is free to use for commercial purposes.
