### ISSUE TITLE
Scrollwheel Zoom ≠ Keyboard (Ctrl+Plus) Zoom [Feature Request] 

### ISSUE THREAD

**Issue by tobealive** [photopea/photopea#4120]
Wondering myself how much of my photoshop work I was being able to switch to photopea. Still using PS sometimes in a VM, but it's hardly necessary anymore. Great work guys, I love what you created! It's big time undervalued. 

Now I'm having a small feature request. I'm used to using Alt+Scrollwheel Zoom to get quickly in and out an exact detailed view on different levels. In photopea the zoom steps are equal to using Ctrl+Plus. Which are rather large sometimes. Would it be possible to decouple the mouse wheel zoom from normal zoom for more delicate zoom steps? A workaround I found for detailed zooming without steps is: while holding Space to Press control than holding down a click and moving in and out to zoom. But that sometimes is erroneous and not as convenient as a scroll wheel zoom. Would that technically be even possible?

**Comment by photopea** [comment]
Hi, you are welcome!

The problem is, that non-standard zoom levels, e.g. all zoom levels between 100 and 200%, make the photo look ugly (in Photoshop and Photopea), so we want our users to avoid them. But as you know, you can hold Ctrl and Space (to temporarily switch to the Zoom tool), and then, click and drag left - right. You can also try the Navigator window (Window - Navigator).

**Comment by tobealive** [comment]
Hey, nice to read from you. Thanks for the response! Yeah getting used to the "temporary-zoom-tool-mode" will be the way for this. The navigator is being used. But to use it for the functionality of zooming feels a bit killing workflow-wise.
