### ISSUE TITLE
After I click on rectangle draw tool, I can't select any other tool

### ISSUE THREAD

**Issue by kiran-vemuri** [photopea/photopea#416]
Env: Firefox Quantum on macOS High Sierra

After I click on the rectangle tool and draw a rectangle, no matter what I do, I can't click on any other tool. It keeps on adding new shapes and layers.

**Comment by photopea** [comment]
I am trying it with the latest FF on Windows and it works fine. Can you see any errors in the JS console?

**Comment by kiran-vemuri** [comment]
Screencast available here: https://ufile.io/06t8m and Nope. I don't see any errors in console.

**Comment by photopea** [comment]
Thanks for the video!  The problem is with the custom mouse cursor on a "retina" display, which is placed 100px left from an actual cursor. So you think you are clicking the tool icons, but the real cursor is still above the canvas :(

These custom cursors on retina displays work differently in each browser now :( I guess I will have to disable them and keep the regular cursor. Can you try some other browsers, please?

**Comment by photopea** [comment]
I fixed it "a little". Otherwise, Firefox has to fix it: https://bugzilla.mozilla.org/show_bug.cgi?id=1425694
