### ISSUE TITLE
RAM required

### ISSUE THREAD

**Issue by sash000000** [photopea/photopea#4163]
Keep asking for more RAM and then crashes.

**Comment by photopea** [comment]
How much RAM do you have, and how large is the file that you are opening?

**Comment by Dida83** [comment]
I have the same problem
Today Photopea doesn't work and crashes every time :-(

Win 10 Home - Version: 21H1 - Build 19043.1415 - Windows Feature Experience Pack 120.2212.3920.0
RAM: 16GB
Video: Nvidie GeForce MX250 + Intel (H) UHD Graphics 620
CPU: Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz   1.99 GHz

**Comment by photopea** [comment]
Did you try this? https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

Does it also happen in a browser with no browser extensions? You did not mention your browser or your extensions at all.

**Comment by Dida83** [comment]
I'm sorry...I thought it might be a RAM problem

I'm using Chrome 96.0.4664.110 (Build official) (64 bit) and haven't changed extension since photopea worked
But photopea it no longer works with these .PSD files (133MB, 12.4MB, 36MB)

Chrome Extension:
 FireShot
 ColorZilla 2.0
Google offline  Document
 Facebook Pixel Helper 2.2.0
 Google Avvisi email 4.4.0
 McAfee® WebAdvisor 8.1.0.1834
 Not Just Analytics 0.0.1
 Page Ruler Redux 1.2.0
 Wappalyzer 6.9.8
....and Chrome official application (Document, sheet, keep and presentation)

thanks for everything

**Comment by photopea** [comment]
So Photopea crashes when you open a 12.4 MB PSD file in it?

Try it in a browser with no extensions (e.g. in the Incognito mode). Otherwise, it could be caused by your extensions.

**Comment by Dida83** [comment]
I've try in Incognito mode and there is the same problem
these files had been used without problems long ago

**Comment by photopea** [comment]
Can you send me the smallest PSD file, which can not be opened by Photopea, to support@photopea.com ?

**Comment by Dida83** [comment]
Yes of course!
Thanks!

**Comment by photopea** [comment]
Your text layer is 4000x3000 pixels (12 million pixels), and it can take up to one second to render a Stroke effect on that layer. You need up to 200 MB of RAM for this layer and the effects.

You have the same layer 23 times, so it needs up to 4.6 GB of RAM, and 23 seconds to render the effects.

I think you dont have enough RAM to work with it. Could you use e.g. only 10 layers instead of 23? Or a smaller resolution, e.g. 10 million pixels? Also, the Outer stroke takes 2x less time and memory than the Center stroke, which you are using.

**Comment by Dida83** [comment]
Thanx!
I didn't make the PSD files but they are freebies downloaded online, which is why they are very heavy.
To be able to modify them and make them lighter I will try to remove some levels waiting for the time you indicated :-)
