### ISSUE TITLE
Feature Request: Photoshop-compatible Plugins Support

### ISSUE THREAD

**Issue by alx359** [photopea/photopea#4228]
One of the most powerful and useful things of Photoshop and compatible desktop apps is in their ability to get extended through plugins (*.8bf). Would it be at all possible for Photopea to achieve that and interact with 8bf plugins already in the local computer? Is this something doable at all for a browser-based-app and in the roadmap? Thanks.

**Comment by photopea** [comment]
If you have a .8bf plugin for Photoshop on Windows, that plugin will not work with Photoshop on Mac, and vice versa.

.8bf plugins are actually small programs for Windows, Mac, etc, which were built for the specific operating system. We would probably have to create a virtual machine for emulating Windows, in order to run the .8bf plugin.

Are there any specific plugins that you like? Maybe we could make our own analogy to them.

**Comment by alx359** [comment]
Not sure I understand why cross-compatibility is a concern? If one loads Photopea from a Windows PC, one would expect to access only locally installed plugins (e.g. via an app cookie to the local path). Same with Mac or whatever else. That local specificity would make such feature simple enough to be feasible; AFAIK the Ps plugin architecture is just a way to share image files between a host application and 3rd-parties.

There are tons of immensely powerful plugins I can't imagine you could possibly have the resources to re-write yourself (e.g. Topaz Labs, Alien Skin, AKVIS, Nik Collection, Focus magic, etc., to name a few).

**Comment by popbee** [comment]
Photopea is a website running on javascript. It's not a regular software running on a machine.  Even if you "install it", it's essentially a browser in a app-like window. The installation is 100% controlled by your browser (Google Chrome, safari, etc.) Access to actual machine code on the machine is completely blocked because it would be a huge security hazard.  That's why all the file accesses is a bit weird in Photopea compared to normal "installed software".  Ivan did an awesome job to make it "look like" a regular app, but really, it's not. 

Maybe it's possible to create a real piece software that you separately install and somehow interfaces with a running Photopea instance and implements the plugin side to interface Ps plugins. Sounds like a big undertaking to me, but hey, Ivan always surprises us, so who knows.

**Comment by photopea** [comment]
I am afraid we can not make this happen.

The .8BF "plugins" is basically a binary program for a specific operating system. It would be technically very hard to run them inside a website. It is as if you give Photopea the ".EXE" of your favourite videogame, and you want Photopea to let you play that game (because you are on Android, which can not run your game).

So, 8BF is not a "versatile plugin format". Even Adobe Photoshop can not run a plugin for Adobe Photoshop (when you are on a Mac, but your .8BF plugin was made for Windows).
