### ISSUE TITLE
Rotate Arbitrary

### ISSUE THREAD

**Issue by Tunycakes** [photopea/photopea#4241]
Missing feature where rotation is calculated based on the ruler so you can straighten out your reference line. I use this a lot with photo retouching old photos that are scanned in.

**Comment by popbee** [comment]
Not sure what you mean, you want grid lines to appear when rotating a Layer arbitrary?  Just put some guide lines out of the ruler on the horizon and rotate your photo to "make it straight".  no?

![image](https://user-images.githubusercontent.com/1083830/149684650-b1205982-f1b5-48e5-9f31-b8ed27138457.png)

**Comment by Tunycakes** [comment]
I mean that in photoshop, if I use the ruler tool on something crooked,
then use Image>Image Rotation>Rotate Arbitrary under the rotation menu, it
will calculate the amount of rotation needed to 0 it, so I don't have to do
it manually or by eye. Under the menu you have rotation 90 degrees and 180
degrees only. I guess I can do it that way but I have done it this way many
years! I really want to stop paying for adobe haha. Very much appreciate
you making this app and I look forward to your updates!

**Comment by MichalSZZ** [comment]
In Photopea you can do it like in Photoshop with ruler tool.
![obraz](https://user-images.githubusercontent.com/38118273/149685317-774d042d-13ae-4558-b60d-a1b73c6eb52c.png)

**Comment by Tunycakes** [comment]
Ah, just notice straighten layer button. Sorry thanks!

**Comment by photopea** [comment]
I see, that you want the content to be rotated X degrees. But what should happen to the canvas size? 

"Rotate Arbitrary" in Photoshop enlarges the canvas to fit the rotated content (I think there is no way to do it in Photopea now).

"Straighten Layer" in the Crop tool shrinks the cropping window so that there are no empty spots.

"Straighten Layer" in the Ruler tool does not change the canvas size.
