### ISSUE TITLE
Drawing on chromium based browsers seems wacky and stuttery

### ISSUE THREAD

**Issue by Beventar** [photopea/photopea#4280]
while on firefox is buttery smooth why is that?

its really infuraiting

https://user-images.githubusercontent.com/51784467/151558230-4cf23517-56de-4628-9d2d-1f85f5e37993.mp4

**Comment by photopea** [comment]
In my case, Photopea is equally smooth in Firefox and Chrome. 

I did not try Brave, I think Brave is basically a virus for your computer. Do you have extensions in Brave? Maybe Brave is mining bitcoins or something in the background, so there are not enough CPU power for Photopea.

**Comment by photopea** [comment]
I just tried it in Brave and it works equally smooth as in Firefox. So maybe it is because of your browser extensions in Brave.

**Comment by Beventar** [comment]
I just tried it with no extensions in Brave and it's the same as with extensions

**Comment by Beventar** [comment]
I think it's a problem with chromium browsers because i checked the task manager and when i draw or something brave is taking like 65% cpu and firefox only 25%

and brave is only taking that much cpu when i draw it drops down when i stop drawing

**Comment by photopea** [comment]
I have noticed, that in Chrome, mouse movement is detected 150 times per second, while in Firefox, it is detected only 60 times per second. So Chrome performs 3x more drawing operations per second.

Is Chrome really "wacky"? In your video, both cases seem to be equally smooth to me.

**Comment by Beventar** [comment]
it feels wacky while firefox feels smooth

**Comment by Beventar** [comment]
Ok I saw a webgl option in the more menu

in Brave: disabling webgl made drawing and everything smooth

in Firefox: disabling webgl made it wacky like in Brave

**Comment by photopea** [comment]
Photopea should always be faster and smoother with WebGL ON. Are you sure Photopea in Brave is slower with WebGL ON?

How old is your computer? Do you know what GPU you are using? What operating system do you have?

**Comment by Beventar** [comment]
Last time i upgraded my computer was in 2021. My GPU is 1050 TI and I use windows 10

Yes when i turned webgl off in brave it was smooth however when i turned it off in firefox it was wacky

**Comment by photopea** [comment]
If Brave became smooth after disabling WebGL, it is definitely a bug in Brave. Could you try it in Chrome or Edge?

BTW. in my Brave, drawing becomes very slow after disabling WebGL.

**Comment by Beventar** [comment]
In Edge drawing also became smoother after disabling webgl just like in brave

**Comment by photopea** [comment]
Can you open about://gpu in your browser? Is everything hadrware-accelerated?

**Comment by Beventar** [comment]
I have disabled hardware acceleration in both Brave and Edge

**Comment by photopea** [comment]
But why? Why didnt you disable it in Firefox?

**Comment by Beventar** [comment]
it takes gpu power which it doesnt really need as sites are still loading fast

there is no option in firefox's settings to disable it

**Comment by photopea** [comment]
Hey, do whatever you want, but Photopea needs the GPU to run fast.

When you have a layer 2000x2000 pixels, each pixel is four Bytes, such layer is 16 MB. If you have 50 such layers, and you want to refresh the image at 60 FPS, you need to process 48 GB of data per second. There is no way to do it on CPUs. Current RAMs can read at 15 GB per second, that is why it needs to be on the GPU memory.

You were using a WebGL emulator in Brave and Edge (it emulates OpenGL on the CPU), and disabling WebGL made it faster (as it was computed directly on the CPU, instead of emulating OpenGL on the CPU). Working with one 2-megapixel layer is fast even on the CPU.

But if you want Photopea to be really fast, even with large documents and many layers, it needs the GPU. There is no way around, it will be slow on the CPU.
