### ISSUE TITLE
Layers commands errors

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#430]
You can change current layer when right click pop-up menu is open in Layers window (or main menu)
You press mouse button down on pop-up then move your cursor to another layer and then release mouse button

For example you can then call "Convert to Shape" command on any layer producing this error
->
Uncaught TypeError: Cannot read property 'lW' of undefined
    at Gh.rU.aP (pp.js:2944)
    at G$.aP (pp.js:5909)
    at G$.kb.P (pp.js:6)
    at G$.$.P (pp.js:4148)
    at GJ.$.P (pp.js:4148)
    at GB.$.P (pp.js:4148)
    at Gm.$.P (pp.js:4148)
    at VO.$.P (pp.js:4148)
    at Ng.$.P (pp.js:4148)
    at VO.SX (pp.js:5312)

**Comment by photopea** [comment]
The problem was, that all UI elements in a Layers panel require "mouseup" to be activated (while only "mousedown" outside context panel can hide it). I don't know why "mouseup" is used instead of "click" (I wrote this part like 4 years ago).

I replaced "mouseup" with "click" events (so mouseup on a layer will not select it). Hope it will not damage any other behavior.
