### ISSUE TITLE
Suggestion: Improved Logo for iOS PWA App

### ISSUE THREAD

**Issue by buzz-lightsnack-2007** [photopea/photopea#4321]
First and foremost, I truly enjoy the web-based professional photo-editing concept of Photopea; thank you and keep up the good work! 

Anyway, I noticed that when I installed Photopea in iOS, there is a black border in the app icon that is not in the actual logo. 
![Screenshot 2022-02-14 at 14 56 38](https://user-images.githubusercontent.com/73412182/153816395-3ab08803-0e06-4624-8e7b-4dcaeb6153c8.png)
This is most likely due to parts of the icon having transparency which iOS app icons don't support. 

I've heard that it is possible to use set a different logo for an iOS PWA; thus, I hope that an opaque or shadow-less version of the icon would be detected and used only on this operating system. 

I hope this would be considered. Thank you!

**Comment by photopea** [comment]
that is interesting. Could youupate your iOS? Maybe Apple fixed it in the new iOS.

**Comment by buzz-lightsnack-2007** [comment]
I'm in the latest version of iOS and yet it is still a problem. A similar issues goes with other PWAs that have transparency in them.

**Comment by photopea** [comment]
I am afraid there will always be some black pixels, as we need to use anti-aliasing for a smooth icon. Otherwise, the edge of the icon will not be smooth.

I think Apple should fix it. You should ask Apple, not us. I think everyone must see that black border, as it will make users angry and will make Apple fix it sooner.
