### ISSUE TITLE
PDF Export - Takes too long

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#4325]
Hi, i know some of my files are huge, but some others don't seems so.

So i was wondering why it takes so long to export as PDF, for this file:
[La Pura y Santa Verdá - Box.zip](https://github.com/photopea/photopea/files/8074104/La.Pura.y.Santa.Verda.-.Box.zip)

Or maybe i can do something to make it lighter?

**Comment by photopea** [comment]
It is because of the QR codes. Your QR code is a vector layer with 765 parts. Some parts have a different mode than Unite.

PDF and SVG do not have any boolean modes, so we need to perform merging. Our merging methods are quite slow, especially when you have 765 parts. It needs to check the intersection between each two parts, so it takes 30 seconds per QR code.

I will think about how to improve it.

**Comment by avagp** [comment]
Oh.

That will be good.

Because I use plenty of qr codes in my designs

**Comment by photopea** [comment]
I have disabled path merging, when there are more than 200 parts. Your QR codes will look incorrectly now.

How do you make your QR codes? There is one path, that is redundant. If you delete that path, the exported shape should look correctly
![image (1)](https://user-images.githubusercontent.com/15955558/154864103-3623e4dd-67fd-4446-97f8-7c5fa3af42a1.png)
.

**Comment by avagp** [comment]
Thanks!

now is a millions times faster.

Did not noticed the QR had redundant paths i removed them.

:D
