### ISSUE TITLE
PDF Import doesn't work properly

### ISSUE THREAD

**Issue by stingray4540** [photopea/photopea#4353]
When I open and place a PDF, none of the font loads. If I open the PDF itself, the fonts load, but aren't correct. They are the wrong size, in the wrong location, solid lines show up as dotted lines, so do text strokes, and even one of the images is missing.

**Comment by photopea** [comment]
I just tried to do it with my PDF and it works well. Could you share your PDF with us?

**Comment by stingray4540** [comment]
Here it is

[Blue Lake Map 2022 No Bleed.pdf](https://github.com/photopea/photopea/files/8112728/Blue.Lake.Map.2022.No.Bleed.pdf)

**Comment by photopea** [comment]
BTW. your PDF file contains an AI file inside. Photopea extracts that AI file and uses it, while ignoring the PDF itself.

I have fixed the problem with invisible text afer placing your document into another document.

Your file uses the Myriad Pro font, which is a commercial font and we dont have a licence to offer it to our users for free. Photopea can not use fonts from your computer. Please, load these fonts into Photopea with File - Open, so that Photopea can use them.

Otherwise, Photopea would use a substitute font (PT Sans in your case).
