### ISSUE TITLE
Increase Ram

### ISSUE THREAD

**Issue by suburbansteve** [photopea/photopea#4413]
Hi I'm not very techy and I want to know if or how to increase the amount of ram allocated to Photopea as I often get a 'not enough ram' notice, I'm running windows 10 on a older laptop and have no other programs that are ram heavy, any advice (except get a new laptop 😊) would be appreciated.
Thanx.

**Comment by photopea** [comment]
Try to close some programs or browser tabs, to free up RAM. 

You can buy an extra RAM module to increase your RAM, a used one costs like 30 USD.

**Comment by suburbansteve** [comment]
I had some extra ram installed a while ago, I'll try shutting down any tabs I have open but was wondering if I could give extra ram to Photopea using the taskmaster and who would I give it to, chrome or Photopea which I think run in chrome?
Thanx

**Comment by photopea** [comment]
Your browser should give Photopea as much RAM as possible, as long as there still is any free RAM.

Try to update your web browser, in case you use an old one.

**Comment by suburbansteve** [comment]
Ok Ill close everything I'm using except Photopea and see if that helps..
Thanx for the quick response.

**Comment by kuzyn1** [comment]
Hello.
I've noticed that Photopea still got that issue with not enough ram.
I've even used that option to install it but the issue is the same.
In my case it says that there is not enough RAM (2048 MB), while I'm using below 50% of my total RAM (which is 32 GB).

I can't find any option to allocate more RAM to Photopea. Even if its installed, does it still use the main web browser? Is that a problem that my browser won't let it use more than 2GB?

**Comment by photopea** [comment]
Photopea can only run in a web browser, even when "installed".

"Is that a problem that my browser won't let it use more than 2GB?" - what do you mean by that? Do you restrict the RAM usage for Photopea on purpose?

**Comment by kuzyn1** [comment]
> Photopea can only run in a web browser, even when "installed".
> 
> "Is that a problem that my browser won't let it use more than 2GB?" - what do you mean by that? Do you restrict the RAM usage for Photopea on purpose?

Hey, no, I dont restrict any RAM usage. Its just says that there is not enough memory and in brackets there is 2048. When I turn on Memory window it shows that usage is about 1.9GB and from time to time that error occurs so I guess it hits that 2GB treshold.

This problem of course is really specific because Im trying to edit about 60mbs jpg file. Moreover, Photopea is not able to save PSD of such big file. Notification with "Saving" appears and do not close in a web version. In installed version notification turns off but PSD file has 0B size.

As my main browser I use newest Vivaldi on Windows 11. I couldnt find any setting related to memory.

**Comment by photopea** [comment]
So do you use Photopea in a browser or in Brackets? Could you try to open www.Photopea.com in a web browser and do the same thing?

Also, could you try to do it all (including saving a PSD) in the incognito window of a web browesr (where all your browser extensions are disabled)?

I never had any problems with opening and saving large PSDs in Photopea (500 MB or more).
