### ISSUE TITLE
Photos lose a lot of their sharpness 

### ISSUE THREAD

**Issue by FrontaalNaakt** [photopea/photopea#444]
Hello, my problem is simple: I notice that photos and screenshots lose a lot of their quality after I treat them with Photopea.

**Comment by photopea** [comment]
Hi, how do you treat your photos with Photopea? If you open a Photo, and save it back (e.g. as PNG), you should get back the same photo. If you save to JPG, you can choose the quality of the output.

Can you show us any examples?

**Comment by FrontaalNaakt** [comment]
I use Photopea mainly to downsize photos and crop them. And yes, I do set the quality to a 100 percent. Here's an example of an original I worked on with Photopea: 
![isadora 1](https://user-images.githubusercontent.com/35367790/34873182-61cb418a-f794-11e7-9847-ea4d8a30fc4e.jpg)

![isadora1](https://user-images.githubusercontent.com/35367790/34873211-73e8f77c-f794-11e7-80b8-183d58fef7a6.jpg)

**Comment by photopea** [comment]
How exactly did you create the second image? It also seems to be a little brighter.

When I export your JPG at 100%, I get the same image as the original.

**Comment by photopea** [comment]
How did you downsize it? Did you use Image - Image Size, or you set the new size in the Save For Web window? When I downsize it in any way, I am still getting the sharp image :(

**Comment by FrontaalNaakt** [comment]
Okay, can you see the difference here? I took an image, cropped it, still looked crispy sharp in Photopea. Then I exported it as JPG, downsizing it to 200 px (it was 1288 px). The result: 

![image](https://user-images.githubusercontent.com/35367790/34874462-4c01ddf0-f799-11e7-8f9b-33b432207dc0.png)

**Comment by FrontaalNaakt** [comment]
After I crop the image, I export it as JPG, that's when I get the option to adapt the size. Wait, I'll use image size first.

**Comment by FrontaalNaakt** [comment]
Makes no difference. I cropped the image, used image size to adjust the size, then exported it as jpg, same loss of quality.

**Comment by photopea** [comment]
I see in your image, that the preview in Photopea is sharp, while the preview in Foto's is blurry (and much larger).

I think the problem is in your program, which you use to view images. It "stretches" the image (making it about 25% larger), that is why it looks blurry. Can you use some other program to preview your image?

**Comment by FrontaalNaakt** [comment]
Doesn't make any difference.

**Comment by photopea** [comment]
Did you try to open the new image in other program, instead of Foto's?

**Comment by FrontaalNaakt** [comment]
I uploaded it directly to my site, result is the same. 

![image](https://user-images.githubusercontent.com/35367790/34877618-06ba3a68-f7a7-11e7-924a-7bc90a060022.png)

**Comment by photopea** [comment]
Seems like your browser is blurring images, too. It has a high device pixel ratio ("retina" display). Do you see, that the text "Frontaal Naakt" and the man on the horse are not sharp? I think it is for the same reason. All images that you ever see on your computer will be blurry.

Can you make the text "Frontaal Naakt" sharp?

**Comment by photopea** [comment]
I think it was fixed.

**Comment by KamranHuseyn11** [comment]
same thing also happened to me, overall quality drops when I save the image every time

**Comment by photopea** [comment]
Can you show us the original image and the new image, so that we can see them side by side?

**Comment by KamranHuseyn11** [comment]
- Sure, it actually gets blurry every time. probably because when i download i gets compressed. I really understand that providing open source as photopea is very helpful and i very much appreciate it. However, if i am getting the same result as just downloading from the browser, it is a not possible to work for me in photopea. i would try to increase the pixel number and work again to see if it works, but if it does not its just waste of time

- 

![eu map original](https://user-images.githubusercontent.com/55633369/65540278-1c657400-df1c-11e9-89f3-4dcb4d72208c.png)
![New Project](https://user-images.githubusercontent.com/55633369/65540413-651d2d00-df1c-11e9-86d4-b64efcf4457a.png)
![New Project (1)](https://user-images.githubusercontent.com/55633369/65540315-2dae8080-df1c-11e9-9fb9-aa22eb6ed468.png)

**Comment by photopea** [comment]
Hi! You sent me three different images. I don't understand which one is the original and which one should be blurry. Could you explain?

**Comment by KamranHuseyn11** [comment]
The one at the top is original, 2nd one is the picture I have saved via photopea, and the 3 rd one is edited version of 2nd one.
So the 3 rd one is saved twice, so it look more blurry

**Comment by photopea** [comment]
I see the second picture is a scaled-down version of the first picture.

Whenver you scale down any image, it becomes a little blurry. This is common in all editors and there is no way to avoid it.

I recommend scaling the image only once (instead of scaling it multiple times). You can also use smart objects, which preserve the original image (and always scale the original, instead of scaling a scaled version).

**Comment by photopea** [comment]
I see you scaled it down to about 70% of the original. This is the best result you can get. To avoid this decrease in the quality, you should use vector graphics, or scale it to 50% (so that 2x2 pixels are mapped into a single pixel).

![image](https://user-images.githubusercontent.com/15955558/65595501-3becb300-df95-11e9-9d52-10dce3927bd1.gif)

**Comment by photopea** [comment]
You are scaling down your image to about 83%.

I made a GIF with the original image, a scaled-down version from Photopea, and scaled-down from Photoshop.  Photoshop performs artificial sharpening after scaling down. It becomes sharper, but some parts of the border disappear.
![image (1)](https://user-images.githubusercontent.com/15955558/65596071-655a0e80-df96-11e9-8bc2-5bd64fb96b39.gif)

**Comment by boarry** [comment]
Was this issue ever resolved? I am new to photopea and I am having the same problem

**Comment by photopea** [comment]
Ok I will add this artificial sharpening. I don't like it, but that is how Photoshop works and it is what people expect.

**Comment by FrontaalNaakt** [comment]
So why don't you like it?

**Comment by photopea** [comment]
If you see a GIF above, in Photoshop version, some parts of white lines disappeared (white line is broken at some places). In general, sharpening, or any other additional image processing, results into the loss of information, and a new information may be created, which may not be related to the original.

**Comment by photopea** [comment]
I implemented it. When you use Image - Size (or Free Transform), you can choose a mode "Bicubic Sharper" instead of "Bilinear". It will sharpen the image after the transform. Here you can see the difference.

![image](https://user-images.githubusercontent.com/15955558/67188671-22505700-f3ed-11e9-9180-64991bc63e6f.gif)
