### ISSUE TITLE
PWA version on macOS prevents quitting by system-wide shortcut CMD+q

### ISSUE THREAD

**Issue by andrewvaca** [photopea/photopea#4467]
When using app installed as PWA (tested from Chrome and Brave browser), the app can't be ended by system-wide keyboard shortcut "CMD+q". Other PWAs can do this, so I assume Photopea catches the shortcut and prevents default browser action.

Steps to reproduce: 
1) Install Photopea as PWA application by clicking on "install" button in the browser's address bar.
2) Run the application (it opens in separate window).
2) Press the keyboard shortcut CMD+q.

Wanted result: 
Application should quit as the shortcut is noted in browser's "File" menu under "Close application" choice.

Actual result:
Nothing happens. The application don't quit. 

System: Apple MacBook Pro M1 14' 2021, macOS 12.3.1, Brave browser version 1.37.109 Chromium: 100.0.4896.60

**Comment by photopea** [comment]
I have noticed, that if you close Photopea on Mac in a regular way, and you have an unsaved work, it asks you, if you really want to lose your work. But when I allowed the Command+Q, it closed Photopea immediately, without asking anything.

I think Command+Q used to work in Photopea before. But then, someone complained, that they pressed it accidentally and lost their work. I think Apple should fix it first, so that it works the same as the "red close window" button.
