### ISSUE TITLE
Add feature like Xnormal Dilation

### ISSUE THREAD

**Issue by Raspac0** [photopea/photopea#4480]
Feature proposal: 
As a 3d artist one of the features missing on photopea and which will be very useful will be a feature like xnormal dilation.

![plugins](https://user-images.githubusercontent.com/25931640/162045989-d70c23a2-e525-41d9-83f7-33d17bb965e0.png)

What it does is it stretches the pixels of an image over the transparent areas.

![xnormalmax](https://user-images.githubusercontent.com/25931640/162047243-32517be6-57bf-427b-b661-ed9515023a42.png)

You can also specify the distance in pixels.
![options](https://user-images.githubusercontent.com/25931640/162047430-2170d1a3-adce-4a16-b91d-d2ac05d1e271.png) ![10px](https://user-images.githubusercontent.com/25931640/162047449-836c0ea9-d9b3-43e5-9616-fdadef292e10.png)

This plugin for photoshop is free and comes with the installation of xnormal.
An explanation and demonstration of the usefulness of being able to do pixel padding here : 
https://youtu.be/fa9ki3MBzsY

If photopea implements this filter then I will completely pass over it for my work :)

**Comment by photopea** [comment]
I have added this feature under Filter - 3D - Texture Dilation. Does it work as you expect it?

I have added the "Crop" parameter, which crops X pixels from around the object before dilating. E.g. if you set the Crop to 2, Dilate radius to 10, it will crop the image by 2 and dilate by 12 (to deliver the "requested size").

![lion](https://user-images.githubusercontent.com/15955558/162192542-71bc0043-813e-4d20-a85b-5602d70c51dd.png)
![lion](https://user-images.githubusercontent.com/15955558/162192556-7b87e045-ac87-4de8-82d6-a31fe158e3dd.png)

**Comment by photopea** [comment]
Let me know if it works as you wanted.

**Comment by ValentinOrient** [comment]
Wow ! I am impressed ! Thank you very much, thank you, thank you. 
I was not thinking that in not even 1 day the functionality will be added ! It's incredible ! 
It works perfectly and the Crop function is a great option! it's even better than the xnormal plugin! the only thing that could be improved would be anti-aliasing where pixel joins, but that's not important because it doesn't change anything for the mipmap generation on 3d game engine.
I switched to Photopea and I bought a license for 1 year! Again, thank you very much !
![moti-hearts](https://user-images.githubusercontent.com/25931640/162442397-955e4225-a064-4bf2-9e17-18450daa232d.gif)

**Comment by photopea** [comment]
Thank you :)
