### ISSUE TITLE
Scam page?

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#4484]
https://fixthephoto.com/es/illustrator-online.html

This site has Photopea embedded, without ads.

i don't know how much traffic it has, but still is misleading.

I found it looking for Illustrator alternatives for web
:/

**Comment by photopea** [comment]
We allow anyone to embed Photopea into their webpage. In 50% of cases, an ad is shown for buying Photopea Premium.

In my opinion, people who got to that page instead of Photopea.com would probably not find Photopea.com anyway. So at least they learn the word "Photopea" and might find the real Photopea.com at some point.
