### ISSUE TITLE
Pattern fill don't stay

### ISSUE THREAD

**Issue by TheRadicalDreamer** [photopea/photopea#4514]
I always have this problem:
I fill a shape with a custom pattern.

I save the PSD. Then open it again, and the pattern is not there.

It IS applied to the shape, but i cannot use anywhere else. I cannot even change it and then go back to it. Because it is gone.

Here is a little example
[pattern.zip](https://github.com/photopea/photopea/files/8502110/pattern.zip)

It should stay inside the PSD or my account ideally

**Comment by photopea** [comment]
It works the same as in Adobe Photoshop. There are patterns inside each PSD file (can be different in each PSD), and global patterns (= our basic pack + your own .PAT files that you loaded: manually or from Edit - Local Storage). So if you define a new global pattern, save it as .PAT to your computer, it will be lost otherwise. Next time, load your .PAT file and choose to keep it in the Local Storage.

If you want to turn a pattern of a layer into a global pattern, try "Define New".

![image](https://user-images.githubusercontent.com/15955558/163728300-0b5773fd-3ee5-4afd-a3ea-87ba3b0579fd.png)

The same goes for Gradients, Brushes, layer styles, actions, etc.

**Comment by TheRadicalDreamer** [comment]
https://user-images.githubusercontent.com/11801254/163837208-8c9126be-7122-4e08-8981-303948b1b5a8.mp4

Here is what i encounter normally

**Comment by photopea** [comment]
That is a little restriction, that the top bar does not have access to the current project (and its textures).

You can see the current pattern in Window - Properties.

**Comment by TheRadicalDreamer** [comment]
I see, but, couldn't be that image on the fill section?

And what about the Define New Pattern, that does not define any?

**Comment by photopea** [comment]
Edit - Define new - Pattern - it defines a global pattern from the current document.

Tiny Triangle - Define new - it defines a global pattern from the current pattern in that specific pattern selector element.

Maybe Adobe explains it better on their website.
