### ISSUE TITLE
Save message won't dissappear (Saving to Google Drive)

### ISSUE THREAD

**Issue by shirgans** [photopea/photopea#4633]
The "Save..." message is showing on screen forever when saving to Google Drive.
Usually it happens when the files becomes bigger (~20MB) 
![Screenshot -bug](https://user-images.githubusercontent.com/18657225/168511162-eb38c59a-ad4d-44f0-98bf-8d56c1e520dc.png)
.

**Comment by TheRadicalDreamer** [comment]
I am on the same boat.

First, my context is: I have a really slow my internet connection, but when i open a Google Drive file, then i prefer to download as a PSD, to upload it myself manually to google drive, because if i save directly in photopea, it gets stuck forever.

Maybe add a % of completition for the saving message like: "Saving... (35%)" so i can tell if it is uploading.

**Comment by photopea** [comment]
It seems like google has removed Photopea from the Drive App Store. If you installed it in the past, it will probably stop working :(

BTW. at www.Photopea.com , you can press "Google Drive" on the left side and access your GDrive from there.
