### ISSUE TITLE
Feature request: CR3 support

### ISSUE THREAD

**Issue by JMoss8** [photopea/photopea#4662]
Firstly, thank you for creating such a great tool! 

I've one of the newer Canon cameras which shoots RAW in CR3 format and Photopea currently supports only CR2. Do you have any plans on adding support for this format? 

I just found this, maybe it could be helpful? [https://github.com/lclevy/canon_cr3](https://github.com/lclevy/canon_cr3)

Thank you, your Premium user

**Comment by photopea** [comment]
The CR3 format is too complicated, and it would take us too much time to implement.

I am not a fan of each brand creating their own format. I think all cameras should switch to open raw formats, e.g. the DNG.

Can your camera shoot in DNG instead of CR3? If not, I recommend you to convert your CR3 files into DNG somehow, if you want them to still be openable e.g.  20 years from now.

**Comment by photopea** [comment]
Photopea can open Canon CR3 files now! 

Could you please try to open your CR3 files in it? If it does not work, could you send me one of your files to support@photopea.com , please? :)
