### ISSUE TITLE
Color picker should have CMYK variables

### ISSUE THREAD

**Issue by TheRadicalDreamer** [photopea/photopea#4709]
![image](https://user-images.githubusercontent.com/11801254/172502513-4e4d1efa-0e56-443a-b0c4-097d2952fcc8.png)

To convert the CMYK to Pantone (which i need to my printable projects) i need the CMYK variables.

There should be a third column on the color picker, like photoshop does:

![image](https://user-images.githubusercontent.com/11801254/172502685-474c9506-50ff-4f69-8a27-901024d79682.png)

Also, the eye dropper should show the variables for both colors. If not i cannot tell if there is the same or not at a glance.

![image](https://user-images.githubusercontent.com/11801254/172503142-4808d915-71b5-4637-8a98-78f3aad43204.png)

Finally the eye dropper should also show RGB if you are in RGB mode and CMYK if you are in CMYK mode

**Comment by photopea** [comment]
I think we discussed it before. The problem is, that the same RGB color corresponds to hundreds of CMYK values. 

In Photoshop, if you enter CMYK (0,0,0,100), you get RGB (35,31,32). But if you enter RGB (35,31,32), you get CMYK (70,67,64,74). The colors (70,67,64,74) and (0,0,0,100) are identical in CMYK.

I don't think these CMYK values can be useful for anyone. What exactly do you do with Pantone? Maybe we could do it directly, without any CMYK.

**Comment by MichalSZZ** [comment]
Yes we have discussed it here https://github.com/photopea/photopea/issues/3883
I think that it should to be in Photopea but it is very hard subject for professional purpose (we shouldn't talk here about color conversion)

**Comment by MichalSZZ** [comment]
'Grayscale mode' was there for example only. In my 20 years of working in Photoshop I used it only once. 
I made few things for print in my whole life. CMYK or other modes and palettes are for professional users. 
I don't know how CMYK works in Photopea now but maybe it is now useless for professional graphic designers. I can't verify it because I don't have experience needed in that case

**Comment by MichalSZZ** [comment]
And about CMYK. In some printing house and their printing methods - you can pay less for the prints when you know that your materials have only some colors. For example they have tariff for Business cards where one side is made from only one color (for example K). And another have full 4 color CMYK. If the K in the PDF will be not 100% K it will be mix of CMY+K for them.

@photopea maybe ask about this specific CMYK differences on some channel for DTP graphic designer or Brand Identity specialist forum (Reddit or something like that). You will get tons of feedback and your software will be more famous in the graphic community.

**Comment by TheRadicalDreamer** [comment]
> I think we discussed it before. The problem is, that the same RGB color corresponds to hundreds of CMYK values.
> 
> In Photoshop, if you enter CMYK (0,0,0,100), you get RGB (35,31,32). But if you enter RGB (35,31,32), you get CMYK (70,67,64,74). The colors (70,67,64,74) and (0,0,0,100) are identical in CMYK.
> 
> I don't think these CMYK values can be useful for anyone. What exactly do you do with Pantone? Maybe we could do it directly, without any CMYK.

I got something from Photoshop. CMYK cannot be modified, so it is way way conversion.
![image](https://user-images.githubusercontent.com/11801254/174681070-68156760-86b7-4587-ab56-ebcdbcaf7581.png)

Users won't be able to set a CMYK, but only RGB/Hex to get a CYMK color

Can someone please confirm this?

**Comment by MichalSZZ** [comment]
@TheRadicalDreamer  you can set parameters in CMYK. There are no any radio buttons but you can set the C M Y K without any problems.
In Photoshop when you set the radio button active that is next to the Letter it change the different color spectrum for each (big colorful box on the left).

**Comment by photopea** [comment]
But I still do not understand what is the purpose of knowing or entering CMYK values? What problem does it solve? Could you explain to me a use case, where it is useful?

**Comment by TheRadicalDreamer** [comment]
To be honest, the issue i have is always a matter of sharing.

### Case A: I send the file to the printer and they text me back showing me the CMYK code of each color for me to correct. I cannot do anything about it to correct it. I don't know my own CMYK values because i work on RGB. And even if i know my own CMYK values i cannot input theirs to check what color are they getting.

On this case, it will be good to have the codes on the color picker and in the eyedropper 


### Case B: When i am working on CYMK mode i want to pick colors on that gamut. Of course i set the checkbox on the color picker
![image](https://user-images.githubusercontent.com/11801254/175784960-35f099e1-7dc1-453d-ad72-303407f630f1.png)
but i am still not bonded to that spectrum, so for example, i cannot pick precisely the brillest color of a type of green, because the feedback on the color picker still shows in RGB. So if i pick a color, i have to use the brush tool to see it for the first time.

In this case it will be great to have the feedbackk of the color picker (the uppper part where is orange in this image 
![image](https://user-images.githubusercontent.com/11801254/175785127-c5e6e10b-15c0-495a-9b64-dff94ba6b10d.png)
)
to be bonded to the CMYK spectrum when i check CMYK gamut, so i can know beforehand the color i will get on the canvas.

**Comment by MichalSZZ** [comment]
CMYK (and Pantone) is very important for people who are making their designs for printing. For professional printing - in printing house, not in their own home or little printing centers who have big Konica Minolta machine (as in my job for example - it cost a lot but isn't professional - it has a limitations like print on A3 max and it can't do it on cardboard). That might to be: brochures, books, packages etc.

For example:
1. I am making something for print for my (or any other) company who has the official Brand Book. There are colors that should to be use in any printing purposes. I need to do it in CMYK or PANTONE (but in this case we will talk about CMYK). Big printing houses need PDF in CMYK. I don't know how it works but if they get a RGB they will ask again to convert all to CMYK.
2. People who work in DTP or designers who make only for printing have something like CMYK/PANTONE color checker/controller. A set of printed on hard paper strips with named color and it CMYK. When I see a proof of real printed color I may to decide on it in my design. But I can't type it in Photopea's color picker. I have something like it in my job for coated and uncoated paper. But as I mentioned - I make something for print very very rare.  
![obraz](https://user-images.githubusercontent.com/38118273/176147550-e50c7896-939e-4372-93f0-237b95a6e91a.png)
3. Sometime I need to make a design (for example flyer or business card) that is matte but has some pieces shiny (with special foil that makes glossy coating). Something like here https://www.youtube.com/watch?v=Zr4f1DIba7c Printing house asks me for another PDF or special layer with one color from CMYK for elements that has been make in UV technology. For example i make 100% Magenta. Printing machine understand that. Printing operators are happy because they don't do any conversions by they own - in many company that is unacceptable responsibility. 
4. Another thing - I want to do a cheap book. All should to be printed only in black. Black from CMYK - 0-100% of K. Now I can't tell Photopea to do that (?)

I'm a noob in DTP. Don't know anything about color profiles but I think that is very important thing for people who are making design for printing purposes. There isn't CTRL+Z ;) and fails can cost a lot :)

**Comment by MichalSZZ** [comment]
Another thing from my little experience in printing. When my company make something for the newspaper (advertisement) - they ask for projects that will be have more than (for example) 130% of ink summary (i don't remember numbers but it is very important). This type of paper has 45g (a half of standard paper that is used in printers) and too much ink can damage it - make paper wet. Only on real CMYK I can set it and check it later when I finish my job. Then summary % of colors can be calculated.

https://creativepro.com/reducing-the-total-ink-limit-cmyk-images-using-photoshop/

Printing subjects are very hard and it can be useless for 99,5% of Photopea users. You have to decide how much work you should to spend on it and what will be not done because of it. That is your decision Ivan. But you could deep in that before you start anything.

**Comment by TheRadicalDreamer** [comment]
I have to add myself to Michal examples.
I do have the material color picker and yes, i have to achieve what I see in paper with the numbers it indicates, because the screen is different on every computer.

Also, as he said. You have coated and non coated materials, and the CMYK variables gives different results depending on the after treatment of the ink.

**Comment by TheRadicalDreamer** [comment]
At least, for now, or as an initial feature. To have the CMYK input with one ink profile is really great.

**Comment by photopea** [comment]
I have implemented the CMYK values into the color picker. However, it can be +- 5% different than the values in Adobe Photoshop.

**Comment by photopea** [comment]
One fact: If you set some RGB values in the Color Picker of Adobe Photoshop, you will see Lab values, and CMYK values of that color. These Lab and CMYK values depend on the color space of a current document.

If you have a CMYK document, and you enter RGB (100,50,31), you get Lab: (27,22,22), CMYK: (38,77,86,49).
If you have a RGB document, and you enter RGB (100,50,31), you get Lab: (28,27,27), CMYK: (35,82,92,46).

Please, confirm, that you know about this, and you want Photopea to work the same.

**Comment by photopea** [comment]
Sorry for spamming you with incorrect information :(

So the CMYK values are present in the color picker of Photopea, and it works very similarly to the one in Adobe Photoshop.

**Comment by MichalSZZ** [comment]
It is only a simulation? It doesn't store any information about CMYK and its CMYK colors in file exported from Photopea?

When I save PSD in CMYK mode in Photopea it opens as a RGB in Photoshop.
When I do the same thing in Photoshop - Photopea can read embeded CMYK and when I look in the Image->Mode, there is a CMYK checked. But the colors in Photopea when I open it are different as those that was set and Saved in Photoshop. K is not 100% but C25% M100% Y100% K100% - was saved as 100% K in Photoshop. Other colors CMY are from 74% to 87%. That is for PSD saved in Photoshop with or without the ICC profile.

CMYK now is in the color picker and the task is completed but I think that it should to be also a way to save file as PSD in CMYK for the easy Photopea => Photoshop sharing. I am setting color mode to CMYK in Photopea. I make K as K100% and when user with Photoshop is opening that file - he has also CMYK and K with 100%.

Maybe it is not so easy to do. I don't know what status is now. But a year ago Gimp in its 3.0 version still doesn't have CMYK

**Comment by TheRadicalDreamer** [comment]
Also, when checking the CMYK gamut, the pointer should always be within the limits of the gamut, even if i click outside in the grey area.

For example, if i pick on the red dot, the pointer should be on the actual color i am picking
![image](https://user-images.githubusercontent.com/11801254/177180220-faacca37-2777-4aa2-bd70-143f79332534.png)


Also the top part of the color picker, when you can compare the new color to the last, should also show the CMYK color if i have checked CMYK gamut, and not show the RGB one

**Comment by photopea** [comment]
We shold imrove our conversion between CMYK and RGB.

**Comment by TheRadicalDreamer** [comment]
> Also, when checking the CMYK gamut, the pointer should always be within the limits of the gamut, even if i click outside in the grey area.
> 
> For example, if i pick on the red dot, the pointer should be on the actual color i am picking ![image](https://user-images.githubusercontent.com/11801254/177180220-faacca37-2777-4aa2-bd70-143f79332534.png)
> 
> Also the top part of the color picker, when you can compare the new color to the last, should also show the CMYK color if i have checked CMYK gamut, and not show the RGB one

Can this be added in the meantime?

**Comment by photopea** [comment]
I am planning to make a big remake of CMYK-related stuff.

**Comment by TheRadicalDreamer** [comment]
How that will see the light?

> I am planning to make a big remake of CMYK-related stuff.

**Comment by photopea** [comment]
We have improved the CMYK support. Conversions between CMYK and RGB should be much more precise now.

**Comment by TheRadicalDreamer** [comment]
Ivan, thanks for improving this!

I know it should have been a headache.

I would like to thank you, and also ask you if you can change the way the color picker works when the CMYK gamut is enabled.

Like in the comment before:

> When i enable CMYK gamut on the color picker, i am not bonded to that spectrum, so for example, i cannot pick precisely the brillest color of a type of green. The circle still shows colors in sRGB. So if i pick a color, i have to use the brush tool to see it for the first time.

Here in this picture i have set a green, outside the gamut, but on the picker i cannot tell which green i will get when i paint. So on the bottom you can see the real green i get:
![image](https://user-images.githubusercontent.com/11801254/213489905-3b6ca2bd-806f-45d8-a364-daa5d1566b51.png)

**Comment by TheRadicalDreamer** [comment]
The same happens with the eye dropper:
![image](https://user-images.githubusercontent.com/11801254/213491374-f4f7cbbd-c7ba-44eb-98ad-998f9355304e.png)

It still shows the sRGB color, an dno the CMYK one, when i have enabled CMYK mode

**Comment by photopea** [comment]
Done! When you enable a CMYK gamut, it will let you pick only the closest color in the CMYK gamut.

Also, in a CMYK mode, the eyedropper shows colors in CMYK (0-100)

**Comment by MichalSZZ** [comment]
@photopea great! I have to test it deeply but your work is just awesome!

I just tested the file from Photopea saved as CMYK in photoshop it is a real CMYK in the 'color mode' :)

Could you add CMYK to the "info panel"? Now it shows only RGB and HSB?

**Comment by photopea** [comment]
Done :)

**Comment by MichalSZZ** [comment]
> Done :)

Thanks. One more thing - it is sampling transparency grid in Info Panel as C75% M68% Y67% K90%. RGB and HSB are set to 0 then.

**Comment by photopea** [comment]
When you pick a color of a transparent pixel, the color is black (RGB 0,0,0, CMYK 75,68,67,90). Adobe Photoshop works the same.
![image](https://user-images.githubusercontent.com/15955558/213732553-c6e7da9f-c4ba-4a93-a3bd-f6c2d9ae780d.jpg)

**Comment by MichalSZZ** [comment]
I was talking about Info Panel. In Adobe Photoshop when you are moving around the canvas - when there are no pixels (there is a transparency grid) - PS don't show any info about color. RGB, HSB, CMYK have nothing next to its colors letter. 

![obraz](https://user-images.githubusercontent.com/38118273/213741066-9b28eb8e-fe09-4b44-b0ad-384ec301b4b3.png)


In your case 
You can use "-": 
R: - (or nothing)
G: - (or nothing)
B: - (or nothing) 

same for HSB and CMYK when the cursor is above pixel without any color.


Once again - I am talking about the "Info Panel".

But BTW... in my version of Photoshop, I am not able to pick a transparent colors with a color picker. Nothing changes when I click on the chessboard

**Comment by photopea** [comment]
Since our Info panel shows Transparency (Alpha), I think it is needed to show a color, too. Sometimes, non-black color can be stored in transparent areas.

**Comment by TheRadicalDreamer** [comment]
![image](https://user-images.githubusercontent.com/11801254/213773668-b5af680f-d563-41cb-94ce-49b4f2cc9998.png)
