### ISSUE TITLE
Photopea doesn't save psd format properly

### ISSUE THREAD

**Issue by halkalabka** [photopea/photopea#4727]
Files that are saved from photopea locally in .psd format are not openable.
Error message when trying to open: "Unknown format "\u000\u000\u000\u000"

**Comment by halkalabka** [comment]
Lost hours of work.. any chance that there files could be fixed? Or that I could access my work from the web app?

**Comment by photopea** [comment]
How large is your file? Is it 0 Bytes?

It happens when you press "Save as PSD", and there is a message "saving ...", but you close Photopea before this message goes away.

If your hard drive speed is 20 MB/s, and your PSD is 100 MB, you need to wait five seconds. If you close Photopea too early, you will end up with a damaged file.

**Comment by halkalabka** [comment]
Yes, it's 0 Bytes. I didn't close Photopea early, I have a bad habit of never closing my tabs so I left them open until the next day.

Is there any way to recover lost work?

**Comment by photopea** [comment]
Your work can be saved only to your computer, we do not save it anywhere else.

Could you describe, how can I produce a 0 Byte PSD file in Photopea?

**Comment by halkalabka** [comment]
I just tested it again - still doesn't save the file.
I go File>Save as PSD>enter file name. 
There's no message re saving.
I don't touch anything for 30 sec. The file that is created locally has 0kb.

**Comment by photopea** [comment]
Did you try these steps? https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by photopea** [comment]
I have to close it because of lack of details :(
