### ISSUE TITLE
Text box with custom shape, path subtraction etc.

### ISSUE THREAD

**Issue by AncientSwordRage** [photopea/photopea#4739]
Is something like the first example here possible https://www.bwillcreative.com/how-to-wrap-text-in-photoshop/

If so how do you make the text flow around a subtracted shape (say a large rectangle with a smaller circle cut out), so that none of the text is hidden/cut (i.e. No masks!)

**Comment by MichalSZZ** [comment]
In Photopea it works the same way. All examples showed by you can be done without any problem.

Look for tutorial for Photopea/Photoshop on Youtube.
For example:
https://youtu.be/nTgP_fMeVNQ

https://youtu.be/pOQkXQ_cHSo

https://youtu.be/y2mdb-i5p1U

**Comment by riderjensen** [comment]
Hey @MichalSZZ, thanks for the links. I briefly looked through them and hopefully didnt miss anything but this problem is actually a little different. There was a discussion on the reddit that this is related to: https://www.reddit.com/r/photopea/comments/vfjlrj/getting_text_fill_in_all_around_an_image/. Basically, the text should not wrap around in a traditional sense but just continue "through" an object without losing any of the text. In the link that @AncientSwordRage linked, that is basically a custom shape with a textbox. But the question is, is it possible to make a text box with missing pieces inside of it but still have the text continue to flow.

This is the image I was thinking of. Basically how Microsoft Word or Google Docs works where you can have an image and the words keep going in a straight line, only interrupted by the image.
![1](https://user-images.githubusercontent.com/25038565/174496793-c4aad5b0-6bb1-44b0-b390-51607135e726.PNG)

**Comment by MichalSZZ** [comment]
@riderjensen Ok now I understand. In Photoshop it is not possible too :( Only in Illustrator or InDesign it can work like you described. But in Photoshop there is a strange workaround for that... You should to do your shape with hole inside and after that make another little shape which will break you main shape. After that you can delete that small rectangle. You have to see that because it is hard to explain.
https://www.photopea.com/#iM5Ga3H6Z that file was made in Photoshop (in step when I filled shape with a text). As you can see - Photopea can read it but when you want to do it by your own in Photopea - it will not work. Look https://www.photopea.com/#iOjSIUrTo @photopea can you look why it doesn't fill like in Photoshop (in step 4)?

**Comment by riderjensen** [comment]
Yeah it looks like you are right, illustrator is the right tool for the job, not photoshop. Thank you for your help! :)

**Comment by photopea** [comment]
Currently, Photopea starts the text only inside one closed path. If you have two rectangles and a circle in one shape layer, it will start text just in one them.

Merge vector shapes into one shape to get a result that you want :)
