### ISSUE TITLE
Collision of shapes just in the line of the stoke

### ISSUE THREAD

**Issue by TheRadicalDreamer** [photopea/photopea#4746]
I have different results for the same shape on different collisions between its parts.

https://user-images.githubusercontent.com/11801254/174672240-d356c61b-1c64-4858-8e23-2c20751c840c.mp4

I have DPI set to pixels/cm btw

**Comment by TheRadicalDreamer** [comment]
i believe it has to do when i converted from pixels/inch to pixels/cm

I could retransform every shape and then it bahaved correctly.

**Comment by photopea** [comment]
I think it is about our shape merging algorithm. When two shapes touch each other, it is not clear, if they should be connected or not.

I would recommend you to draw yur graphics in a way, that there are no two exact lines / curves on top of each other. E.g. just draw a biger rectangle instead of two small ones.
