### ISSUE TITLE
Move "Reduce Colors" and "Vectorize Bitmap" into Filter menu

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#4884]
They work like filters and are used infrequently, so Filter menu is a better place for them. What do you think?

**Comment by photopea** [comment]
Adjustments and Filters convert pixels to other pixels, no adjustment or a filter creates vector graphics.

But "Reduce color" does act like a filter. But since it is related to Vectorize Bitmap, I think it is better to have them together. We already have Auto Tone, Auto Color, Apply Bitmap, which also work like filters.
