### ISSUE TITLE
Starburst Generator plugin not working on Firefox

### ISSUE THREAD

**Issue by xan2622** [photopea/photopea#4910]
Hi @yikuansun.
_(You probably already know about it)_ but I just wanted to report that the **Starburst Generator** plugin doesn't work on Firefox 103.0.2 64 bits, Windows 11. 

![ShareX_2spemFGxnA](https://user-images.githubusercontent.com/1732773/184381076-e289c47e-7aec-4a83-a36e-61fadcf3d75e.gif)

I also tested on Edge 104.0.1293.54 and with that web browser it works fine: 

![ShareX_itSclF9fn5](https://user-images.githubusercontent.com/1732773/184383878-122f479c-2f10-41f1-8224-e59882ee4c24.gif)

It might be an expected behaviour (on Firefox), IIRC, Ivan mentioned in other Github comments that Firefox lacks some features. 
But just in case.. I thought it could worth it reporting it.

**Comment by yikuansun** [comment]
Hi @xan2622 , thanks for letting me know. You are right, I used some Firefox-incompatible tech for that plugin. The whole plugin started out as just an experiment, so I didn't really care. I may switch it in the future to use more commonly supported tech.

FYI, Screen usually works better than Soft Light for overlays with black background.

**Comment by photopea** [comment]
Ok I will close it.

**Comment by photopea** [comment]
Hi Yuakysun, could you make a plugin for https://beta.dreamstudio.ai/  - Stable Diffusion? many people are asking for it, it should be possible to do with the DreamStuido API.

**Comment by yikuansun** [comment]
@photopea Sorry, I don't think I understand. Correct me if I'm wrong, but Stable Diffusion seems like an AI tool for creating a whole image from a text prompt. It doesn't seem like something that needs (or wants) to be integrated with Photopea. Sure, users could import a Stable Diffusion image to color grade or add noise or something, but a) DreamStudio already gives some of that customization and b) it doesn't really need to be a plugin in my opinion. I may be wrong, but my guess is that the users requesting the plugin are interested in using the Stable Diffusion tech by itself with no real intention of editing in Photopea, but they don't want to have to pay for the plans offered by DreamStudio (they'd rather have a developer like myself pay to integrate the API into a software that they can use for free). Additionally, I personally don't find AI art to be "artistic," for a lack of a better word. Think about it this way: could a natural object, even one of great beauty, such as a pink rose, be considered art? My answer would be no, because I believe that art is more than just a glorified method of entertainment. Art, in my opinion, is a form of conversation, the most powerful form of human communication. It's not just about entertaining an audience; as an artist myself, I find that using art as a medium for expressing myself is equally important, if not more important, than the experience of the audience. Art is not a one-way thing. It tells something about the artist. It is a human-to-human interaction. Nothing against the people at DreamStudio, or others creating equally impressive technology, that's just my personal opinion.

Yours truly,
Yuakysun

**Comment by xan2622** [comment]
Hi.

> Correct me if I'm wrong, but Stable Diffusion seems like an AI tool for creating a whole image from a text prompt. It doesn't seem like something that needs (or wants) to be integrated with Photopea

😲 On the contrary, a **lot** of users want their favorite DCC application to feature this new technology. Especially because these "AI tools" often require the user to install many dependencies and utilities before even being able to generate *AI art* thanks to prompts in a Console. 

For the moment, many of these projects require users to have medium or advanced computer skills to be able to install and use these AI tools correctly.

Here are some projects that already integrate Stable Diffusion in DCC softwares:

Figma:
- https://80.lv/articles/an-upcoming-figma-plug-in-uses-stable-diffusion-s-ai-powers-to-design-ideas/

The Gimp:
- https://mobile.twitter.com/nousr_/status/1563912133120647168

Krita: 
- https://github.com/sddebz/stable-diffusion-krita-plugin

Blender: 
- https://www.reddit.com/r/blender/comments/xapo8g/stable_diffusion_builtin_to_the_blender_shader/

- https://carlosedubarreto.gumroad.com/l/ceb_sd

Houdini:
- https://80.lv/articles/combining-stable-diffusion-and-houdini-to-create-3d-art/

>  it doesn't really need to be a plugin in my opinion.
I wouldn't mind Stable Diffusion to be directly integrated into Photopea but IMO, it would make more sense to create a plugin to easily create AI Art. I am not aware of other DCC softwares that directly integrated AI Art creation inside their UI. 

> I may be wrong, but my guess is that the users requesting the plugin are interested in using the Stable Diffusion tech by itself with no real intention of editing in Photopea

On the contrary. If all these other DCC softwares now have Stable Diffusion plugins (often made by volunteers) it's exactly/especially to let users work easier with these generated images: 

3D artists will be able to [replace a part of a texture](https://mobile.twitter.com/IRCSS/status/1554088473434509313) easily. 

Digital Artists will be able to generate AI Art thanks to prompts, letting them get examples of scenes, characters or landscapes... that can be used just for inspiration or as a base for their overpaintings. Other artists may want to  [generate textures](https://withpoly.com/textures or patterns) thanks to AI.

I understand that some people might not like AI Art, but anyway, this technology will be part of many artists' workflow from now on.

**Comment by yikuansun** [comment]
Hi @xan2622 , thanks for the detailed reply. I'm still not convinced though.

> many of these projects require users to have medium or advanced computer skills to be able to install and use these AI tools correctly.

Is DreamStudio one of these? I was under the impression that it was pretty easy to use.

> Digital Artists ~will be~ are already able to generate AI Art thanks to prompts, letting them get examples of scenes, characters or landscapes... that can be used just for inspiration or as a base for their overpaintings.

Again, not sure why this would be a plugin. You could export the image from DreamStudio and import it back in, and the UI would probably be easier to use.

For right now, I just don't think it's worth my time to build this plugin, especially since the API costs money, which I am currently short on. Maybe I'd build it if there was a very easy formula for it.

I did notice that you mentioned Poly, which I do think could be useful (I am okay artists being assisted by AI, to a certain extent). Poly doesn't seem to have an API, though, so I don't know how it could be a plugin.

**Comment by progproc** [comment]
To me, the benefit of having Photope with the Stable Diffusion integrated would be to have a quick tool to edit the img2img "seed image" (source image). 
Also, obviously the user would have to buy their own membership with a tool like Dream Studio and then use the API Key for their own account. Nobody is askign the programmer to foot the bill 😁

**Comment by photopea** [comment]
Personally, I don't see any point in such plugin either. I think people are asking us because it is a "hype" nowadays.

I think there are 2 advantages:

- Many users want to edit a generated image. Once it is a plugin for Photopea, you can just click the button to get it to Photopea (and save 5 seconds of your time)
- If the feature allows turning a sketch image into a photo-ish image, there could be a button for loading the current image from Photopea (also save 5 seconds of your time of saving your image from Photopea and loading it into another website).

Also, since it is a buzzword, your plugin could get more users than all your other plugins combined :)

**Comment by xan2622** [comment]
There is also another usage :
-  **inpainting** with mask. 
https://youtu.be/N913hReVxMM

**Comment by photopea** [comment]
@progproc We could make a plugin like this: https://christiancantrell.com/#ai-ml  would you like it?

But keep in mind, that this Photoshop plugin requires you paying 1 cent for each click of the "Generate" button, would you be ok with it?

**Comment by progproc** [comment]
That is exactly what I had in mind. Yes, I think using different API Key
for paid services or paying per generation makes sense.
