### ISSUE TITLE
Very often the name of the text layer will stay still with first time edit

### ISSUE THREAD

**Issue by hgs54371** [photopea/photopea#494]
First time edit - name stays still, nothing changes
Have to edit twice for it to actually be edited

**Comment by photopea** [comment]
Hi, do you mean "the edit" of the name of the text layer (in the Layers panel), or the edit of the content of the text layer (with a Type tool)?  If it is the second one, should the name of the text layer always correspond to its text content?

**Comment by hgs54371** [comment]
I mean the name of the text layer in the layers panel, it'll show as the same with the text content, which I often change it to something else, but I found very often it wont change until the second edit. And no, the layer name only update once with content when first created is just enough

**Comment by hgs54371** [comment]
Maybe I found the answer to this, because after edit I click out on another layer, instead of hit enter, which I expect it to respond the same as hitting enter, like in photoshop, but in here click out on another layer after editing leads to cancel the edit

**Comment by ewnjtgouierg** [comment]
I was caught into this too
From my experience, it's not just Photoshop, when clicking outside/something else after changing something, most users would expect the change to be committed rather than canceled.
Especially with the trend in modern apps to abandon "ok"/"save" etc buttons and just save everything, that has been here for a while.

**Comment by photopea** [comment]
Ok it was fixed. When you click somewhere while editing the layer name, the new name is confirmed.
