### ISSUE TITLE
Magic Wand showing opaque

### ISSUE THREAD

**Issue by rehansanish** [photopea/photopea#4989]
Whenever I use magic eraser, cut and paste, I always get a border of opaque pixels.

Image below:
![image](https://user-images.githubusercontent.com/94996859/190286627-a3ac3f1c-7ad5-49b1-8ea4-3161245ac02f.png)

It happens all of the time and I want to know how to fix it

**Comment by photopea** [comment]
I think it is a natural property of the magic wand tool. That is because between the green and the gray area, there are pixels wich are half-green and half-gray, which create this border.

If you can find any software which can do what you want, I will investigate it. Otherwise, I think it is impossible to make it work as you want.

**Comment by photopea** [comment]
I have to close it because of lack of details.
