### ISSUE TITLE
On Mac holding command key and changing arrows to move the arrow keeps the first one pressed

### ISSUE THREAD

**Issue by vendoNZ** [photopea/photopea#5064]
1. With marquee selection tool selected, I hold down command key to change it to move key (old PS habit) - if I click the up arrow then the right arrow it applies the up arrow again. I can "reset" it by letting go of the command key in between. This happens on a lot of functions not just when moving an element.
2. When opening a dialog like feather I immediately type the amount, like 20 but because the value input is not preselected it changes the layer opacity to 20. To fix, preselect the input on dialogs.
3. On Mac: With the Lasso select, in PS you can hold down option key to click and remember the point; it makes it similar to the Polygonal Lasso select. This would be useful as I imagine its how most PS users are used to using the lasso.
4. When selecting a tool from the left tool menu, I am used to clicking and holding down then releasing to select. You have to click to select it.
5. In the downloaded version I have adblock disabled in Chrome but it still says adblock detected and doesn't show ads.
6. Upgrade to Premium errors (minor): I selected github and goes to a blank page and stops: https://www.photopea.com/papi/login.php?code=6d164515a6... tried again by clicking back, another error after payment by cc it didn't confirm that payment was successful, just the loading gif - probably nothing to worry about, just comgate error with possible conflict with sessions when starting again.  It shows as premium successful in photopea so all good.

**Comment by photopea** [comment]
Hi, thanks for your report!

1) this is a bug in the Mac OS and only Apple can fix it. Please, report it to Apple, or switch to a diferent system.
2) Done.
3) Done.
4) Done.
5) Your adblock is probably lying to you. It is still enabled and is blocking ads. Otherwise, we would not be able to detect it. Disable the extension completely instead of asking it to not block ads and hoping it will not. Or switch to a different adblock.
6) I think it could be caused by your browser extensions. Can you reproduce it in a browser with no extensions?

**Comment by vendoNZ** [comment]
thanks! Don't worry about 6. I think it was caused by clicking back, but I paid successfully so premium is activated and no ads

**Comment by photopea** [comment]
okay :)
