### ISSUE TITLE
[Bug] Editor thinks I'm holding Ctrl while I'm not

### ISSUE THREAD

**Issue by avi12** [photopea/photopea#5136]
The last thing I tried is to insert a text, I held <kbd>Ctrl</kbd> to move it and then resize it, but after pressing Enter, it refused to get inputs, e.g. clicking a layer without holding <kbd>Ctrl</kbd> resulted in toggling the layer's selection

Browser: Brave 1.45.133

**Comment by photopea** [comment]
We ignore browsers like Brave or Internet Explorer, as it is almost impossible to run a modern, advanced web app in them. Could you test it in any other browser?

**Comment by avi12** [comment]
Brave is a fork of Chromium. Development for it should resemble Chrome, i.e. quite easy

**Comment by photopea** [comment]
We tried to report bugs to Brave in the past, but they blocked us. So it makes no sense to test Photopea in Brave, when we know, that some crucial features of Photopea will never work properly in Brave (because it is a browser issue,  and the browser maker refuses to fix it).

https://github.com/brave/brave-browser/issues/17850

**Comment by avi12** [comment]
That's very unfortunate
The main reason I'm using Brave is to get a reliable adblocker by default, which is not supplied by the popular browsers
You can use browser extensions, but because they cannot truly support MV2, their days are numbered

**Comment by photopea** [comment]
I have to close it, as I can not fix it.
