### ISSUE TITLE
Slow Speeds with raw files and high resolution jps

### ISSUE THREAD

**Issue by 9g2hj5** [photopea/photopea#5176]
When using filter gallery or camera raw filter on high res jps or raw files the program runs extremely slow. The only time I can seem to get it work right is using a screenshot of my file.

**Comment by photopea** [comment]
What is a resolution of your photos? It works slow for a high resolution.

**Comment by 9g2hj5** [comment]
5184x3456, 240 dpi

**Comment by photopea** [comment]
Could you record a video of how slow is Camera Raw filter in your case? Or tell us how long does each redraw take?

**Comment by 9g2hj5** [comment]
https://user-images.githubusercontent.com/35235868/207745517-0fc8746c-ee19-4fac-a709-cf0f47e61a28.mp4

**Comment by 9g2hj5** [comment]
https://user-images.githubusercontent.com/35235868/207745683-dc6dc1a2-3276-40db-94df-5fc5551dca70.mp4

**Comment by 9g2hj5** [comment]
It wouldn't let me upload as one video so made it 2.

**Comment by photopea** [comment]
I have made the Camera Raw filter 25% faster. Also, since your image on screen is  zoomed out to e.g. 800x600 screen pixels, it is applied only to this small image. If you zoom in, it will be recomputed for the new zoom, up to the original resolution (which is still slow).

For the Filter gallery, it is true, that some filters take up to 1 second to process a million pixels (so 18 seconds for 18 MPx). E.g. Colored Pencil is slow, Film Grain is fast. 

I tried to apply these filters to large photos in Adobe Photoshop, and they are equally slow (Colored Pencil takes 10 seconds for 18 MPx). I dont think they can be made faster.
