### ISSUE TITLE
Can't open files

### ISSUE THREAD

**Issue by TerrorTerror13** [photopea/photopea#5177]
Lately, when I attempt to open pics in Photopea, I get the following error: "www.photopea.com can't open files in this folder because it contains system files."
What has happened?

<img width="461" alt="Screen Shot 2022-12-14 at 3 08 11 PM" src="https://user-images.githubusercontent.com/105249058/207735249-486b9b81-e6ce-4b27-8eb9-78965e22490c.png">

**Comment by TerrorTerror13** [comment]
I have tried all of these suggestions and still no luck.
https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by photopea** [comment]
Is it happening on Mac OS? What OS are you using?

**Comment by TerrorTerror13** [comment]
I'm using Chrome browser on an iMac. This just started happening lately.
I've tried turning off all extensions with no luck.

**Comment by photopea** [comment]
From what folder are you loading files? Did you try to open them from a different folder?

**Comment by TerrorTerror13** [comment]
omg. that totally fixed it! i've been opening the file from a folder on my
desktop. i moved the folder off of there and now it works.

THANK YOU!

**Comment by photopea** [comment]
okay :)

**Comment by photopea** [comment]
okay :) So you probably have system files in your "desktop" folder, just delete these files and it should probably work, I guess.

**Comment by photopea** [comment]
Turns out, it is happening on purpose, because the developers of Chrome think it is a good idea to limit you that way (not let you access the Downloads, Documents, Desktop etc.). They are protecting you from evil websites like Photopea, which migh try to get access to your downloaded files (even if you explicitly allow it).

https://github.com/photopea/photopea/issues/5261
