### ISSUE TITLE
Photopea

### ISSUE THREAD

**Issue by D8N11** [photopea/photopea#5282]
when opening some .png files an error message pops up saying that the file is unable to be opened as it contains system files.. Happens on multiple peoples computers

**Comment by D8N11** [comment]
> Man, @photopea , it sure seems like this issue has been asked about 10 times in the last two days. I bet their teacher told them all to open tickets. 😆

So you are unaware of any fix to this?

**Comment by camoody1** [comment]
I'm not the developer. You'll have to wait for him to chime in. I've just seen the same question asked multiple times in the last couple of days. From the discussions I've seen, it seems to be a limitation of the Chrome browser and how Google determines which folders are allowed to be accessed by your web browser. It doesn't allow certain folders to be used. Try creating a folder directly on your C:\ drive and opening your PNGs from there.

But, again, I'm not the developer, just another interested Photopea user.

**Comment by photopea** [comment]
What operating system and a web browser do you use? Did you try to do it in the Incognito mode?

**Comment by NikRowlands** [comment]
We are having the same issue at our school. We are using windows 10 and Google Chrome where incognitio mode is disabled.
It seems to work if you use a mapped network drive but if you use one of the quick access folders like Documents then it will fail with the error in the OP. Below is a picture and it will fail on the top location path but work on the bottom path.

![unnamed](https://user-images.githubusercontent.com/123077263/213434231-28565943-e2ce-4221-b1d4-33f61d762cfa.png)

**Comment by D8N11** [comment]
> What operating system and a web browser do you use? Did you try to do it in the Incognito mode?

Google chrome and yes I have, is it still the same result

**Comment by NikRowlands** [comment]
I think it could be a escape error for use anything that has \\ seems to causes the error both directories above are the same location but ones in the network address and the other is the drive address. so the permissions are the same.

**Comment by photopea** [comment]
Are you using File - Open to load files? I made a fix yesterday, do you still have this problem?

**Comment by NikRowlands** [comment]
Yes we are still having problems when using file open 

as long as we dont drag & drop,  or file open or try save to the \\... directory it works fine 

we have not had this issue until last week.

**Comment by photopea** [comment]
@tomayac Do you know how Google Chrome works? Does \<input type="file"\> have identical restrictions as showOpenFilePicker() ? I have replaced the showOpenFilePicker() with \<input\> , but a person above claims that it still does not work.

**Comment by tomayac** [comment]
File inputs have no such constraints. I wonder if this user could share a screencast of what they do. Really curious.

**Comment by NikRowlands** [comment]
> Please, could you record a video of an error, which is 10 - 30 seconds? Start by opening [www.Photopea.com](http://www.Photopea.com) . Since many people are commenting here, I got confused what exactly is happening in whose case.

This is the video you requested along with how we get around it.

https://user-images.githubusercontent.com/123077263/213479502-f33e8bc0-4fb3-4bd8-8b87-610f501f16d4.mp4

I noticed you changed the save. now when trying to save it makes a new copy for every save rather than over right the current one they are working on. This wasn't an issue previously and can you put it back to how it was?

https://user-images.githubusercontent.com/123077263/213478324-ffe9a4dd-4116-443c-bf47-ac6313856ccf.mp4

Thanks for your help.

**Comment by photopea** [comment]
@tomayac So the person was drag-and-dropping a file, which does not use \<input type="file\>, but uses getAsFileSystemHandle() 

@NikRowlands We can not "make it work like before", because your web browser does not work like before. You (and billions of other people) have updated their browser to a new version, which works differently than it did a week ago. You would have to switch to the old version of Chrome / Edge to see it work as before.

**Comment by photopea** [comment]
I have taken back all the changes that I made in the last two days. Photopea looks just as it looked a week ago.

If you want it to work as it worked a week ago, just switch to the older version of your browser. Do not use the latest version of Chrome, which does not allow websites to open your files (probably in order to protect you from these websites).

**Comment by tomayac** [comment]
Thanks for creating the screencasts in https://github.com/photopea/photopea/issues/5282#issuecomment-1397130170, @NikRowlands! I'm forwarding them to our Storage team to take a look. Appreciate the effort to get this problem resolved.

**Comment by NikRowlands** [comment]
> Thanks for creating the screencasts in [#5282 (comment)](https://github.com/photopea/photopea/issues/5282#issuecomment-1397130170), @NikRowlands! I'm forwarding them to our Storage team to take a look. Appreciate the effort to get this problem resolved.

No probs , tbf the work around is easy enough to do .

**Comment by photopea** [comment]
@tomayac in the long-term, will there be a way to let users drag-and-drop files from any folder to Photopea? There are so many people complaining and I dont know what to tell them https://www.reddit.com/r/photopea/comments/10ja2qy/i_cant_send_minecraft_screenshots_to_photopea/

**Comment by NikRowlands** [comment]
> @tomayac in the long-term, will there be a way (an API) in Chrome to let users drag-and-drop files from any folder to Photopea? There are so many people complaining and I dont know what to tell them https://www.reddit.com/r/photopea/comments/10ja2qy/i_cant_send_minecraft_screenshots_to_photopea/

Tbf , now I have found a way round it by ensuring I am using the drive letter rather than quick access. I’m happy with it , it’s not difficult to use the work around.

maybe add a video to the pop up that shows people the work around would reduce complaints.

hope this helps

**Comment by photopea** [comment]
@lakelands we can not do anything about it. If your browser decides to not let you open any website at all, there is also nothing we can do abou tit.
