### ISSUE TITLE
Impossible to save project :(

### ISSUE THREAD

**Issue by DariuszAlbert** [photopea/photopea#5291]
It is not possible to save project neither as .psd nor as any other format :( 
All is lost ...

**Comment by MichalSZZ** [comment]
@DariuszAlbert  how big is your project in px and how many layers do you have? 
Have you closed the Photopea window or you can still do something in your project?
Anything else works and only saving/exporting doesn't work? Maybe try to save it in a different place than your hard drive (menu Save more - and use a different place on your hard drive or cloud PeaDrive)

**Comment by DariuszAlbert** [comment]
Thanks for advices! It was unfortunaltely not possible to save enywhere else because the all save windows were not showing up at all :( were completetly dead... every other function worked fine... I think it could be some browser issue - I have been using Brave. I've rebuild my project in Chrome and everythink works perfect... for now :)
Once more thank you!

**Comment by photopea** [comment]
https://twitter.com/photopeacom/status/1522687569833738248

**Comment by MichalSZZ** [comment]
@DariuszAlbert I see that many people have problems with Brave. I am using Photopea on Chrome (without any extensions) from the beginning (since 4-5 years with my Photopea experiences) and don't have any strange situations with Photopea functionality.

But my first browser is FF with some extensions. I think Brave is the worst solution for using Photopea. Try to use Chrome or Edge and its PWA version of Photopea - https://www.youtube.com/watch?v=9AVnTrBk0BU
