### ISSUE TITLE
[Feature request]  Select multiple words in a single text layer for mass editing

### ISSUE THREAD

**Issue by Handlicka18** [photopea/photopea#5298]
Hello,

is it possible add feature to select multiple words in a single text layer to mass edit it (for example change the color of all selected words or change font of these words etc.)? Like in Windows - holding CTRL and selecting multiple words/text across paragraph...I don´t know if Photoshop has it but it would be handy.

**Comment by photopea** [comment]
I have never heard of any text editing environment, that allows selecting / highlighting more than one interval of text. Even here in a web browser, I try holding Ctrl etc, but I can not select two different parts of your post at the same time. I don't think any program has such a feature.

So yes, I think it can be implemented, but since nobody expects such feature to exist, nobody will probably use it (except of you) :(

**Comment by Handlicka18** [comment]
Windows has this feature:

https://support.microsoft.com/en-us/topic/how-to-select-items-that-are-not-next-to-each-other-8b9c1be9-cca3-935a-7cbf-94403aa48d2e

I use it in Office and other programs too...

**Comment by photopea** [comment]
That is interesting! What other programs have it? 

The fact is that you are the first person in 10 years of Photopea who asks for it.

**Comment by camoody1** [comment]
Microsoft Word has this capability, too.

**Comment by Handlicka18** [comment]
Firefox has this feature too (I don´t know about other web browsers):

![obrazek](https://user-images.githubusercontent.com/123298194/213985143-3f6063c4-728e-4e37-81e3-3dc05eed60d8.png)

**Comment by photopea** [comment]
I can not implement it now, but if more people ask, I will consider it.

It could be better, if you could define several text styles in Photopea (combinations of a font / size / color / ...), and after selecting text, you just click one of the styles to apply it to your text

**Comment by camoody1** [comment]
Yeah, I could see where a "Font Style" would be just as helpful as a Layer Style or even Brush Style.
