### ISSUE TITLE
More SVG problems

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#5316]
While testing my new Flags & Countries plugin. I encountered potential problems with loading SVG files of some flags or emblems:
Screenshot:
![image](https://user-images.githubusercontent.com/6370548/215187663-8870584c-4e16-44b0-a10f-a9aa6f349970.png)
1.) Problem with stars in flags of Vietnam,Pakistan or Tuvalu - there is hole in the middle of star
https://upload.wikimedia.org/wikipedia/commons/2/21/Flag_of_Vietnam.svg
https://upload.wikimedia.org/wikipedia/commons/3/32/Flag_of_Pakistan.svg
https://upload.wikimedia.org/wikipedia/commons/3/38/Flag_of_Tuvalu.svg
2.) Emblem of Croatia is covered with black color
https://upload.wikimedia.org/wikipedia/commons/c/c9/Coat_of_arms_of_Croatia.svg
3.) Emblem of Czech Republic is not entirely visible (when tried on my computer) and also when I tried on my tablet it did not load at all with message "Error. Please, send your file to support@photopea.com" and we will solve it."
https://upload.wikimedia.org/wikipedia/commons/e/ed/Coat_of_arms_of_the_Czech_Republic.svg
Screenshot from tablet:
![image](https://user-images.githubusercontent.com/6370548/215189899-075586e2-0a3b-418f-8645-7acb165dd207.png)

**Comment by camoody1** [comment]
Nice plugin

**Comment by photopea** [comment]
Are you able to draw a vector star in Adobe Photoshop, which has five points?

**Comment by photopea** [comment]
1) PSD files have only an "even-odd" fill mode, they do not support "nonzero", see https://blog.ivank.net/how-vector-graphics-work.html  . That is why it is the best to avoid self-intersecting paths.

2) The flag is filled with a vector pattern, PSD has no analogy for it.

3) I have fixed the cropping issue. Your SVG is rendered at 4000x5500 pixels, it has 447 layers, so I think you run out of RAM on your tablet.

All these issues will be fixed with our new vector editor.
