### ISSUE TITLE
Feature Request: "select subject" and "select and  mask" button

### ISSUE THREAD

**Issue by tenkafubu** [photopea/photopea#5326]
I would like to see this feature implemented in photopea.
Can you add something like Photoshop's "select subject" and "select and  mask" button to the options bar?

**Comment by camoody1** [comment]
Would this function any differently from the current "Select -> Remove BG" option?

**Comment by photopea** [comment]
I have added the button "Select Subject" to the Magic Wand, Quick Selection and Object Selection. Unlike Select - Remove BG, this button produces a selection.

I think our analogy to "Select and Mask" is "Refine Edge" or "Magic Cut". Do you think we should rename the "Refine Edge" to "Select and Mask", so that users of Photoshop know what it is?

**Comment by tenkafubu** [comment]
Thank you so much for the swift response. 
I really appreciate it.
Regarding the latter, I think it's better to change  "Select and Mask".

**Comment by photopea** [comment]
Sorry, I forgot to update Photopea. The "Select Subject" button should be there now.

**Comment by camoody1** [comment]
> Sorry, I forgot to update Photopea. The "Select Subject" button should be there now.

I still do not see this new tool where you say it should be. 🤔

**Comment by photopea** [comment]
It is here.

![image](https://user-images.githubusercontent.com/15955558/216276497-64934591-1f89-4836-875e-e085667dbb6f.png)
