### ISSUE TITLE
installing or adding font files

### ISSUE THREAD

**Issue by vijay544** [photopea/photopea#533]
can i add my font files to get the required result. ? or should i use only available fonts ?
i am willing to create and pay the money to do this. or is it possible to use the free version to achieve this?

**Comment by photopea** [comment]
Hi Vijay. At the moment, you should load your fonts manually into Photopea (File - Open, choose TTF or OTF files, Open). Then, these fonts would be added to the end of the font list.

People often use commercial fonts (such as Arial or Helvetica) and we can not provide them in Photopea. And since Photopea is just a website, it does not have a direct access to fonts installed in your device (as Photoshop and Sketch have).
