### ISSUE TITLE
Feature Request: Select color mode when creating a new file

### ISSUE THREAD

**Issue by tenkafubu** [photopea/photopea#5360]
I would like to be able to select a color mode such as RGB, CMYK, etc. when creating a new document , just like in photoshop.

![color_mode](https://user-images.githubusercontent.com/124027046/219456527-9b995ea6-fe65-4743-9030-ad979817bfa3.JPG)

**Comment by camoody1** [comment]
So, you want the option added to the New Project screen instead of just switching to CMYK mode under Image -> Mode as soon as you start a new project?

I would think a more beneficial change would be to add a new section under Edit -> Preferences to allow users to set a default color space mode, either RBG or CMYK.

**Comment by tenkafubu** [comment]
Great if you can do both.

**Comment by photopea** [comment]
The color mode only tells you how many color channels should you have (1,2,3,4,5, ...). Currently, Photopea supports 3 channels (often called RGB) or 4 channels (often called CMYK). Note, that it does not tell anything about what will the colors look like. The look totally depends on a color profile / color space, you need a specific ICC file which describes the relation between a number of a color (3 or 4 numbers) and how it looks like.

**Comment by photopea** [comment]
You can simply switch to Image - Mode - CMYK right after creating your document.
