### ISSUE TITLE
Don't show keyboard 

### ISSUE THREAD

**Issue by Abeelme** [photopea/photopea#5361]
Hello
Can you please not show the keyboard when clicking on the menus
It can be displayed when entering the value
Another thing, if it is possible, I know that it is possible in the Android system. When entering numerical values, the entire keyboard does not appear, only the numbers.
![Screenshot_20230211_235602_Kiwi Browser](https://user-images.githubusercontent.com/44150697/218284778-e1ef1263-4351-4960-8510-52203471dc8d.jpg)

**Comment by camoody1** [comment]
> When entering numerical values, the entire keyboard does not appear, only the numbers.
Oh, this would be fantastic for us phone users. If the entry field only allows numeric entry, only show a number pad. Nice idea if possible.

**Comment by photopea** [comment]
But many people want to enter a number right after they start the gaussian blur. You can click anywhere to hide the keyboard. Am I right?

**Comment by Abeelme** [comment]
I agree with you, but it is not difficult if you use the keyboard
It's annoying when you're using a tablet and every time the keyboard pops up
Anyway, I found a solution to this problem, which is to use a s pen feature "s pen to text" no more keyboard pop up

**Comment by camoody1** [comment]
> But many people want to enter a number right after they start the gaussian blur. You can click anywhere to hide the keyboard. Am I right?

For PC users, you're absolutely right. They would want one of the fields to be automatically active for immediate number entry. But for phone and small tablet users, opening a new menu often results in half of your screen immediately disappearing behind pop-up keyboard. It's not something you'd even think about unless you were using a smaller device without a keyboard.

Ideally, PC users would have a field immediately active, while non-keyboard users would not. I doubt you want to program the gui down to that level, though. But if you could make only a numeric keyboard pop-up instead of a full keyboard, that would probably help quite a bit, too.

**Comment by photopea** [comment]
I have fixed it.

Photopea will focus at the text field (and a browser will show a keyboard if a device has no physical keyboard) only when the display resolution is big enough (both width and height bigger than 500 pixels).
