### ISSUE TITLE
all pen tools

### ISSUE THREAD

**Issue by TheRadicalDreamer** [photopea/photopea#5536]
![image](https://user-images.githubusercontent.com/11801254/232087573-4c857b14-608a-4864-b4a6-1e24ac3b17a1.png)

This is from photoshop.

I know those features can be done with key combinations, but it is good to have them as well :)

**Comment by camoody1** [comment]
Especially helpful to those using tablets with limited keyboard in the app.

**Comment by camoody1** [comment]
If you DO apply add these additional pen tools, would you be able to modify the cursor to show the actual tool being used similar to what Photoshop does? I don't really think I've seen many instances of you changing the cursor for different tools in Photopea, but it would be especially useful in the case of all these pen options. The other tool I specifically know PS changes the curser for is the eyedropper tool.

Of course, it could just be that you don't have cursor icons to match each of these tools. And, sadly, I'm no artist. Maybe we could get AI to make us some if you want to make the code changes. 😆

**Comment by photopea** [comment]
I think I have implemented it. There are three new tools. I also implemented the icons.

I am not sure if I have implemented all "modes" of these new tools, so let me know if anything is missing.

**Comment by TheRadicalDreamer** [comment]
great!

you also implemented the cursor icons!

**Comment by camoody1** [comment]
I could be wrong, but shouldn't I be able to delete handle lines by dragging them into their associated anchor point using the Convert Point tool? Currently, if I use that tool on a corner anchor point, the anchor immediately turns into a smooth anchor and I can drag the handle lines around to make a curve. But if I use that same tool on an already smooth anchor, nothing happens. Should both handles disappear when I convert a smooth anchor to a corner anchor? Similarly, if I use the convert point tool on an existing handle of a smooth anchor, I can move that handle independently (converting the smooth anchor to a corner anchor), but I am unable to fully delete that handle. I _believe_ I should be able to drag that handle into the anchor and have it disappear. Or, at least there should be SOME way to make them disappear. Yes? I don't have Photoshop, so I can't test exactly how it works there.

**Comment by camoody1** [comment]
@photopea So there's no way to remove the handles from an anchor once you've created them? That seems weird.🤷🏽‍♂️

**Comment by TheRadicalDreamer** [comment]
Double click i believe

**Comment by TheRadicalDreamer** [comment]
https://community.adobe.com/t5/photoshop-ecosystem-discussions/delete-just-one-handle-from-anchor-point/m-p/4766956?profile.language=es

![image](https://github.com/photopea/photopea/assets/11801254/c7200fe7-6c44-49fb-a0a7-b8449e46bb81)

Yes, i believe there is a feature missing @photopea .

Check that photoshop forum

**Comment by camoody1** [comment]
@photopea Okay, I just confirmed this in Photoshop...

When using the Convert Point Tool, if you click on a Smooth Anchor, both handles should disappear, and the anchor should immediately turn into a Corner Anchor. If you click a Corner Anchor and drag, both handles reappear. So, for sure, that change should be made in Photopea to coincide with PS. I still need to check other functionality.

**Comment by camoody1** [comment]
Also confirmed in Photoshop...

When using the Convert Point Tool, if you hold the ALT-key and then left click on a Smooth Anchor with two handles, one of those handles should disappear.

**Comment by camoody1** [comment]
@photopea I went ahead and made a short-ish video showing how the Convert Point Tool works in Photoshop vs how it works in Photopea. I figured it would be a lot easier to show you what I'm talking about instead of trying to describe it. Please let me know if you have any questions.
https://youtu.be/qJFCzixOrIo

**Comment by photopea** [comment]
I think it is fixed now

**Comment by camoody1** [comment]
@photopea Good evening (my time) sir...

I made a follow-up video to show you a couple of things that are still outstanding to be changed if you want Photopea to match the functionality of Photoshop with the Convert Point Tool. I apologize if it's a bit confusing at some points. I got a bit mixed up bouncing back and forth between PS and PP. Also, there's two parts to a the video, because I forgot one of the items I wanted to cover in the first part. Please let me know if you need any clarification. Thank you for your continuous efforts to enhance Photopea.

https://youtu.be/qJFCzixOrIo

**Comment by photopea** [comment]
Ok, I think I have implemented all three features that you have asked for:

- Click the "middle point" to remove both handles (make a sharp corner)
- Alt+click the "middle point" to remove just the "next handle".
- Click the part of the curve in between points to highlight adjacent handles

**Comment by camoody1** [comment]
> Ok, I think I have implemented all three features that you have asked for:
> 
> * Click the "middle point" to remove both handles (make a sharp corner)
> * Alt+click the "middle point" to remove just the "next handle".
> * Click the part of the curve in between points to highlight adjacent handles

The only item that works slightly differently than Photoshop now is the last item. In Photopea now, instead of activating just the two adjacent handles on a segment, it's activating the next handle in front of the segment and previous **three** handles behind it. This is still way better than not activating any handles, it's just not exactly the same as PS. Not a big deal if you want to leave it. I won't tell anyone. 😊

Thanks for sticking with me on these Pen changes and getting them squared away.

**Comment by TheRadicalDreamer** [comment]
it will be great if that minor fix is done 😃

> The only item that works slightly differently than Photoshop now is the last item. In Photopea now, instead of activating just the two adjacent handles on a segment, it's activating the next handle in front of the segment and previous **three** handles behind it.
