### ISSUE TITLE
bottom, right and channel information lost for Color Fill layers

### ISSUE THREAD

**Issue by daaaaa** [photopea/photopea#5558]
I have a `.psd` file created in Photoshop containing a Color Fill layer.
When I parse this file the corresponding [Layer Record](https://www.adobe.com/devnet-apps/photoshop/fileformatashtml/#50577409_13084) has the `bottom` and `right` data with a value different from `0`.
The same happens for the `Channel information`.

If I open the file with Photopea and save it after a small change, the values of `bottom` and `right` are lost (probably default to `0`) and the same happens for the `Channel information`.

Is there any chance to keep the behaviour of these information consistent between Photoshop and Photopea?
Thanks for your support!

**Comment by photopea** [comment]
Just to be clear, you are not reporting a bug in Photopea. If you edit a PSD in Photopea, it will look the same in Photoshop, and vice versa. But I will try to help you anyway.

Vector layers in PSD files do not contain pixel data sometimes (i.e. a rectangle of pixels is 0x0) to make a PSD file smaller. Since this layer contains vector data ("vmsk") and fill data (SoCo, GdFl, PtFl), the pixel data can be easily generated by the software which opens a PSD file. Seems like you were lucky and did not see such a PSD file (made in Photoshop) yet.

**Comment by photopea** [comment]
Photoshop can generate small PSD files, too (with no pixel data for vector layers). You can change it in Photoshop settings. There is an option "maximize compatibility" in Photoshop.
