### ISSUE TITLE
75% size registration phenomenon when placing images

### ISSUE THREAD

**Issue by Charliebaek** [photopea/photopea#5612]
When loading an image, it is loaded at 75% size. I tried it on another computer, wondering if I had touched something wrong, but it was the same, and images that were normally registered at 100% size were registered at 75% size. How to solve this?

**Comment by photopea** [comment]
We changed the method of inserting images yesterday (to make it more like Adobe Photoshop).

We use physical units now (instead of pixels).  So if you are inserting a 5x5 inch image into a 10x10 inch image, it will have half the widht and height (no matter how many pixels there are).

So if both of your images have the same size in pixels, but one is inserted as "smaller", it probably has a different DPI.
