### ISSUE TITLE
Document/Release .clip File Handling

### ISSUE THREAD

**Issue by Efruit** [photopea/photopea#5626]
As far as I'm aware, Photopea is the only project that has successfully decoded .clip files.

Other projects would greatly benefit from some documentation about the .clip format's internal structure, or (better yet) a library that implements it like UPNG, UTIF, etc.

**Comment by camoody1** [comment]
> We can also open Krita, Affinity Photo, Paint.NET, Figma, Pixlr, CorelDraw, Adobe Illustrator, Adobe InDesign and other formats, which can not be opened in any software other than the "original one".

My man, Ivan, out here bragging about his skills. 😆

**Comment by Efruit** [comment]
All true, and all impressive (though .kra is a bit of a stretch, since the code is out in the open 😉)

While I'm sure numerous projects would be interested in the details of the other formats, my interest rests solely in the .clip format. (But I surely wouldn't complain about the others getting unofficial specs written...)

**Comment by photopea** [comment]
Since these features are in a way unique for Photopea, and they are the main reason why many people use our service, I am afraid that if we disclosed our know-how, we would only fuel the competition, and it could damage our capability to make money and keep the project alive.

But we published our own CDR specification: https://github.com/photopea/CDR-specification
