### ISSUE TITLE
Pen tool path not working

### ISSUE THREAD

**Issue by wtnvi0** [photopea/photopea#5645]
Whenever I use the pen tool and change the mode from shape to path, The pen tool doesnt work anymore I dont know what do

**Comment by camoody1** [comment]
I had this same problem earlier tonight while testing the new changes to the pen tool. I thought it was just weird I had done.

In order to get mine working again, I had to start to draw something as a Shape and then switch back to Path and it worked again. Not sure if that will work for you, too. Good luck!

**Comment by Krakxen** [comment]
How do i make it work

**Comment by photopea** [comment]
I am soooo sorry guys, it should be fixed now.

**Comment by Sulhnafein** [comment]
It's still an issue that i'm having when i'm pixel arting.

**Comment by photopea** [comment]
Please, tell us what should we do to see the issue ourselves. We can fix only what we can see.

**Comment by Sulhnafein** [comment]
I just created my projects with 8 bit when its 16 bit pen 3 or less pixel radius pen tool is un use able.

**Comment by photopea** [comment]
Could you please make a new issue and write a proper description?
