### ISSUE TITLE
Could you please add the ability to outline strings?

### ISSUE THREAD

**Issue by taiko-tenter-morita** [photopea/photopea#5696]
Could you please add the ability to outline strings?

**Comment by camoody1** [comment]
Pardon my lack of understanding, but what exactly does this mean?

**Comment by taiko-tenter-morita** [comment]
Sorry, I'm Jamanese.
Because I can't use correct english.

I would like to outline text, similar to the functionality of "Ctrl + Shift + O" in Adobe Illustrator.
The reason is that when I save data in PSD format and pass it on to others, the font data is not preserved.

**Comment by camoody1** [comment]
Oh, I understand, now. In Adobe Illustrator, CTRL-SHIFT-O turns the outline of text into a Path. He won't be able to make the exact same shortcut because CTRL-SHIFT-O in most web browsers is used to open the Favorites or Bookmarks folder. Perhaps he can do something else for you. 🤷🏽‍♂️

As a fast workaround, try this...
1. Type your text in Photopea.
2. Open the Layers panel.
3. While holding your CTRL key, left-click the Text layer in the Layers panel. This will create a selection around the outline of your text.
4. Now, open the Paths panel.
5. At the bottom of the Paths panel, click the "Selection to Path" button. This will create a new Path for you around the outline of your text.

If you then want to Stroke that Path...
6. Select your desired stroke color as your primary brush color.
7. Set your Brush tool to your desired Stroke thickness.
8. Change to your Path Tool, right-click on the Path you have created and choose Stroke. You could also choose Fill. This should change your Text into vector shapes that can be shared with other people.

Good luck!

**Comment by taiko-tenter-morita** [comment]
Thank you for your help.

I can do it by shaping it.

**Comment by MichalSZZ** [comment]
Why you can't use "convert to shape" by right-clicking on the layer's name?
![obraz](https://github.com/photopea/photopea/assets/38118273/31b51cc0-06ff-4d0f-af35-98cec632d756)
that will create a perfect shape outline (path) from your text. See:
![obraz](https://github.com/photopea/photopea/assets/38118273/b3b0f1f4-8e32-49e0-9f76-2313cd79636f)
![obraz](https://github.com/photopea/photopea/assets/38118273/36aa2ff6-3bbf-4f56-8fe0-559f3b1fd654)

**Comment by camoody1** [comment]
@MichalSZZ Well, that seems like a MUCH better idea.
![bitmoji](https://sdk.bitmoji.com/render/panel/a1fa7d18-fdbb-4fbe-973a-1ae08941ec34-33290fb4-ad75-46e6-8062-305f1f5378d9-v1.png?transparent=1&palette=1&width=246)
