### ISSUE TITLE
Firefox: Cannot copy to OS clipboard

### ISSUE THREAD

**Issue by pattlebass** [photopea/photopea#5720]
Browser: Firefox 114.0
OS: Windows 11

On Firefox, when you try to copy a layer or use Copy Merged, it doesn't get added to the OS clipboard, so you can't past it outside Photopea. It seems to work just fine on MS Edge.

**Comment by photopea** [comment]
This is simply because Firefox does not allow websites to put images into a clipboard, see https://caniuse.com/async-clipboard. The only two browsers which miss this feature is Internet Explorer and Mozilla Firefox.

https://bugzilla.mozilla.org/show_bug.cgi?id=1619251#c2

I remember speaking with someone from Firefox many years ago, and it sounded like they actually hate websites. If a website was allowed to put images into a clipboard, or play sound, or go fullscreen, that would made them feel insecure and "not in control". So I gave up asking Firefox to improve.

You can try to convince them, or switch to a better web browser.

**Comment by pattlebass** [comment]
There seems to be at least [_some_](https://bugzilla.mozilla.org/show_bug.cgi?id=1809106) intent to add this to Nightly. Better late than never I guess.

For anyone else finding this issue, you can enable this flag in `about:config`: `dom.events.asyncClipboard.clipboardItem`. It'll make everything work.

**Comment by steponmepls** [comment]
> For anyone else finding this issue, you can enable this flag in `about:config`: `dom.events.asyncClipboard.clipboardItem`. It'll make everything work.

Shame this also adds an extra step when trying to paste things into the canvas. An extra popup menu shows up that forces me to click on `Paste` to actually paste what I want. Not to mention the menu shows randomly when working on a project

![image](https://github.com/photopea/photopea/assets/63500907/d128fc78-ed2e-4ff7-af55-29655de9b309)

**Comment by photopea** [comment]
did you try to get in touch with Firefox and ask them why dont they enable it by default?

**Comment by steponmepls** [comment]
>enable it by default?

Even if that were the case, it's still annoying/kinda broken so I would rather have the feature turned off so it doesn't get in the way while I work on a project. I just wanted to report what I noticed in case it was just an issue on my end
