### ISSUE TITLE
Some PSDs don't open as they should

### ISSUE THREAD

**Issue by EllaDarling** [photopea/photopea#575]
I get most of my PSDs from Tumblr, which means they often come along with examples of how the PSD looks on images. This happens quite often, when the PSD that opens does NOT look like the example. I've come to learn that it's Photopea, rather than a mishap on the PSD distributor, because they work perfectly fine on my friends' PS (Adobe). Usually they're made much redder and grainier.

**Comment by photopea** [comment]
Hi Ella,
can you send us one of your PSDs to support@photopea.com ?

**Comment by EllaDarling** [comment]
Sent!

**Comment by photopea** [comment]
Hi, are you sure? I did not receive anything :(

**Comment by EllaDarling** [comment]
Sent it again.

**Comment by photopea** [comment]
ok got it, thanks!

**Comment by EllaDarling** [comment]
Any luck? :)

**Comment by photopea** [comment]
Hi, I think the problem is in the Vibrance adjustment. We do not know, how Vibrance in Photoshop works, so we could not reproduce the same effect in Photopea (our Vibrance works slightly different).

As you combine many adjustments, the difference caused by Vibrance grows, and gives completely different colors at the end. We need a formula for Photoshops Vibrance to be able to fix it :(

BTW. is there any reason why you use like 200 adjustment layers for one image? People usually use 1 to 5 adjustment layers.
