### ISSUE TITLE
Equirectangular viewer/editor

### ISSUE THREAD

**Issue by hgs54371** [photopea/photopea#585]
There are more and more cameras on market that produce equirectangular images since 2016
https://en.wikipedia.org/wiki/List_of_omnidirectional_cameras

A toggle for preview them like the way in google street view without leaving photopea would be good

**Comment by photopea** [comment]
I think we have discussed it before  https://github.com/photopea/photopea/issues/543

Ok, I will keep this issue open, and when the time comes, we will imlement a nice spherical photo editor.

**Comment by hgs54371** [comment]
I've created this video showing how it's implemented in Affinity Photo

[Af.eq.test.mp4.zip](https://github.com/photopea/photopea/files/1866983/Af.eq.test.mp4.zip)

The View controls are in the Tool bar through move tool after entering Live Projection, this is better than PS using panel, 

Layers are distorted manually with Perspective Tool, But the Drag to Pan direction is "Reversed" compared to Google street view, which is counter-intuitive

**Comment by photopea** [comment]
@hgs54371  What if in Affinity Photo, in a equirectangular view, you "rotate" the view without merging a new layer with the layer below? Do all layers move, or only one layer?

**Comment by dirkdesmet** [comment]
Bump - I would also LOVE to see an equirectangular viewer integrated into Photopea, that would be so neat for editing 360 panoramic pictures and it would definitely increase my productivity as a Linux user who only has limited options for graphic tools.

A equirectangular viewer / editor is the only feature of Photoshop that I am missing in Photopea.

A feature to stitch panorama parts together would also be a nice to have; but I can imagine that would be extremely hard to create in javascript and I think it would also ask a lot from the browser on a performance level.
Kolor Autopano Giga was an excellent tool for that (it was available for Linux, Windows, OsX), but [GoPro bought the Kolor company and the project died](https://ivrpa.org/news/gopro-kills-kolor/)...
Such a shame, it was my favorite pano tool to work with by far.

Maybe one day? => I could live with a premium-users-only feature, because I'm a paying customer. :)

**Comment by photopea** [comment]
BTW. we already have a feature for stitching photos: https://www.photopea.com/tuts/stitch-images-together-online/

**Comment by photopea** [comment]
I will close it, as I think such feature is out of the scope of photo editors like Photopea, Photoshop or Gimp.
