### ISSUE TITLE
can't open a raw files

### ISSUE THREAD

**Issue by vsartshop** [photopea/photopea#5853]
Evrytime I want to open a raw file the picture is dark with lines I try many photos and it as not work so far
<img width="1071" alt="Screen Shot 2023-07-12 at 9 25 10 AM" src="https://github.com/photopea/photopea/assets/139375889/8a14255d-2a2f-40f7-9d92-958903d7bccf">

**Comment by photopea** [comment]
could you share your file, so that I can try it myself?

**Comment by vsartshop** [comment]
Any files i am trying isn’t working if its a raw files i have try many
different one
 000_9269.NEF
<https://drive.google.com/file/d/1ARI31vvMgwWcUAaIBTVBMkjfy57AyNzv/view?usp=drive_web>

**Comment by photopea** [comment]
Please, do not send emails to random Github email addresses.

Open https://github.com/photopea/photopea/issues/5853 in your web browser and reply there. 

Is your photo from Nikon Z9? Which of the compression options do you use when taking Photos? See https://onlinemanual.nikonimglib.com/z9/en/15_menu_guide_02_09.html#nef_raw_recording

Since Nikon never released any information on what exactly is inside NEF files, it is very hard for us to discover how they work (unlike the open DNG format used by Pentax, Ricoh, Leica and others).

**Comment by photopea** [comment]
I have to close it as the person did not respond.
