### ISSUE TITLE
Magic Replace not working

### ISSUE THREAD

**Issue by emerputz** [photopea/photopea#5868]
Whenever using magic replace, it is just stuck on loading and not actually doing anything. Usually it will replace my selected area but right now it says "processing" at the top and is not moving

**Comment by camoody1** [comment]
@emerputz Dezgo (the AI processing site for Photopea) is still up and running on their website, so I assume this is an account issue that @photopea will need to handle.

Ivan, I think it would be helpful if you could provide a different message response in the app depending on the result of an API call to Dezgo. I like that you're now leaving "Processing" on the screen until the image has been returned, but I'm assuming in instances like the one being described in this post there is likely some other response being received from the Dezgo servers. Instead of leaving "Processing" on the screen when a call has failed, a different notification that doesn't stay on the user's screen would be helpful.

**Comment by photopea** [comment]
It should be fixed now.

I have added a delay limit of 20 seconds in between calls, to encourage people to improve the selection / the keywords, rather than clicking the "Replace" button blindly many times.

**Comment by xyzzart** [comment]
> It should be fixed now.
> 
> I have added a delay limit of 20 seconds in between calls, to encourage people to improve the selection / the keywords, rather than clicking the "Replace" button blindly many times.

that is pretty wise decision,but for those who use magic replace tool for editing without specific prompting - 20 is way to long ) its just ruining the whole workflow( but, i think i can get used to it...anyways thnx for providing us that great tool

**Comment by xyzzart** [comment]
> You can use the content-aware fill, which is free.
> 
> You can also pay $0.16 for a whole day of unlimited Magic Replace usage.

how can i do that? there is only premium account option starting with 30 days

**Comment by camoody1** [comment]
> > You can use the content-aware fill, which is free.
> > You can also pay $0.16 for a whole day of unlimited Magic Replace usage.
> 
> how can i do that? there is only premium account option starting with 30 days

He means you can pay for a monthly premium account that basically comes to only $0.16 per day. You can't _actually_ purchase the premium account by the day.

$5.00 per month divided by 30 days per month equals $0.16 per day.

**Comment by photopea** [comment]
Yes, you can have 90 days for $15, that is $.16 per day.
