### ISSUE TITLE
Project Canvas Crashes

### ISSUE THREAD

**Issue by Wanambisix** [photopea/photopea#5872]
Hi, Thanks for the continued good work you are doing with Photopea. When working on a project, there are times that the canvas goes blank. You can see the files on the right side panel, but the project itself is not visible. Then after sometime it goes from blank to white screen. How do I fix this? I use Chrome Browser.

**Comment by Wanambisix** [comment]
My Laptop has 4GB RAM. I do not work on a lot of projects, but while checking Cache I noticed that the browser had 3GB Cache of Photopea. Might this be contributing to maxing out the RAM?

**Comment by photopea** [comment]
yes, 4 GB of RAM might not be enough for certain kind of work. Especially if you have other tabs opened. I have 24 GB of RAM in my laptop.

Can you make it crash on purpose? What exactly do you do when it crashes? I would recommend using smaller resolutions (e.g. 4 million pixels instead of 40 million pixels) and maybe save it often, in case it crashes again.

**Comment by photopea** [comment]
I have to close it, as there was no response.
