### ISSUE TITLE
I can't export 

### ISSUE THREAD

**Issue by TorontoAreaTransit** [photopea/photopea#5912]
issue is pretty self explanatory. I can't export my images

**Comment by camoody1** [comment]
What are you doing? Exactly what steps are you taking to export your image? What happens when you attempt to export an image? Do you get an error message? Does the application freeze? Your issue may be self-explanatory, but you've given no details to assist anyone who might try to help you.

Try the steps on this page and see if it makes any difference for you.
www.photopea.com/tuts/photopea-doesnt-work-what-to-do

**Comment by TorontoAreaTransit** [comment]
Thanks for the link! Turns out it was an extension issue. Ill be looking for the source of the issue and uninstalling it.

**Comment by camoody1** [comment]
@TorontoAreaTransit Glad you were able to find a workaround. It seems browser extensions are more often than not the cause of most Photopea problems. Have a great rest of your week.

**Comment by photopea** [comment]
I think about half of our users use some extensions, and about 5% of our users have extensions which break Photopea to a certain degree (e.g. a "security extension" which does not allow any website to save any file into the computer).

I think there are thousands of people who stopped using Photopea because it did not work, but it did not work because of their extensions :(
