### ISSUE TITLE
Quick selection tool not working

### ISSUE THREAD

**Issue by engcamila79** [photopea/photopea#5928]
The quick selection tool is not working. When I try to select the object, nothing happens.

**Comment by camoody1** [comment]
Well, the Quick Selection is definitely working, otherwise we would see dozens of other users reporting the same problem. 🙂

Can you send us some screenshots or, better yet, a short video showing us exactly what you're doing when you attempt to use the tool? Make sure you're on the correct layer before trying to select an area. And make sure that the Tolerance value isn't set too low in the top toolbar.

**Comment by photopea** [comment]
Could you share a screenshot of what is happening on your screen? Maybe you are using it the wrong way.

**Comment by photopea** [comment]
I have to close it, because the person did not respond.
