### ISSUE TITLE
Layer comps not working properly as expected

### ISSUE THREAD

**Issue by notzeussz** [photopea/photopea#5943]
This has been a recurring issue. I tried to make a layer comp of my main project, and then make a simple change of the background and create a new separate layer comp, then when I try to switch to the previous layer comp that I've just made, it doesn't revert the changes. Here's a video.

https://github.com/photopea/photopea/assets/72874681/d84505d6-f517-451e-8a77-ca3f883039f9

I am surprised no one has discovered this issue yet. Please fix it ASAP. Thanks.

**Comment by camoody1** [comment]
@notzeussz I don't think this works exactly the way you think it does. Read the manual for Layer Comps closely:
https://www.photopea.com/learn/layer-comps

Layer Comps keep track of three "properties" of each layer in them: Visibility, Position and Appearance (opacity, blend mode, layer style). In your sample video, you actually changed the Fill color of a Shape within a layer. That sort of change is not one of these three properties.

If you wanted to keep one Layer Comp for a tan background and another for a green background, you would need to make two separate background layers and make only one of those background layers visible for each Layer Comp.

Alternatively, you could have just ONE all white layer for your background and apply a Layer Effect -> Color Overlay to that layer. Set the Color Overlay to tan for the first Layer Comp and save that, then change the Color Overlay to Green and save that as second Layer Comp. Now, THAT change (because it is an Appearance change) will actually be saved as part of the Layer Comp.

I hope that makes sense. Have a great Sunday!
