### ISSUE TITLE
language

### ISSUE THREAD

**Issue by patserYT** [photopea/photopea#5949]
How fucking dumb is this photopea app i cant change my fucking language to english i dont want to see dutch dumbasses how hard is it to change the language fuck you.

**Comment by camoody1** [comment]
How dumb do you have to be to come asking for help and act the way you do? I'm sure your parents are really proud of the ass you've become. Now, go away you foul-mouth, piece of human garbage. 

More -> Language -> English
If it's not there, it's because you've got some piece of shit browser extension causing you issues.

**Comment by bluep55** [comment]
You could ask an adult to show you how to do it.

![mad-tantrum](https://github.com/photopea/photopea/assets/118609932/432fe892-cef7-4352-8080-8620167e1873)

**Comment by fahad786khan** [comment]
You can change it from More>Language>English
and please don't say bad to photopea

**Comment by photopea** [comment]
we do not respond to requests containing offensive words.
