### ISSUE TITLE
slice tool isn't working properly

### ISSUE THREAD

**Issue by CxryzNFTs** [photopea/photopea#5961]
hey,

the slice function in photopea does not work like photoshop?
i cannot slice evenly like split an image into fourths.

i'm trying to follow this tutorial: https://www.youtube.com/watch?v=VOmGMcHjTv0

any help would be appreciated!

**Comment by camoody1** [comment]
Follow the tutorial video just as shown, but instead of right clicking to get the Divide option, just look up at the top toolbar. There is a button there that reads "Divide". Click that and then select 2 for Horizontal and 2 for Vertical. Then, export as png or jpg. I just did this and it worked for me.

Have a great weekend!

**Comment by CxryzNFTs** [comment]
okay, thank you!

but for some reason, when doing this with gifs, and exporting it as a .GIF, it still remains a static image.

anyone how how i can resolve this?

**Comment by photopea** [comment]
Sorry, we dont support sliced animations at the moment :/
