### ISSUE TITLE
smart object must be rasterized first

### ISSUE THREAD

**Issue by CB17G** [photopea/photopea#5987]
Your Operating System:windows11
Your Web Browser:opera
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. make a new project
3. upload a pic
4. try to use eny tool
5. get a error that says smart object must be rasterized first.(idfk what that means)

**Comment by camoody1** [comment]
Just because you don't understand something doesn't make that thing broken or a bug. All images pasted into Photopea come in as Smart Objects. If you don't know what that means, look it up on Google or YouTube for some helpful information.

You can Rasterize a Smart Object by right clicking on the Smart Object layer in the layers panel and choosing Rasterize.

**Comment by photopea** [comment]
That is the way it should work. It works like this in all programs. I recommend buying a book about Adobe Photoshop and reading it, before using Photoshop or Photopea.
