### ISSUE TITLE
Adverts keep taking focus away from making edits, especially using text. 

### ISSUE THREAD

**Issue by cyclops365** [photopea/photopea#5995]
Your Operating System: W10
Your Web Browser: Edge v116.0.1938.69 
The problem happens in the Incognito Mode, too: Not tried.

**This must be done to see the problem**
1. Go to www.photopea.com
2. Open document and start typing into a text box. 
3. When certain adverts load in on the right, text cannot be typed anymore until you click in the text box. 
4. This is happening every 30 seconds or so. I don't have a problem with adverts on the right, but it seems to be the video adverts that are being shown.

**Comment by photopea** [comment]
I think it could be done by your browser extensions. Could you try this? https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by cyclops365** [comment]
It's the NBA advert that does it. All the "solutions" do nothing.

**Comment by photopea** [comment]
Hi, could you show us a screenshot of that ad, so that we can report it?

**Comment by cyclops365** [comment]
https://gyazo.com/4028c3b7191606d9eafd843f40ba8a82 Here you go
It's loud too.

**Comment by cyclops365** [comment]
![image](https://github.com/photopea/photopea/assets/72573834/57ee0a47-359f-4edf-8a69-c851405996a8)
And this. 

Any with sound is just far too loud and really blasts my headphones off my head. 

Photopea is starting to become unusable these days :(

**Comment by photopea** [comment]
Hi, could you tell me if this still happens? "Bad" ads should be blocked now. Maybe clear your cache before using Photopea.

**Comment by elderMicheal** [comment]
I didn't want to open a new ticket since this exists, but I have also noticed problems with the ads. Whenever they refresh, Photopea hangs until they are done loading, and they steal focus. I have taken the steps suggested and usually run in incognito mode as suggested

I do have extensions, tho. However, I completely removed my adblocker, because I think your program is a good one and understand why you need ads, and it was interfering even when it was paused on Photopea. 

I have zero issues with any of Photopea's functionality (kudos to the dev team!), just the Google ads. I am considering subscribing, which will eliminate the ads and the problem, I'm assuming, but I just wanted to alert someone to the fact that I am experiencing it.

Thank you for your time. I hope this was not the wrong place to say this. I've never commented here before.

**Comment by photopea** [comment]
Could you disable all your browser extensions and use Photopea for a few minutes? Does it still happens? Our ads should never steal any focus.

**Comment by cyclops365** [comment]
Sometime recently too I’m typing in a text box, and a new advert pops up and takes focus away from my typing. So I have to click in the text box to continue.

**Comment by elderMicheal** [comment]
I've been running Photoshop almost constantly lately, as I do a lot of graphics work. I'm still in the evaluation phase, so I keep it open alongside Krita.

I learned that I need to keep Krita (or some other program) open to receive the clipboard from time to time  because the problem with the ads has caused a loss of work a couple of times. Nothing of consequence, as I wouldn't put my work on the line for an evaluation product, but the crash has erased work. I save frequently but... well, not as frequently as I should, I'm sure, but that's on me, not you.

Specifically, I've noticed what I show in this screenshot. The LL Cool J ad covers up the canvas and will break whatever tool you are using at the time, and the tobacco ad seems to hang. I think those are the two culprits, but I wouldn't rule out the code that places the ad block on the page, as I noticed this happening before those ads came into rotation.
![image](https://github.com/photopea/photopea/assets/144031542/1afee092-934e-4f81-8ebb-3d18a10d2e6e)

**Comment by camoody1** [comment]
> I've been running Photopea almost constantly lately, as I do a lot of graphics work.

I assume you mean Photopea. 😊

**Comment by elderMicheal** [comment]
yes lol i corrected it... i had to correct multiple time because autocorrect kept changing it to Photoshop :O

**Comment by photopea** [comment]
Could you please tell us, if it ever happened with all your browser extensions disabled?

**Comment by elderMicheal** [comment]
Yes, it has. I've not only disabled them, but this issue prompted me to review all of my extensions, and I removed all but 5 essential ones. those, I disabled and still had the problems. 

It also seems to be two separate issues. The issue of the "hang" when reloading ads occurs during almost every reload. The issue with the overlay ad seems to be a layout issue specific to that ad.

**Comment by photopea** [comment]
Ok, we are working on it. Could you please try to do it again, and if you see the ad, could you click it and tell us the link which is opened after clicking the ad?

**Comment by elderMicheal** [comment]
Frankly and honestly, the problem is that you have 4 ads running on the right side and they update so frequently they are almost rendering your app useless. I can't use any tool unless I can complete any action faster than the reload time on the ads, and it hitches so badly it jerks the cursor around which makes any attempt at painting a futile effort.

None of this is related to your app. Your app works fine. But the constant update of the ads is breaking your program and breaking the deal with a lot of people, I would bet. I understand you need extensions shut off, but some of the extensions in my browser are necessary for my workflow, and if I can't use them and use your app, your app, unfortunately, will have to be the one I sacrifice.

I'm not to that point yet, tho. I think your team has done an excellent job. As a designer, I understand the need to monetize, but you need to incorporate it better. Given the nature of your app, I would strongly recommend you slow the ads down (way down) and not use any multimedia ads at all. Your program sells itself. You don't need Google ads getting in your way. 

People are talking about your program. I've seen it referred to in many YouTube videos. Don't let AdSense break your good thing.

**Comment by photopea** [comment]
Ads in Photopea should not slow down your computer, or interrupt your work in any way.

Could you maybe record a video of what it looks like? Also, what kind of a computer do you have? Is it old? How fast is your CPU?
