### ISSUE TITLE
Photopea window resizes when logging into account

### ISSUE THREAD

**Issue by EXT-OWL** [photopea/photopea#6024]
Your Operating System: Windows 10
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Use the editor. You have a completely full view. 
3. Log into your account. The right view gets hidden. Even if you resize the monitor it stays out of view. 

![chrome_91Q3oKnox4](https://github.com/photopea/photopea/assets/133682961/19912280-e36e-4f98-993b-2516b614efc3)
![chrome_hvW1sGsJ5W](https://github.com/photopea/photopea/assets/133682961/66dd27bf-3392-4699-a9e4-a5930edb7ece)

**Comment by camoody1** [comment]
I don't see anyone else reporting this issue currently. Please disable all of your browser extensions and try again. If that works, re-enable one extension at a time to figure out which extension is the problem.

**Comment by photopea** [comment]
I think you are using a browser extension, which modifies Photopea. It is probably "ublock origin".

Are you 100% sure it happens in the Incognito? Could you show us a screenshot that is not cut-out (so that we see you are using the Incognito mode). Because extensions are usually disabled in the Incognito mode.
