### ISSUE TITLE
need help in french 

### ISSUE THREAD

**Issue by B2DouX** [photopea/photopea#6027]
bonjour , Jai trouver votre site web et petit app . ces super ,

mes Jai un gros bug qui fait toujours perdre mon édite.

voici une image du bug  je faite juste réduite l'app en bas dans Win. et remets en haut et plus rien qui affiche 

![bug](https://github.com/photopea/photopea/assets/144631641/5838af6e-b384-4961-bcee-3b8307f1b1bc)

je ne sais pas si ces un bug connue.

**Comment by photopea** [comment]
Hi, so you can not open any file in www.Photopea.com ? Could you try this: https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by TheRadicalDreamer** [comment]
Bonjour, vous pouvez essayer d'ouvrir Photopea depuis le navigateur, mais en mode navigation privée. De cette façon, nous pouvons voir si le problème/bug est causé par une extension que vous avez installée dans le navigateur.

Si vous voyez toujours le bug, veuillez réécrire ici.

**Comment by B2DouX** [comment]
bonjours merci davoir repondu ,

ça le fait dans l'extension qu' on peut télécharger sur votre site web . et
parfois cela fait aussi sur chrome

**Comment by photopea** [comment]
Sorry, I have to close it, as this place is only for English discussions :(

**Comment by B2DouX** [comment]
you wrote to me in French. but not serious . if your app bugs teops i will
stop using it.

Le jeu. 28 sept. 2023, 10 h 06, Photopea ***@***.***> a
écrit :

**Comment by TheRadicalDreamer** [comment]
@B2DouX I wrote you in french, not Photopea. I am just a user like you.
I was trying to help, indicating that you should disable all extensions of the chrome browser, then enter in chrome with the incognito mode and try again and see if the bug is still there. Just like Photopea indicates in its documentation: https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/


----

@B2DouX Je vous ai écrit en français, pas en Photopea. Je ne suis qu'un utilisateur comme toi. J'essayais de vous aider en indiquant que vous devez désactiver toutes les extensions du navigateur Chrome, puis entrer Chrome en mode navigation privée et réessayer pour voir si l'erreur persiste. Comme Photopea l'indique dans sa documentation: https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by TheRadicalDreamer** [comment]
Sorry @photopea for not speaking in english as well

**Comment by B2DouX** [comment]
a ok
Cest parce-que je reçois les messages  par mail
