### ISSUE TITLE
Reposition loading notice to prevent obscuring toolbar

### ISSUE THREAD

**Issue by rcarlislehealy** [photopea/photopea#6041]
![Screenshot 2023-09-14 122255](https://github.com/photopea/photopea/assets/144952093/3339b192-8e9a-4504-a393-c95474f30d87)

Hello! I have a general suggestion. Is there any way the Loading and Saving notice could be repositioned in some way so that we could continue to access the features on the toolbar behind it?

Sorry if this question has already been addressed. Thank you so much for developing Photopea!

**Comment by photopea** [comment]
This message should appear only for a fraction of a second. It should definitely not stay there for a long time.

How long does it stay there? What exactly are you loading?

**Comment by klaslod** [comment]
shut up no one asked you melt

**Comment by klaslod** [comment]
like actually go away

**Comment by tuconeves** [comment]
Would be a great change. We cannot edit the project on those few seconds, most of the the times the message is read even faster. If not possible to move the UI, would be possible to add a 'close' button?

**Comment by camoody1** [comment]
What actually drives me a bit crazy is when I first open Photopea and I have wait as 10 different messages slowly scroll up my screen announcing everything its loading from my Preferences. Fonts, Gradients, Brushes, Styles... and the messages make it so I can't click on anything to start working. It's just a wasted 10 seconds. 🤷🏽‍♂️

**Comment by photopea** [comment]
What should I do to see it happen? Is it in Edit - Local Storage?

**Comment by photopea** [comment]
The "Loading" message should never appear for more than 1 - 2 seconds. If you can make it appear for a longer period of time, how do you do it?

**Comment by camoody1** [comment]
> The "Loading" message should never appear for more than 1 - 2 seconds. If you can make it appear for a longer period of time, how do you do it?

Sometimes, it just randomly happens. There's no rhyme or reason to it. It's happened to me before, also... especially when saving to cloud storage. My workaround is to save the project to a local drive, restart Photopea, open the project from my local drive and then resave it to the cloud.

But the positioning of the information bar sits over the top toolbar making it impossible to use any of the other buttons/menus until you restart. On a mobile phone, this is even more problematic, because it can be hard to scroll back to the File menu to try saving again.

Even if you could just lower the positioning of the notifications to just the top of the canvas area, that would be enough to leave the toolbar area always accessible.

**Comment by photopea** [comment]
okay, I have put these messages a bit lower, so they do not cover the top menu now.

**Comment by CiteClimb** [comment]
For a temporary fix, you can just open Chrome DevTools and delete the HTML element that is responsible for the **"Loading"** notice.
