### ISSUE TITLE
Magin tool -> Remove often puts a random object in place of the removed object

### ISSUE THREAD

**Issue by grass29** [photopea/photopea#6079]
Your Operating System: Ubuntu
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too: haven't tested in incognito

**This must be done to see the problem**
1. Go to www.photopea.com
2. Upload some digital art image
3. Use Magic Replace tool
4. Select an area around an object
5. Click "remove"
6. 70% of the time, depending on the selected area, the object to be removed is replaced with a random object, such as a pipe, piano keyboard, flying saucer, and any other random object.

**Comment by photopea** [comment]
Could you show us an example or a screenshot? Which image you use, what area you replace, whtat keywords do you enter?

**Comment by photopea** [comment]
I see. It is probably because in practice, images like yours usually contain some element at the bottom part.

I have entered "purble background" as "New Content" and it works perfectly.

Our "Remove" button was my own idea. It just performs "Replace" with the new content set to a phrase "empty background". It does not always work. Do you think I should remove the "Remove" key?

**Comment by grass29** [comment]
Thank you for the explanation. Perhaps you could add a tooltip with this explanation when the user hovers over the "remove" button.

**Comment by camoody1** [comment]
@photopea I remember, at one point, Clem had told me that Dezgo had plans to create a "remove" tool that was supposed to handle this exact case. I haven't heard or seen any update on that in awhile. I'll send him a message to see if they still have it on their schedule.

**Comment by photopea** [comment]
When you get the content which you did not want, try to specify what you want with more words.
