### ISSUE TITLE
Grey screen

### ISSUE THREAD

**Issue by RUReadyForJoshh** [photopea/photopea#6151]
I was working on something in photopea on the app, (it's happened on the website too though.) and then I opened a youtube video in google chrome, and when I returned to photopea, my screen was all grey. I can see all of my layers on the side, and they are not hidden. does anyone know how to fix this?

**Comment by kenthhhh** [comment]
Got the same issues for the last few days and I had to restart my project so many times:((

**Comment by photopea** [comment]
I think your web browser kills Photopea, because there is not enough RAM memory in your computer for several apps to run simultaneously.

You should still be able to press File - Save as PSD at that point, to save your work. Does saving work?

Also, if Photopea crashes completely, your work should be saved thanks to this mechanism: https://www.photopea.com/tuts/photopea-opens-up-old-files/ , unless you have browser extensions which prevent websites from storing files to your computer.

**Comment by photopea** [comment]
I have to close it because of the lack of details :(

**Comment by ggfiles** [comment]
### ### ### ### ### ### ### ### ### ### ### po
