### ISSUE TITLE
Some Characters mess up the rest of the text block

### ISSUE THREAD

**Issue by saahilveneno** [photopea/photopea#6179]
When you put in some characters (e.g. curly quotes and apostrophes “”‘’), a lot of the time the rest of the text block gets a bit messed up, video below (the period afterwards gets sent to the beginning of the line, though when editing the text it still thinks that its at the end rather than beginning of the line):

https://github.com/photopea/photopea/assets/88685873/4a107bee-b7c0-4726-8b2f-a398ca27e0fd

**Comment by photopea** [comment]
I am not able to reproduce it :( could you share your PSD file with us?

**Comment by photopea** [comment]
I have opened your PSD file in Adobe Photoshop, and the text is rendered exactly the same as in Photopea. So I think the photopea works correctly.

I think it feels "strange" because you have set the typing direction to right-to-left, see 
![image](https://github.com/photopea/photopea/assets/15955558/a7646ba1-8a30-4fd3-ae3b-b4ac020b73ee)

**Comment by saahilveneno** [comment]
Yep, that was the issue, thanks!
