### ISSUE TITLE
Feature request for Canvas Resize.

### ISSUE THREAD

**Issue by bluep55** [photopea/photopea#6186]
When using 'Canvas Resize' in Photopea, the only resize option for the extension appears to be transparent.
Would it be possible to give the option of using either the 'Foreground' or 'Background' colour similar to how it is in Photoshop.

![Canvas resize 72](https://github.com/photopea/photopea/assets/118609932/3a15204c-82dc-4bc5-b141-388f4b1b99e8)

**Comment by photopea** [comment]
Photopea exists for 10 years and nobody ever asked for this feature.

Into which layer exactly should the background be painted into? What if you have just one text layer in your document, should a new layer at the bottom be created? You know you can create a new layer manually and put it behind other layers?

**Comment by camoody1** [comment]
@photopea Here is how that option works in Photoshop:

The “Canvas extension color” option in Photoshop is only available when your image has a **background layer that is not transparent**. A background layer is a layer that is locked and named “Background” in the Layers panel. It is usually the bottommost layer in the layer stack. [A background layer does not have any transparency, so when you extend the canvas, you can choose a color to fill the extra space].

However, if your image does not have a background layer, or if your background layer has some transparency, the “Canvas extension color” option will be disabled. This is because the extended canvas will be transparent by default, and you cannot fill it with a color. [Transparency is represented by a checkerboard pattern in Photoshop].

To enable the “Canvas extension color” option, you need to make sure your image has a background layer that is not transparent. You can do this by either creating a new background layer or converting an existing layer into a background layer. [Here are some ways to do this]:


- If your image does not have any layers, you can create a new background layer by going to Layer > New > Background from Layer. This will fill the entire canvas with the current background color, which you can change by using the Color Picker tool.

- If your image has one or more layers, you can convert the bottommost layer into a background layer by going to Layer > New > Background from Layer. This will lock the layer and rename it as “Background”. If the layer has any transparency, it will be filled with the current background color.

- If your image has a background layer that has some transparency, you can fill it with a color by using the Paint Bucket tool or the Edit > Fill command. You can also remove the transparency by going to Layer > Layer Mask > Delete. This will delete any layer mask that is making the layer transparent.

**Comment by bluep55** [comment]
This is a very clear explanation from Camoody1.
It appears that the difference between a Photoshop Locked Background layer and a Photopea Locked Background Layer is that in Photoshop the locked layer has no transparency, whereas in Photopea the locked layer does have transparency.
Consequently, when the Locked Background canvas is extended in Photoshop the extended section has to have colour.
Using the Paint Bucket tool as suggested to fill the transparent section in Photopea is maybe the best option.
