### ISSUE TITLE
Photopea keeps deleting all of my work progess every single time 

### ISSUE THREAD

**Issue by trillinxfn** [photopea/photopea#6202]
Your Operating System  keeps deleeting my work so i can not do my work because it keeps freezing and deletin g all of my amazing work i can not keep doing this over and over again this has deleted all of the work i have spent time to create this is crazy how everything keeps getting deleted it does not make any sense how it keeps deleting it i cant im bout to quit this is so annoying i cant this is so bad it deleted a project i spent 4 days on

**Comment by photopea** [comment]
Hi, what is deleting? You should save your work to your computer using File - Save. What should I do to see a problem which you are describing?

**Comment by camoody1** [comment]
@trillinxfn Is Photopea also deleting all of your punctuation marks? It's very hard to read when you write with no punctuation.

Are you actually SAVING your work? If so, where are you saving it? On your PC? In the Cloud somewhere? Are the project files completely disappearing? Or are they just empty when you open them?

**Comment by pmelga01** [comment]
Had a similar issue, though I saved a .psd file to a different directly than normal, waited for the saving message to finish, but when I closed photopea and reopened the file I had just saved, i get an error message saying the file is empty. I went back to where the file was previously stored, and I get a very old version of the file. Not sure if there's any way to recover the most recent version, even though I had clicked save and save as multiple times while working

**Comment by pmelga01** [comment]
Thanks for responding!
I had been working on a file on the browser version of Photopea with a drawing tablet however, there got a point where there was a delay whenever I would draw, only on Photopea, the tablet did not delay anywhere else. I thought this was due to the advertisements loading on the side of the screen.
I installed and purchased Photopea for the month and opened my project locally rather than through the browser. I continued working on it locally. I saved about twice (Ctrl+S) and saw the saving message. I continued working on the document until I reached a stopping point. I wanted to be sure this would save, so I decided to "save as" and choose a different directory to save the project in. 

Once the saving message box went away, I closed the file/photopea application, and then went to where I saved the project (my Downloads folder), and once I opened it, I got an error saying Empty File (0 bytes) on Photopea (both trying to open the project I saved from the browser as well as locally on the installed Photopea application.

Lastly, I tried to open the project I saved in its original local folder, the one I was working on in the browser Photopea prior to purchasing the subscription and installing it onto my computer. That project did actually work to open, however, it was the earlier version of the project I had been working on prior to installing Photopea. I thought it was strange because I was saving the project throughout using the local installed version, and did not get any abnormal message. So I imagine it was not saving onto the project, properly.

**Comment by photopea** [comment]
I see. Could you make it happen again, on purpose? Maybe 5 - 10 steps are enough to make it happen. I need to make this problem happen on my computer to be able to analyze it further.

**Comment by aole** [comment]
There is definitely something weird going when files are getting saved. Happened when saving on google drive and even when saving locally.
One thing to definitely look at is when the connection is dropped with cloud, you are not able to save the changes anymore, all the changes are lost.
Other would be saving PSD locally.

**Comment by photopea** [comment]
Could you describe some steps, which lead to your issue (every time)? I need to see a problem happen myself, so that I can fix it :(

**Comment by photopea** [comment]
I have to close it because of lack of details.
