### ISSUE TITLE
Can't screenshot with ChromeOS in photopea

### ISSUE THREAD

**Issue by MesaBlack** [photopea/photopea#6210]
The keybind is Ctrl + Shift +/Shift + Ctrl + (Show Windows) on chromeos.

**Comment by TheRadicalDreamer** [comment]
Hi!
Yes it is possible.
If you are using Photopea on a browser tab, you can use the key combo you already know @MesaBlack 

But if you are using Photopea as a webapp (installed version), then you have to click the screenshot button on the taskbar with your mouse.

![image](https://github.com/photopea/photopea/assets/11801254/28d1836c-9f0e-450a-85d1-23c8ab99f13d)

I know it is not as quick as hitting the key combo, but this is because when using a Webapp, Photopea can access all key combos that were reserved to the browser, so the Shift + Ctrl + (Show Windows) does not work.

It happens the same with Ctrl + T to transform in Photopea, if you use it when you are in a browser tab it will open a new tab on the browser, instead of transforming the layer you are editing.

**Comment by MesaBlack** [comment]
> Hi!
> Yes it is possible.
> If you are using Photopea on a browser tab, you can use the key combo you already know @MesaBlack 
> 
> But if you are using Photopea as a webapp (installed version), then you have to click the screenshot button on the taskbar with your mouse.
> 
> ![image](https://github.com/photopea/photopea/assets/11801254/28d1836c-9f0e-450a-85d1-23c8ab99f13d)
> 
> I know it is not as quick as hitting the key combo, but this is because when using a Webapp, Photopea can access all key combos that were reserved to the browser, so the Shift + Ctrl + (Show Windows) does not work.
> 
> It happens the same with Ctrl + T to transform in Photopea, if you use it when you are in a browser tab it will open a new tab on the browser, instead of transforming the layer you are editing.

Ahhhh now that can be why

**Comment by photopea** [comment]
Ok I think I can close it now.

**Comment by photopea** [comment]
@TheRadicalDreamer thanks a lot for your help! :)
