### ISSUE TITLE
trying to draw on photopea and it keeps saying "select a layer first" even though i don't have any layers.

### ISSUE THREAD

**Issue by cats1984** [photopea/photopea#6236]
Your Operating System:Chrome OS
Your Web Browser:Chrome

**This must be done to see the problem**
1. Go to www.photopea.com
2.?
3. ?
4.?
there is nothing really you have to do to see the problem, it happens randomly

**Comment by photopea** [comment]
It is not possible to have no layers in Photopea. There always must be at least one layer.

Press Window - Layer, and choose a layer where you want to draw.

You probably clicked with the Move tool with Auto-select enabled (at the start), which deselects all layers (since the background layer is locked for movement).
