### ISSUE TITLE
Photopea Crash

### ISSUE THREAD

**Issue by VLD345** [photopea/photopea#6247]
Your Operating System: MacOS Ventura 13.2.1
Your Web Browser: Google Chrome, Safari
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Open .psd file from downloads
3. Select path tool
4. Photopea crashes - page unresponsive - tools can be selected and file can be saved, but page does no longer function. Sometimes happens with other tools/functions also. 
5.

**Comment by VLD345** [comment]
This happens consistently every time I try to open a file; I reloaded chrome and restarted my laptop. Seems to be an issue with something on my end rather than the app, what can I do? Happened today for the first time that I can't fix an issue by reloading the site...

**Comment by photopea** [comment]
I am confused about the step number three, what is the "path tool"?

Could you record a short video of opening www.photopea.com and doing these steps, until a moment it crashes?

**Comment by FouadMsr** [comment]
Hi.

The site crashes for me too when I try to edit a PSD file, as soon as I do "open and place", the site crashes shortly during loading.

I use a Samsung galaxy tab A8 with android 13, and this happened to me using Google Chrome and Samsung Internet Browser.

**Comment by photopea** [comment]
@FouadMsr what is the document that you are placing? What is the width and the height of that document in pixels? It is more than a billion pixels?

**Comment by FouadMsr** [comment]
@photopea, not at this point, the file is 16000×10949 px.

But apparently I only encounter this problem with a single mockup associated with a single image, because I tried the image with other mockups and it works fine, and I tried the mockup with other images and it works well too.

For some reason the combination between the two doesn't work.

In any case, thank you for your responsiveness, it proves that you care about the proper functioning of your site.

**Comment by FouadMsr** [comment]
@photopea, hhh, not at this point, the file is 16000×10949 px.

But apparently I only encounter this problem with a single mockup associated with a single image, because I tried the image with other mockups and it works fine, and I tried the mockup with other images and it works well too.

For some reason the combination between the two doesn't work.

In any case, thank you for your responsiveness, it proves that you care about the proper functioning of your site.

**Comment by photopea** [comment]
That is 176 million pixels, which is not a billion, but still a lot.

How much RAM do you have? You probably dont have enough RAM for this kind of work. Could you shrink your image e.g. to 4000x2500  pixels before placing it into your mockup?

**Comment by FouadMsr** [comment]
You were right, it was too much, even if it's not a trillion but it's almost around 200 million pixels.

I set it to 5000×3422 and it works very well.

thank you, and have a good day (evening).

**Comment by photopea** [comment]
Ihave to close it, because the original person did not respond :(
