### ISSUE TITLE
Text is auto converting into a FontAwesome Icon

### ISSUE THREAD

**Issue by vazahat** [photopea/photopea#6292]
Your Operating System: Windows 11
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. Create a new project, and select the text tool.
3. Chose any FontAwesome font. Try writing some stuff like Edit, Map etc, some specific words turn into icons instead of remaining text characters.
4. I tried looking everywhere in the text properties and didn't find any option to prevent my text character from becoming an Icon automatically. There should be an option there where people who don't want to use the icon can still use the text characters for the Fontawesome font.

**Comment by photopea** [comment]
The creator of a font decides, how each character / characters should be rendered. E.g. they can set it render two characters ":)" as a special picture of a smiling face. This is a standard mechanism.

I tried the first FontAwesome font in the list and it does not do that. Otherwise, you should ask the creator of the font to give you a font which works differently.
