### ISSUE TITLE
SSL causing issues

### ISSUE THREAD

**Issue by byrning** [photopea/photopea#63]
Hi,

It appears that http://www.photopea.com now(recently) redirects to https://

This is causing issues when trying to load non https content in the json object.. for example: 
http://www.photopea.com/?p=%7B%22files%22:%5B%22http://dashboard.morphogine.com/images/blank-canvas.png%22%5D%7D

The following happens:
1. Firefox: the entire editor doesn't load
2. Chrome: the editor loads, but the image doesn't
3. Safari: the editor loads, but the image doesn't
4. IE: the entire editor doesn't load

The errors shown are:
1. Blocked loading mixed active content "http://dashboard.morphogine.com/images/blank-canvas.png"
2. TypeError: this.tools.map[this.tools.current] is undefined

Thanks.

**Comment by photopea** [comment]
Hi byrning, I am aware of this problem.

I decided to transfer everything to HTTPS mainly because of loading and saving external files. When PP loaded or saved a file (e.g. from your server or from Google Drive), it was transferred unencrypted. Is it ok for you to transfer your files (and URLs) unencrypted? Can you also go HTTPS? What solution do you suggest?

**Comment by byrning** [comment]
Well we can go HTTPS, but you may want to have that as an option, because not everyone has HTTPS. Most websites don't use https = barrier to entry for your tool.

Thanks!

**Comment by photopea** [comment]
I assumed, that HTTPS is becoming more and more accessible. I am using Let's Encrypt for certificates.

Do you want me to keep http version online, too? I am just a little afraid, that users would get confused, when there are 2 versions.

**Comment by byrning** [comment]
Well I recommend having 2 options, HTTP or HTTPS, with HTTPS being the **default** setting. So, to disable it, one could set "https":false in your json struct. That way people who don't have HTTPS can still use your tool over HTTP. 

I agree about HTTPS being more accessible, but I think it's going to be a while before most websites have it. I imagine HTTPS adoption can't be more than 5% of all websites. Take us for example, we have a bunch of clients, but the only ones on SSL are the online stores and websites with online payments.

**Comment by photopea** [comment]
So if you go to http://www.photopea.com, the whole PP should load itself, check the query string, parse JSON and then eventually redirect to https, because it is the default? 

I realised that I don't like that idea of providing the content over both protocols. Not only people would get confused, but also the search engines ... I am afraid they would record my site twice etc ... So can you please fetch only the files, which are stored at https? I don't have that many API users besides you.

**Comment by byrning** [comment]
Well I would have it exactly as you have it now, https://www.photopea.com by default, but if the json includes "https":false, then it redirects to http://www.photopea.com .  It doesn't need to load the entire editor to get the json, you'd process it server side and then redirect accordingly.

With the above setup, google would only index the https version, because it has no way of getting to the http version without the https:false json setting.  

Either way, it's totally your call. I just think going forward as is, you might find more and more people running into this issue.

**Comment by photopea** [comment]
I have no "server side" right now (there is only a file server). I will leave it HTTPS only. You still can insert Photopea into HTTP webpages as an iframe, but resources must be located at https.
