### ISSUE TITLE
Hello! Why do I have to watch an ad twice to get the one result when using magic replace?

### ISSUE THREAD

**Issue by ronaldafrica** [photopea/photopea#6362]

**Comment by photopea** [comment]
A single use of Magic Replace costs us $0.003. When you watch a video ad, we get paid $0.001. When we showed just one ad, we were losing money. Now, we increased it to two, but we are still losing money. We are planning to switch to three or four video ads each time you use the Magic Replace.

So in order to use the Magic Replace 333 times, you will have to watch 999 video ads. Or would you rather pay $1?

**Comment by camoody1** [comment]
> So in order to use the Magic Replace 333 times, you will have to watch 999 video ads. Or would you rather pay $1?

😂

**Comment by photopea** [comment]
Since we introduced two video ads, the Magic Replace is used 2x less often.

I agree, it is crazy with two ads now. We should even find a provider who can do AI for less than $0.003, or an ad provider who can pay us more than $0.001 per video ad.

Also, we get paid $0.001 when a child watches an ad, but we get paid up to $0.005 when an adult watches an ad.

**Comment by camoody1** [comment]
I think you'll find it VERY hard to find a service provider cheaper than Dezgo who can handle Photopea's volume. I've looked. I'm always looking. And I've never found anyone close to their offering.

Leave it at two videos per image but add a link to the message that makes it super easy to buy a month's subscription. Maybe get a PayPal account that makes it easier for a customer to transfer money instead of needing a credit card. If a subscription is worth so much more to you than an advertisement, perhaps consider dropping your subscription rate to just $3 per month (instead of $10 for three months). If it's that inexpensive and available to pay via PayPal, even kids might be more likely to make an "impulse buy".

Just some ideas.

**Comment by photopea** [comment]
I will close it for now.

**Comment by photopea** [comment]
BTW. there are users who use the Magic Replace 500 times a day, every day. It costs us $1.50 a day, $45 a month, while they pay $5 a month for Premium.

**Comment by camoody1** [comment]
500 times per day?! Okay. Maybe it's time to make a limit. That's someone taking advantage of you. Probably has an account shared with multiple users or even a website. 200 per day limit is MORE than reasonable.

500 per day is one use every three minutes for 24 straight hours. Let's say they're only using Photopea for 8 hours (which is still HIGHLY doubtful)... that's still more than one use every minute for 8 straight hours. There's just no way.

**Comment by photopea** [comment]
It takes about five seconds to get a result for the magic Replace. Users often click "Replace" again and again, until they get the result they like. So you can easily use it 60 times in 5 minutes.
