### ISSUE TITLE
This website just makes me wanna STRANGLE MYSELF TO DEATH. I'm just learning to make a good thumbnail with this website, takes me about 5-6 hours because it's my first time and I alr know where the undo option is but I saw a history button where the layers were, so I clicked on it just so it can REMOVE EVERYTHING I WORKED ON I TRIED TO UNDO IT BUT IT DIDN'T UNDO ANYTHING AND NOW I LOST ALL MY GOD DAMN SHIT CAUSE OF A HISTORY BUTTON WTF IS ITS PURPOSE WHEN I CAN JUST CLICK AND DELETE, WHY DOE THAT BUTTON HAVE TO EXIST, I'M LOSING MY DAMN MIND CAUSE OF ONE SHITTY BUTTON.

### ISSUE THREAD

**Issue by Ihatephotopea1234** [photopea/photopea#6403]
Your Operating System:
Your Web Browser:
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. ....
3. ....
4. ....

**Comment by camoody1** [comment]
You sound like you have anger issues... and an inability to research how to use the tools that you are using. Don't blame the tool for your lack of understanding.

Good luck to you on your next thumbnail creation.

**Comment by photopea** [comment]
I am sorry for your loss. What kind of a device do you use? Do you use any browser extensions which have your permissions to manipulate with the content of websites?

**Comment by bluep55** [comment]
During that 5-6 hours of work, did you ever consider periodically saving the file as a PSD file, so that if anything were to go drastically wrong, you'd have a saved file to fall back on?

**Comment by that-ben** [comment]
Wow, relax OP.  I just found out about Photopea and it's the best thing I've seen so far in 2024.  It literally is the best option for me under Apple Silicon, since I cannot run Intel software and I don't want to pay a subscription to Adobe to use Photoshop.  I'd like to thank you @photopea for this incredible web page.  It loads faster than any actual Photoshop binary and you even managed to preserve keyboard shortcuts faithful to Adobe Photoshop CS3.  It's incredibly good and absolutely just what I needed.  I just edited a few PSD files instantaneously and it works perfectly for me.

**Comment by MesaBlack** [comment]
what?

**Comment by photopea** [comment]
@that-ben thank you very much! :)

I will close this issue, because the person who wrote it is not responding.

**Comment by MesaBlack** [comment]
they joined on the day they posted this.

And their username checks out.
