### ISSUE TITLE
Issues editing CR2 raw image files

### ISSUE THREAD

**Issue by ZLEA1138** [photopea/photopea#6450]
Your Operating System: Windows 11 Pro (23H2)
Your Web Browser: Firefox 122.0.1 and Chrome 121.0.6167.185
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Click File
3. Click Open...
4. Open any .CR2 raw image file

.CR2 raw image files appear black in Raw Photopea.  Manipulating the channels and/or sliders does not fix the problem.
![Screenshot 2024-02-20 221818](https://github.com/photopea/photopea/assets/123418160/4de4612e-da09-4a1f-b320-1d864c16e481)

The .CR2 files I am trying to edit are too large to attach here, but I can provide them via email upon request.

**Comment by photopea** [comment]
I just tried to open several CR2 files in Photopea, from different cameras, and they all seem to work fine.

I guess all your CR2 files come from the same camera. Could you share your CR2 file, or at least tell us the name of your camera, so that we can find CR2 files from that camera on the internet?

**Comment by photopea** [comment]
I am very sorry, it should all be fixed now.
