### ISSUE TITLE
Automation- Resize options need DPI

### ISSUE THREAD

**Issue by jporter19** [photopea/photopea#6493]
Your Operating System: Windows 10
Your Web Browser: Brave, Chrome
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. File -> Automate -> Batch  OR Convert Formats OR Resize Image
**problem**:  There is no selection for DPI.   800 x 800 pixel are different sizes based on dpi.  dpi of 72 yields a different size image than a 300.  I need to save all images at 300 dpi.

**Comment by photopea** [comment]
Right now, Photopea should keep the DPI of the original file. So if your image was 1000x1000 pixels, DPI 300, and you resize it to 500x500 pixels, the DPI is still 300 (so both the pixel size and the physical size in inches is 2x smaller).

Do you want to set a new DPI, the same value for all exported files, no matter what the old DPI was?  Or maybe adapt the new DPI, so that the physical size is the same after resizing?

**Comment by jporter19** [comment]
My goal was to run a conversion on all files in a folder at 1:1 aspect
ratio.  The files are .webp downloads from MidJourney AI, which are all 72
DPI and I want to increase them to 300 DPI and save them as different
sizes.  I'm still a bit new to this... I'm guessing i can do all of this
with action sets. I was surprised that the resize automation didn't have
the same choices as the image resize (from image menu)

Enhancement suggestion: it would be great to have a crop & resize feature ,
so that I could start with an image in 2:3 ratio and crop and save it as
1500x2100 or 2400x3000 (other common frame sizes)

Thanks,
John

**Comment by photopea** [comment]
Maybe try using the actions for this, it should work.
