### ISSUE TITLE
Add pen pressure sensitivity for tablets

### ISSUE THREAD

**Issue by photopea** [photopea/photopea#65]
It would be nice to add pen pressure sensitivity for tablets.

**Comment by ryanmcnz** [comment]
Adding a comment here for testing tablet sensitivity. Looking forward to testing this one!

**Comment by photopea** [comment]
@ryanmcnz  I am sorry for such a delay. Can we take a look at it now?

**Comment by ryanmcnz** [comment]
@photopea Yup sure. Will be a slight delay as I don't have a tablet now, but can borrow a friends one to test. Shall comment again soon.

**Comment by TomasHubelbauer** [comment]
I'd also be willing to help testing pen pressure sensitivity implementation. I have a Wacom tablet at hand which I can use for testing.

**Comment by photopea** [comment]
Hi, I added the basic support for pressure. The pressure should influence the thickness of the line. Can you try it how it works?

**Comment by TomasHubelbauer** [comment]
I have tried with the brush tool and the pencil too. I get constant width with both in Firefox 60.0b12 and Chrome 65.0.3325.181. In Edge 41.16299.371.0, additionally, pen dragging generates the vertical scroll gesture which causes the page to bounce around. I had a fix for that somewhere, I can try to find it and share it if you care about Edge, but seeing that in it, the cascading menu is all broken I don't think any QA happens in it which makes me wonder if it is supported?

**Comment by TomasHubelbauer** [comment]
[This is my demo which works correctly in Chrome and doesn't do the vertical overdrag bound in Edge.](http://hubelbauer.net/post/pressure-draw/src/index.html)

[The source is here](https://gitlab.com/TomasHubelbauer/pressure-draw)

**Comment by photopea** [comment]
It is so cool that you are a programmer too! :)  for pointer events, what pointerType are you getting with a pen? I set the pressure to constant 1 when pointerType is "mouse".

**Comment by TomasHubelbauer** [comment]
Speaking of which, I did your project and thanks for pouring so much effort into it. :-) I hope it will be feasible to open source it one day.

The pointer types I am getting are `mouse` and `pen` respectively in Chrome and Edge, it works perfectly in both.

```javascript
paintCanvas.addEventListener('pointerdown', ({ offsetX: x, offsetY: y, pressure, pointerType }) => {
	console.log('pt', pointerType);
	instructions.push({ type: 'stroke', points: [{ x, y, pressure }] });
});
```

In Firefox, I get `touch` for `pointerType` and in my demo, the thickness is again constant, but I think that's because I don't have the Wacom driver installed, just some generic one. You can also check out `doc/notes/firefox.md` in my demo where I have noted my struggles with Firefox. It should work in there, but I have the config switch set and it doesn't make a difference.

**Comment by photopea** [comment]
Ok I removed the pointerType check. How does it work now!

BTW thank you!

**Comment by TomasHubelbauer** [comment]
Works in Chrome. In Firefox and Edge, I don't get any drawing at all now. I tried with browsers on my PC. I will also try with browsers on my Mac and my work computer tomorrow to see if I get different results.

**Comment by photopea** [comment]
I think that Photopea should work the same as your demo now (in all browsers). So does your demo work in Firefox and Edge right now?

**Comment by TomasHubelbauer** [comment]
Nope, there must be some subtle difference still. I am not sure what could be causing it. I should also mention that mouse drawing works fine, it's just pen drawing that doesn't do anything currently for me except in Chrome.

**Comment by TomasHubelbauer** [comment]
My demo works in Edge, but in Firefox `pressure` is always constant for me, which I think is a problem with my installation of the tablet or the browser.

**Comment by photopea** [comment]
Also, in Photopea, the "down" event must have a "button" property null or zero. Otherwise, nothing happens. What "button" property are you getting for a pen in Edge?

**Comment by TomasHubelbauer** [comment]
```javascript
paintCanvas.addEventListener('pointerdown', ({ pointerType, button, buttons }) => {
	console.log(pointerType, button, buttons);
});
```

This gives me `mouse 0 1` and `pen 0 1` respectively. In Edge and Chrome and `mouse 0 1` and `touch 0 1` in Firefox.

**Comment by photopea** [comment]
And does drawing with mouse work well in Edge? I was afraid I am reading the mouse coordinates incorrectly.

BTW. I was able to play with the pressure in Photopea on my Phone :D

**Comment by TomasHubelbauer** [comment]
Yeah mouse drawing works well in Photopea on Edge. :-) I tried it on an iPhone just now and, surprise, surprise, Safari wasn't able to handle it. But I think macOS Safari will work, haven't tried yet though.

**Comment by TomasHubelbauer** [comment]
I think definitely thickness, pressure-opacity mode maybe underneath a key combo as an alternate mode, but the default everyone will expect is pressure-thickness. In my case I will definitely add smoothing and I recommend you do the same. In strokes with many twists and turns, it should be easy to do.

I will also look into breaking up longer line segments within a poly-line to smaller ones (happens when you move the hand quickly or erratically) so that there is always some maximum distance between the polyline points over which the easing can step, otherwise the variance in thickness is too obvious.

The same problem will manifest with quick changes in pressure even without long line segments within the poly-line. If the poly-line with pressure is rendered as a set of line segments with different thicknesses and the user changes the pressure too quickly, the line-end rounding artifact would be visible, so additional break-up of the line into more segments and some easing function with an upper bound on the maximal allowed difference (deriveable from the current resolution at which the line is rendered, it only needs to be precise enough to fool the viewer into seeing a smooth transition at the current zoom level) is in order to make the line appear smooth.

**Comment by TomasHubelbauer** [comment]
Tests on macOS 10.13.4 High Sierra:

- Chrome 65.0.3325.181: works perfectly.
- Firefox 58.0.1: no drawing with either a table, or a touchpad, or an mouse (external)
- Safari 11.1 (13605.1.33.1.2): no drawing with either a table, or a touchpad, or an mouse (external)

**Comment by photopea** [comment]
Are you using the latest Safari on Mac OS?  Does our drawing tool work there? Can you debug your tool for all these browsers and then, I will make it according to your tool?

**Comment by photopea** [comment]
Are you sure your demo ever worked in Safari? According to this, Safari does not support pointer events: https://caniuse.com/#search=pointer%20events

**Comment by TomasHubelbauer** [comment]
I apologize for the confusion, I have not tried my demo on Safari before, just Photopea, without knowing pointer events were not supported in it.

**Comment by photopea** [comment]
I started to use PointerEvents only when they are available in the browser (if not, MouseEvents are used). So now, the pressure in Photopea should work just like in your demo, for all browsers. Can you confirm it?

I added the thickness change along the line segment. Is there anything else you would like me to do, or can I close it?

**Comment by TomasHubelbauer** [comment]
Let me get back to you on that tonight. Yesterday the last time I tried, there were issues with no drawing at all still, but maybe I hit a stale copy from the cache.

**Comment by photopea** [comment]
So I think we can close it for now. It will start working in Safari as soon as Safari implements pointer events: https://caniuse.com/#search=pointer%20events
