### ISSUE TITLE
Popup says I'm blocking ads but I'm not

### ISSUE THREAD

**Issue by cyclops365** [photopea/photopea#6502]
As you can clearly see, I'm not blocking the ads. 
![image](https://github.com/photopea/photopea/assets/72573834/36cf4349-44c5-4d8e-a465-67ae4f2b2c0b)

Your Web Browser: Microsoft Edge

**Comment by DragoshDX** [comment]
I am plus onening this, I have add block paused forever on this site. 
I use photopea to teach coding on Twitch, but I can't if it keeps saying my disabled ad blocker is enabled.

**Comment by photopea** [comment]
The message says "Are you not aware of blocking ads? Read this article", did you try to read that article?

Or at least, could you show me a list of your extensions, which you allowed to modify Photopea? As the image suggests.

**Comment by photopea** [comment]
> As you can clearly see, I'm not blocking the ads.
What do you mean by "clearly see"? I clearly see, that Photopea says you are blocking ads :D

**Comment by camoody1** [comment]
@cyclops365 @DragoshDX You are blocking REAL ads. What you see there are placeholder ads that the developer has forced there because you are blocking the REAL ads that make him money. These game "ads" are just other web apps that the dev has written. They make him no money. Disable all of your extensions and then add them back one at a time until you figure out which one is blocking the ads.

**Comment by camoody1** [comment]
@bennyschmidt @photopea Delete this post. We don't need more people blocking ads on Photopea. People blocking ads and refusing to spend $3 for premium is why people have to watch a video to use AI or export images.

**Comment by photopea** [comment]
We accept only bug reports, which you can make happen in a web browser with no extensions running.

If the problem happens only when you use a specific extension (and it disappears by turning off that extension), it means, that the problem is caused by your extension.

In this case, the message that you see in Photopea provides you the steps to fix it.
