### ISSUE TITLE
Issue with ttf font with special character in the name

### ISSUE THREAD

**Issue by CharlesFairclough** [photopea/photopea#6585]
Your Operating System: MacOS
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too: yup

**This must be done to see the problem**
1. Go to www.photopea.com
2. load the following font: https://perfected.media/files/soehne-buch.ttf
3. it doesnt show up in the list
4. * sad face *

**Comment by photopea** [comment]
The name of your font is "Copyright Klim Type Foundry". I can load it into Photopea and see it there.

Just because you rename your file to "forg.ttf" does not mean that your font will be named "Frog" in Photoshop / Photopea, it does not work that way :D

![image (1)](https://github.com/photopea/photopea/assets/15955558/643c1f59-3801-4a10-b832-508fce3ec8c8)
