### ISSUE TITLE
Two Photopea entries in Open with menu

### ISSUE THREAD

**Issue by SangreSam** [photopea/photopea#6607]
Your Operating System: Windows 11 Pro
Your Web Browser: Edge, but using installed Edge App.
The problem happens in the Incognito Mode, too:  NA

**This must be done to see the problem**
1. Installed Photopea App
2. R-Click on an single image file (png, jpg, tif, etc.)
3. Under the Open with context menu Photopea appears twice. 
4. Selecting the first Photopea in list opens image in Photopea App.
5. But selecting the second instance results in a Microsoft Edge Window that says "Open and edit 2 files in the web app?"
6. Then, below that the file is listed twice.  Clicking on Open button Photopea opens but does not open an image at all.
7. How do I get rid of the second instance in the context menu?

Regards, Dan
![2024-03-31_18-30-25](https://github.com/photopea/photopea/assets/165610351/d097decf-2880-4548-ae17-233cdf464283)

**Comment by photopea** [comment]
Hi, it is totally up to your browser, how it decides to "install" a website. It is not under our control.

I think it is a bug in Microsoft Edge. Could you report it to Microsoft? Otherwise, open "about://apps" in Edge and uninstall Photopea. You can still use it whenever you want at www.photopea.com

**Comment by photopea** [comment]
I have to close it because of lack of details.
