### ISSUE TITLE
Pricing Question

### ISSUE THREAD

**Issue by Abystus** [photopea/photopea#6663]
This is a general question on pricing as I see two prices listed on the site for a month, and am wondering which is the correct value for 30 days:

![image](https://github.com/photopea/photopea/assets/1529049/e93fdc8f-380d-46ba-bdf8-b64975691485)
![image](https://github.com/photopea/photopea/assets/1529049/e466f393-5b77-4120-a43b-336a4cd32339)

**Comment by camoody1** [comment]
It's $8 for one month if you pay for just one month at a time. If you pay for three months at a time, it's a total of $15 - or $5 per month. That's why that first screen you shared says "**From**" $5/mo.

It actually could say "From $4.17/mo" (considering $50 for 12 months), but $5 is a more normal looking number, I suppose.

**Comment by Abystus** [comment]
> It's $8 for one month if you pay for just one month at a time. If you pay for three months at a time, it's a total of $15 - or $5 per month. That's why that first screen you shared says "**From**" $5/mo.
> 
> It actually could say "From $4.17/mo" (considering $50 for 12 months), but $5 is a more normal looking number, I suppose.

Ok, that makes sense. Thanks for the explanation.

**Comment by photopea** [comment]
We need to pay our payment provider over $1 from each payment, no matter what the amount is. So we want to encourage users to buy at least 90 day Premium instead of short 30 days.
