### ISSUE TITLE
Controls are shown even that environment arguments are set to disable them

### ISSUE THREAD

**Issue by mszuchman** [photopea/photopea#6674]
Your Operating System: OS X
Your Web Browser: Google Chrome
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Enable distance controls
3. Open Photopea again but this time sending the topt for distance as 0 (disabled) "topt":{"t0":[0,0,0]}}  (ie: https://www.photopea.com/#%7B%22resources%22%3A%5B%22https%3A%2F%2Fstorage.googleapis.com%2Ffusion-cloud-ai-ugc%2F66202f0787d899301b58351d%2Ftypography%2F089aa54e-cd86-45bc-998d-889b5c794792.ttf%22%5D%2C%22environment%22%3A%7B%22vmode%22%3A2%2C%22theme%22%3A2%2C%22panels%22%3A%5B2%5D%2C%22menus%22%3A%5B%5D%2C%22showtools%22%3A%5B%5D%2C%22topt%22%3A%7B%22t0%22%3A%5B0%2C0%2C0%5D%7D%7D%2C%22files%22%3A%5B%22https%3A%2F%2Fpsd-generator.s3.eu-north-1.amazonaws.com%2F8e4673aa-82b9-40c8-a87a-5943c413be53.psd%22%5D%7D)

Result obtained: The second time, Photopea is open with the distance control enabled

Expected result: The second time, Photopea should open with the controls disabled as stated in the documentation:
` Three values mean Auto-Select, Transformation controls and Distances. 1 means enabled, 0: disabled, null: not specified.`

**Comment by photopea** [comment]
When you use "showtools" to hide specific tools, these tools should be removed completely, not just removed from the screen. Otherwise, you would still be able to press "B" for the Brush tool (which is removed).

You remove the Move tool by setting "showtools":[]. But then, you are setting "topt" for the move tool, which breaks Photopea, as it can not find the Move tool.

BTW. I have fixed the bug with "vmode":2, so the toolbars will be hidden, and you dont have to hide tools with "showtools".
