### ISSUE TITLE
Free transform won't work 

### ISSUE THREAD

**Issue by SheLuvVegas** [photopea/photopea#6699]
Your Operating System:
Your Web Browser:
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. Import an image or add text
3. When I import an image I'll press free transform, but it won't work. 
4. I tried again and again it'll work every once in a while, but if I press off it I won't work anymore I pressed ALT, CTRL, T and it won't work.

**Comment by photopea** [comment]
Did you try it in the Incognito mode?

**Comment by SheLuvVegas** [comment]
No

**Comment by photopea** [comment]
Could you try it and tell me if it works?

**Comment by Abystus** [comment]
@photopea I am also experiencing issues with this tool as shown in the below video:

https://www.youtube.com/watch?v=1JWiQa89nmo

**Comment by SheLuvVegas** [comment]
@photopea how do I get into incognito mode

**Comment by camoody1** [comment]
@Abystus Your video is in Private mode.

**Comment by camoody1** [comment]
@SheLuvVegas What browser are you using? You didn't fill-out your the issue template.

**Comment by Abystus** [comment]
@camoody1 @photopea try again.

**Comment by photopea** [comment]
@Abystus I think it happens only when inserting images with transparent areas around the object. Could you share the exact file that you are inserting? Did you do anything differently when inserting it, compared to previous insertions?

**Comment by Abystus** [comment]
@photopea This is the exact file in question, but technically it could be any PNG with transparency. Additionally, it isn't always a set number of attempts before it fails; rather, it's a completely random number of attempts. I didn't do anything differently than using drag and drop from my file browser to the web page for each insertion. It's pretty easy to replicate; just keep inserting images and resizing until you notice one where the section area around it is different upon insertion compared to the others. After that, it's broken for all images in the project.

![ivan_pp](https://github.com/photopea/photopea/assets/1529049/a4425f34-1f2f-49d5-9a79-7ffb229851ad)

**Comment by photopea** [comment]
I have been trying to do what you are doing for a while, but with no luck :( It always works well. 

BTW. someone else is reporting it here: https://www.reddit.com/r/photopea/comments/1cecqdk/hey_i_need_your_guys_help/

I have noticed in your video, that you are using Brave. Have you tried to make it happen in any other browser? It could be a bug in Brave.

**Comment by Abystus** [comment]
@photopea So far, within the latest stable version of Chrome, I cannot reproduce this issue. I also tried in Brave in incognito mode and was still able to reproduce it. I agree with you that this may be a Brave specific issue. You can disregard it for now unless I find a way to reproduce it in Chrome. Thanks for looking into it.

**Comment by photopea** [comment]
BTW. Brave hides ads in Photopea by default. About 30 - 40 seconds after opening Photopea, you should see a message about you blocking ads, asking you to stop blocking ads.

Can you see this message? I can not see it in your video. Maybe Brave is removing this message and as a result, it breaks the layer somehow.

**Comment by photopea** [comment]
Ok, if somebody else reports it again, now I know it could be because of Brave. BTW. I can not make your issue happen in Brave. I do see the adblock message in Brave. So it is weird, that your Brave treated Photopea differently than my Brave.

![image (1)](https://github.com/photopea/photopea/assets/15955558/f4871160-aea7-4791-bf1d-7412cecf89e0)

**Comment by Abystus** [comment]
@photopea I did manage to track down what the issue was. I found that when disabling my ad blocker on your site (not the one built into Brave, but uBlock Origin), even though ads were shown, the messages would never show. Apparently, you have to completely close down Brave after disabling it, or the issue will persist (the notification not showing, which breaks the resizing tool, but the side ads were showing perfectly). I was able to reinstall Brave, completely disable uBlock Origin, and then visit your site without issue. Is there, by any chance, a way to prevent it from breaking the resize tool if the message is hidden or not interacted with for some reason? I've also noticed in Brave that I cannot use any of the AI tools (the free way) due to the short ads not playing, as Brave has its own ad blocker which cannot be disabled. Is there, by any chance, a way to show those ads somewhere that Brave users could access them?

**Comment by photopea** [comment]
Look, you are not having problems with Photopea (which runs perfectly fine for millions of users). You are having problems with Brave and uBlock Origin. I am not the author of these things :( Why don't you simply ask them about it - ask them to fix it?

**Comment by Abystus** [comment]
@photopea Relax, my guy. I was just letting you know what the issue was and that some users may not be able to experience your site as you designed it. I completely understand where you're coming from; it's not your problem, but I wanted to make you aware in case you encounter this issue in the future with other users who are also not using browsers that hold the majority market share. Anyways, thanks for the assistance on this issue and for your continued work on this project. It's great not having to rely on Photoshop for the small bit of photo editing I do.
