### ISSUE TITLE
Unable to copy or paste

### ISSUE THREAD

**Issue by harveygithub20101124** [photopea/photopea#6733]
Your Operating System: Windows 10
Your Web Browser: Google Chrome
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Create an object
3. ctrl + c
4. ctrl + v
5. NOTHING HAPPENSSSSS

**Comment by photopea** [comment]
What is an object? Do you mean a layer? 

Also, check this: https://www.photopea.com/tuts/give-photopea-clipboard-permissions/

**Comment by Navid-JL** [comment]
> Your Operating System: Windows 10 Your Web Browser: Google Chrome The problem happens in the Incognito Mode, too: Yes
> 
> **This must be done to see the problem**
> 
> 1. Go to [www.photopea.com](http://www.photopea.com)
> 2. Create an object
> 3. ctrl + c
> 4. ctrl + v
> 5. NOTHING HAPPENSSSSS

The reason you can't copy anything in incognito mode is probably due to the latest update for Chrome in which Google has implemented the following features:

- Windows: Clipboard will be prevented from writing data into clipboard history and cloud clipboard if the data copied is from the Incognito window. This includes all data, including data from Ominox views.
- Mac: There’s no special type for pasteboard history, but when using Incognito Mode, the pasteboard can be marked for the current host only preventing data syncing. As for passwords, they are marked as confidential while being copied to the pasteboard.
- Android: Passwords are marked as sensitive.

[Source](https://windowsreport.com/chrome-improves-privacy-clipboard-history-incognito-mode/)

**Comment by photopea** [comment]
I have to close it because of lack of details :(
