### ISSUE TITLE
Very Laggy and slow to respond to commands

### ISSUE THREAD

**Issue by LaserFocusedUS** [photopea/photopea#6750]
Your Operating System: Windows 11 Home
Your Web Browser: Chrome and Edge
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. ....can't upload the file where it says to "click to add files" 
3. When I am on my computer I will open my file in PSD format size 73.6mb
4. ....the lag time to create text on the image is so slow, really slow. I end up quitting the program and heading over to Canva.
5. ....I have 16gb of RAM, Is that to small for this program? 
6. I have the paid version no ads which I thought would help with the laggy glitchy Ness but does not seem to help with the Laginess of the program in the app or browsers. 
7. Please provide suggestions to make this program run smoothly.

**Comment by photopea** [comment]
Where does Photopea say "click to add files"?

And how do you open your 73.6mb PSD in Canva?

**Comment by LaserFocusedUS** [comment]
The "click to add files" is here in this forum when I am writing my comment. It must disappear once submitted. 

I don't use the PSD file in Canva. I go there to design what I would like to design in Photopea when it is laggy. 

I did make a smaller file in photopea than the original one I was using and it did help a little. 

Is there a recommended max file size to use in photopea?

**Comment by photopea** [comment]
If you make documents 2000 x 3000 pixels (6 million pixels), it should be fine. But if you make documents 20,000 x 30,000 pixels (600 million pixels), and have too many layers, rendering so many pixels can take up to half a second.

Do you have WebGL available? You can check it under More - Use WebGL.

You can use www.vectorpea.com for your work (more similar to Canva / Illustrator, rather than Photopea / Photoshop).

**Comment by photopea** [comment]
I have to close it because of lack of details :(
