### ISSUE TITLE
recorde_new.php slows down startup speed

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#6815]
record_new.php prevents cached Photopea from starting up quickly. What does it do?
![屏幕截图 2024-06-01 021404](https://github.com/photopea/photopea/assets/79258245/56c2af57-4d20-440a-a6f5-91b11dd7a3ef)

**Comment by photopea** [comment]
If you set the foreground color to purple, it is saved in your cookies. But if you press "Account" at the top and log in, this record (foreground color etc) will be saved on our server. If you use Photopea next time, and log in (even on a different device), Photopea will download your record from our server, and set the foreground color to the one from your record.

It can not be cached, because the foreground color might be different for each user. But we could make it faster. Are you sure it takes 500 ms because of our server and not your internet provider?

**Comment by photopea** [comment]
We need to check if you have a Premium account or not, and then, we show or not show you the ads, and the rest of the UI.

If you dont have Premium, just log out, this record will not be downloaded then.

**Comment by photopea** [comment]
In my case, "record_new.php" is takes between 90 and 120ms to load. My guess is, that our server processes it in 10ms, and the rest of the time is the delivery of data, which depends on your internet provider.
