### ISSUE TITLE
Brush size type selector in Firefox

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#689]
Brush size type selector in Firefox seems broken. Icons for brush types/sizes are missing.

**Comment by photopea** [comment]
Hi, it looks normal in Firefox for me. What do you mean?

**Comment by hxim** [comment]
I think I did not clicked Allow Data Access when it asked
"Will you allow www.photopea.com" to use your HTML5 canvas image data? This may ..."
When I click Allow and then refresh page it shows icons normally but when I close this message or click Don't allow it is not working. See screenshots
![scr2](https://user-images.githubusercontent.com/6370548/39568103-659b5c30-4ec1-11e8-8fb0-ae04e2912d71.png)
![scr3](https://user-images.githubusercontent.com/6370548/39568114-6d6d1ec6-4ec1-11e8-8f06-36444cd5e483.png)

**Comment by photopea** [comment]
I see that Firefox did that because of "canvas fingerprinting". They say, that Canvas draws graphics differently for each user.

Reading the canvas data is essential for photopea. We use it mainly to rasterize vector graphics. The canvas should draw graphics the same way for all users. I suggest to report it as a bug in Firefox.
