### ISSUE TITLE
Not printing on Photopea page, opening new tab on browser

### ISSUE THREAD

**Issue by glapere** [photopea/photopea#6965]
Your Operating System: Microsoft
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too: YES, tried that too

**This must be done to see the problem**
1. Go to www.photopea.com
2. Input dimensions & upload document/design
3. Click print
4. ****print will bring you to new tab on browser (I've tried firefox, chrome and bing with no luck) INSTEAD of printing on photopea page. 
I printed several times today before 3 pm successfully and by 8 pm it has not worked once. 

*******IF YOU HIT PRINT FROM HERE: It will print out tons of pages of coding. Not the image you loaded*****

**Comment by photopea** [comment]
When I press File - Print, a new tab is opened, which offers me to print my document. What exactly happens when you press it?

![image](https://github.com/user-attachments/assets/77815fdf-11f8-4341-a327-4acb5ca9fffd)

![image (1)](https://github.com/user-attachments/assets/7fd9767a-93c9-46c5-976d-80e2d0c5814f)

**Comment by photopea** [comment]
It should work as before now.
