### ISSUE TITLE
Unable to open SVG exported from openstreetmap

### ISSUE THREAD

**Issue by dark-light-cz** [photopea/photopea#7038]
Your Operating System: MacOS Sonoma 14.6.1 
Your Web Browser: Safari or Chrome

1. Go to www.photopea.com 
2. Uplodad svg exported from Openstreetmap
3. Error message is shown
![map-2](https://github.com/user-attachments/assets/73c0670c-f1ca-4fe3-9053-6475566f5153)

**Comment by photopea** [comment]
Photopea does not support vector patterns. So I changed it - it will use the orange color instead of vector patterns, it should work now.

BTW. your file contains too many layers. Photopea is a raster editor and it needs to convert each vector layer to a raster image for blending. You can open your file in www.vectorpea.com which is a vector editor, so it is opened and rendered much faster.
