### ISSUE TITLE
Black rim appears when exporting DDS

### ISSUE THREAD

**Issue by c2oh25n3o** [photopea/photopea#7059]
Your Operating System: Windows 10
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too: yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Open PNG or DDS file (exported from game files and/or saved from Photoshop)
3. Choose 'Export as DDS'
4. See the black outline appear to the bottom and to the right of the image, adding 2 pixels to those sides

I wonder if that's a bug or not, and is it possible to get rid of it? Some time ago I already went through the same process and somehow managed to get the images without the rim, but now I can't remember how I did that. Any help is appreciated! <3

![ppea](https://github.com/user-attachments/assets/3f60fedb-56a7-41a1-8c64-5bfe625d859d)

**Comment by photopea** [comment]
I think that DDS files must have the width and the height to be a multiple of 4 (4, 8, 12, 16, 20, 24, 28, 32 ....)  See .e.g. here: https://superuser.com/questions/684689/cant-convert-to-dds-file-because-width-and-height-are-not-multiples-of-four

254 and 334 can not be devided by 4, so Photopea must expand it by 2 pixels (256 and 336).

So a DDS file 254 x 334 pixels can not exist. If you think it can exist, please, show us such a DDS file as a proof.
