### ISSUE TITLE
Problem with RAW photos from Nikon Coolpix B700

### ISSUE THREAD

**Issue by photopea** [photopea/photopea#7183]
files are here: https://we.tl/t-ASOrTJLaAQ

**Comment by Jan-Flaska** [comment]
The files were deleted from the original repository, here we go again:

https://drive.google.com/drive/folders/1RVjaCSOaXtkis_8mTIoSz18PtfvdCjis?usp=sharing

Photopea attempts to open the NRW file, the result, however, is distorted (due to optical correction not being applied, which is fine for a RAW file) and the colours are distorted (with magenta lines throughout).

**Comment by photopea** [comment]
It should be fixed now.

The photo requires some lens correction. Since we cannot extract parameters out of NRW files, you can do it manually using Filter - Lens Correction.
