### ISSUE TITLE
PSD saved from Photopea no longer viewable with IrfanView

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#723]
When I try view psd file saved with (latest version of) Photopea with IrfanView it is no longer working. It was working month ago. Also if I only open PSD file which I saved month ago and save it with no changes saved  file is different from original and is not possible to view it in my IrfanView image viewer. It seems you changed how are PSD files saved or something.

**Comment by photopea** [comment]
So here is the thing. PSD files contain the final rasterized image at the end of the file. It usually takes 20 to 40% of the file (or even 80% of the file, if the file consists only of vector shapes). This image is redundant, because it can be reconstructed from the layer content.

I decided to remove that image from the resulting PSD. It makes PSD files up to 40% smaller, and the PSD is exported faster (useful for large PSDs). Regular image viewers apparently use that raster image at the end of PSD.

What do you think we should do? Should we make PSDs larger while attaching a final image?

**Comment by hxim** [comment]
Hmm... Yes I prefer old behaviour with ability to preview in IrfanView and slightly larger file. I guess Photoshop also always saves that final image inside psd file or not??

**Comment by photopea** [comment]
In Photoshop, you can set "Maximum Compatibility", which will preserve this preview.

**Comment by Ser-Gen** [comment]
I think, `psd` sould include rasterized image.
Maybe add option like in PS.
There are programs, that can't reconstruct image from layers data or can't apply some effects.

**Comment by photopea** [comment]
I fixed it, PSDs do contain rasterized image now for more basic image viewers.

BTW. Photopea can generate "minified" PSDs now (that use ZIP compression, still a standard PSD). Such PSDs are up to 4x smaller, but take about 4x longer to generate (e.g. you can get a 26 MB PSD in 700 ms, or 6 MB PSD in 2.9 sec), they also miss the rasterized image.  The minified PSDs are available only for saving to the server (https://www.photopea.com/api/) - that was the original reason for creating them.
