### ISSUE TITLE
Layer Selection Not working when using the Ctrl Key

### ISSUE THREAD

**Issue by ClippySystem32** [photopea/photopea#7257]
Your Operating System: Windows 10
Your Web Browser: Google Chrome 129.0.6668.101 (Official Build) (64-bit)

**This must be done to see the problem**
1. Go to www.photopea.com
2. Make a new Layer or multiple
3. Try to select multiple layers using the Ctrl Key

**Comment by photopea** [comment]
I just checked and everything seems to work as it should.

You told me your OS and your browser, but you did not tell me which browser extensions I should install, in order to see the same beahviour as you do. Could you tel me which extensions I should install and what settings should I apply in these extensions in order to see what you see happen?

**Comment by ClippySystem32** [comment]
I Updated my browser and things ended up working normally

**Comment by photopea** [comment]
okay.
