### ISSUE TITLE
UX improvement suggestion. Please help

### ISSUE THREAD

**Issue by DavidJGrimsley** [photopea/photopea#7258]
Hello I have made some changes to the Photopea UI based on how much I dislike the original UI and and confused all the time. Please take a look at my [Photopea prototype in Figma](https://www.figma.com/proto/9JWt2VfT3yEuVrMgoIJsD4/Photopea?page-id=0%3A1&node-id=1-2&node-type=canvas&viewport=294%2C377%2C0.69&t=UKue1dVAnbF8igOn-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=1%3A2) and let me know what you think. I need feedback for my homework assignment so please help me. I'm counting on you ;).
![Home](https://github.com/user-attachments/assets/9270d98d-3294-4181-912f-607eb6e22105)
![Open from Computer](https://github.com/user-attachments/assets/182afd6d-af4c-426b-ba21-47df2cc09749)
![ProjectOpen](https://github.com/user-attachments/assets/e22e8deb-c466-4ca7-b96f-fb0ce3859d92)

**Comment by Mayur-hot** [comment]
Home? Homework?
You added Home button for Homework. :)

Instead of recent, I prefer Drag and Drop... + Recent is not reliable for web/browser based online apps..

Current Design of Main Screen is Nice & Simple.. + Modern Browser Already Shows Recent in File Open DialogBox..

+ For having TOOLTIP on hover of each tool with video/tutorial links, I think no need for that, that will create a mess.. and covers design area, and useless for advance users.

tutorial link already there, user can read / learn..
https://www.photopea.com/learn/
https://www.photopea.com/tuts/

This is my personal onion, but I appreciate your design too 

Thanks a Lot DavidJGrimsley :)

**Comment by photopea** [comment]
I think you should discuss it on reddit: https://www.reddit.com/r/photopea/comments/1g89m5r/ui_improvement_i_need_your_input/

**Comment by DavidJGrimsley** [comment]
Cool thanks. But no one is responding on Reddit and people are responding here. Maybe I just won't use Photopea anymore?
