### ISSUE TITLE
lenta

### ISSUE THREAD

**Issue by Isaias-134** [photopea/photopea#7262]
photopea se alenta mucho despues de usarla un par de minutos

**Comment by Mayur-hot** [comment]
![Opera Snapshot_2024-10-22_120744_www google com](https://github.com/user-attachments/assets/8ccf8160-793b-486b-9fb2-2d326b046044)

**Comment by photopea** [comment]
We can not remove ads, since it is the main source of our income :(

**Comment by BlackSp1der** [comment]
I didn't say to remove the ads. The problem is that the ads have priority, and the work routines are secondary. You should manage the priorities better; loading ads so continuously to show more ads degrades the app's performance. I can't consider moving to a paid plan if I see the app doesn't work well. In the end, you lose the audience's interest. I've already stopped using it.

**Comment by photopea** [comment]
@BlackSp1der could you run the Peamark test? Press More - Peamark, it takes 5 seconds.

I think only about 10% of our users have slow hardware, which can not handle ads and photopea simultaneously. 

What do you mean by "ads have priority"? How should I change that priority?

**Comment by BlackSp1der** [comment]
I don't think it's because the hardware is old. It didn't happen before, and I've been using Photopea for a long time. When the ads change, the interaction with the editor stops, which suggests the routines aren't running in different threads.
But it doesn't matter if the paid version works well.
