### ISSUE TITLE
lagging issues

### ISSUE THREAD

**Issue by kungfufighting-duduu** [photopea/photopea#7263]
Your Operating System:windows
Your Web Browser:google
The problem happens in the Incognito Mode, too: no

**This must be done to see the problem**
1. Go to www.photopea.com
2. start doing things anthe lag will start

**Comment by suomi35** [comment]
I am having the same issues. I think it's related to the continuous stream of 3+ ads in the right column. It gets worse the longer I work on an image.

**Comment by photopea** [comment]
Can you press More - PeaMark and tell us your score?

**Comment by Eve-Roblox** [comment]
**I have massive lag issues** , **click delay** is **10 - 20 seconds** and **frames per second** are about **3 normaly** wich **makes Photopea** really **unusable**. This **lag** is probably **because** of **video ads playing** because **when they're** **loading** (the ads) it's **run**ning completly **fine** **with** about a **100 fps** and close to **no click delay**. I am really **thinking about** just **buying photoshop** because it **takes me** about **5 - 20 times** more time **to make** an **image** **than before**.

**Comment by photopea** [comment]
Please make a proper report. It is not clear if you use an iphone or a
chromebook.  Or whether you use any browser extensions, which could be
modifying our ads and making them slower.

**Comment by suomi35** [comment]
> I am having the same issues. I think it's related to the continuous stream of 3+ ads in the right column. It gets worse the longer I work on an image.

Sorry for the delay. I get a range of results from PeaMark:
CPU: from 500s - 600s
GPU: from high 200s to high 300s

**Comment by photopea** [comment]
Did you try to click the "X" at the top right corner of the ad, to close it? Does it help?

**Comment by photopea** [comment]
I have to close it, because nobody is responding to me.
