### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by LotP1** [photopea/photopea#7275]
Your Operating System: Windows
Your Web Browser: Chrome (standalone install)
The problem happens in the Incognito Mode, too: yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. open the chrome taskmanager (shift + esc)
3. You will see that Photopea's memory usage goes up over time.

The page starts at ~80 MB ram used.
After about 30 minutes the page was using ~1.2 GB ram.
When a new ad loads you can see the ram usage jump by a couple MB.
Turning off the computer's internet while the first ads are loading causes the page to falsely detect an adblocker, and no ads load (of course). After about 30 min of running without internet the ram usage actually fell to about 75 MB used.

This leads me to believe that the ads are causing the memory leak. My guess would be that the website loads new ads every ad-refresh if possible, without deleting the older cached ads. The ads are definitely cached as disabling internet after ads have loaded and refreshed a few times will not cause the "Adblock detected" warning and the ads will keep refreshing without pulling new ads over the internet.

**Comment by photopea** [comment]
I think someone reported it before. But it is hard to tell whether it is really a memory leak (ads ask the browser to keep some data in memory), or it is how a browser works (ads clear data properly, but a garbage collector in a browser does not collect these data, as there is plenty of RAM still free on your device).

**Comment by LotP1** [comment]
If the home page can cause more than 1.2 GB ram to be used just because of the ad provider, then it'd categorize it as a memory leak personally.
I think i've read the last issue about this and iirc you mentioned that your ad provider takes care of this stuff for you. Could you try bringing this up with them?

**Comment by photopea** [comment]
Can you use the Developer tools in Google Chrome? There is a memory snapshot feature. I remember when I did it, it showed me the usage of 100 MB, while keeping a mouse cursor "over a tab" showed me 2 GB. So I think these extra data / leak could come from Chrome itself, and not from a website (and it could be triggered by something what ads do).

**Comment by LotP1** [comment]
Interesting
.Dev tools is only showing 571 MB used, while Chrome Taskmanager is reporting 1.7 GB.

**Comment by Ausfilm** [comment]
Just commenting to +1 that I've been noticing similar issues for the last week or two on an older Mac using the latest Chrome.

Photopea as a desktop app lags to the point that many tools and key commands simply don't function.

Attempting to dig into this a bit, I had a look at the chrome inspector and the memory use sat at around 600mb - not terrible so I don't think this is the actual cause of the issue.

What did stand out was that there was an alert 'Reading cookie in cross-site context may be impacted on Chrome', this itself is not so much of an issue but the frequency of the alert was noteworthy - it is occuring thousands of times a minute, to the point that there were over 10,000 alerts within a few minutes of having the app open, implying there is some script that is constantly firing. These alerts occur in chunks of a few hundred at a time, and these line up exactly with when the app starts to grind to a halt.

Further looking into what those cookie reads relate to - it appears they are linked to the ad bidding process. My guess is that with ~5 ads and the regular refresh happening every 30 seconds user's computer is managing thousands of outgoing and incoming bids for the ad slots each minute, some of which might be getting delayed and compounding over time.

To further test if this issue was ad-related, I deleted the entire ad sidebar stack using the inspector, meaning the actual ad iframes were no longer in the DOM. The alerts didn't immediately stop, nor did the lag, but after about about 30 seconds the console stopped showing alters/errors and the lagging was gone. 5 minutes of use later and it's still fast and snappy without the ad side bar, which suggests the active bidding process might be where the issues lie.

Personally, knowing the ads are the issue I think the solution is to purchase an ad free account, but I thought it worth logging this here in case it helps to narrow down the issue.

**Comment by photopea** [comment]
I am thinking more and more about removing ads from Photopea completely. If only 1% of our usrers paid for Photopea Premium,  it would fully cover for the loss of the ad revenue (i.e. 1 in 100 people paying would allow us to provide it to the other 99% of users for free). Right now, about 0.05% of our users pay for Premium.

Do you think we should introduce some "harsh" measures to encourage free users to go Premium, like "save a PSD only 4 times a day", or "use Photopea only 4 hours a week" without Premium?

**Comment by LotP1** [comment]
personally i'm trying to stay away from subscriptions, that's why i went with Photopea instead of Photoshop.
i'd happily pay for like 3 years as a one time fee instead if possible.

**Comment by photopea** [comment]
We don't have subscriptions, we only have one time fees.

**Comment by LotP1** [comment]
the "Go Premium" menu only has subscription options tho?
![image](https://github.com/user-attachments/assets/156383db-dc73-45b5-8bce-014fbcaafdbd)

**Comment by photopea** [comment]
I think a subscription is when you are expected to pay regularly, usually you must give someone permission to take money from you automatically.

You mentioned 3 years. So you cak pay $50 for a year and then you see, if you like it, you can pay again. It would be $150 for 3 years without ads.

**Comment by LotP1** [comment]
I've been using Photopea for more than 3 years at this point, but I haven't bought premium yet as i don't like paying for software or services that expire if possible.
How much would you sell a perpetual license for?

**Comment by photopea** [comment]
We do not offer any perpetual license, sorry.

**Comment by photopea** [comment]
I had Photopea opened for 15 minutes, doing nothing, and it never exceeded 320 MB of RAM.

Does it still happen? My ads provider is looking into it, but if they can't do anything, the only thing I can recommend you is getting a Premium account :(

**Comment by Ausfilm** [comment]
Hi Ivan, just noting that as previously mentioned we tried to pay for premium for a year to get around these issues with the ads. If you're having problems with not many people paying premium, it might be worth revisiting that payment process as it's pretty confusing and seems to have failed for us at the payment stage.

Points of friction include:
1. Not being able to immediately find how to subscribe (or "Go premium" as its called here) easily (turns out it's under account - then you have to click 'I accept' and then click one of 12 price options that don't specify the currency and aren't immediately identifiable as buttons)
2. Once you click the price you are then bounced out of the web app back to your browser and asked to log in on a page that is pretty bare bones and doesn't offer an email login option - only 'sign up with google', 'sign up with facebook' etc. which has some drawbacks. While the barebones design is fine, it makes you hesitant to hand over credit card details if it feels like the page feels cobbled together.
3. Once signed in you're bounced to a Czech payment processor. Unfortunately a vast majority of people in the west will view this with great suspicion, as it's both an unfamiliar processor and has a country code European domain name, which is often associated with scams.
4. Having provided credit card details, the payment didn't actually process and simply says "it may take up to a day to verify" without much more detail - this is a completely unfamiliar payment result that I've never encountered before, and had I not seen how much work you've put into Photopea I would almost certainly assume at this point that I had been scammed and my credit card details stolen.

To increase the chance of people actually paying I'd strongly suggest simplifying the subscription options, the signup process, and the payment process. A three step popup window with the user flow of: price > enter email/password to login/signup > Stripe credit card payment fields is about as complicated as you can get before people start dropping out of the process.

In my case I really want to pay and have struggled to do so, I can't imagine how less enthusiastic people would react. Hope this is of some help!

**Comment by Ausfilm** [comment]
To follow on from the above - I've re-checked the payment processor status 24 hours later and it says the payment has not been made - no suggestion of a remedy or any pending/attempted charges on my card.

**Comment by photopea** [comment]
Hi @Ausfilm . All prices contain the sign of the US dollar - "$". I receive hundreds of payments each week, almost all from people outside Czechia, and nobody ever complained about the "complicated process". So I think you might be making it up :/

I think asking a person to type their email address, or to come up with a password, would be the opposite of "simplifying", since now, logging in with e.g. a Microsoft or a Google account takes like two clicks.

"european domain name is associated with scams" - that is completely crazy, I don't know what to tell you.

Payments work immediately and if you could not pay, the payment was probably blocked by your bank, so you should get in touch with your bank. Maybe your bank thinks that any company outside your country must be "associated with scams".
