### ISSUE TITLE
API -> Can't rotate text using .rotate()

### ISSUE THREAD

**Issue by arthur469** [photopea/photopea#7283]
Your Operating System:Windows11
Your Web Browser:Chrome, firefox, IE
The problem happens when i open generated url using API:

Hi. I use the API of Photopea and i'm trying to rotate a text but the function rotate that is provide in [Photoshop script documentation](https://github.com/Adobe-CEP/CEP-Resources/tree/master/Documentation/Product%20specific%20Documentation/Photoshop%20Scripting) don't seem's to work. Any ideas ?

Also, RasterizeType() (=pixelize) don't work either. It erase all text content.

```
"script": """
        var doc = app.activeDocument;
        var textLayer = doc.artLayers.add();
        textLayer.kind = LayerKind.TEXT;

        var textItem = textLayer.textItem;
        textItem.contents = "Hello, Photopea!";
        textItem.size = 50;
        textItem.font = "Arial";
        textItem.position = [doc.width / 2, doc.height / 2];

        // Apply rotation
        textLayer.rotate(-45, AnchorPosition.MIDDLECENTER);
    """
```

**Comment by photopea** [comment]
Currently, Photopea can rotate text layers only if the font is already loaded. Also, Photopea cannot pause the script execution. Since the font "Arial" is not loaded when you call rotate(), the rotation is ignored. You have two solutions:

1. Call rotate() about 2 - 5 seconds later than the rest of your script
2. Run your script only when the needed fonts are loaded. E.g. run it in a document which already contains a text layer with the Arial font. Or provide the Arial font in "resources", if you use our API.
