### ISSUE TITLE
Doesn't draw at cursor position

### ISSUE THREAD

**Issue by PatrickOne1** [photopea/photopea#730]
Hi!
I'm using Firefox 60.0.1 on a Microsoft surface 3 pro pc/tablet. When ever I try to draw the drawn isn't placed where I hold the cursor. Instead it's placed up and to the left (about 315 degrees), how do I fix it, is there some setting?
At max zoomed in it's one pixel left and one up, but at other zoom it can be 10 or more pixels, seems to be about same fysical differnce on sctreen each time.

**Comment by photopea** [comment]
Hi, I guess you have a high-DPI display.  This is a known bug in firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1107646  (I am Ivan Kuckir in that discussion).

You can write there to encourage them to implement it (it has been open for 4 years). Otherwise, try some better browser. See here: https://caniuse.com/#feat=css-image-set
