### ISSUE TITLE
Erro na instalação

### ISSUE THREAD

**Issue by DavidDeveloperBots** [photopea/photopea#7318]
Estou tentando instalar o Photopea, mas encontro dificuldades ao interagir com o botão "Mais", E o bota installa ta desabilitado Esse botão parece não responder, impedindo a continuação do processo de instalação. O erro ocorre todas as vezes que tento, mesmo após verificar a estabilidade da conexão de internet e reiniciar o dispositivo.

Acredito que possa ser um bug, pois o botão simplesmente não exibe nenhum tipo de resposta, como mensagem de erro ou indicação de carregamento. Isso torna difícil entender o que está impedindo a instalação.

**Comment by DavidDeveloperBots** [comment]
aberto aonde?

**Comment by DavidDeveloperBots** [comment]
Tipo eu tentei installa ele
Ai ele ficou na minha barra fixada
E quando eu eu sair do photopea 
ai fui abrir dnv e nao tava mais la

**Comment by DavidDeveloperBots** [comment]
![image](https://github.com/user-attachments/assets/2792235c-a80c-4716-840d-1b1de8f174af)
isso ai quando aperto não installa

**Comment by photopea** [comment]
Did you read my article?

Open "about://apps" and uninstall Photopea. Then, you can install it again.

**Comment by DavidDeveloperBots** [comment]
OBRIGADO!!!

**Comment by DavidDeveloperBots** [comment]
tem como tira o negocio de anuncio do lado?

**Comment by DavidDeveloperBots** [comment]
pra deixa o photo mais grand

**Comment by photopea** [comment]
Yes, but you must pay for the Premium account. 90 days without ads cost 15 USD. It looks like this: https://www.photopea.com/promo/no_ads.png

**Comment by DavidDeveloperBots** [comment]
sem dinheiro faz de graça ai kk

**Comment by DavidDeveloperBots** [comment]
ei photo
euu quero abaixa a imagem com
com tamanho e o que coloquei 
me ajuda

**Comment by DavidDeveloperBots** [comment]
quando eu salvo a imagem ele fica assim
![Picsart_24-07-23_03-36-34-590](https://github.com/user-attachments/assets/207a14b3-7b8f-4cd6-aa7d-30b5fe4b3c22)
sabe disse como abaixa sem aparece isso??
pfv

**Comment by DavidDeveloperBots** [comment]
www.photopea.com/#iboZ_GF-T ser vc entra vai ver o jeito que eu quero

**Comment by mrrfyW** [comment]
> sabe disse como abaixa sem aparece isso??
Did you export the image correctly? Or perhaps did you click "Reveal All"?
You can always crop the image back to the resolution it shows in the PSD link, since that appears to have been the fixed version. Also, I exported the image myself, and it didn't show the gradients outside of the image's frame.
Next time you mention an issue like this that feels unrelated, I'd rather you not post it here, this just seems like general Q&A. You can always figure out more about how Photopea works with https://www.photopea.com/learn/, might need to use a translator if you want to understand it all, since it's all in English.

**Comment by photopea** [comment]
I will close it, because we accept only reports in English, and doing it thorough google translate is too hard for me, with a risk that important things might get lost in translation.
