### ISSUE TITLE
Photopea is not working-mixed issues.

### ISSUE THREAD

**Issue by rainynightmare** [photopea/photopea#7335]
Good evening !
Photopea is not working while using the Brave browser , the functions seem to stop. 
Everything works badly -for example, when you want to use the Free Transform tool it will not allow you to do
so and neither if you want to addsome kind of PSD effect to a job- , the files open but then you can't close them.
I've visited the site a thousand times and the error doesn't seem to be resolved.
The gif tools are very slow, morewhen you want to save a modified gif with some kind of psd files or something like that.
Sometimes you open a large file and the entire Photopea site crashes causing the computer to freeze completely.
My system is Windows 10 Version 22H2 for x64. 
These problems have been around for a long time. I forgot to mention that sometimes when you leave the site open for a while -for example ten minutes- the work is completely lost if you don't leave a folder or something open to prevent that.
The tools are excellent and the service is as well, if you could fix all this I would be very grateful !
Thank you very much in advance. Best regards.

**Comment by photopea** [comment]
Hi, we have been discussing many bugs with Brave, e.g. see https://github.com/brave/brave-browser/issues/41552

They decided to "improve" your experience by modifying our source code when it runs in Brave. They probably do it mostly because of ads, but their "improvements" break many other features, too.

Did you try to disable the Brave Shields? I think if you disable them, Photopea should run without their "improvements", just like it would run in a normal browser like Safari or Firefox.

**Comment by photopea** [comment]
I am closing it, as we can not do anything about it. You must use a web browser which works according to web standards, if you want Photopea to work.
