### ISSUE TITLE
Multiple smart effects added when inverting an imported image

### ISSUE THREAD

**Issue by Atomk** [photopea/photopea#7376]
Your Operating System: Windows 10 64bit
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too: yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Drag an image into Photopea (home screen or existing project)
3. Do the step above again, so the image will be opened in a different mode (smart object? I lack some knowledge here)
4. Use `CTRL`+`I` multiple times to invert the image colors
5. Notice how a new "smart effect" is added each time you press `CTRL`+`I`, intead of just toggling the existing one

**Comment by photopea** [comment]
This is how it should work. Adjustments on smart objects are added in a "non-destructive" way, as smart filters. In your case, you can do a step back instead of pressing Ctrl+I again, if you want to avoid having multiple smart filters. You can also disable or delete the smart filters by dragging them to a garbage bin.
