### ISSUE TITLE
Crashes when export Variables in PDF

### ISSUE THREAD

**Issue by TheRadicalDreamer** [photopea/photopea#7379]
Your Operating System: chromeos 

Your Web Browser: chrome
The problem happens in the Incognito Mode, too: yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Open this file [Cardsv2.zip](https://github.com/user-attachments/files/17972550/Cardsv2.zip)
3. Load this data set [Cartas.csv](https://github.com/user-attachments/files/17972565/Juicio.Final.-.Cartas.-.Cartas.csv)
4. Export from Image > Variables > PDF
5. Photopea hangs up and the app crashes

**Comment by photopea** [comment]
Did you try to export your PSD as a PDF without variables?

You have two vector layers, one has 4126 knots / 64 paths, another has 975 knots / 43 paths. Since there are no boolean operations in PDF paths (Subtract, Intersect ...), Photopea must check the intersection of every two paths, to generate a correct PDF path.

I changed Photopea - the merging step is skipped if there are more than 30 paths within a layer. It should still give you a correct result in your case.

**Comment by TheRadicalDreamer** [comment]
Thanks, now it works.

But i wonder, why this file could be exported before correctly?

I made this file over 2 years ago, and i have exported with variables a couple of times before, so what changed?

**Comment by photopea** [comment]
I probably changed the conditions for how many paths it should not do the
intersection test. Photopea is updated almost every day.

**Comment by photopea** [comment]
BTW. we just found out that PSD file can store fill-rules, so we can remake Photopea and avoid the shape merging step during the PDF / SVG export: https://github.com/photopea/photopea/issues/6957
