### ISSUE TITLE
Beige Screen?

### ISSUE THREAD

**Issue by starriescythe** [photopea/photopea#7389]
Your Operating System: (I'm not sure? It's a Chromebook w/ a Google Play Store so...?)
Your Web Browser: Chrome :3
The problem happens in the Incognito Mode, too: No, but a different problem happens there

**This must be done to see the problem**
1. Go to www.photopea.com
2. That's it. It just gives me a beige screen when on a normal browser

It shows up in Incog Mode but when I logged into my account, the peadrive was empty (I saved multiple times and it was there before the beige screen) and a important thing was in there ):

**Comment by photopea** [comment]
Your browser extensions could be breaking Photopea. So I would start with finding an extension which breakd Photopea and turning it off, or asking the person who made this extension for you to fix it.

If you log in into Photopea and your Peadrive is empty, it is probably because you logged in under a different email address than before. Each email address in Photopea has its own Peadrive storage.

**Comment by photopea** [comment]
I have to close it because nobody is responding :(
