### ISSUE TITLE
Vectors don't export correctly on PDF or SVG

### ISSUE THREAD

**Issue by TheRadicalDreamer** [photopea/photopea#7401]
Your Operating System: chromeos
Your Web Browser:chrome
The problem happens in the Incognito Mode, too: yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. open this [PSD](https://github.com/user-attachments/files/18087589/defund.zip)
3. Export it to PDF or SVG
4. It will look like this:
![image](https://github.com/user-attachments/assets/1a609e5f-2a9f-4eb8-9607-92a43179ca99)

**Comment by photopea** [comment]
This is happening exactly because of me fixing this: https://github.com/photopea/photopea/issues/7379 

The PDF export of vector shapes can either be correct and slow, or incorrect and fast (as it is now). You can fix it yourself by not having intersecting paths within one layer (e.g. merge them all).

**Comment by TheRadicalDreamer** [comment]
Yes, in fact i did that after. I merged them. But still i thought it was a weird behaviour.

And, what if when trying to export to a SVG or PDF with too many anchors, Photopea tells you that you have too many anchors, so probably the result won't be correct?

**Comment by photopea** [comment]
Okay, now, Photopea will tell you about skipping the vector merging process.
