### ISSUE TITLE
Accidentally uploaded very personal photo to imgur

### ISSUE THREAD

**Issue by kiki2804-bit** [photopea/photopea#7422]
Your Operating System: Windows
Your Web Browser: Google Chrome
The problem happens in the Incognito Mode, too: no

**This must be done to see the problem**
Hello,
I was editing my ID document on Photopea and when I wanted to save that picture, I accidentally uploaded it to imgur. I really need help with locating that picture (finding its url adress) and then taking it off the imgur because it is my very personal document in question.

Please help me and thank you in advance.

**Comment by photopea** [comment]
uploading the image to Imgur through Photopea is the same as uploading it at www.photopea.com . We do not track which files our users upload, or what are the URLs of these images.

Only Imgur can delete these images. So you need to ask Imgur. But since you dont have a URL, I think nobody will ever see your image, as it is impossible to "guess" the URL of an image.
