### ISSUE TITLE
I saved it as a .dds file, and the proportions changed.

### ISSUE THREAD

**Issue by sudtichai** [photopea/photopea#7457]
Your Operating System: Win11
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. Created at 100x50 px
3. Added a gradient background
4. Saved as a .dds file

After saving, the image size became 100x52 px, and sometimes 104x54 px.

![สกรีนช็อต 2024-12-31 152112](https://github.com/user-attachments/assets/de4c5bc2-7aec-4fb4-93a8-b14c655ffd5f)

**Comment by photopea** [comment]
Have you ever seen a DDS file which is 100 x 50 pixels? If yes, could you show it to us as a proof?

I think the width and the height of DDS files should be a multiple of 4, so you can have only 48, 52, 56, 60, 64 .... What size would you like it to be instead of 50 pixels? If you want extra pixels, what color should these extra pixels have?

**Comment by sudtichai** [comment]
Here, check out the video.

https://youtu.be/WAYZkMxXYtg

**Comment by photopea** [comment]
As I said, DDS files of your dimensions can not exist. Do you understand what I am saying?

**Comment by sudtichai** [comment]
Oh, I understand. Thank you very much.
