### ISSUE TITLE
Question: when opening PDFs, can the resolution used for rendering be set?

### ISSUE THREAD

**Issue by k-risc** [photopea/photopea#771]
When I open a PDF with Photopea, the resulting image seems to be rastered with 72dpi. Can this be changed somehow?

**Comment by photopea** [comment]
Hi, I set the default PDF resolution to 150 dpi. I am afraid to use more, because if you open a PDF with many pages, there may be not enough memory to rasterize them all.

You can change the DPI using Image - Image Size. You can set Pixels + DPI : inches will be deduced, or inches + DPI : pixels will be deduced (resampled).

**Comment by k-risc** [comment]
Ah, so you do not re-calculate using the rastered image if dpi and pixel side are increased, but you re-raster out of the pdf data?

**Comment by photopea** [comment]
I don't know what you mean. PDF is a vector format and it can be rasterized at any precission. PDF is converted into a PSD when it is loaded. 

The PSD has three properties: Size in PX, size in Inches, and DPI. Any of these values can be re-computed from the other two (so PSD files store only two of them).

Some PSD layers are special: Vector shapes, Text layers and Smart Objects. Their pixel data are irrelevant, since they can be re-rasterized at any time with any precission. 

Photopea converts PDF elements into Vector shapes, Text layers and Smart Objects.

**Comment by k-risc** [comment]
Sorry if I wasn't clear enough. What I mean is that PDFs can contained image data that is already rastered. I thought that if such a pdf is opened, these images are rastered once in the final resolution (currently in Photopea being 150dpi). So a DIN A4 sheet of paper, 21cm wide, about 8,27 inches, yields 1240px in width.

In Photoshop I can choose the resolution of the rastered image when opening a pdf. If I choose 300dpi, the resulting image will have  8,27 inches times 300 dpi = 2480px.

In order to achieve the same size and resolution in Photopea (setting dpi to 300 and width to 2480px), I thought the result would be computed from the already rastered image, resulting in an image not as sharp as if directly rendered in 300dpi. But it seems the Smart Object does the trick. The image data is not just upscaled and "rough".

**Comment by photopea** [comment]
Adobe Photoshop can not open PDF files. It can only rasterize them, and work with raster (the whole page content in one bitmap)

Photopea is different. It reads vectors and text from PDF, and stores bitmaps from PDF in an original resolution. Scaling Smart objects up or down does not affect their quality.

**Comment by k-risc** [comment]
I am amazed! Thank you for these explanations and the good work.

**Comment by photopea** [comment]
You are welcome :)  You can actually edit PDFs with Photopea: e.g. edit vector shapes or a text, and save back as PDF.
