### ISSUE TITLE
Zoom gradation, notification and resetting settings

### ISSUE THREAD

**Issue by sergey-pimenov** [photopea/photopea#772]
Hi! Firstly, thank you very much for the awesome product. I use it every day and it helps me a lot.

**I.** It is very necessary to do more accurately zooming (in percentages). 

![Zooming](https://image.ibb.co/dQWVbd/zoom_Photopea.png)

Now I haven't the opportunity to zooming by a specific percentage, just only the steps that are predefined by Photopea.

This feature in Photoshop:

![Zooming PS](https://image.ibb.co/kv1tUy/zoom.png)

---

**II.** Also it's highly desirable opportunity to reset all Photopea settings to default.

---

**III.**  It would be nice to limit the number of notifications. Sometimes I call a whole bunch of them and wait a long time until they disappear:

![Notifications](https://preview.ibb.co/mnKNpy/New_Project_1.png)

---

**IV.** When I save for web with shortcut "Ctrl + Shift + Alt + S" Photopea also save .psd:

![Save for web](https://preview.ibb.co/mMjKKy/save_for_web.png)

**Comment by photopea** [comment]
Hi Sergey!
1. There is a slight problem with it. We need Photopea to work without WebGL, and without it, it takes too much time to produce a nice any-percentage zoom. Even with WebGL, I think that zooms like 80% or 110% would look very misleading, pixels would bleed to each other etc. I would rather stay with the current fixed zooms.

2. What settings do you mean? You can use PP with default settings, if you start it in anonymous window, or if you remove all Photopea cookies from your browser.

3. I fixed it, so that the message from a Clone Stamp is printed at most once per second.

4. I fixed it a bit. But you still have to press Alt before pressing S (if you press Ctrl + Shift + S, it performs Save as PSD, even if you add Alt a moment later).
