### ISSUE TITLE
Shortcuts don't work on Microsoft Edge

### ISSUE THREAD

**Issue by klocus** [photopea/photopea#799]
Hello,

Shortcuts don't work on Microsoft Edge. My version: Microsoft Edge 42.17134.1.0

**Comment by photopea** [comment]
Hi, do you mean all keyboard shortcuts? Or just some of them?

**Comment by klocus** [comment]
Yes, all of them.

**Comment by photopea** [comment]
Can you please go here: http://jsfiddle.net/p45f44zb/16 , click into bottom right area and press some keys, if you see anything?

**Comment by klocus** [comment]
Press one key: [null]
Press two keys: window with "undefined" in content.

**Comment by photopea** [comment]
It seems like the Edge does not support KeyboardEvent.code : https://caniuse.com/#feat=keyboardevent-code  . I am quite surprised by that.

It took us many GitHub issues and many hours of struggle to get to the keyboard handling that we have now. I think it would be wrong to remake it, just because the Edge is "behind" in this area.

You can tell Edge developers to implement KeyboardEvent.code , or just use a "better" browser.

**Comment by photopea** [comment]
I see it is being solved here: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/18367767/  . So shortcuts may start working in Edge very soon.

**Comment by klocus** [comment]
Yup, it's my post :)

**Comment by kuckir** [comment]
Cool, we are those who make the future of the web :)
