### ISSUE TITLE
Patch / Select / Lasso tool operations

### ISSUE THREAD

**Issue by kevintey** [photopea/photopea#805]
Hello Photopea,

Suggestions for operations function of Patch / Select / Lasso tool. For example:

Patch tool:
1. Patch tool icon (instead of a mouse cursor, to indicate patch tool is selected)
2. Patch tool + 'Shift' key: (+) Add additional areas to selection
3. Patch tool + 'Alt' key: (-) Subtract selection
4. Patch tool + 'Shift' + 'Alt' keys: (x) Intersect selection _(It will exclude areas not intersected with the new selection)_

*Maybe a small operation icon (+ , - , x) at the cursor of selected tools as well. 

Thanks!

**Comment by photopea** [comment]
Hi, I added the set operations (Union, Subtract ...) to the Patch tool. They can be used from the top bar, or from the keyboard.

There are no appropriate cursors in a CSS spec: https://www.w3schools.com/cssref/tryit.asp?filename=trycss_cursor

We avoid using custom cursors (PNG images), because they do not work properly in Firefox on hi-dpi displays at the moment. If you have any friends at Firefox, please, ask them to fix this issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1107646
