### ISSUE TITLE
brush/cursor alignment

### ISSUE THREAD

**Issue by natrader** [photopea/photopea#828]
When I make a stroke with the brush tool, the stroke shows up to the left and a little higher than where my cursor shows it should be. Not sure if this is a glitch or something that I can fix.

**Comment by natrader** [comment]
thank you, is there another browser that you could recommend?

**Comment by SebastianZ** [comment]
> It is a known bug in Firefox, and they refuse to fix it for 4 years. https://bugzilla.mozilla.org/show_bug.cgi?id=1107646 . Please use a different browser, until they fix it.

> Any other than Firefox. Like Chrome, Opera, Edge, Safari etc.

Two things need to be clarified here. First, Mozilla obviously doesn't "refuse" to implement `image-set()`, they just have limited resources and other priorities. Second, having a look at [caniuse.com](https://caniuse.com/#feat=css-image-set) and making some tests by my own in Chrome, Opera and Edge show that Edge has also does *not* support `image-set()` yet. And Chrome and Opera require to prefix it with `-webkit-`. I can't test Safari, though it looks like it has some limitations, too.

Sebastian

**Comment by SebastianZ** [comment]
> Yes, I know that they have -webkit-image-set. But it is still bether than nothing in Firefox.

Sure, just wanted to clarify that.

> The Edge browser is for Windows 10 only, and as long as it stays this way, I don't think about it as a browser, that will still be here in the future.

Though you recommended it in your previous post, indicating it can handle the use case, which it currently cannot, unfortunately.

> By "refuse" I mean, that they do not give the issue a necessary attention and resources, as it deserves (in my oppinion).

Well, that's your opinion. Btw. it's also mine, that's why I'm on CC on the bug you referred to. Nonetheless there are many, many more features I think should get priority, though are neglected by implementors. And that not only applies to Mozilla, but to all browser implementors. It always depends on the priorities and resources when something gets implemented.

Sebastian
