### ISSUE TITLE
Please add Tibetan Language we can translate

### ISSUE THREAD

**Issue by sonamdawa101** [photopea/photopea#870]
As requested we have huge number of people in Tibet, Bhutan, Nepal and India using photopea. Our language is Tibetan and we would love to translate photopea in Tibetan if you could add Tibetan as new Language for the interface. 

Thank you
sonamdawa

**Comment by photopea** [comment]
Hi, since we don't have money to pay for professiona localizations of Photopea, we let our users translate Photopea into their language.

We made this interface : https://www.photopea.com/translate/ . Please, click on the Tibetan language, and below, you can translate each phrase from English to Tibetan (there are 511 phrases right now). I hope the interface is simple and clear, but if you have any problem, just let me know :)

**Comment by sonamdawa101** [comment]
Thanks . We will do the translation.

**Comment by photopea** [comment]
Ok, thanks! I will publish it once it is translated.
