### ISSUE TITLE
Zoom not working with Active Text tool

### ISSUE THREAD

**Issue by sonamdawa101** [photopea/photopea#880]
While text tool is active I can not zoom the canvas using Ctrl+Alt with mouseScroll or Even with Ctrl plus/minus. It you do the browser is zoomed instead of the photopea canva

![text tool with ctrl alt issue](https://user-images.githubusercontent.com/36448436/45355817-0883f400-b5df-11e8-92de-44c183d8bb8c.JPG)

**Comment by photopea** [comment]
Hi, I think I fixed it. Hope my fix will not ruin something else :D 

Basically, most of shortcuts work differently in a Text Field than outside it. In a Text Field, Backspace removes a character, but otherwise, it deletes a layer. Ctrl+A selects the whole text, but otherwise, it creates a selection of the whole document. So I allowed Ctrl, Alt, Plus and Minus keys to work "normally" even inside the text field.

**Comment by sonamdawa101** [comment]
Working ! Perfect !
