### ISSUE TITLE
Support for PNG export palette selection

### ISSUE THREAD

**Issue by john-bonachon** [photopea/photopea#884]
Would it be possible to select which colors use in a palette for PNG export?
I've also noticed it is very slow/unresponsive.

In other words, Photopea is a bless!

**Comment by photopea** [comment]
Hi, what would be the purpose of such feature?

Currently, Photopea selects the best palette for PNG / GIF automatically. The Quality slider limits the size of the palette.

What exactly is unresponsive? PNG compression is quite hard and it may take several seconds for large images.

**Comment by photopea** [comment]
But what is the purpose of this? Do you just want to make the PNG smaller? Or do you want it to look a certain way? 

If you want the colors and pixels to look a certain way, it should be done with image-editing tools (like Adjustments or Filters), before you export the image.

**Comment by john-bonachon** [comment]
for aesthetics and cheapness

**Comment by john-bonachon** [comment]
but haven't checked the filters yet, maybe there's some color reducer and/or dithering tool

**Comment by photopea** [comment]
The purpose of Save For Web tool is to compress the image as much as possible, without losing too much information. If we let the user to define his own palette, the PNG file would either become larger (with the same quality), or would have worse quality (at the same size) in comparison with our own palette generator.

If your two-color image has only red and blue pixels, and you want to export it with green and yellow pixels, you should do it using Adjustments (e.g. Gradient Map).

Our PNG generator does not do dithering, because our current dithering implementation added too much noise (generated huge files).
