### ISSUE TITLE
Highlight Selected Text

### ISSUE THREAD

**Issue by namalesamamira** [photopea/photopea#9]
This is more of a feature request.

When one select text, e.g to copy it, one is not sure of what they have selected. Could Photopea highlight selected text?

**Comment by photopea** [comment]
Hi, what do you mean? Text can be highlighted with Type tool when you select it.

Maybe the problem is, that "highlight" is just semi-transparent black, so it is not visible on black background. Is that what are you talking about?
![pea](https://cloud.githubusercontent.com/assets/15955558/12529667/5ae12454-c1c0-11e5-8803-af81b0e3aecf.png)

**Comment by photopea** [comment]
I am closing the issue because of lack of additional details about it.
