### ISSUE TITLE
Add distort filters found in photoshop

### ISSUE THREAD

**Issue by hgs54371** [photopea/photopea#903]
Especially displace, that do distort with displacement map, this is often used for compositing

Also polar coordinates, for creating tiny planet effect

**Comment by photopea** [comment]
All filters should work also as Smart Filters on Smart Objects.

There is a problem with Displace.  The PSD only stores the local computer path to the displacement PSD. That displacement PSD should be read each time you redraw the filter (e.g. when you show/hide it). Photopea as a website can not access local paths. I can implement it in a different way (e.g. use another smart object as a displacement map), but I think it would be cool if our Smart Filters worked in Photoshop, too.

**Comment by photopea** [comment]
Hi, so I added these Distortion filters: Pinch, Polar Coordinates, Ripple, Shear, Spherize and Twirl.

**Comment by photopea** [comment]
I added Difference Clouds, too.

**Comment by kevintey** [comment]
> There is a problem with Displace. The PSD only stores the local computer path to the displacement PSD. That displacement PSD needs to be accessed each time you redraw the filter (e.g. when you show/hide it). Photopea as a website can not access local paths. I can implement it in a different way (e.g. use another smart object as a displacement map)

Is it still possible though? When a user selects the displacement filter, a window will prompt to 'upload' the **displacement.psd**. Much like brush preset, its now cached, and users can select how many pixels (horizontal and vertical) to distort after that. 

As per your idea, if smart objects can be used as a displacement map, it will be very seamless and more efficient.

**Comment by photopea** [comment]
@kevintey Ok, I added the Displace filter, which uses a Smart Object (its source) as a displacement map.

**Comment by kevintey** [comment]
Tested, works like a charm, and very convenient:
![displacement](https://user-images.githubusercontent.com/41601071/46938959-a4e65e00-d097-11e8-8283-08a00cd2a0a4.jpg)

I am wondering if we can add additional check box, for 'Repeat Edge Pixels' ? 
This function actually replicates the edge pixels so that the edge is extended. That way, with the distortion applied, we would not see empty areas as its nicely stitched, and will not need to manually enlarge or crop the image.
![new project](https://user-images.githubusercontent.com/41601071/46939416-d27fd700-d098-11e8-8c73-2c7b46e5eb9c.jpg)

Thanks for awesome updates so far ;)

**Comment by photopea** [comment]
Ok, I added such parameter to the Displace filter :)  You are welcome! Thank you for suggesting all these features!
