### ISSUE TITLE
Adjust corner radius After the shape layer is created

### ISSUE THREAD

**Issue by hgs54371** [photopea/photopea#905]
The corner radius for rec shape and parametric ones is not adjustable/live after it's created

**Comment by photopea** [comment]
It is already in our todo list: https://github.com/photopea/photopea/issues/650

**Comment by photopea** [comment]
Hi, it was implemented, see here: https://blog.photopea.com/photopea-3-8-live-shapes-and-new-filters.html

**Comment by Zachruff** [comment]
pretty sure this is still an issue, again its only for pre-existing shapes, i can edit other stuff about them like the corner type, line color etc but corner radius i need to redraw the shape

**Comment by photopea** [comment]
What shapes exactly do you have in mind? The PSD format stores vector shapes "as they are".  A hexagon with a huge corner radius will be drawn as a circle, there is no information that it was a hexagon in the past.

**Comment by Zachruff** [comment]
ah ok so it isnt possible to return to an already created shape later to adjust the corner radius like you can adjust the color? That is what I was trying to do

**Comment by MichalSZZ** [comment]
> What shapes exactly do you have in mind? The PSD format stores vector shapes "as they are". A triangle with a huge corner radius will be drawn as a circle, there is no information that it was a triangle in the past. And you can not change the corner radius of a circle.

@photopea are you sure? There are Live Shapes for polygonal shapes since 2021? in Photoshop. You can draw Triangle (they made a special tool for that :D) and then change the corner radius, the number of sides, and many other options in the live shape properties panel. Look at the bottom of this page https://www.photoshopessentials.com/basics/how-to-draw-shapes-with-the-shape-tools/ 
![obraz](https://user-images.githubusercontent.com/38118273/199684480-9597dfd4-4b68-4428-9c57-c378e164fbe0.png)

**Comment by MichalSZZ** [comment]
@photopea for a Smart Shapes idea - go to the mail from me (21.10.2020, 14:25) and there we have discussed that. Then you didn't make an update because it was an "experimental" feature in Photoshop (in your opinion - and I respected that). Now 2 years later it works still in PS in that way and maybe it is time to implement it?

**Comment by photopea** [comment]
Photopea does have tools for editing Polygonal Live Shapes, see https://www.photopea.com/#iu7Ze3Jvb.psd  - select a layer and press Window - Properties.

But we dont have the Polygon tool for creating these polygons. Also, I think the author wanted to change a radius of any shape, not just regular polygons.

**Comment by photopea** [comment]
Live Polygon in Photoshop (and in Photopea) is very confusing. E.g. when you change the Angle, it rotates around the center of a bounding box, which is not a center of a triangle, or a pentagon.

**Comment by MichalSZZ** [comment]
@photopea Thank you very much for explaining - when and where it works and where doesn't. It is very important information for me (as for somebody who is teaching Photopea)
