### ISSUE TITLE
Favorite fonts list limited to 10 items

### ISSUE THREAD

**Issue by hgs54371** [photopea/photopea#931]
After reaching 10 items, every new ones added will replace the ones previously added

**Comment by photopea** [comment]
It is not a bug, it is a feature :) What limit would you like to have?

**Comment by hgs54371** [comment]
10 is too limiting, maybe 20 is enough

**Comment by photopea** [comment]
I think 20 would be too many.

**Comment by hgs54371** [comment]
Why even set a limit for this ? Memory concern ?

**Comment by marcos-abreu** [comment]
First I want to thank you for all the hard work you provide with photopea. What a great tool!

I want to weigh on this feature request because it is something that has me searching for other tools that I could use to set a set of fonts that I could refer to whenever working on a project.

Basically when working on some projects it is good to save a set of fonts that I can use on it. Think on someone creating a invitation for an event... what I usually do is to search a set of fonts I would like to apply to that invitation based on a theme set for it. Then I can latter chose the ones I want to use as I put the text and the final assets... sometimes I even bring the person I'm making the invitation and ask them to choose a font over a set of fonts.

Yes I can find a external tool to save a set of fonts, but showing the font applied to the artwork would make the process much easier and provide a full workflow inside of photopea, instead of having to use multiple tools and spending so much time trying to coordinate the process.

I haven't look into the process you created in order to save as favorite, but I would guess you are storing a font id in some sort of list that can be a memory list or a stored in local storage (or both). I'm sure there is more involved to it, but hopefully it is a feature you would consider.

Just to give you an idea, for some projects I would set a list of 30 fonts, some 40, some 60. If you must put a cap on this I think 100 would be a good number.

If this is not possible due to some technical problem  I hope I can help you find a way around it. I'm here if you want someone to test the feature.

Again thanks for the great work with photopea

**Comment by photopea** [comment]
I think I can extend the limit for favourite fonts from 10 to more. But is it really what you need? Do you maybe want to create collections of fonts? A font could be in multiple collections.

There could be a special "plugin" for it on the right side, similar to Characters or Brushes window.

**Comment by marcos-abreu** [comment]
custom font collections would work for sure, and I think would be a better implementation since would probably have more use cases.

Let me know if there is anything I can help with

**Comment by photopea** [comment]
Ok, I set the limit to 30 fonts. I don't think it makes sense to extend it even more. It would be much better to have a special plugin, which could do much more interesting structue of favourite fonts.

But it is hard to say, how many people would be interested in such plugin.

**Comment by marcos-abreu** [comment]
I would :)
