### ISSUE TITLE
There is a white pixel on the top-left of the cursor when you select brush tool 

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#99]
It is just an inch far.

I cannot take a screenshot, because if i press Ctrl the cursor changes.  :/

you can see the pixel if you position the cursor (with the brush tool) just to the right of the ball's shadow (the photopea logo)

**Comment by photopea** [comment]
Hi, it was made on purpose because of the bug in Chrome browser. I thought that nobody will ever notice it :D 
The problem is, that when you have a small diameter and you zoom out too much, the cursor becomes transparent. Chrome renders a transparent cursor as a big black square (Firefox is fine, though). Let's wait until Chrome fixes it, then we can remove the extra pixel. https://bugs.chromium.org/p/chromium/issues/detail?id=647599

**Comment by photopea** [comment]
I am not sure when Chrome will fix it, so I decided to add a little crosshair to tiny cursors, so that cursor is never transparent.

**Comment by avagp** [comment]
:D i hope chrome fixes it. I know you can of hate right now chrome for developing web apps :P

**Comment by photopea** [comment]
During the development of Photopea, I reported about 20 bugs to Chrome, 15 to Firefox, some to Microsoft and Apple.  Web browsers are a very important part of the "Photopea experience" :)
